-- AUTO-GENERATED by tools/winmd-gen (via gen-windows-package.ps1)
-- Namespace: Windows.Win32.System.Console
-- Counts: 22 structs, 0 unions, 4 enums, 0 COM interfaces, 95 functions, 49 constants, 1 handle typedefs, 3 nested unions/structs, 1 delegates
--
local W = require "windows"

ffi.cdef[[
/* primitive Win32 typedefs (idempotent vs. runtime built-ins) */
typedef char               CHAR;

typedef void * HPCON;

/* enum typedefs (members live in the return table below) */
typedef WORD CONSOLE_CHARACTER_ATTRIBUTES;
typedef DWORD CONSOLE_MODE;
typedef LONG CONSOLECONTROL;
typedef DWORD STD_HANDLE;

typedef struct _COORD COORD;
typedef struct _SMALL_RECT SMALL_RECT;
typedef struct _KEY_EVENT_RECORD KEY_EVENT_RECORD;
typedef struct _MOUSE_EVENT_RECORD MOUSE_EVENT_RECORD;
typedef struct _WINDOW_BUFFER_SIZE_RECORD WINDOW_BUFFER_SIZE_RECORD;
typedef struct _MENU_EVENT_RECORD MENU_EVENT_RECORD;
typedef struct _FOCUS_EVENT_RECORD FOCUS_EVENT_RECORD;
typedef struct _INPUT_RECORD INPUT_RECORD;
typedef struct _CHAR_INFO CHAR_INFO;
typedef struct _CONSOLE_FONT_INFO CONSOLE_FONT_INFO;
typedef struct _CONSOLE_READCONSOLE_CONTROL CONSOLE_READCONSOLE_CONTROL;
typedef struct _CONSOLE_CURSOR_INFO CONSOLE_CURSOR_INFO;
typedef struct _CONSOLE_SCREEN_BUFFER_INFO CONSOLE_SCREEN_BUFFER_INFO;
typedef struct _CONSOLE_SCREEN_BUFFER_INFOEX CONSOLE_SCREEN_BUFFER_INFOEX;
typedef struct _CONSOLE_FONT_INFOEX CONSOLE_FONT_INFOEX;
typedef struct _CONSOLE_SELECTION_INFO CONSOLE_SELECTION_INFO;
typedef struct _CONSOLE_HISTORY_INFO CONSOLE_HISTORY_INFO;
typedef struct _CONSOLEENDTASK CONSOLEENDTASK;
typedef struct _CONSOLEWINDOWOWNER CONSOLEWINDOWOWNER;
typedef struct _CONSOLESETFOREGROUND CONSOLESETFOREGROUND;
typedef struct _CONSOLE_PROCESS_INFO CONSOLE_PROCESS_INFO;
typedef struct _CONSOLE_CARET_INFO CONSOLE_CARET_INFO;
typedef union __uChar_e__Union_tag _uChar_e__Union;
typedef union __Event_e__Union_tag _Event_e__Union;
typedef union __Char_e__Union_tag _Char_e__Union;
typedef struct _COLORREF_opaque COLORREF;

/* callback (function-pointer) typedefs */
typedef BOOL (*PHANDLER_ROUTINE)(DWORD);

union __uChar_e__Union_tag {
    WCHAR UnicodeChar;
    CHAR AsciiChar;
};
union __Event_e__Union_tag {
    KEY_EVENT_RECORD KeyEvent;
    MOUSE_EVENT_RECORD MouseEvent;
    WINDOW_BUFFER_SIZE_RECORD WindowBufferSizeEvent;
    MENU_EVENT_RECORD MenuEvent;
    FOCUS_EVENT_RECORD FocusEvent;
};
union __Char_e__Union_tag {
    WCHAR UnicodeChar;
    CHAR AsciiChar;
};
struct _COORD {
    short X;
    short Y;
};
struct _SMALL_RECT {
    short Left;
    short Top;
    short Right;
    short Bottom;
};
struct _KEY_EVENT_RECORD {
    BOOL bKeyDown;
    WORD wRepeatCount;
    WORD wVirtualKeyCode;
    WORD wVirtualScanCode;
    _uChar_e__Union uChar;
    DWORD dwControlKeyState;
};
struct _MOUSE_EVENT_RECORD {
    COORD dwMousePosition;
    DWORD dwButtonState;
    DWORD dwControlKeyState;
    DWORD dwEventFlags;
};
struct _WINDOW_BUFFER_SIZE_RECORD {
    COORD dwSize;
};
struct _MENU_EVENT_RECORD {
    DWORD dwCommandId;
};
struct _FOCUS_EVENT_RECORD {
    BOOL bSetFocus;
};
struct _INPUT_RECORD {
    WORD EventType;
    _Event_e__Union Event;
};
struct _CHAR_INFO {
    _Char_e__Union Char;
    WORD Attributes;
};
struct _CONSOLE_FONT_INFO {
    DWORD nFont;
    COORD dwFontSize;
};
struct _CONSOLE_READCONSOLE_CONTROL {
    DWORD nLength;
    DWORD nInitialChars;
    DWORD dwCtrlWakeupMask;
    DWORD dwControlKeyState;
};
struct _CONSOLE_CURSOR_INFO {
    DWORD dwSize;
    BOOL bVisible;
};
struct _CONSOLE_SCREEN_BUFFER_INFO {
    COORD dwSize;
    COORD dwCursorPosition;
    CONSOLE_CHARACTER_ATTRIBUTES wAttributes;
    SMALL_RECT srWindow;
    COORD dwMaximumWindowSize;
};
struct _CONSOLE_SCREEN_BUFFER_INFOEX {
    DWORD cbSize;
    COORD dwSize;
    COORD dwCursorPosition;
    CONSOLE_CHARACTER_ATTRIBUTES wAttributes;
    SMALL_RECT srWindow;
    COORD dwMaximumWindowSize;
    WORD wPopupAttributes;
    BOOL bFullscreenSupported;
    COLORREF * ColorTable;
};
struct _CONSOLE_FONT_INFOEX {
    DWORD cbSize;
    DWORD nFont;
    COORD dwFontSize;
    DWORD FontFamily;
    DWORD FontWeight;
    WCHAR * FaceName;
};
struct _CONSOLE_SELECTION_INFO {
    DWORD dwFlags;
    COORD dwSelectionAnchor;
    SMALL_RECT srSelection;
};
struct _CONSOLE_HISTORY_INFO {
    DWORD cbSize;
    DWORD HistoryBufferSize;
    DWORD NumberOfHistoryBuffers;
    DWORD dwFlags;
};
struct _CONSOLEENDTASK {
    HANDLE ProcessId;
    HWND hwnd;
    DWORD ConsoleEventCode;
    DWORD ConsoleFlags;
};
struct _CONSOLEWINDOWOWNER {
    HWND hwnd;
    DWORD ProcessId;
    DWORD ThreadId;
};
struct _CONSOLESETFOREGROUND {
    HANDLE hProcess;
    BOOL bForeground;
};
struct _CONSOLE_PROCESS_INFO {
    DWORD dwProcessID;
    DWORD dwFlags;
};
struct _CONSOLE_CARET_INFO {
    HWND hwnd;
    RECT rc;
};
/* System.Console -- 95 functions */
BOOL AllocConsole();
BOOL FreeConsole();
BOOL AttachConsole(DWORD dwProcessId);
DWORD GetConsoleCP();
DWORD GetConsoleOutputCP();
BOOL GetConsoleMode(HANDLE hConsoleHandle, CONSOLE_MODE * lpMode);
BOOL SetConsoleMode(HANDLE hConsoleHandle, CONSOLE_MODE dwMode);
BOOL GetNumberOfConsoleInputEvents(HANDLE hConsoleInput, DWORD * lpNumberOfEvents);
BOOL ReadConsoleInputA(HANDLE hConsoleInput, INPUT_RECORD * lpBuffer, DWORD nLength, DWORD * lpNumberOfEventsRead);
BOOL ReadConsoleInputW(HANDLE hConsoleInput, INPUT_RECORD * lpBuffer, DWORD nLength, DWORD * lpNumberOfEventsRead);
BOOL PeekConsoleInputA(HANDLE hConsoleInput, INPUT_RECORD * lpBuffer, DWORD nLength, DWORD * lpNumberOfEventsRead);
BOOL PeekConsoleInputW(HANDLE hConsoleInput, INPUT_RECORD * lpBuffer, DWORD nLength, DWORD * lpNumberOfEventsRead);
BOOL ReadConsoleA(HANDLE hConsoleInput, void * lpBuffer, DWORD nNumberOfCharsToRead, DWORD * lpNumberOfCharsRead, CONSOLE_READCONSOLE_CONTROL * pInputControl);
BOOL ReadConsoleW(HANDLE hConsoleInput, void * lpBuffer, DWORD nNumberOfCharsToRead, DWORD * lpNumberOfCharsRead, CONSOLE_READCONSOLE_CONTROL * pInputControl);
BOOL WriteConsoleA(HANDLE hConsoleOutput, LPSTR lpBuffer, DWORD nNumberOfCharsToWrite, DWORD * lpNumberOfCharsWritten, void * lpReserved);
BOOL WriteConsoleW(HANDLE hConsoleOutput, LPWSTR lpBuffer, DWORD nNumberOfCharsToWrite, DWORD * lpNumberOfCharsWritten, void * lpReserved);
BOOL SetConsoleCtrlHandler(PHANDLER_ROUTINE HandlerRoutine, BOOL Add);
HRESULT CreatePseudoConsole(COORD size, HANDLE hInput, HANDLE hOutput, DWORD dwFlags, HPCON * phPC);
HRESULT ResizePseudoConsole(HPCON hPC, COORD size);
void ClosePseudoConsole(HPCON hPC);
BOOL FillConsoleOutputCharacterA(HANDLE hConsoleOutput, CHAR cCharacter, DWORD nLength, COORD dwWriteCoord, DWORD * lpNumberOfCharsWritten);
BOOL FillConsoleOutputCharacterW(HANDLE hConsoleOutput, WCHAR cCharacter, DWORD nLength, COORD dwWriteCoord, DWORD * lpNumberOfCharsWritten);
BOOL FillConsoleOutputAttribute(HANDLE hConsoleOutput, WORD wAttribute, DWORD nLength, COORD dwWriteCoord, DWORD * lpNumberOfAttrsWritten);
BOOL GenerateConsoleCtrlEvent(DWORD dwCtrlEvent, DWORD dwProcessGroupId);
HANDLE CreateConsoleScreenBuffer(DWORD dwDesiredAccess, DWORD dwShareMode, SECURITY_ATTRIBUTES * lpSecurityAttributes, DWORD dwFlags, void * lpScreenBufferData);
BOOL SetConsoleActiveScreenBuffer(HANDLE hConsoleOutput);
BOOL FlushConsoleInputBuffer(HANDLE hConsoleInput);
BOOL SetConsoleCP(DWORD wCodePageID);
BOOL SetConsoleOutputCP(DWORD wCodePageID);
BOOL GetConsoleCursorInfo(HANDLE hConsoleOutput, CONSOLE_CURSOR_INFO * lpConsoleCursorInfo);
BOOL SetConsoleCursorInfo(HANDLE hConsoleOutput, CONSOLE_CURSOR_INFO * lpConsoleCursorInfo);
BOOL GetConsoleScreenBufferInfo(HANDLE hConsoleOutput, CONSOLE_SCREEN_BUFFER_INFO * lpConsoleScreenBufferInfo);
BOOL GetConsoleScreenBufferInfoEx(HANDLE hConsoleOutput, CONSOLE_SCREEN_BUFFER_INFOEX * lpConsoleScreenBufferInfoEx);
BOOL SetConsoleScreenBufferInfoEx(HANDLE hConsoleOutput, CONSOLE_SCREEN_BUFFER_INFOEX * lpConsoleScreenBufferInfoEx);
BOOL SetConsoleScreenBufferSize(HANDLE hConsoleOutput, COORD dwSize);
BOOL SetConsoleCursorPosition(HANDLE hConsoleOutput, COORD dwCursorPosition);
COORD GetLargestConsoleWindowSize(HANDLE hConsoleOutput);
BOOL SetConsoleTextAttribute(HANDLE hConsoleOutput, CONSOLE_CHARACTER_ATTRIBUTES wAttributes);
BOOL SetConsoleWindowInfo(HANDLE hConsoleOutput, BOOL bAbsolute, SMALL_RECT * lpConsoleWindow);
BOOL WriteConsoleOutputCharacterA(HANDLE hConsoleOutput, LPSTR lpCharacter, DWORD nLength, COORD dwWriteCoord, DWORD * lpNumberOfCharsWritten);
BOOL WriteConsoleOutputCharacterW(HANDLE hConsoleOutput, LPWSTR lpCharacter, DWORD nLength, COORD dwWriteCoord, DWORD * lpNumberOfCharsWritten);
BOOL WriteConsoleOutputAttribute(HANDLE hConsoleOutput, WORD * lpAttribute, DWORD nLength, COORD dwWriteCoord, DWORD * lpNumberOfAttrsWritten);
BOOL ReadConsoleOutputCharacterA(HANDLE hConsoleOutput, LPSTR lpCharacter, DWORD nLength, COORD dwReadCoord, DWORD * lpNumberOfCharsRead);
BOOL ReadConsoleOutputCharacterW(HANDLE hConsoleOutput, LPWSTR lpCharacter, DWORD nLength, COORD dwReadCoord, DWORD * lpNumberOfCharsRead);
BOOL ReadConsoleOutputAttribute(HANDLE hConsoleOutput, WORD * lpAttribute, DWORD nLength, COORD dwReadCoord, DWORD * lpNumberOfAttrsRead);
BOOL WriteConsoleInputA(HANDLE hConsoleInput, INPUT_RECORD * lpBuffer, DWORD nLength, DWORD * lpNumberOfEventsWritten);
BOOL WriteConsoleInputW(HANDLE hConsoleInput, INPUT_RECORD * lpBuffer, DWORD nLength, DWORD * lpNumberOfEventsWritten);
BOOL ScrollConsoleScreenBufferA(HANDLE hConsoleOutput, SMALL_RECT * lpScrollRectangle, SMALL_RECT * lpClipRectangle, COORD dwDestinationOrigin, CHAR_INFO * lpFill);
BOOL ScrollConsoleScreenBufferW(HANDLE hConsoleOutput, SMALL_RECT * lpScrollRectangle, SMALL_RECT * lpClipRectangle, COORD dwDestinationOrigin, CHAR_INFO * lpFill);
BOOL WriteConsoleOutputA(HANDLE hConsoleOutput, CHAR_INFO * lpBuffer, COORD dwBufferSize, COORD dwBufferCoord, SMALL_RECT * lpWriteRegion);
BOOL WriteConsoleOutputW(HANDLE hConsoleOutput, CHAR_INFO * lpBuffer, COORD dwBufferSize, COORD dwBufferCoord, SMALL_RECT * lpWriteRegion);
BOOL ReadConsoleOutputA(HANDLE hConsoleOutput, CHAR_INFO * lpBuffer, COORD dwBufferSize, COORD dwBufferCoord, SMALL_RECT * lpReadRegion);
BOOL ReadConsoleOutputW(HANDLE hConsoleOutput, CHAR_INFO * lpBuffer, COORD dwBufferSize, COORD dwBufferCoord, SMALL_RECT * lpReadRegion);
DWORD GetConsoleTitleA(LPSTR lpConsoleTitle, DWORD nSize);
DWORD GetConsoleTitleW(LPWSTR lpConsoleTitle, DWORD nSize);
DWORD GetConsoleOriginalTitleA(LPSTR lpConsoleTitle, DWORD nSize);
DWORD GetConsoleOriginalTitleW(LPWSTR lpConsoleTitle, DWORD nSize);
BOOL SetConsoleTitleA(LPSTR lpConsoleTitle);
BOOL SetConsoleTitleW(LPWSTR lpConsoleTitle);
BOOL GetNumberOfConsoleMouseButtons(DWORD * lpNumberOfMouseButtons);
COORD GetConsoleFontSize(HANDLE hConsoleOutput, DWORD nFont);
BOOL GetCurrentConsoleFont(HANDLE hConsoleOutput, BOOL bMaximumWindow, CONSOLE_FONT_INFO * lpConsoleCurrentFont);
BOOL GetCurrentConsoleFontEx(HANDLE hConsoleOutput, BOOL bMaximumWindow, CONSOLE_FONT_INFOEX * lpConsoleCurrentFontEx);
BOOL SetCurrentConsoleFontEx(HANDLE hConsoleOutput, BOOL bMaximumWindow, CONSOLE_FONT_INFOEX * lpConsoleCurrentFontEx);
BOOL GetConsoleSelectionInfo(CONSOLE_SELECTION_INFO * lpConsoleSelectionInfo);
BOOL GetConsoleHistoryInfo(CONSOLE_HISTORY_INFO * lpConsoleHistoryInfo);
BOOL SetConsoleHistoryInfo(CONSOLE_HISTORY_INFO * lpConsoleHistoryInfo);
BOOL GetConsoleDisplayMode(DWORD * lpModeFlags);
BOOL SetConsoleDisplayMode(HANDLE hConsoleOutput, DWORD dwFlags, COORD * lpNewScreenBufferDimensions);
HWND GetConsoleWindow();
BOOL AddConsoleAliasA(LPSTR Source, LPSTR Target, LPSTR ExeName);
BOOL AddConsoleAliasW(LPWSTR Source, LPWSTR Target, LPWSTR ExeName);
DWORD GetConsoleAliasA(LPSTR Source, LPSTR TargetBuffer, DWORD TargetBufferLength, LPSTR ExeName);
DWORD GetConsoleAliasW(LPWSTR Source, LPWSTR TargetBuffer, DWORD TargetBufferLength, LPWSTR ExeName);
DWORD GetConsoleAliasesLengthA(LPSTR ExeName);
DWORD GetConsoleAliasesLengthW(LPWSTR ExeName);
DWORD GetConsoleAliasExesLengthA();
DWORD GetConsoleAliasExesLengthW();
DWORD GetConsoleAliasesA(LPSTR AliasBuffer, DWORD AliasBufferLength, LPSTR ExeName);
DWORD GetConsoleAliasesW(LPWSTR AliasBuffer, DWORD AliasBufferLength, LPWSTR ExeName);
DWORD GetConsoleAliasExesA(LPSTR ExeNameBuffer, DWORD ExeNameBufferLength);
DWORD GetConsoleAliasExesW(LPWSTR ExeNameBuffer, DWORD ExeNameBufferLength);
void ExpungeConsoleCommandHistoryA(LPSTR ExeName);
void ExpungeConsoleCommandHistoryW(LPWSTR ExeName);
BOOL SetConsoleNumberOfCommandsA(DWORD Number, LPSTR ExeName);
BOOL SetConsoleNumberOfCommandsW(DWORD Number, LPWSTR ExeName);
DWORD GetConsoleCommandHistoryLengthA(LPSTR ExeName);
DWORD GetConsoleCommandHistoryLengthW(LPWSTR ExeName);
DWORD GetConsoleCommandHistoryA(LPSTR Commands, DWORD CommandBufferLength, LPSTR ExeName);
DWORD GetConsoleCommandHistoryW(LPWSTR Commands, DWORD CommandBufferLength, LPWSTR ExeName);
DWORD GetConsoleProcessList(DWORD * lpdwProcessList, DWORD dwProcessCount);
NTSTATUS ConsoleControl(CONSOLECONTROL Command, void * ConsoleInformation, DWORD ConsoleInformationLength);
HANDLE GetStdHandle(STD_HANDLE nStdHandle);
BOOL SetStdHandle(STD_HANDLE nStdHandle, HANDLE hHandle);
BOOL SetStdHandleEx(STD_HANDLE nStdHandle, HANDLE hHandle, HANDLE * phPrevValue);
]]

return {
    ALTNUMPAD_BIT = 0x04000000,
    ATTACH_PARENT_PROCESS = 0xFFFFFFFF,
    CAPSLOCK_ON = 0x00000080,
    CONSOLE_FULLSCREEN = 0x00000001,
    CONSOLE_FULLSCREEN_HARDWARE = 0x00000002,
    CONSOLE_FULLSCREEN_MODE = 0x00000001,
    CONSOLE_MOUSE_DOWN = 0x00000008,
    CONSOLE_MOUSE_SELECTION = 0x00000004,
    CONSOLE_NO_SELECTION = 0x00000000,
    CONSOLE_SELECTION_IN_PROGRESS = 0x00000001,
    CONSOLE_SELECTION_NOT_EMPTY = 0x00000002,
    CONSOLE_TEXTMODE_BUFFER = 0x00000001,
    CONSOLE_WINDOWED_MODE = 0x00000002,
    CTRL_BREAK_EVENT = 0x00000001,
    CTRL_C_EVENT = 0x00000000,
    CTRL_CLOSE_EVENT = 0x00000002,
    CTRL_LOGOFF_EVENT = 0x00000005,
    CTRL_SHUTDOWN_EVENT = 0x00000006,
    DOUBLE_CLICK = 0x00000002,
    ENHANCED_KEY = 0x00000100,
    FOCUS_EVENT = 0x00000010,
    FROM_LEFT_1ST_BUTTON_PRESSED = 0x00000001,
    FROM_LEFT_2ND_BUTTON_PRESSED = 0x00000004,
    FROM_LEFT_3RD_BUTTON_PRESSED = 0x00000008,
    FROM_LEFT_4TH_BUTTON_PRESSED = 0x00000010,
    HISTORY_NO_DUP_FLAG = 0x00000001,
    KEY_EVENT = 0x00000001,
    LEFT_ALT_PRESSED = 0x00000002,
    LEFT_CTRL_PRESSED = 0x00000008,
    MENU_EVENT = 0x00000008,
    MOUSE_EVENT = 0x00000002,
    MOUSE_HWHEELED = 0x00000008,
    MOUSE_MOVED = 0x00000001,
    MOUSE_WHEELED = 0x00000004,
    NLS_ALPHANUMERIC = 0x00000000,
    NLS_DBCSCHAR = 0x00010000,
    NLS_HIRAGANA = 0x00040000,
    NLS_IME_CONVERSION = 0x00800000,
    NLS_IME_DISABLE = 0x20000000,
    NLS_KATAKANA = 0x00020000,
    NLS_ROMAN = 0x00400000,
    NUMLOCK_ON = 0x00000020,
    PSEUDOCONSOLE_INHERIT_CURSOR = 0x00000001,
    RIGHT_ALT_PRESSED = 0x00000001,
    RIGHT_CTRL_PRESSED = 0x00000004,
    RIGHTMOST_BUTTON_PRESSED = 0x00000002,
    SCROLLLOCK_ON = 0x00000040,
    SHIFT_PRESSED = 0x00000010,
    WINDOW_BUFFER_SIZE_EVENT = 0x00000004,
    -- enum CONSOLE_CHARACTER_ATTRIBUTES
    CONSOLE_CHARACTER_ATTRIBUTES_FOREGROUND_BLUE = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_FOREGROUND_GREEN = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_FOREGROUND_RED = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_FOREGROUND_INTENSITY = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_BACKGROUND_BLUE = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_BACKGROUND_GREEN = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_BACKGROUND_RED = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_BACKGROUND_INTENSITY = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_COMMON_LVB_LEADING_BYTE = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_COMMON_LVB_TRAILING_BYTE = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_COMMON_LVB_GRID_HORIZONTAL = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_COMMON_LVB_GRID_LVERTICAL = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_COMMON_LVB_GRID_RVERTICAL = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_COMMON_LVB_REVERSE_VIDEO = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_COMMON_LVB_UNDERSCORE = 0,
    CONSOLE_CHARACTER_ATTRIBUTES_COMMON_LVB_SBCSDBCS = 0,
    -- enum CONSOLE_MODE
    CONSOLE_MODE_ENABLE_PROCESSED_INPUT = 0x00000001,
    CONSOLE_MODE_ENABLE_LINE_INPUT = 0x00000002,
    CONSOLE_MODE_ENABLE_ECHO_INPUT = 0x00000004,
    CONSOLE_MODE_ENABLE_WINDOW_INPUT = 0x00000008,
    CONSOLE_MODE_ENABLE_MOUSE_INPUT = 0x00000010,
    CONSOLE_MODE_ENABLE_INSERT_MODE = 0x00000020,
    CONSOLE_MODE_ENABLE_QUICK_EDIT_MODE = 0x00000040,
    CONSOLE_MODE_ENABLE_EXTENDED_FLAGS = 0x00000080,
    CONSOLE_MODE_ENABLE_AUTO_POSITION = 0x00000100,
    CONSOLE_MODE_ENABLE_VIRTUAL_TERMINAL_INPUT = 0x00000200,
    CONSOLE_MODE_ENABLE_PROCESSED_OUTPUT = 0x00000001,
    CONSOLE_MODE_ENABLE_WRAP_AT_EOL_OUTPUT = 0x00000002,
    CONSOLE_MODE_ENABLE_VIRTUAL_TERMINAL_PROCESSING = 0x00000004,
    CONSOLE_MODE_DISABLE_NEWLINE_AUTO_RETURN = 0x00000008,
    CONSOLE_MODE_ENABLE_LVB_GRID_WORLDWIDE = 0x00000010,
    -- enum CONSOLECONTROL
    CONSOLECONTROL_Reserved1 = 0,
    CONSOLECONTROL_ConsoleNotifyConsoleApplication = 1,
    CONSOLECONTROL_Reserved2 = 2,
    CONSOLECONTROL_ConsoleSetCaretInfo = 3,
    CONSOLECONTROL_Reserved3 = 4,
    CONSOLECONTROL_ConsoleSetForeground = 5,
    CONSOLECONTROL_ConsoleSetWindowOwner = 6,
    CONSOLECONTROL_ConsoleEndTask = 7,
    -- enum STD_HANDLE
    STD_HANDLE_STD_INPUT_HANDLE = 0xFFFFFFF6,
    STD_HANDLE_STD_OUTPUT_HANDLE = 0xFFFFFFF5,
    STD_HANDLE_STD_ERROR_HANDLE = 0xFFFFFFF4,
}
