-- AUTO-GENERATED by tools/winmd-gen (via gen-windows-package.ps1)
-- Namespace: Windows.Win32.System.Memory
-- Counts: 14 structs, 0 unions, 19 enums, 0 COM interfaces, 104 functions, 5 constants, 2 handle typedefs, 5 nested unions/structs, 2 delegates
--
local W = require "windows"

ffi.cdef[[
/* primitive Win32 typedefs (idempotent vs. runtime built-ins) */
typedef char               CHAR;

typedef void * AtlThunkData_t;
typedef void * MEMORY_MAPPED_VIEW_ADDRESS;
typedef void *HGLOBAL;
typedef void *HLOCAL;

/* enum typedefs (members live in the return table below) */
typedef DWORD FILE_MAP;
typedef DWORD GLOBAL_ALLOC_FLAGS;
typedef DWORD HEAP_FLAGS;
typedef LONG HEAP_INFORMATION_CLASS;
typedef DWORD LOCAL_ALLOC_FLAGS;
typedef LONG MEM_DEDICATED_ATTRIBUTE_TYPE;
typedef LONG MEM_EXTENDED_PARAMETER_TYPE;
typedef LONG MEM_SECTION_EXTENDED_PARAMETER_TYPE;
typedef LONG MEMORY_RESOURCE_NOTIFICATION_TYPE;
typedef LONG OFFER_PRIORITY;
typedef DWORD PAGE_PROTECTION_FLAGS;
typedef DWORD PAGE_TYPE;
typedef DWORD SECTION_FLAGS;
typedef DWORD SETPROCESSWORKINGSETSIZEEX_FLAGS;
typedef DWORD UNMAP_VIEW_OF_FILE_FLAGS;
typedef DWORD VIRTUAL_ALLOCATION_TYPE;
typedef DWORD VIRTUAL_FREE_TYPE;
typedef LONG WIN32_MEMORY_INFORMATION_CLASS;
typedef LONG WIN32_MEMORY_PARTITION_INFORMATION_CLASS;

typedef struct _PROCESS_HEAP_ENTRY PROCESS_HEAP_ENTRY;
typedef struct _HEAP_SUMMARY HEAP_SUMMARY;
typedef struct _WIN32_MEMORY_RANGE_ENTRY WIN32_MEMORY_RANGE_ENTRY;
typedef struct _WIN32_MEMORY_REGION_INFORMATION WIN32_MEMORY_REGION_INFORMATION;
typedef struct _WIN32_MEMORY_PARTITION_INFORMATION WIN32_MEMORY_PARTITION_INFORMATION;
typedef struct _MEMORY_BASIC_INFORMATION MEMORY_BASIC_INFORMATION;
typedef struct _MEMORY_BASIC_INFORMATION MEMORY_BASIC_INFORMATION;
typedef struct _MEMORY_BASIC_INFORMATION32 MEMORY_BASIC_INFORMATION32;
typedef struct _MEMORY_BASIC_INFORMATION64 MEMORY_BASIC_INFORMATION64;
typedef struct _CFG_CALL_TARGET_INFO CFG_CALL_TARGET_INFO;
typedef struct _MEM_ADDRESS_REQUIREMENTS MEM_ADDRESS_REQUIREMENTS;
typedef struct _MEM_EXTENDED_PARAMETER MEM_EXTENDED_PARAMETER;
typedef struct _MEMORY_PARTITION_DEDICATED_MEMORY_ATTRIBUTE MEMORY_PARTITION_DEDICATED_MEMORY_ATTRIBUTE;
typedef struct _MEMORY_PARTITION_DEDICATED_MEMORY_INFORMATION MEMORY_PARTITION_DEDICATED_MEMORY_INFORMATION;
typedef union __Anonymous_e__Union_tag _Anonymous_e__Union;
typedef struct __Block_e__Struct_tag _Block_e__Struct;
typedef struct __Region_e__Struct_tag _Region_e__Struct;
typedef struct __Anonymous1_e__Struct_tag _Anonymous1_e__Struct;
typedef union __Anonymous2_e__Union_tag _Anonymous2_e__Union;

/* callback (function-pointer) typedefs */
typedef void (*PBAD_MEMORY_CALLBACK_ROUTINE)(void);
typedef BYTE (*PSECURE_MEMORY_CACHE_CALLBACK)(void *, void *);

union __Anonymous_e__Union_tag {
    _Block_e__Struct Block;
    _Region_e__Struct Region;
};
struct __Block_e__Struct_tag {
    HANDLE hMem;
    DWORD * dwReserved;
};
struct __Region_e__Struct_tag {
    DWORD dwCommittedSize;
    DWORD dwUnCommittedSize;
    void * lpFirstBlock;
    void * lpLastBlock;
};
struct __Anonymous1_e__Struct_tag {
    ULONGLONG _bitfield;
};
union __Anonymous2_e__Union_tag {
    ULONGLONG ULong64;
    void * Pointer;
    void * Size;
    HANDLE Handle;
    DWORD ULong;
};
struct _PROCESS_HEAP_ENTRY {
    void * lpData;
    DWORD cbData;
    BYTE cbOverhead;
    BYTE iRegionIndex;
    WORD wFlags;
    _Anonymous_e__Union Anonymous;
};
struct _HEAP_SUMMARY {
    DWORD cb;
    void * cbAllocated;
    void * cbCommitted;
    void * cbReserved;
    void * cbMaxReserve;
};
struct _WIN32_MEMORY_RANGE_ENTRY {
    void * VirtualAddress;
    void * NumberOfBytes;
};
struct _WIN32_MEMORY_REGION_INFORMATION {
    void * AllocationBase;
    DWORD AllocationProtect;
    _Anonymous_e__Union Anonymous;
    void * RegionSize;
    void * CommitSize;
};
struct _WIN32_MEMORY_PARTITION_INFORMATION {
    DWORD Flags;
    DWORD NumaNode;
    DWORD Channel;
    DWORD NumberOfNumaNodes;
    ULONGLONG ResidentAvailablePages;
    ULONGLONG CommittedPages;
    ULONGLONG CommitLimit;
    ULONGLONG PeakCommitment;
    ULONGLONG TotalNumberOfPages;
    ULONGLONG AvailablePages;
    ULONGLONG ZeroPages;
    ULONGLONG FreePages;
    ULONGLONG StandbyPages;
    ULONGLONG * Reserved;
    ULONGLONG MaximumCommitLimit;
    ULONGLONG Reserved2;
    DWORD PartitionId;
};
struct _MEMORY_BASIC_INFORMATION {
    void * BaseAddress;
    void * AllocationBase;
    PAGE_PROTECTION_FLAGS AllocationProtect;
    WORD PartitionId;
    void * RegionSize;
    VIRTUAL_ALLOCATION_TYPE State;
    PAGE_PROTECTION_FLAGS Protect;
    PAGE_TYPE Type;
};
struct _MEMORY_BASIC_INFORMATION {
    void * BaseAddress;
    void * AllocationBase;
    PAGE_PROTECTION_FLAGS AllocationProtect;
    void * RegionSize;
    VIRTUAL_ALLOCATION_TYPE State;
    PAGE_PROTECTION_FLAGS Protect;
    PAGE_TYPE Type;
};
struct _MEMORY_BASIC_INFORMATION32 {
    DWORD BaseAddress;
    DWORD AllocationBase;
    PAGE_PROTECTION_FLAGS AllocationProtect;
    DWORD RegionSize;
    VIRTUAL_ALLOCATION_TYPE State;
    PAGE_PROTECTION_FLAGS Protect;
    PAGE_TYPE Type;
};
struct _MEMORY_BASIC_INFORMATION64 {
    ULONGLONG BaseAddress;
    ULONGLONG AllocationBase;
    PAGE_PROTECTION_FLAGS AllocationProtect;
    DWORD __alignment1;
    ULONGLONG RegionSize;
    VIRTUAL_ALLOCATION_TYPE State;
    PAGE_PROTECTION_FLAGS Protect;
    PAGE_TYPE Type;
    DWORD __alignment2;
};
struct _CFG_CALL_TARGET_INFO {
    void * Offset;
    void * Flags;
};
struct _MEM_ADDRESS_REQUIREMENTS {
    void * LowestStartingAddress;
    void * HighestEndingAddress;
    void * Alignment;
};
struct _MEM_EXTENDED_PARAMETER {
    _Anonymous1_e__Struct Anonymous1;
    _Anonymous2_e__Union Anonymous2;
};
struct _MEMORY_PARTITION_DEDICATED_MEMORY_ATTRIBUTE {
    MEM_DEDICATED_ATTRIBUTE_TYPE Type;
    DWORD Reserved;
    ULONGLONG Value;
};
struct _MEMORY_PARTITION_DEDICATED_MEMORY_INFORMATION {
    DWORD NextEntryOffset;
    DWORD SizeOfInformation;
    DWORD Flags;
    DWORD AttributesOffset;
    DWORD AttributeCount;
    DWORD Reserved;
    ULONGLONG TypeId;
};
/* System.Memory -- 104 functions */
HANDLE HeapCreate(HEAP_FLAGS flOptions, void * dwInitialSize, void * dwMaximumSize);
BOOL HeapDestroy(HANDLE hHeap);
void * HeapAlloc(HANDLE hHeap, HEAP_FLAGS dwFlags, void * dwBytes);
void * HeapReAlloc(HANDLE hHeap, HEAP_FLAGS dwFlags, void * lpMem, void * dwBytes);
BOOL HeapFree(HANDLE hHeap, HEAP_FLAGS dwFlags, void * lpMem);
void * HeapSize(HANDLE hHeap, HEAP_FLAGS dwFlags, void * lpMem);
HANDLE GetProcessHeap();
void * HeapCompact(HANDLE hHeap, HEAP_FLAGS dwFlags);
BOOL HeapSetInformation(HANDLE HeapHandle, HEAP_INFORMATION_CLASS HeapInformationClass, void * HeapInformation, void * HeapInformationLength);
BOOL HeapValidate(HANDLE hHeap, HEAP_FLAGS dwFlags, void * lpMem);
BOOL HeapSummary(HANDLE hHeap, DWORD dwFlags, HEAP_SUMMARY * lpSummary);
DWORD GetProcessHeaps(DWORD NumberOfHeaps, HANDLE * ProcessHeaps);
BOOL HeapLock(HANDLE hHeap);
BOOL HeapUnlock(HANDLE hHeap);
BOOL HeapWalk(HANDLE hHeap, PROCESS_HEAP_ENTRY * lpEntry);
BOOL HeapQueryInformation(HANDLE HeapHandle, HEAP_INFORMATION_CLASS HeapInformationClass, void * HeapInformation, void * HeapInformationLength, void * * ReturnLength);
void * VirtualAlloc(void * lpAddress, void * dwSize, VIRTUAL_ALLOCATION_TYPE flAllocationType, PAGE_PROTECTION_FLAGS flProtect);
BOOL VirtualProtect(void * lpAddress, void * dwSize, PAGE_PROTECTION_FLAGS flNewProtect, PAGE_PROTECTION_FLAGS * lpflOldProtect);
BOOL VirtualFree(void * lpAddress, void * dwSize, VIRTUAL_FREE_TYPE dwFreeType);
void * VirtualQuery(void * lpAddress, MEMORY_BASIC_INFORMATION * lpBuffer, void * dwLength);
void * VirtualAllocEx(HANDLE hProcess, void * lpAddress, void * dwSize, VIRTUAL_ALLOCATION_TYPE flAllocationType, PAGE_PROTECTION_FLAGS flProtect);
BOOL VirtualProtectEx(HANDLE hProcess, void * lpAddress, void * dwSize, PAGE_PROTECTION_FLAGS flNewProtect, PAGE_PROTECTION_FLAGS * lpflOldProtect);
void * VirtualQueryEx(HANDLE hProcess, void * lpAddress, MEMORY_BASIC_INFORMATION * lpBuffer, void * dwLength);
HANDLE CreateFileMappingW(HANDLE hFile, SECURITY_ATTRIBUTES * lpFileMappingAttributes, PAGE_PROTECTION_FLAGS flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPWSTR lpName);
HANDLE OpenFileMappingW(DWORD dwDesiredAccess, BOOL bInheritHandle, LPWSTR lpName);
MEMORY_MAPPED_VIEW_ADDRESS MapViewOfFile(HANDLE hFileMappingObject, FILE_MAP dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, void * dwNumberOfBytesToMap);
MEMORY_MAPPED_VIEW_ADDRESS MapViewOfFileEx(HANDLE hFileMappingObject, FILE_MAP dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, void * dwNumberOfBytesToMap, void * lpBaseAddress);
BOOL VirtualFreeEx(HANDLE hProcess, void * lpAddress, void * dwSize, VIRTUAL_FREE_TYPE dwFreeType);
BOOL FlushViewOfFile(void * lpBaseAddress, void * dwNumberOfBytesToFlush);
BOOL UnmapViewOfFile(MEMORY_MAPPED_VIEW_ADDRESS lpBaseAddress);
void * GetLargePageMinimum();
BOOL GetProcessWorkingSetSizeEx(HANDLE hProcess, void * * lpMinimumWorkingSetSize, void * * lpMaximumWorkingSetSize, DWORD * Flags);
BOOL SetProcessWorkingSetSizeEx(HANDLE hProcess, void * dwMinimumWorkingSetSize, void * dwMaximumWorkingSetSize, SETPROCESSWORKINGSETSIZEEX_FLAGS Flags);
BOOL VirtualLock(void * lpAddress, void * dwSize);
BOOL VirtualUnlock(void * lpAddress, void * dwSize);
DWORD GetWriteWatch(DWORD dwFlags, void * lpBaseAddress, void * dwRegionSize, void * * lpAddresses, void * * lpdwCount, DWORD * lpdwGranularity);
DWORD ResetWriteWatch(void * lpBaseAddress, void * dwRegionSize);
HANDLE CreateMemoryResourceNotification(MEMORY_RESOURCE_NOTIFICATION_TYPE NotificationType);
BOOL QueryMemoryResourceNotification(HANDLE ResourceNotificationHandle, BOOL * ResourceState);
BOOL GetSystemFileCacheSize(void * * lpMinimumFileCacheSize, void * * lpMaximumFileCacheSize, DWORD * lpFlags);
BOOL SetSystemFileCacheSize(void * MinimumFileCacheSize, void * MaximumFileCacheSize, DWORD Flags);
HANDLE CreateFileMappingNumaW(HANDLE hFile, SECURITY_ATTRIBUTES * lpFileMappingAttributes, PAGE_PROTECTION_FLAGS flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPWSTR lpName, DWORD nndPreferred);
BOOL PrefetchVirtualMemory(HANDLE hProcess, void * NumberOfEntries, WIN32_MEMORY_RANGE_ENTRY * VirtualAddresses, DWORD Flags);
HANDLE CreateFileMappingFromApp(HANDLE hFile, SECURITY_ATTRIBUTES * SecurityAttributes, PAGE_PROTECTION_FLAGS PageProtection, ULONGLONG MaximumSize, LPWSTR Name);
MEMORY_MAPPED_VIEW_ADDRESS MapViewOfFileFromApp(HANDLE hFileMappingObject, FILE_MAP DesiredAccess, ULONGLONG FileOffset, void * NumberOfBytesToMap);
BOOL UnmapViewOfFileEx(MEMORY_MAPPED_VIEW_ADDRESS BaseAddress, UNMAP_VIEW_OF_FILE_FLAGS UnmapFlags);
BOOL AllocateUserPhysicalPages(HANDLE hProcess, void * * NumberOfPages, void * * PageArray);
BOOL FreeUserPhysicalPages(HANDLE hProcess, void * * NumberOfPages, void * * PageArray);
BOOL MapUserPhysicalPages(void * VirtualAddress, void * NumberOfPages, void * * PageArray);
BOOL AllocateUserPhysicalPagesNuma(HANDLE hProcess, void * * NumberOfPages, void * * PageArray, DWORD nndPreferred);
void * VirtualAllocExNuma(HANDLE hProcess, void * lpAddress, void * dwSize, VIRTUAL_ALLOCATION_TYPE flAllocationType, DWORD flProtect, DWORD nndPreferred);
BOOL GetMemoryErrorHandlingCapabilities(DWORD * Capabilities);
void * RegisterBadMemoryNotification(PBAD_MEMORY_CALLBACK_ROUTINE Callback);
BOOL UnregisterBadMemoryNotification(void * RegistrationHandle);
DWORD OfferVirtualMemory(void * VirtualAddress, void * Size, OFFER_PRIORITY Priority);
DWORD ReclaimVirtualMemory(void * VirtualAddress, void * Size);
DWORD DiscardVirtualMemory(void * VirtualAddress, void * Size);
BOOL SetProcessValidCallTargets(HANDLE hProcess, void * VirtualAddress, void * RegionSize, DWORD NumberOfOffsets, CFG_CALL_TARGET_INFO * OffsetInformation);
BOOL SetProcessValidCallTargetsForMappedView(HANDLE Process, void * VirtualAddress, void * RegionSize, DWORD NumberOfOffsets, CFG_CALL_TARGET_INFO * OffsetInformation, HANDLE Section, ULONGLONG ExpectedFileOffset);
void * VirtualAllocFromApp(void * BaseAddress, void * Size, VIRTUAL_ALLOCATION_TYPE AllocationType, DWORD Protection);
BOOL VirtualProtectFromApp(void * Address, void * Size, DWORD NewProtection, DWORD * OldProtection);
HANDLE OpenFileMappingFromApp(DWORD DesiredAccess, BOOL InheritHandle, LPWSTR Name);
BOOL QueryVirtualMemoryInformation(HANDLE Process, void * VirtualAddress, WIN32_MEMORY_INFORMATION_CLASS MemoryInformationClass, void * MemoryInformation, void * MemoryInformationSize, void * * ReturnSize);
MEMORY_MAPPED_VIEW_ADDRESS MapViewOfFileNuma2(HANDLE FileMappingHandle, HANDLE ProcessHandle, ULONGLONG Offset, void * BaseAddress, void * ViewSize, DWORD AllocationType, DWORD PageProtection, DWORD PreferredNode);
BOOL UnmapViewOfFile2(HANDLE Process, MEMORY_MAPPED_VIEW_ADDRESS BaseAddress, UNMAP_VIEW_OF_FILE_FLAGS UnmapFlags);
BOOL VirtualUnlockEx(HANDLE Process, void * Address, void * Size);
void * VirtualAlloc2(HANDLE Process, void * BaseAddress, void * Size, VIRTUAL_ALLOCATION_TYPE AllocationType, DWORD PageProtection, MEM_EXTENDED_PARAMETER * ExtendedParameters, DWORD ParameterCount);
MEMORY_MAPPED_VIEW_ADDRESS MapViewOfFile3(HANDLE FileMapping, HANDLE Process, void * BaseAddress, ULONGLONG Offset, void * ViewSize, VIRTUAL_ALLOCATION_TYPE AllocationType, DWORD PageProtection, MEM_EXTENDED_PARAMETER * ExtendedParameters, DWORD ParameterCount);
void * VirtualAlloc2FromApp(HANDLE Process, void * BaseAddress, void * Size, VIRTUAL_ALLOCATION_TYPE AllocationType, DWORD PageProtection, MEM_EXTENDED_PARAMETER * ExtendedParameters, DWORD ParameterCount);
MEMORY_MAPPED_VIEW_ADDRESS MapViewOfFile3FromApp(HANDLE FileMapping, HANDLE Process, void * BaseAddress, ULONGLONG Offset, void * ViewSize, VIRTUAL_ALLOCATION_TYPE AllocationType, DWORD PageProtection, MEM_EXTENDED_PARAMETER * ExtendedParameters, DWORD ParameterCount);
HANDLE CreateFileMapping2(HANDLE File, SECURITY_ATTRIBUTES * SecurityAttributes, DWORD DesiredAccess, PAGE_PROTECTION_FLAGS PageProtection, DWORD AllocationAttributes, ULONGLONG MaximumSize, LPWSTR Name, MEM_EXTENDED_PARAMETER * ExtendedParameters, DWORD ParameterCount);
BOOL AllocateUserPhysicalPages2(HANDLE ObjectHandle, void * * NumberOfPages, void * * PageArray, MEM_EXTENDED_PARAMETER * ExtendedParameters, DWORD ExtendedParameterCount);
HANDLE OpenDedicatedMemoryPartition(HANDLE Partition, ULONGLONG DedicatedMemoryTypeId, DWORD DesiredAccess, BOOL InheritHandle);
BOOL QueryPartitionInformation(HANDLE Partition, WIN32_MEMORY_PARTITION_INFORMATION_CLASS PartitionInformationClass, void * PartitionInformation, DWORD PartitionInformationLength);
void * RtlCompareMemory(void * Source1, void * Source2, void * Length);
DWORD RtlCrc32(void * Buffer, void * Size, DWORD InitialCrc);
ULONGLONG RtlCrc64(void * Buffer, void * Size, ULONGLONG InitialCrc);
BYTE RtlIsZeroMemory(void * Buffer, void * Length);
HGLOBAL GlobalAlloc(GLOBAL_ALLOC_FLAGS uFlags, void * dwBytes);
HGLOBAL GlobalReAlloc(HGLOBAL hMem, void * dwBytes, DWORD uFlags);
void * GlobalSize(HGLOBAL hMem);
BOOL GlobalUnlock(HGLOBAL hMem);
void * GlobalLock(HGLOBAL hMem);
DWORD GlobalFlags(HGLOBAL hMem);
HGLOBAL GlobalHandle(void * pMem);
HLOCAL LocalAlloc(LOCAL_ALLOC_FLAGS uFlags, void * uBytes);
HLOCAL LocalReAlloc(HLOCAL hMem, void * uBytes, DWORD uFlags);
void * LocalLock(HLOCAL hMem);
HLOCAL LocalHandle(void * pMem);
BOOL LocalUnlock(HLOCAL hMem);
void * LocalSize(HLOCAL hMem);
DWORD LocalFlags(HLOCAL hMem);
HANDLE CreateFileMappingA(HANDLE hFile, SECURITY_ATTRIBUTES * lpFileMappingAttributes, PAGE_PROTECTION_FLAGS flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPSTR lpName);
HANDLE CreateFileMappingNumaA(HANDLE hFile, SECURITY_ATTRIBUTES * lpFileMappingAttributes, PAGE_PROTECTION_FLAGS flProtect, DWORD dwMaximumSizeHigh, DWORD dwMaximumSizeLow, LPSTR lpName, DWORD nndPreferred);
HANDLE OpenFileMappingA(DWORD dwDesiredAccess, BOOL bInheritHandle, LPSTR lpName);
MEMORY_MAPPED_VIEW_ADDRESS MapViewOfFileExNuma(HANDLE hFileMappingObject, FILE_MAP dwDesiredAccess, DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, void * dwNumberOfBytesToMap, void * lpBaseAddress, DWORD nndPreferred);
BOOL IsBadReadPtr(void * lp, void * ucb);
BOOL IsBadWritePtr(void * lp, void * ucb);
BOOL IsBadCodePtr(FARPROC lpfn);
BOOL IsBadStringPtrA(LPSTR lpsz, void * ucchMax);
BOOL IsBadStringPtrW(LPWSTR lpsz, void * ucchMax);
BOOL MapUserPhysicalPagesScatter(void * * VirtualAddresses, void * NumberOfPages, void * * PageArray);
BOOL AddSecureMemoryCacheCallback(PSECURE_MEMORY_CACHE_CALLBACK pfnCallBack);
BOOL RemoveSecureMemoryCacheCallback(PSECURE_MEMORY_CACHE_CALLBACK pfnCallBack);
]]

return {
    FILE_CACHE_MAX_HARD_DISABLE = 0x00000002,
    FILE_CACHE_MAX_HARD_ENABLE = 0x00000001,
    FILE_CACHE_MIN_HARD_DISABLE = 0x00000008,
    FILE_CACHE_MIN_HARD_ENABLE = 0x00000004,
    MEHC_PATROL_SCRUBBER_PRESENT = 0x00000001,
    -- enum FILE_MAP
    FILE_MAP_FILE_MAP_WRITE = 0x00000002,
    FILE_MAP_FILE_MAP_READ = 0x00000004,
    FILE_MAP_FILE_MAP_ALL_ACCESS = 0x000F001F,
    FILE_MAP_FILE_MAP_EXECUTE = 0x00000020,
    FILE_MAP_FILE_MAP_COPY = 0x00000001,
    FILE_MAP_FILE_MAP_RESERVE = 0x80000000,
    FILE_MAP_FILE_MAP_TARGETS_INVALID = 0x40000000,
    FILE_MAP_FILE_MAP_LARGE_PAGES = 0x20000000,
    -- enum GLOBAL_ALLOC_FLAGS
    GLOBAL_ALLOC_FLAGS_GHND = 0x00000042,
    GLOBAL_ALLOC_FLAGS_GMEM_FIXED = 0x00000000,
    GLOBAL_ALLOC_FLAGS_GMEM_MOVEABLE = 0x00000002,
    GLOBAL_ALLOC_FLAGS_GMEM_ZEROINIT = 0x00000040,
    GLOBAL_ALLOC_FLAGS_GPTR = 0x00000040,
    -- enum HEAP_FLAGS
    HEAP_FLAGS_HEAP_NONE = 0x00000000,
    HEAP_FLAGS_HEAP_NO_SERIALIZE = 0x00000001,
    HEAP_FLAGS_HEAP_GROWABLE = 0x00000002,
    HEAP_FLAGS_HEAP_GENERATE_EXCEPTIONS = 0x00000004,
    HEAP_FLAGS_HEAP_ZERO_MEMORY = 0x00000008,
    HEAP_FLAGS_HEAP_REALLOC_IN_PLACE_ONLY = 0x00000010,
    HEAP_FLAGS_HEAP_TAIL_CHECKING_ENABLED = 0x00000020,
    HEAP_FLAGS_HEAP_FREE_CHECKING_ENABLED = 0x00000040,
    HEAP_FLAGS_HEAP_DISABLE_COALESCE_ON_FREE = 0x00000080,
    HEAP_FLAGS_HEAP_CREATE_ALIGN_16 = 0x00010000,
    HEAP_FLAGS_HEAP_CREATE_ENABLE_TRACING = 0x00020000,
    HEAP_FLAGS_HEAP_CREATE_ENABLE_EXECUTE = 0x00040000,
    HEAP_FLAGS_HEAP_MAXIMUM_TAG = 0x00000FFF,
    HEAP_FLAGS_HEAP_PSEUDO_TAG_FLAG = 0x00008000,
    HEAP_FLAGS_HEAP_TAG_SHIFT = 0x00000012,
    HEAP_FLAGS_HEAP_CREATE_SEGMENT_HEAP = 0x00000100,
    HEAP_FLAGS_HEAP_CREATE_HARDENED = 0x00000200,
    -- enum HEAP_INFORMATION_CLASS
    HEAP_INFORMATION_CLASS_HeapCompatibilityInformation = 0,
    HEAP_INFORMATION_CLASS_HeapEnableTerminationOnCorruption = 1,
    HEAP_INFORMATION_CLASS_HeapOptimizeResources = 3,
    HEAP_INFORMATION_CLASS_HeapTag = 7,
    -- enum LOCAL_ALLOC_FLAGS
    LOCAL_ALLOC_FLAGS_LHND = 0x00000042,
    LOCAL_ALLOC_FLAGS_LMEM_FIXED = 0x00000000,
    LOCAL_ALLOC_FLAGS_LMEM_MOVEABLE = 0x00000002,
    LOCAL_ALLOC_FLAGS_LMEM_ZEROINIT = 0x00000040,
    LOCAL_ALLOC_FLAGS_LPTR = 0x00000040,
    LOCAL_ALLOC_FLAGS_NONZEROLHND = 0x00000002,
    LOCAL_ALLOC_FLAGS_NONZEROLPTR = 0x00000000,
    -- enum MEM_DEDICATED_ATTRIBUTE_TYPE
    MEM_DEDICATED_ATTRIBUTE_TYPE_MemDedicatedAttributeReadBandwidth = 0,
    MEM_DEDICATED_ATTRIBUTE_TYPE_MemDedicatedAttributeReadLatency = 1,
    MEM_DEDICATED_ATTRIBUTE_TYPE_MemDedicatedAttributeWriteBandwidth = 2,
    MEM_DEDICATED_ATTRIBUTE_TYPE_MemDedicatedAttributeWriteLatency = 3,
    MEM_DEDICATED_ATTRIBUTE_TYPE_MemDedicatedAttributeMax = 4,
    -- enum MEM_EXTENDED_PARAMETER_TYPE
    MEM_EXTENDED_PARAMETER_TYPE_MemExtendedParameterInvalidType = 0,
    MEM_EXTENDED_PARAMETER_TYPE_MemExtendedParameterAddressRequirements = 1,
    MEM_EXTENDED_PARAMETER_TYPE_MemExtendedParameterNumaNode = 2,
    MEM_EXTENDED_PARAMETER_TYPE_MemExtendedParameterPartitionHandle = 3,
    MEM_EXTENDED_PARAMETER_TYPE_MemExtendedParameterUserPhysicalHandle = 4,
    MEM_EXTENDED_PARAMETER_TYPE_MemExtendedParameterAttributeFlags = 5,
    MEM_EXTENDED_PARAMETER_TYPE_MemExtendedParameterImageMachine = 6,
    MEM_EXTENDED_PARAMETER_TYPE_MemExtendedParameterMax = 7,
    -- enum MEM_SECTION_EXTENDED_PARAMETER_TYPE
    MEM_SECTION_EXTENDED_PARAMETER_TYPE_MemSectionExtendedParameterInvalidType = 0,
    MEM_SECTION_EXTENDED_PARAMETER_TYPE_MemSectionExtendedParameterUserPhysicalFlags = 1,
    MEM_SECTION_EXTENDED_PARAMETER_TYPE_MemSectionExtendedParameterNumaNode = 2,
    MEM_SECTION_EXTENDED_PARAMETER_TYPE_MemSectionExtendedParameterSigningLevel = 3,
    MEM_SECTION_EXTENDED_PARAMETER_TYPE_MemSectionExtendedParameterMax = 4,
    -- enum MEMORY_RESOURCE_NOTIFICATION_TYPE
    MEMORY_RESOURCE_NOTIFICATION_TYPE_LowMemoryResourceNotification = 0,
    MEMORY_RESOURCE_NOTIFICATION_TYPE_HighMemoryResourceNotification = 1,
    -- enum OFFER_PRIORITY
    OFFER_PRIORITY_VmOfferPriorityVeryLow = 1,
    OFFER_PRIORITY_VmOfferPriorityLow = 2,
    OFFER_PRIORITY_VmOfferPriorityBelowNormal = 3,
    OFFER_PRIORITY_VmOfferPriorityNormal = 4,
    -- enum PAGE_PROTECTION_FLAGS
    PAGE_PROTECTION_FLAGS_PAGE_NOACCESS = 0x00000001,
    PAGE_PROTECTION_FLAGS_PAGE_READONLY = 0x00000002,
    PAGE_PROTECTION_FLAGS_PAGE_READWRITE = 0x00000004,
    PAGE_PROTECTION_FLAGS_PAGE_WRITECOPY = 0x00000008,
    PAGE_PROTECTION_FLAGS_PAGE_EXECUTE = 0x00000010,
    PAGE_PROTECTION_FLAGS_PAGE_EXECUTE_READ = 0x00000020,
    PAGE_PROTECTION_FLAGS_PAGE_EXECUTE_READWRITE = 0x00000040,
    PAGE_PROTECTION_FLAGS_PAGE_EXECUTE_WRITECOPY = 0x00000080,
    PAGE_PROTECTION_FLAGS_PAGE_GUARD = 0x00000100,
    PAGE_PROTECTION_FLAGS_PAGE_NOCACHE = 0x00000200,
    PAGE_PROTECTION_FLAGS_PAGE_WRITECOMBINE = 0x00000400,
    PAGE_PROTECTION_FLAGS_PAGE_GRAPHICS_NOACCESS = 0x00000800,
    PAGE_PROTECTION_FLAGS_PAGE_GRAPHICS_READONLY = 0x00001000,
    PAGE_PROTECTION_FLAGS_PAGE_GRAPHICS_READWRITE = 0x00002000,
    PAGE_PROTECTION_FLAGS_PAGE_GRAPHICS_EXECUTE = 0x00004000,
    PAGE_PROTECTION_FLAGS_PAGE_GRAPHICS_EXECUTE_READ = 0x00008000,
    PAGE_PROTECTION_FLAGS_PAGE_GRAPHICS_EXECUTE_READWRITE = 0x00010000,
    PAGE_PROTECTION_FLAGS_PAGE_GRAPHICS_COHERENT = 0x00020000,
    PAGE_PROTECTION_FLAGS_PAGE_GRAPHICS_NOCACHE = 0x00040000,
    PAGE_PROTECTION_FLAGS_PAGE_ENCLAVE_THREAD_CONTROL = 0x80000000,
    PAGE_PROTECTION_FLAGS_PAGE_REVERT_TO_FILE_MAP = 0x80000000,
    PAGE_PROTECTION_FLAGS_PAGE_TARGETS_NO_UPDATE = 0x40000000,
    PAGE_PROTECTION_FLAGS_PAGE_TARGETS_INVALID = 0x40000000,
    PAGE_PROTECTION_FLAGS_PAGE_ENCLAVE_UNVALIDATED = 0x20000000,
    PAGE_PROTECTION_FLAGS_PAGE_ENCLAVE_MASK = 0x10000000,
    PAGE_PROTECTION_FLAGS_PAGE_ENCLAVE_DECOMMIT = 0x10000000,
    PAGE_PROTECTION_FLAGS_PAGE_ENCLAVE_SS_FIRST = 0x10000001,
    PAGE_PROTECTION_FLAGS_PAGE_ENCLAVE_SS_REST = 0x10000002,
    PAGE_PROTECTION_FLAGS_SEC_PARTITION_OWNER_HANDLE = 0x00040000,
    PAGE_PROTECTION_FLAGS_SEC_64K_PAGES = 0x00080000,
    PAGE_PROTECTION_FLAGS_SEC_FILE = 0x00800000,
    PAGE_PROTECTION_FLAGS_SEC_IMAGE = 0x01000000,
    PAGE_PROTECTION_FLAGS_SEC_PROTECTED_IMAGE = 0x02000000,
    PAGE_PROTECTION_FLAGS_SEC_RESERVE = 0x04000000,
    PAGE_PROTECTION_FLAGS_SEC_COMMIT = 0x08000000,
    PAGE_PROTECTION_FLAGS_SEC_NOCACHE = 0x10000000,
    PAGE_PROTECTION_FLAGS_SEC_WRITECOMBINE = 0x40000000,
    PAGE_PROTECTION_FLAGS_SEC_LARGE_PAGES = 0x80000000,
    PAGE_PROTECTION_FLAGS_SEC_IMAGE_NO_EXECUTE = 0x11000000,
    -- enum PAGE_TYPE
    PAGE_TYPE_MEM_PRIVATE = 0x00020000,
    PAGE_TYPE_MEM_MAPPED = 0x00040000,
    PAGE_TYPE_MEM_IMAGE = 0x01000000,
    -- enum SECTION_FLAGS
    SECTION_FLAGS_SECTION_ALL_ACCESS = 0x000F001F,
    SECTION_FLAGS_SECTION_QUERY = 0x00000001,
    SECTION_FLAGS_SECTION_MAP_WRITE = 0x00000002,
    SECTION_FLAGS_SECTION_MAP_READ = 0x00000004,
    SECTION_FLAGS_SECTION_MAP_EXECUTE = 0x00000008,
    SECTION_FLAGS_SECTION_EXTEND_SIZE = 0x00000010,
    SECTION_FLAGS_SECTION_MAP_EXECUTE_EXPLICIT = 0x00000020,
    -- enum SETPROCESSWORKINGSETSIZEEX_FLAGS
    SETPROCESSWORKINGSETSIZEEX_FLAGS_QUOTA_LIMITS_HARDWS_MIN_ENABLE = 0x00000001,
    SETPROCESSWORKINGSETSIZEEX_FLAGS_QUOTA_LIMITS_HARDWS_MIN_DISABLE = 0x00000002,
    SETPROCESSWORKINGSETSIZEEX_FLAGS_QUOTA_LIMITS_HARDWS_MAX_ENABLE = 0x00000004,
    SETPROCESSWORKINGSETSIZEEX_FLAGS_QUOTA_LIMITS_HARDWS_MAX_DISABLE = 0x00000008,
    -- enum UNMAP_VIEW_OF_FILE_FLAGS
    UNMAP_VIEW_OF_FILE_FLAGS_MEM_UNMAP_NONE = 0x00000000,
    UNMAP_VIEW_OF_FILE_FLAGS_MEM_UNMAP_WITH_TRANSIENT_BOOST = 0x00000001,
    UNMAP_VIEW_OF_FILE_FLAGS_MEM_PRESERVE_PLACEHOLDER = 0x00000002,
    -- enum VIRTUAL_ALLOCATION_TYPE
    VIRTUAL_ALLOCATION_TYPE_MEM_COMMIT = 0x00001000,
    VIRTUAL_ALLOCATION_TYPE_MEM_RESERVE = 0x00002000,
    VIRTUAL_ALLOCATION_TYPE_MEM_RESET = 0x00080000,
    VIRTUAL_ALLOCATION_TYPE_MEM_RESET_UNDO = 0x01000000,
    VIRTUAL_ALLOCATION_TYPE_MEM_REPLACE_PLACEHOLDER = 0x00004000,
    VIRTUAL_ALLOCATION_TYPE_MEM_LARGE_PAGES = 0x20000000,
    VIRTUAL_ALLOCATION_TYPE_MEM_RESERVE_PLACEHOLDER = 0x00040000,
    VIRTUAL_ALLOCATION_TYPE_MEM_FREE = 0x00010000,
    -- enum VIRTUAL_FREE_TYPE
    VIRTUAL_FREE_TYPE_MEM_DECOMMIT = 0x00004000,
    VIRTUAL_FREE_TYPE_MEM_RELEASE = 0x00008000,
    -- enum WIN32_MEMORY_INFORMATION_CLASS
    WIN32_MEMORY_INFORMATION_CLASS_MemoryRegionInfo = 0,
    -- enum WIN32_MEMORY_PARTITION_INFORMATION_CLASS
    WIN32_MEMORY_PARTITION_INFORMATION_CLASS_MemoryPartitionInfo = 0,
    WIN32_MEMORY_PARTITION_INFORMATION_CLASS_MemoryPartitionDedicatedMemoryInfo = 1,
}
