-- AUTO-GENERATED by tools/winmd-gen (via gen-windows-package.ps1)
-- Namespace: Windows.Win32.System.Threading
-- Counts: 35 structs, 0 unions, 29 enums, 4 COM interfaces, 337 functions, 57 constants, 8 handle typedefs, 6 nested unions/structs, 18 delegates
--
local W = require "windows"

ffi.cdef[[
/* primitive Win32 typedefs (idempotent vs. runtime built-ins) */
typedef char               CHAR;

typedef struct _winmdgen_GUID_W {
    DWORD Data1; WORD Data2; WORD Data3; BYTE Data4[8];
} GUID_W;

typedef void * LPPROC_THREAD_ATTRIBUTE_LIST;
typedef void * PTP_CALLBACK_INSTANCE;
typedef void * PTP_CLEANUP_GROUP;
typedef void * PTP_IO;
typedef void * PTP_POOL;
typedef void * PTP_TIMER;
typedef void * PTP_WAIT;
typedef void * PTP_WORK;
typedef void *PSID;

/* enum typedefs (members live in the return table below) */
typedef LONG AVRT_PRIORITY;
typedef DWORD CREATE_EVENT;
typedef DWORD CREATE_PROCESS_LOGON_FLAGS;
typedef DWORD GET_GUI_RESOURCES_FLAGS;
typedef LONG MACHINE_ATTRIBUTES;
typedef DWORD MEMORY_PRIORITY;
typedef DWORD POWER_REQUEST_CONTEXT_FLAGS;
typedef DWORD PROC_THREAD_ATTRIBUTE_NUM;
typedef DWORD PROCESS_ACCESS_RIGHTS;
typedef DWORD PROCESS_AFFINITY_AUTO_UPDATE_FLAGS;
typedef DWORD PROCESS_CREATION_FLAGS;
typedef DWORD PROCESS_DEP_FLAGS;
typedef LONG PROCESS_INFORMATION_CLASS;
typedef LONG PROCESS_MEMORY_EXHAUSTION_TYPE;
typedef LONG PROCESS_MITIGATION_POLICY;
typedef DWORD PROCESS_NAME_FORMAT;
typedef DWORD PROCESS_PROTECTION_LEVEL;
typedef DWORD PROCESSOR_FEATURE_ID;
typedef LONG QUEUE_USER_APC_FLAGS;
typedef LONG RTWQ_WORKQUEUE_TYPE;
typedef DWORD STARTUPINFOW_FLAGS;
typedef DWORD SYNCHRONIZATION_ACCESS_RIGHTS;
typedef DWORD THREAD_ACCESS_RIGHTS;
typedef DWORD THREAD_CREATION_FLAGS;
typedef LONG THREAD_INFORMATION_CLASS;
typedef LONG THREAD_PRIORITY;
typedef LONG TP_CALLBACK_PRIORITY;
typedef LONG UMS_THREAD_INFO_CLASS;
typedef DWORD WORKER_THREAD_FLAGS;

/* cross-namespace enum typedefs */
typedef WORD IMAGE_FILE_MACHINE;
typedef LONG RTL_UMS_SCHEDULER_REASON;
typedef DWORD TOKEN_ACCESS_MASK;
typedef DWORD WAIT_EVENT;

typedef struct _PROCESS_BASIC_INFORMATION PROCESS_BASIC_INFORMATION;
typedef struct _REASON_CONTEXT REASON_CONTEXT;
typedef struct _PROCESS_INFORMATION PROCESS_INFORMATION;
typedef struct _STARTUPINFOA STARTUPINFOA;
typedef struct _STARTUPINFOW STARTUPINFOW;
typedef struct _MEMORY_PRIORITY_INFORMATION MEMORY_PRIORITY_INFORMATION;
typedef struct _THREAD_POWER_THROTTLING_STATE THREAD_POWER_THROTTLING_STATE;
typedef struct _APP_MEMORY_INFORMATION APP_MEMORY_INFORMATION;
typedef struct _PROCESS_MACHINE_INFORMATION PROCESS_MACHINE_INFORMATION;
typedef struct _OVERRIDE_PREFETCH_PARAMETER OVERRIDE_PREFETCH_PARAMETER;
typedef struct _PROCESS_MEMORY_EXHAUSTION_INFO PROCESS_MEMORY_EXHAUSTION_INFO;
typedef struct _PROCESS_POWER_THROTTLING_STATE PROCESS_POWER_THROTTLING_STATE;
typedef struct _PROCESS_PROTECTION_LEVEL_INFORMATION PROCESS_PROTECTION_LEVEL_INFORMATION;
typedef struct _PROCESS_LEAP_SECOND_INFO PROCESS_LEAP_SECOND_INFO;
typedef struct _PROCESS_DYNAMIC_EH_CONTINUATION_TARGET PROCESS_DYNAMIC_EH_CONTINUATION_TARGET;
typedef struct _PROCESS_DYNAMIC_EH_CONTINUATION_TARGETS_INFORMATION PROCESS_DYNAMIC_EH_CONTINUATION_TARGETS_INFORMATION;
typedef struct _PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGE PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGE;
typedef struct _PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGES_INFORMATION PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGES_INFORMATION;
typedef struct _IO_COUNTERS IO_COUNTERS;
typedef struct _INIT_ONCE INIT_ONCE;
typedef struct _SYNCHRONIZATION_BARRIER SYNCHRONIZATION_BARRIER;
typedef struct _CRITICAL_SECTION_DEBUG CRITICAL_SECTION_DEBUG;
typedef struct _CRITICAL_SECTION CRITICAL_SECTION;
typedef struct _SRWLOCK SRWLOCK;
typedef struct _CONDITION_VARIABLE CONDITION_VARIABLE;
typedef struct _TP_POOL_STACK_INFORMATION TP_POOL_STACK_INFORMATION;
typedef struct _TP_CALLBACK_ENVIRON_V3 TP_CALLBACK_ENVIRON_V3;
typedef struct _UMS_SCHEDULER_STARTUP_INFO UMS_SCHEDULER_STARTUP_INFO;
typedef struct _UMS_SYSTEM_THREAD_INFORMATION UMS_SYSTEM_THREAD_INFORMATION;
typedef struct _STARTUPINFOEXA STARTUPINFOEXA;
typedef struct _STARTUPINFOEXW STARTUPINFOEXW;
typedef struct _PEB_LDR_DATA PEB_LDR_DATA;
typedef struct _RTL_USER_PROCESS_PARAMETERS RTL_USER_PROCESS_PARAMETERS;
typedef struct _PEB PEB;
typedef struct _TEB TEB;
typedef union __Reason_e__Union_tag _Reason_e__Union;
typedef struct __Detailed_e__Struct_tag _Detailed_e__Struct;
typedef union __u_e__Union_tag _u_e__Union;
typedef struct __s_e__Struct_tag _s_e__Struct;
typedef union __Anonymous_e__Union_tag _Anonymous_e__Union;
typedef struct __Anonymous_e__Struct_tag _Anonymous_e__Struct;
typedef struct IRtwqAsyncResult IRtwqAsyncResult;
typedef struct IRtwqAsyncResultVtbl IRtwqAsyncResultVtbl;
typedef struct IRtwqAsyncCallback IRtwqAsyncCallback;
typedef struct IRtwqAsyncCallbackVtbl IRtwqAsyncCallbackVtbl;
typedef struct RTWQASYNCRESULT RTWQASYNCRESULT;
typedef struct RTWQASYNCRESULTVtbl RTWQASYNCRESULTVtbl;
typedef struct IRtwqPlatformEvents IRtwqPlatformEvents;
typedef struct IRtwqPlatformEventsVtbl IRtwqPlatformEventsVtbl;
typedef struct _GROUP_AFFINITY_opaque GROUP_AFFINITY;
typedef struct _IUnknown_opaque IUnknown;
typedef struct _LIST_ENTRY_opaque LIST_ENTRY;
typedef struct _PROCESSOR_NUMBER_opaque PROCESSOR_NUMBER;
typedef struct _SLIST_ENTRY_opaque SLIST_ENTRY;
typedef struct _SLIST_HEADER_opaque SLIST_HEADER;
typedef struct _UNICODE_STRING_opaque UNICODE_STRING;

/* callback (function-pointer) typedefs */
typedef DWORD (*LPTHREAD_START_ROUTINE)(void *);
typedef BOOL (*PINIT_ONCE_FN)(INIT_ONCE *, void *, void * *);
typedef void (*PTIMERAPCROUTINE)(void *, DWORD, DWORD);
typedef void (*PTP_WIN32_IO_CALLBACK)(PTP_CALLBACK_INSTANCE, void *, void *, DWORD, void *, PTP_IO);
typedef void (*RTWQPERIODICCALLBACK)(IUnknown);
typedef void (*PRTL_UMS_SCHEDULER_ENTRY_POINT)(RTL_UMS_SCHEDULER_REASON, void *, void *);
typedef void (*WAITORTIMERCALLBACK)(void *, BYTE);
typedef void (*WORKERCALLBACKFUNC)(void *);
typedef void (*APC_CALLBACK_FUNCTION)(DWORD, void *, void *);
typedef void (*PFLS_CALLBACK_FUNCTION)(void *);
typedef void (*PTP_SIMPLE_CALLBACK)(PTP_CALLBACK_INSTANCE, void *);
typedef void (*PTP_CLEANUP_GROUP_CANCEL_CALLBACK)(void *, void *);
typedef void (*PTP_WORK_CALLBACK)(PTP_CALLBACK_INSTANCE, void *, PTP_WORK);
typedef void (*PTP_TIMER_CALLBACK)(PTP_CALLBACK_INSTANCE, void *, PTP_TIMER);
typedef void (*PTP_WAIT_CALLBACK)(PTP_CALLBACK_INSTANCE, void *, PTP_WAIT, DWORD);
typedef void (*LPFIBER_START_ROUTINE)(void *);
typedef void (*PPS_POST_PROCESS_INIT_ROUTINE)(void);
typedef void (*PAPCFUNC)(void *);

union __Reason_e__Union_tag {
    _Detailed_e__Struct Detailed;
    LPWSTR SimpleReasonString;
};
struct __Detailed_e__Struct_tag {
    HMODULE LocalizedReasonModule;
    DWORD LocalizedReasonId;
    DWORD ReasonStringCount;
    LPWSTR * ReasonStrings;
};
union __u_e__Union_tag {
    DWORD Flags;
    _s_e__Struct s;
};
struct __s_e__Struct_tag {
    DWORD _bitfield;
};
union __Anonymous_e__Union_tag {
    _Anonymous_e__Struct Anonymous;
    DWORD ThreadUmsFlags;
};
struct __Anonymous_e__Struct_tag {
    DWORD _bitfield;
};
struct _PROCESS_BASIC_INFORMATION {
    NTSTATUS ExitStatus;
    PEB * PebBaseAddress;
    void * AffinityMask;
    LONG BasePriority;
    void * UniqueProcessId;
    void * InheritedFromUniqueProcessId;
};
struct _REASON_CONTEXT {
    DWORD Version;
    POWER_REQUEST_CONTEXT_FLAGS Flags;
    _Reason_e__Union Reason;
};
struct _PROCESS_INFORMATION {
    HANDLE hProcess;
    HANDLE hThread;
    DWORD dwProcessId;
    DWORD dwThreadId;
};
struct _STARTUPINFOA {
    DWORD cb;
    LPSTR lpReserved;
    LPSTR lpDesktop;
    LPSTR lpTitle;
    DWORD dwX;
    DWORD dwY;
    DWORD dwXSize;
    DWORD dwYSize;
    DWORD dwXCountChars;
    DWORD dwYCountChars;
    DWORD dwFillAttribute;
    STARTUPINFOW_FLAGS dwFlags;
    WORD wShowWindow;
    WORD cbReserved2;
    BYTE * lpReserved2;
    HANDLE hStdInput;
    HANDLE hStdOutput;
    HANDLE hStdError;
};
struct _STARTUPINFOW {
    DWORD cb;
    LPWSTR lpReserved;
    LPWSTR lpDesktop;
    LPWSTR lpTitle;
    DWORD dwX;
    DWORD dwY;
    DWORD dwXSize;
    DWORD dwYSize;
    DWORD dwXCountChars;
    DWORD dwYCountChars;
    DWORD dwFillAttribute;
    STARTUPINFOW_FLAGS dwFlags;
    WORD wShowWindow;
    WORD cbReserved2;
    BYTE * lpReserved2;
    HANDLE hStdInput;
    HANDLE hStdOutput;
    HANDLE hStdError;
};
struct _MEMORY_PRIORITY_INFORMATION {
    MEMORY_PRIORITY MemoryPriority;
};
struct _THREAD_POWER_THROTTLING_STATE {
    DWORD Version;
    DWORD ControlMask;
    DWORD StateMask;
};
struct _APP_MEMORY_INFORMATION {
    ULONGLONG AvailableCommit;
    ULONGLONG PrivateCommitUsage;
    ULONGLONG PeakPrivateCommitUsage;
    ULONGLONG TotalCommitUsage;
};
struct _PROCESS_MACHINE_INFORMATION {
    IMAGE_FILE_MACHINE ProcessMachine;
    WORD Res0;
    MACHINE_ATTRIBUTES MachineAttributes;
};
struct _OVERRIDE_PREFETCH_PARAMETER {
    DWORD Value;
};
struct _PROCESS_MEMORY_EXHAUSTION_INFO {
    WORD Version;
    WORD Reserved;
    PROCESS_MEMORY_EXHAUSTION_TYPE Type;
    void * Value;
};
struct _PROCESS_POWER_THROTTLING_STATE {
    DWORD Version;
    DWORD ControlMask;
    DWORD StateMask;
};
struct _PROCESS_PROTECTION_LEVEL_INFORMATION {
    PROCESS_PROTECTION_LEVEL ProtectionLevel;
};
struct _PROCESS_LEAP_SECOND_INFO {
    DWORD Flags;
    DWORD Reserved;
};
struct _PROCESS_DYNAMIC_EH_CONTINUATION_TARGET {
    void * TargetAddress;
    void * Flags;
};
struct _PROCESS_DYNAMIC_EH_CONTINUATION_TARGETS_INFORMATION {
    WORD NumberOfTargets;
    WORD Reserved;
    DWORD Reserved2;
    PROCESS_DYNAMIC_EH_CONTINUATION_TARGET * Targets;
};
struct _PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGE {
    void * BaseAddress;
    void * Size;
    DWORD Flags;
};
struct _PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGES_INFORMATION {
    WORD NumberOfRanges;
    WORD Reserved;
    DWORD Reserved2;
    PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGE * Ranges;
};
struct _IO_COUNTERS {
    ULONGLONG ReadOperationCount;
    ULONGLONG WriteOperationCount;
    ULONGLONG OtherOperationCount;
    ULONGLONG ReadTransferCount;
    ULONGLONG WriteTransferCount;
    ULONGLONG OtherTransferCount;
};
struct _INIT_ONCE {
    void * Ptr;
};
struct _SYNCHRONIZATION_BARRIER {
    DWORD Reserved1;
    DWORD Reserved2;
    void * * Reserved3;
    DWORD Reserved4;
    DWORD Reserved5;
};
struct _CRITICAL_SECTION_DEBUG {
    WORD Type;
    WORD CreatorBackTraceIndex;
    CRITICAL_SECTION * CriticalSection;
    LIST_ENTRY ProcessLocksList;
    DWORD EntryCount;
    DWORD ContentionCount;
    DWORD Flags;
    WORD CreatorBackTraceIndexHigh;
    WORD Identifier;
};
struct _CRITICAL_SECTION {
    CRITICAL_SECTION_DEBUG * DebugInfo;
    LONG LockCount;
    LONG RecursionCount;
    HANDLE OwningThread;
    HANDLE LockSemaphore;
    void * SpinCount;
};
struct _SRWLOCK {
    void * Ptr;
};
struct _CONDITION_VARIABLE {
    void * Ptr;
};
struct _TP_POOL_STACK_INFORMATION {
    void * StackReserve;
    void * StackCommit;
};
struct _TP_CALLBACK_ENVIRON_V3 {
    DWORD Version;
    PTP_POOL Pool;
    PTP_CLEANUP_GROUP CleanupGroup;
    PTP_CLEANUP_GROUP_CANCEL_CALLBACK CleanupGroupCancelCallback;
    void * RaceDll;
    void * ActivationContext;
    PTP_SIMPLE_CALLBACK FinalizationCallback;
    _u_e__Union u;
    TP_CALLBACK_PRIORITY CallbackPriority;
    DWORD Size;
};
struct _UMS_SCHEDULER_STARTUP_INFO {
    DWORD UmsVersion;
    void * CompletionList;
    PRTL_UMS_SCHEDULER_ENTRY_POINT SchedulerProc;
    void * SchedulerParam;
};
struct _UMS_SYSTEM_THREAD_INFORMATION {
    DWORD UmsVersion;
    _Anonymous_e__Union Anonymous;
};
struct _STARTUPINFOEXA {
    STARTUPINFOA StartupInfo;
    LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList;
};
struct _STARTUPINFOEXW {
    STARTUPINFOW StartupInfo;
    LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList;
};
struct _PEB_LDR_DATA {
    BYTE * Reserved1;
    void * * Reserved2;
    LIST_ENTRY InMemoryOrderModuleList;
};
struct _RTL_USER_PROCESS_PARAMETERS {
    BYTE * Reserved1;
    void * * Reserved2;
    UNICODE_STRING ImagePathName;
    UNICODE_STRING CommandLine;
};
struct _PEB {
    BYTE * Reserved1;
    BYTE BeingDebugged;
    BYTE * Reserved2;
    void * * Reserved3;
    PEB_LDR_DATA * Ldr;
    RTL_USER_PROCESS_PARAMETERS * ProcessParameters;
    void * * Reserved4;
    void * AtlThunkSListPtr;
    void * Reserved5;
    DWORD Reserved6;
    void * Reserved7;
    DWORD Reserved8;
    DWORD AtlThunkSListPtr32;
    void * * Reserved9;
    BYTE * Reserved10;
    PPS_POST_PROCESS_INIT_ROUTINE PostProcessInitRoutine;
    BYTE * Reserved11;
    void * * Reserved12;
    DWORD SessionId;
};
struct _TEB {
    void * * Reserved1;
    PEB * ProcessEnvironmentBlock;
    void * * Reserved2;
    BYTE * Reserved3;
    void * * TlsSlots;
    BYTE * Reserved4;
    void * * Reserved5;
    void * ReservedForOle;
    void * * Reserved6;
    void * TlsExpansionSlots;
};
/* ===== COM interfaces ===== */
struct IRtwqAsyncResultVtbl {
    HRESULT (__stdcall *QueryInterface)(IRtwqAsyncResult *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IRtwqAsyncResult *This);
    ULONG (__stdcall *Release)(IRtwqAsyncResult *This);
    HRESULT (__stdcall *GetState)(IRtwqAsyncResult *This, IUnknown * ppunkState);
    HRESULT (__stdcall *GetStatus)(IRtwqAsyncResult *This);
    HRESULT (__stdcall *SetStatus)(IRtwqAsyncResult *This, HRESULT hrStatus);
    HRESULT (__stdcall *GetObject)(IRtwqAsyncResult *This, IUnknown * ppObject);
    IUnknown (__stdcall *GetStateNoAddRef)(IRtwqAsyncResult *This);
};
struct IRtwqAsyncResult { IRtwqAsyncResultVtbl *lpVtbl; };
struct IRtwqAsyncCallbackVtbl {
    HRESULT (__stdcall *QueryInterface)(IRtwqAsyncCallback *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IRtwqAsyncCallback *This);
    ULONG (__stdcall *Release)(IRtwqAsyncCallback *This);
    HRESULT (__stdcall *GetParameters)(IRtwqAsyncCallback *This, DWORD * pdwFlags, DWORD * pdwQueue);
    HRESULT (__stdcall *Invoke)(IRtwqAsyncCallback *This, IRtwqAsyncResult pAsyncResult);
};
struct IRtwqAsyncCallback { IRtwqAsyncCallbackVtbl *lpVtbl; };
struct RTWQASYNCRESULTVtbl {
    HRESULT (__stdcall *QueryInterface)(RTWQASYNCRESULT *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(RTWQASYNCRESULT *This);
    ULONG (__stdcall *Release)(RTWQASYNCRESULT *This);
    HRESULT (__stdcall *GetState)(RTWQASYNCRESULT *This, IUnknown * ppunkState);
    HRESULT (__stdcall *GetStatus)(RTWQASYNCRESULT *This);
    HRESULT (__stdcall *SetStatus)(RTWQASYNCRESULT *This, HRESULT hrStatus);
    HRESULT (__stdcall *GetObject)(RTWQASYNCRESULT *This, IUnknown * ppObject);
    IUnknown (__stdcall *GetStateNoAddRef)(RTWQASYNCRESULT *This);
};
struct RTWQASYNCRESULT { RTWQASYNCRESULTVtbl *lpVtbl; };
struct IRtwqPlatformEventsVtbl {
    HRESULT (__stdcall *QueryInterface)(IRtwqPlatformEvents *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IRtwqPlatformEvents *This);
    ULONG (__stdcall *Release)(IRtwqPlatformEvents *This);
    HRESULT (__stdcall *InitializationComplete)(IRtwqPlatformEvents *This);
    HRESULT (__stdcall *ShutdownStart)(IRtwqPlatformEvents *This);
    HRESULT (__stdcall *ShutdownComplete)(IRtwqPlatformEvents *This);
};
struct IRtwqPlatformEvents { IRtwqPlatformEventsVtbl *lpVtbl; };
/* System.Threading -- 337 functions */
HANDLE GetCurrentProcessToken();
HANDLE GetCurrentThreadToken();
HANDLE GetCurrentThreadEffectiveToken();
BOOL GetProcessWorkingSetSize(HANDLE hProcess, void * * lpMinimumWorkingSetSize, void * * lpMaximumWorkingSetSize);
BOOL SetProcessWorkingSetSize(HANDLE hProcess, void * dwMinimumWorkingSetSize, void * dwMaximumWorkingSetSize);
DWORD FlsAlloc(PFLS_CALLBACK_FUNCTION lpCallback);
void * FlsGetValue(DWORD dwFlsIndex);
BOOL FlsSetValue(DWORD dwFlsIndex, void * lpFlsData);
BOOL FlsFree(DWORD dwFlsIndex);
BOOL IsThreadAFiber();
void InitializeSRWLock(SRWLOCK * SRWLock);
void ReleaseSRWLockExclusive(SRWLOCK * SRWLock);
void ReleaseSRWLockShared(SRWLOCK * SRWLock);
void AcquireSRWLockExclusive(SRWLOCK * SRWLock);
void AcquireSRWLockShared(SRWLOCK * SRWLock);
BYTE TryAcquireSRWLockExclusive(SRWLOCK * SRWLock);
BYTE TryAcquireSRWLockShared(SRWLOCK * SRWLock);
void InitializeCriticalSection(CRITICAL_SECTION * lpCriticalSection);
void EnterCriticalSection(CRITICAL_SECTION * lpCriticalSection);
void LeaveCriticalSection(CRITICAL_SECTION * lpCriticalSection);
BOOL InitializeCriticalSectionAndSpinCount(CRITICAL_SECTION * lpCriticalSection, DWORD dwSpinCount);
BOOL InitializeCriticalSectionEx(CRITICAL_SECTION * lpCriticalSection, DWORD dwSpinCount, DWORD Flags);
DWORD SetCriticalSectionSpinCount(CRITICAL_SECTION * lpCriticalSection, DWORD dwSpinCount);
BOOL TryEnterCriticalSection(CRITICAL_SECTION * lpCriticalSection);
void DeleteCriticalSection(CRITICAL_SECTION * lpCriticalSection);
void InitOnceInitialize(INIT_ONCE * InitOnce);
BOOL InitOnceExecuteOnce(INIT_ONCE * InitOnce, PINIT_ONCE_FN InitFn, void * Parameter, void * * Context);
BOOL InitOnceBeginInitialize(INIT_ONCE * lpInitOnce, DWORD dwFlags, BOOL * fPending, void * * lpContext);
BOOL InitOnceComplete(INIT_ONCE * lpInitOnce, DWORD dwFlags, void * lpContext);
void InitializeConditionVariable(CONDITION_VARIABLE * ConditionVariable);
void WakeConditionVariable(CONDITION_VARIABLE * ConditionVariable);
void WakeAllConditionVariable(CONDITION_VARIABLE * ConditionVariable);
BOOL SleepConditionVariableCS(CONDITION_VARIABLE * ConditionVariable, CRITICAL_SECTION * CriticalSection, DWORD dwMilliseconds);
BOOL SleepConditionVariableSRW(CONDITION_VARIABLE * ConditionVariable, SRWLOCK * SRWLock, DWORD dwMilliseconds, DWORD Flags);
BOOL SetEvent(HANDLE hEvent);
BOOL ResetEvent(HANDLE hEvent);
BOOL ReleaseSemaphore(HANDLE hSemaphore, LONG lReleaseCount, LONG * lpPreviousCount);
BOOL ReleaseMutex(HANDLE hMutex);
WAIT_EVENT WaitForSingleObject(HANDLE hHandle, DWORD dwMilliseconds);
DWORD SleepEx(DWORD dwMilliseconds, BOOL bAlertable);
WAIT_EVENT WaitForSingleObjectEx(HANDLE hHandle, DWORD dwMilliseconds, BOOL bAlertable);
WAIT_EVENT WaitForMultipleObjectsEx(DWORD nCount, HANDLE * lpHandles, BOOL bWaitAll, DWORD dwMilliseconds, BOOL bAlertable);
HANDLE CreateMutexA(SECURITY_ATTRIBUTES * lpMutexAttributes, BOOL bInitialOwner, LPSTR lpName);
HANDLE CreateMutexW(SECURITY_ATTRIBUTES * lpMutexAttributes, BOOL bInitialOwner, LPWSTR lpName);
HANDLE OpenMutexW(SYNCHRONIZATION_ACCESS_RIGHTS dwDesiredAccess, BOOL bInheritHandle, LPWSTR lpName);
HANDLE CreateEventA(SECURITY_ATTRIBUTES * lpEventAttributes, BOOL bManualReset, BOOL bInitialState, LPSTR lpName);
HANDLE CreateEventW(SECURITY_ATTRIBUTES * lpEventAttributes, BOOL bManualReset, BOOL bInitialState, LPWSTR lpName);
HANDLE OpenEventA(SYNCHRONIZATION_ACCESS_RIGHTS dwDesiredAccess, BOOL bInheritHandle, LPSTR lpName);
HANDLE OpenEventW(SYNCHRONIZATION_ACCESS_RIGHTS dwDesiredAccess, BOOL bInheritHandle, LPWSTR lpName);
HANDLE OpenSemaphoreW(SYNCHRONIZATION_ACCESS_RIGHTS dwDesiredAccess, BOOL bInheritHandle, LPWSTR lpName);
HANDLE OpenWaitableTimerW(SYNCHRONIZATION_ACCESS_RIGHTS dwDesiredAccess, BOOL bInheritHandle, LPWSTR lpTimerName);
BOOL SetWaitableTimerEx(HANDLE hTimer, LONGLONG * lpDueTime, LONG lPeriod, PTIMERAPCROUTINE pfnCompletionRoutine, void * lpArgToCompletionRoutine, REASON_CONTEXT * WakeContext, DWORD TolerableDelay);
BOOL SetWaitableTimer(HANDLE hTimer, LONGLONG * lpDueTime, LONG lPeriod, PTIMERAPCROUTINE pfnCompletionRoutine, void * lpArgToCompletionRoutine, BOOL fResume);
BOOL CancelWaitableTimer(HANDLE hTimer);
HANDLE CreateMutexExA(SECURITY_ATTRIBUTES * lpMutexAttributes, LPSTR lpName, DWORD dwFlags, DWORD dwDesiredAccess);
HANDLE CreateMutexExW(SECURITY_ATTRIBUTES * lpMutexAttributes, LPWSTR lpName, DWORD dwFlags, DWORD dwDesiredAccess);
HANDLE CreateEventExA(SECURITY_ATTRIBUTES * lpEventAttributes, LPSTR lpName, CREATE_EVENT dwFlags, DWORD dwDesiredAccess);
HANDLE CreateEventExW(SECURITY_ATTRIBUTES * lpEventAttributes, LPWSTR lpName, CREATE_EVENT dwFlags, DWORD dwDesiredAccess);
HANDLE CreateSemaphoreExW(SECURITY_ATTRIBUTES * lpSemaphoreAttributes, LONG lInitialCount, LONG lMaximumCount, LPWSTR lpName, DWORD dwFlags, DWORD dwDesiredAccess);
HANDLE CreateWaitableTimerExW(SECURITY_ATTRIBUTES * lpTimerAttributes, LPWSTR lpTimerName, DWORD dwFlags, DWORD dwDesiredAccess);
BOOL EnterSynchronizationBarrier(SYNCHRONIZATION_BARRIER * lpBarrier, DWORD dwFlags);
BOOL InitializeSynchronizationBarrier(SYNCHRONIZATION_BARRIER * lpBarrier, LONG lTotalThreads, LONG lSpinCount);
BOOL DeleteSynchronizationBarrier(SYNCHRONIZATION_BARRIER * lpBarrier);
void Sleep(DWORD dwMilliseconds);
BOOL WaitOnAddress(void * Address, void * CompareAddress, void * AddressSize, DWORD dwMilliseconds);
void WakeByAddressSingle(void * Address);
void WakeByAddressAll(void * Address);
WAIT_EVENT WaitForMultipleObjects(DWORD nCount, HANDLE * lpHandles, BOOL bWaitAll, DWORD dwMilliseconds);
HANDLE CreateSemaphoreW(SECURITY_ATTRIBUTES * lpSemaphoreAttributes, LONG lInitialCount, LONG lMaximumCount, LPWSTR lpName);
HANDLE CreateWaitableTimerW(SECURITY_ATTRIBUTES * lpTimerAttributes, BOOL bManualReset, LPWSTR lpTimerName);
void InitializeSListHead(SLIST_HEADER * ListHead);
SLIST_ENTRY * InterlockedPopEntrySList(SLIST_HEADER * ListHead);
SLIST_ENTRY * InterlockedPushEntrySList(SLIST_HEADER * ListHead, SLIST_ENTRY * ListEntry);
SLIST_ENTRY * InterlockedPushListSListEx(SLIST_HEADER * ListHead, SLIST_ENTRY * List, SLIST_ENTRY * ListEnd, DWORD Count);
SLIST_ENTRY * InterlockedFlushSList(SLIST_HEADER * ListHead);
WORD QueryDepthSList(SLIST_HEADER * ListHead);
DWORD QueueUserAPC(PAPCFUNC pfnAPC, HANDLE hThread, void * dwData);
BOOL QueueUserAPC2(PAPCFUNC ApcRoutine, HANDLE Thread, void * Data, QUEUE_USER_APC_FLAGS Flags);
BOOL GetProcessTimes(HANDLE hProcess, FILETIME * lpCreationTime, FILETIME * lpExitTime, FILETIME * lpKernelTime, FILETIME * lpUserTime);
HANDLE GetCurrentProcess();
DWORD GetCurrentProcessId();
void ExitProcess(DWORD uExitCode);
BOOL TerminateProcess(HANDLE hProcess, DWORD uExitCode);
BOOL GetExitCodeProcess(HANDLE hProcess, DWORD * lpExitCode);
BOOL SwitchToThread();
HANDLE CreateThread(SECURITY_ATTRIBUTES * lpThreadAttributes, void * dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, void * lpParameter, THREAD_CREATION_FLAGS dwCreationFlags, DWORD * lpThreadId);
HANDLE CreateRemoteThread(HANDLE hProcess, SECURITY_ATTRIBUTES * lpThreadAttributes, void * dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, void * lpParameter, DWORD dwCreationFlags, DWORD * lpThreadId);
HANDLE GetCurrentThread();
DWORD GetCurrentThreadId();
HANDLE OpenThread(THREAD_ACCESS_RIGHTS dwDesiredAccess, BOOL bInheritHandle, DWORD dwThreadId);
BOOL SetThreadPriority(HANDLE hThread, THREAD_PRIORITY nPriority);
BOOL SetThreadPriorityBoost(HANDLE hThread, BOOL bDisablePriorityBoost);
BOOL GetThreadPriorityBoost(HANDLE hThread, BOOL * pDisablePriorityBoost);
LONG GetThreadPriority(HANDLE hThread);
void ExitThread(DWORD dwExitCode);
BOOL TerminateThread(HANDLE hThread, DWORD dwExitCode);
BOOL GetExitCodeThread(HANDLE hThread, DWORD * lpExitCode);
DWORD SuspendThread(HANDLE hThread);
DWORD ResumeThread(HANDLE hThread);
DWORD TlsAlloc();
void * TlsGetValue(DWORD dwTlsIndex);
BOOL TlsSetValue(DWORD dwTlsIndex, void * lpTlsValue);
BOOL TlsFree(DWORD dwTlsIndex);
BOOL CreateProcessA(LPSTR lpApplicationName, LPSTR lpCommandLine, SECURITY_ATTRIBUTES * lpProcessAttributes, SECURITY_ATTRIBUTES * lpThreadAttributes, BOOL bInheritHandles, PROCESS_CREATION_FLAGS dwCreationFlags, void * lpEnvironment, LPSTR lpCurrentDirectory, STARTUPINFOA * lpStartupInfo, PROCESS_INFORMATION * lpProcessInformation);
BOOL CreateProcessW(LPWSTR lpApplicationName, LPWSTR lpCommandLine, SECURITY_ATTRIBUTES * lpProcessAttributes, SECURITY_ATTRIBUTES * lpThreadAttributes, BOOL bInheritHandles, PROCESS_CREATION_FLAGS dwCreationFlags, void * lpEnvironment, LPWSTR lpCurrentDirectory, STARTUPINFOW * lpStartupInfo, PROCESS_INFORMATION * lpProcessInformation);
BOOL SetProcessShutdownParameters(DWORD dwLevel, DWORD dwFlags);
DWORD GetProcessVersion(DWORD ProcessId);
void GetStartupInfoW(STARTUPINFOW * lpStartupInfo);
BOOL CreateProcessAsUserW(HANDLE hToken, LPWSTR lpApplicationName, LPWSTR lpCommandLine, SECURITY_ATTRIBUTES * lpProcessAttributes, SECURITY_ATTRIBUTES * lpThreadAttributes, BOOL bInheritHandles, PROCESS_CREATION_FLAGS dwCreationFlags, void * lpEnvironment, LPWSTR lpCurrentDirectory, STARTUPINFOW * lpStartupInfo, PROCESS_INFORMATION * lpProcessInformation);
BOOL SetThreadToken(HANDLE * Thread, HANDLE Token);
BOOL OpenProcessToken(HANDLE ProcessHandle, TOKEN_ACCESS_MASK DesiredAccess, HANDLE * TokenHandle);
BOOL OpenThreadToken(HANDLE ThreadHandle, TOKEN_ACCESS_MASK DesiredAccess, BOOL OpenAsSelf, HANDLE * TokenHandle);
BOOL SetPriorityClass(HANDLE hProcess, PROCESS_CREATION_FLAGS dwPriorityClass);
DWORD GetPriorityClass(HANDLE hProcess);
BOOL SetThreadStackGuarantee(DWORD * StackSizeInBytes);
DWORD GetProcessId(HANDLE Process);
DWORD GetThreadId(HANDLE Thread);
void FlushProcessWriteBuffers();
DWORD GetProcessIdOfThread(HANDLE Thread);
BOOL InitializeProcThreadAttributeList(LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList, DWORD dwAttributeCount, DWORD dwFlags, void * * lpSize);
void DeleteProcThreadAttributeList(LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList);
BOOL UpdateProcThreadAttribute(LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList, DWORD dwFlags, void * Attribute, void * lpValue, void * cbSize, void * lpPreviousValue, void * * lpReturnSize);
BOOL SetProcessDynamicEHContinuationTargets(HANDLE Process, WORD NumberOfTargets, PROCESS_DYNAMIC_EH_CONTINUATION_TARGET * Targets);
BOOL SetProcessDynamicEnforcedCetCompatibleRanges(HANDLE Process, WORD NumberOfRanges, PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGE * Ranges);
BOOL SetProcessAffinityUpdateMode(HANDLE hProcess, PROCESS_AFFINITY_AUTO_UPDATE_FLAGS dwFlags);
BOOL QueryProcessAffinityUpdateMode(HANDLE hProcess, PROCESS_AFFINITY_AUTO_UPDATE_FLAGS * lpdwFlags);
HANDLE CreateRemoteThreadEx(HANDLE hProcess, SECURITY_ATTRIBUTES * lpThreadAttributes, void * dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, void * lpParameter, DWORD dwCreationFlags, LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList, DWORD * lpThreadId);
void GetCurrentThreadStackLimits(void * * LowLimit, void * * HighLimit);
BOOL GetProcessMitigationPolicy(HANDLE hProcess, PROCESS_MITIGATION_POLICY MitigationPolicy, void * lpBuffer, void * dwLength);
BOOL SetProcessMitigationPolicy(PROCESS_MITIGATION_POLICY MitigationPolicy, void * lpBuffer, void * dwLength);
BOOL GetThreadTimes(HANDLE hThread, FILETIME * lpCreationTime, FILETIME * lpExitTime, FILETIME * lpKernelTime, FILETIME * lpUserTime);
HANDLE OpenProcess(PROCESS_ACCESS_RIGHTS dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId);
BOOL IsProcessorFeaturePresent(PROCESSOR_FEATURE_ID ProcessorFeature);
BOOL GetProcessHandleCount(HANDLE hProcess, DWORD * pdwHandleCount);
DWORD GetCurrentProcessorNumber();
BOOL SetThreadIdealProcessorEx(HANDLE hThread, PROCESSOR_NUMBER * lpIdealProcessor, PROCESSOR_NUMBER * lpPreviousIdealProcessor);
BOOL GetThreadIdealProcessorEx(HANDLE hThread, PROCESSOR_NUMBER * lpIdealProcessor);
void GetCurrentProcessorNumberEx(PROCESSOR_NUMBER * ProcNumber);
BOOL GetProcessPriorityBoost(HANDLE hProcess, BOOL * pDisablePriorityBoost);
BOOL SetProcessPriorityBoost(HANDLE hProcess, BOOL bDisablePriorityBoost);
BOOL GetThreadIOPendingFlag(HANDLE hThread, BOOL * lpIOIsPending);
BOOL GetSystemTimes(FILETIME * lpIdleTime, FILETIME * lpKernelTime, FILETIME * lpUserTime);
BOOL GetThreadInformation(HANDLE hThread, THREAD_INFORMATION_CLASS ThreadInformationClass, void * ThreadInformation, DWORD ThreadInformationSize);
BOOL SetThreadInformation(HANDLE hThread, THREAD_INFORMATION_CLASS ThreadInformationClass, void * ThreadInformation, DWORD ThreadInformationSize);
BOOL IsProcessCritical(HANDLE hProcess, BOOL * Critical);
BOOL SetProtectedPolicy(GUID_W * PolicyGuid, void * PolicyValue, void * * OldPolicyValue);
BOOL QueryProtectedPolicy(GUID_W * PolicyGuid, void * * PolicyValue);
DWORD SetThreadIdealProcessor(HANDLE hThread, DWORD dwIdealProcessor);
BOOL SetProcessInformation(HANDLE hProcess, PROCESS_INFORMATION_CLASS ProcessInformationClass, void * ProcessInformation, DWORD ProcessInformationSize);
BOOL GetProcessInformation(HANDLE hProcess, PROCESS_INFORMATION_CLASS ProcessInformationClass, void * ProcessInformation, DWORD ProcessInformationSize);
BOOL GetProcessDefaultCpuSets(HANDLE Process, DWORD * CpuSetIds, DWORD CpuSetIdCount, DWORD * RequiredIdCount);
BOOL SetProcessDefaultCpuSets(HANDLE Process, DWORD * CpuSetIds, DWORD CpuSetIdCount);
BOOL GetThreadSelectedCpuSets(HANDLE Thread, DWORD * CpuSetIds, DWORD CpuSetIdCount, DWORD * RequiredIdCount);
BOOL SetThreadSelectedCpuSets(HANDLE Thread, DWORD * CpuSetIds, DWORD CpuSetIdCount);
BOOL CreateProcessAsUserA(HANDLE hToken, LPSTR lpApplicationName, LPSTR lpCommandLine, SECURITY_ATTRIBUTES * lpProcessAttributes, SECURITY_ATTRIBUTES * lpThreadAttributes, BOOL bInheritHandles, PROCESS_CREATION_FLAGS dwCreationFlags, void * lpEnvironment, LPSTR lpCurrentDirectory, STARTUPINFOA * lpStartupInfo, PROCESS_INFORMATION * lpProcessInformation);
BOOL GetProcessShutdownParameters(DWORD * lpdwLevel, DWORD * lpdwFlags);
BOOL GetProcessDefaultCpuSetMasks(HANDLE Process, GROUP_AFFINITY * CpuSetMasks, WORD CpuSetMaskCount, WORD * RequiredMaskCount);
BOOL SetProcessDefaultCpuSetMasks(HANDLE Process, GROUP_AFFINITY * CpuSetMasks, WORD CpuSetMaskCount);
BOOL GetThreadSelectedCpuSetMasks(HANDLE Thread, GROUP_AFFINITY * CpuSetMasks, WORD CpuSetMaskCount, WORD * RequiredMaskCount);
BOOL SetThreadSelectedCpuSetMasks(HANDLE Thread, GROUP_AFFINITY * CpuSetMasks, WORD CpuSetMaskCount);
HRESULT GetMachineTypeAttributes(WORD Machine, MACHINE_ATTRIBUTES * MachineTypeAttributes);
HRESULT SetThreadDescription(HANDLE hThread, LPWSTR lpThreadDescription);
HRESULT GetThreadDescription(HANDLE hThread, LPWSTR * ppszThreadDescription);
BOOL QueueUserWorkItem(LPTHREAD_START_ROUTINE Function, void * Context, WORKER_THREAD_FLAGS Flags);
BOOL UnregisterWaitEx(HANDLE WaitHandle, HANDLE CompletionEvent);
HANDLE CreateTimerQueue();
BOOL CreateTimerQueueTimer(HANDLE * phNewTimer, HANDLE TimerQueue, WAITORTIMERCALLBACK Callback, void * Parameter, DWORD DueTime, DWORD Period, WORKER_THREAD_FLAGS Flags);
BOOL ChangeTimerQueueTimer(HANDLE TimerQueue, HANDLE Timer, DWORD DueTime, DWORD Period);
BOOL DeleteTimerQueueTimer(HANDLE TimerQueue, HANDLE Timer, HANDLE CompletionEvent);
BOOL DeleteTimerQueue(HANDLE TimerQueue);
BOOL DeleteTimerQueueEx(HANDLE TimerQueue, HANDLE CompletionEvent);
PTP_POOL CreateThreadpool(void * reserved);
void SetThreadpoolThreadMaximum(PTP_POOL ptpp, DWORD cthrdMost);
BOOL SetThreadpoolThreadMinimum(PTP_POOL ptpp, DWORD cthrdMic);
BOOL SetThreadpoolStackInformation(PTP_POOL ptpp, TP_POOL_STACK_INFORMATION * ptpsi);
BOOL QueryThreadpoolStackInformation(PTP_POOL ptpp, TP_POOL_STACK_INFORMATION * ptpsi);
void CloseThreadpool(PTP_POOL ptpp);
PTP_CLEANUP_GROUP CreateThreadpoolCleanupGroup();
void CloseThreadpoolCleanupGroupMembers(PTP_CLEANUP_GROUP ptpcg, BOOL fCancelPendingCallbacks, void * pvCleanupContext);
void CloseThreadpoolCleanupGroup(PTP_CLEANUP_GROUP ptpcg);
void SetEventWhenCallbackReturns(PTP_CALLBACK_INSTANCE pci, HANDLE evt);
void ReleaseSemaphoreWhenCallbackReturns(PTP_CALLBACK_INSTANCE pci, HANDLE sem, DWORD crel);
void ReleaseMutexWhenCallbackReturns(PTP_CALLBACK_INSTANCE pci, HANDLE mut);
void LeaveCriticalSectionWhenCallbackReturns(PTP_CALLBACK_INSTANCE pci, CRITICAL_SECTION * pcs);
void FreeLibraryWhenCallbackReturns(PTP_CALLBACK_INSTANCE pci, HMODULE mod);
BOOL CallbackMayRunLong(PTP_CALLBACK_INSTANCE pci);
void DisassociateCurrentThreadFromCallback(PTP_CALLBACK_INSTANCE pci);
BOOL TrySubmitThreadpoolCallback(PTP_SIMPLE_CALLBACK pfns, void * pv, TP_CALLBACK_ENVIRON_V3 * pcbe);
PTP_WORK CreateThreadpoolWork(PTP_WORK_CALLBACK pfnwk, void * pv, TP_CALLBACK_ENVIRON_V3 * pcbe);
void SubmitThreadpoolWork(PTP_WORK pwk);
void WaitForThreadpoolWorkCallbacks(PTP_WORK pwk, BOOL fCancelPendingCallbacks);
void CloseThreadpoolWork(PTP_WORK pwk);
PTP_TIMER CreateThreadpoolTimer(PTP_TIMER_CALLBACK pfnti, void * pv, TP_CALLBACK_ENVIRON_V3 * pcbe);
void SetThreadpoolTimer(PTP_TIMER pti, FILETIME * pftDueTime, DWORD msPeriod, DWORD msWindowLength);
BOOL IsThreadpoolTimerSet(PTP_TIMER pti);
void WaitForThreadpoolTimerCallbacks(PTP_TIMER pti, BOOL fCancelPendingCallbacks);
void CloseThreadpoolTimer(PTP_TIMER pti);
PTP_WAIT CreateThreadpoolWait(PTP_WAIT_CALLBACK pfnwa, void * pv, TP_CALLBACK_ENVIRON_V3 * pcbe);
void SetThreadpoolWait(PTP_WAIT pwa, HANDLE h, FILETIME * pftTimeout);
void WaitForThreadpoolWaitCallbacks(PTP_WAIT pwa, BOOL fCancelPendingCallbacks);
void CloseThreadpoolWait(PTP_WAIT pwa);
PTP_IO CreateThreadpoolIo(HANDLE fl, PTP_WIN32_IO_CALLBACK pfnio, void * pv, TP_CALLBACK_ENVIRON_V3 * pcbe);
void StartThreadpoolIo(PTP_IO pio);
void CancelThreadpoolIo(PTP_IO pio);
void WaitForThreadpoolIoCallbacks(PTP_IO pio, BOOL fCancelPendingCallbacks);
void CloseThreadpoolIo(PTP_IO pio);
BOOL SetThreadpoolTimerEx(PTP_TIMER pti, FILETIME * pftDueTime, DWORD msPeriod, DWORD msWindowLength);
BOOL SetThreadpoolWaitEx(PTP_WAIT pwa, HANDLE h, FILETIME * pftTimeout, void * Reserved);
BOOL IsWow64Process(HANDLE hProcess, BOOL * Wow64Process);
WORD Wow64SetThreadDefaultGuestMachine(WORD Machine);
BOOL IsWow64Process2(HANDLE hProcess, IMAGE_FILE_MACHINE * pProcessMachine, IMAGE_FILE_MACHINE * pNativeMachine);
DWORD Wow64SuspendThread(HANDLE hThread);
HANDLE CreatePrivateNamespaceW(SECURITY_ATTRIBUTES * lpPrivateNamespaceAttributes, void * lpBoundaryDescriptor, LPWSTR lpAliasPrefix);
HANDLE OpenPrivateNamespaceW(void * lpBoundaryDescriptor, LPWSTR lpAliasPrefix);
BYTE ClosePrivateNamespace(HANDLE Handle, DWORD Flags);
HANDLE CreateBoundaryDescriptorW(LPWSTR Name, DWORD Flags);
BOOL AddSIDToBoundaryDescriptor(HANDLE * BoundaryDescriptor, PSID RequiredSid);
void DeleteBoundaryDescriptor(HANDLE BoundaryDescriptor);
BOOL GetNumaHighestNodeNumber(DWORD * HighestNodeNumber);
BOOL GetNumaNodeProcessorMaskEx(WORD Node, GROUP_AFFINITY * ProcessorMask);
BOOL GetNumaNodeProcessorMask2(WORD NodeNumber, GROUP_AFFINITY * ProcessorMasks, WORD ProcessorMaskCount, WORD * RequiredMaskCount);
BOOL GetNumaProximityNodeEx(DWORD ProximityId, WORD * NodeNumber);
BOOL GetProcessGroupAffinity(HANDLE hProcess, WORD * GroupCount, WORD * GroupArray);
BOOL GetThreadGroupAffinity(HANDLE hThread, GROUP_AFFINITY * GroupAffinity);
BOOL SetThreadGroupAffinity(HANDLE hThread, GROUP_AFFINITY * GroupAffinity, GROUP_AFFINITY * PreviousGroupAffinity);
HANDLE AvSetMmThreadCharacteristicsA(LPSTR TaskName, DWORD * TaskIndex);
HANDLE AvSetMmThreadCharacteristicsW(LPWSTR TaskName, DWORD * TaskIndex);
HANDLE AvSetMmMaxThreadCharacteristicsA(LPSTR FirstTask, LPSTR SecondTask, DWORD * TaskIndex);
HANDLE AvSetMmMaxThreadCharacteristicsW(LPWSTR FirstTask, LPWSTR SecondTask, DWORD * TaskIndex);
BOOL AvRevertMmThreadCharacteristics(HANDLE AvrtHandle);
BOOL AvSetMmThreadPriority(HANDLE AvrtHandle, AVRT_PRIORITY Priority);
BOOL AvRtCreateThreadOrderingGroup(HANDLE * Context, LONGLONG * Period, GUID_W * ThreadOrderingGuid, LONGLONG * Timeout);
BOOL AvRtCreateThreadOrderingGroupExA(HANDLE * Context, LONGLONG * Period, GUID_W * ThreadOrderingGuid, LONGLONG * Timeout, LPSTR TaskName);
BOOL AvRtCreateThreadOrderingGroupExW(HANDLE * Context, LONGLONG * Period, GUID_W * ThreadOrderingGuid, LONGLONG * Timeout, LPWSTR TaskName);
BOOL AvRtJoinThreadOrderingGroup(HANDLE * Context, GUID_W * ThreadOrderingGuid, BOOL Before);
BOOL AvRtWaitOnThreadOrderingGroup(HANDLE Context);
BOOL AvRtLeaveThreadOrderingGroup(HANDLE Context);
BOOL AvRtDeleteThreadOrderingGroup(HANDLE Context);
BOOL AvQuerySystemResponsiveness(HANDLE AvrtHandle, DWORD * SystemResponsivenessValue);
HRESULT RtwqStartup();
HRESULT RtwqShutdown();
HRESULT RtwqLockWorkQueue(DWORD workQueueId);
HRESULT RtwqUnlockWorkQueue(DWORD workQueueId);
HRESULT RtwqLockSharedWorkQueue(LPWSTR usageClass, LONG basePriority, DWORD * taskId, DWORD * id);
HRESULT RtwqJoinWorkQueue(DWORD workQueueId, HANDLE hFile, HANDLE * out);
HRESULT RtwqUnjoinWorkQueue(DWORD workQueueId, HANDLE hFile);
HRESULT RtwqCreateAsyncResult(IUnknown appObject, IRtwqAsyncCallback callback, IUnknown appState, IRtwqAsyncResult * asyncResult);
HRESULT RtwqInvokeCallback(IRtwqAsyncResult result);
HRESULT RtwqLockPlatform();
HRESULT RtwqUnlockPlatform();
HRESULT RtwqRegisterPlatformWithMMCSS(LPWSTR usageClass, DWORD * taskId, LONG lPriority);
HRESULT RtwqUnregisterPlatformFromMMCSS();
HRESULT RtwqPutWorkItem(DWORD dwQueue, LONG lPriority, IRtwqAsyncResult result);
HRESULT RtwqPutWaitingWorkItem(HANDLE hEvent, LONG lPriority, IRtwqAsyncResult result, ULONGLONG * key);
HRESULT RtwqAllocateSerialWorkQueue(DWORD workQueueIdIn, DWORD * workQueueIdOut);
HRESULT RtwqScheduleWorkItem(IRtwqAsyncResult result, LONGLONG Timeout, ULONGLONG * key);
HRESULT RtwqAddPeriodicCallback(RTWQPERIODICCALLBACK Callback, IUnknown context, DWORD * key);
HRESULT RtwqRemovePeriodicCallback(DWORD dwKey);
HRESULT RtwqCancelWorkItem(ULONGLONG Key);
HRESULT RtwqAllocateWorkQueue(RTWQ_WORKQUEUE_TYPE WorkQueueType, DWORD * workQueueId);
HRESULT RtwqBeginRegisterWorkQueueWithMMCSS(DWORD workQueueId, LPWSTR usageClass, DWORD dwTaskId, LONG lPriority, IRtwqAsyncCallback doneCallback, IUnknown doneState);
HRESULT RtwqBeginUnregisterWorkQueueWithMMCSS(DWORD workQueueId, IRtwqAsyncCallback doneCallback, IUnknown doneState);
HRESULT RtwqEndRegisterWorkQueueWithMMCSS(IRtwqAsyncResult result, DWORD * taskId);
HRESULT RtwqGetWorkQueueMMCSSClass(DWORD workQueueId, LPWSTR usageClass, DWORD * usageClassLength);
HRESULT RtwqGetWorkQueueMMCSSTaskId(DWORD workQueueId, DWORD * taskId);
HRESULT RtwqGetWorkQueueMMCSSPriority(DWORD workQueueId, LONG * priority);
HRESULT RtwqRegisterPlatformEvents(IRtwqPlatformEvents platformEvents);
HRESULT RtwqUnregisterPlatformEvents(IRtwqPlatformEvents platformEvents);
HRESULT RtwqSetLongRunning(DWORD workQueueId, BOOL enable);
HRESULT RtwqSetDeadline(DWORD workQueueId, LONGLONG deadlineInHNS, HANDLE * pRequest);
HRESULT RtwqSetDeadline2(DWORD workQueueId, LONGLONG deadlineInHNS, LONGLONG preDeadlineInHNS, HANDLE * pRequest);
HRESULT RtwqCancelDeadline(HANDLE pRequest);
HANDLE GetProcessHandleFromHwnd(HWND hwnd);
BOOL AttachThreadInput(DWORD idAttach, DWORD idAttachTo, BOOL fAttach);
DWORD WaitForInputIdle(HANDLE hProcess, DWORD dwMilliseconds);
DWORD GetGuiResources(HANDLE hProcess, GET_GUI_RESOURCES_FLAGS uiFlags);
BOOL IsImmersiveProcess(HANDLE hProcess);
BOOL SetProcessRestrictionExemption(BOOL fEnableExemption);
BOOL GetProcessAffinityMask(HANDLE hProcess, void * * lpProcessAffinityMask, void * * lpSystemAffinityMask);
BOOL SetProcessAffinityMask(HANDLE hProcess, void * dwProcessAffinityMask);
BOOL GetProcessIoCounters(HANDLE hProcess, IO_COUNTERS * lpIoCounters);
void SwitchToFiber(void * lpFiber);
void DeleteFiber(void * lpFiber);
BOOL ConvertFiberToThread();
void * CreateFiberEx(void * dwStackCommitSize, void * dwStackReserveSize, DWORD dwFlags, LPFIBER_START_ROUTINE lpStartAddress, void * lpParameter);
void * ConvertThreadToFiberEx(void * lpParameter, DWORD dwFlags);
void * CreateFiber(void * dwStackSize, LPFIBER_START_ROUTINE lpStartAddress, void * lpParameter);
void * ConvertThreadToFiber(void * lpParameter);
BOOL CreateUmsCompletionList(void * * UmsCompletionList);
BOOL DequeueUmsCompletionListItems(void * UmsCompletionList, DWORD WaitTimeOut, void * * UmsThreadList);
BOOL GetUmsCompletionListEvent(void * UmsCompletionList, HANDLE * UmsCompletionEvent);
BOOL ExecuteUmsThread(void * UmsThread);
BOOL UmsThreadYield(void * SchedulerParam);
BOOL DeleteUmsCompletionList(void * UmsCompletionList);
void * GetCurrentUmsThread();
void * GetNextUmsListItem(void * UmsContext);
BOOL QueryUmsThreadInformation(void * UmsThread, UMS_THREAD_INFO_CLASS UmsThreadInfoClass, void * UmsThreadInformation, DWORD UmsThreadInformationLength, DWORD * ReturnLength);
BOOL SetUmsThreadInformation(void * UmsThread, UMS_THREAD_INFO_CLASS UmsThreadInfoClass, void * UmsThreadInformation, DWORD UmsThreadInformationLength);
BOOL DeleteUmsThreadContext(void * UmsThread);
BOOL CreateUmsThreadContext(void * * lpUmsThread);
BOOL EnterUmsSchedulingMode(UMS_SCHEDULER_STARTUP_INFO * SchedulerStartupInfo);
BOOL GetUmsSystemThreadInformation(HANDLE ThreadHandle, UMS_SYSTEM_THREAD_INFORMATION * SystemThreadInfo);
void * SetThreadAffinityMask(HANDLE hThread, void * dwThreadAffinityMask);
BOOL SetProcessDEPPolicy(PROCESS_DEP_FLAGS dwFlags);
BOOL GetProcessDEPPolicy(HANDLE hProcess, DWORD * lpFlags, BOOL * lpPermanent);
BOOL PulseEvent(HANDLE hEvent);
DWORD WinExec(LPSTR lpCmdLine, DWORD uCmdShow);
WAIT_EVENT SignalObjectAndWait(HANDLE hObjectToSignal, HANDLE hObjectToWaitOn, DWORD dwMilliseconds, BOOL bAlertable);
HANDLE CreateSemaphoreA(SECURITY_ATTRIBUTES * lpSemaphoreAttributes, LONG lInitialCount, LONG lMaximumCount, LPSTR lpName);
HANDLE CreateWaitableTimerA(SECURITY_ATTRIBUTES * lpTimerAttributes, BOOL bManualReset, LPSTR lpTimerName);
HANDLE OpenWaitableTimerA(DWORD dwDesiredAccess, BOOL bInheritHandle, LPSTR lpTimerName);
HANDLE CreateSemaphoreExA(SECURITY_ATTRIBUTES * lpSemaphoreAttributes, LONG lInitialCount, LONG lMaximumCount, LPSTR lpName, DWORD dwFlags, DWORD dwDesiredAccess);
HANDLE CreateWaitableTimerExA(SECURITY_ATTRIBUTES * lpTimerAttributes, LPSTR lpTimerName, DWORD dwFlags, DWORD dwDesiredAccess);
BOOL QueryFullProcessImageNameA(HANDLE hProcess, PROCESS_NAME_FORMAT dwFlags, LPSTR lpExeName, DWORD * lpdwSize);
BOOL QueryFullProcessImageNameW(HANDLE hProcess, PROCESS_NAME_FORMAT dwFlags, LPWSTR lpExeName, DWORD * lpdwSize);
void GetStartupInfoA(STARTUPINFOA * lpStartupInfo);
BOOL CreateProcessWithLogonW(LPWSTR lpUsername, LPWSTR lpDomain, LPWSTR lpPassword, CREATE_PROCESS_LOGON_FLAGS dwLogonFlags, LPWSTR lpApplicationName, LPWSTR lpCommandLine, PROCESS_CREATION_FLAGS dwCreationFlags, void * lpEnvironment, LPWSTR lpCurrentDirectory, STARTUPINFOW * lpStartupInfo, PROCESS_INFORMATION * lpProcessInformation);
BOOL CreateProcessWithTokenW(HANDLE hToken, CREATE_PROCESS_LOGON_FLAGS dwLogonFlags, LPWSTR lpApplicationName, LPWSTR lpCommandLine, PROCESS_CREATION_FLAGS dwCreationFlags, void * lpEnvironment, LPWSTR lpCurrentDirectory, STARTUPINFOW * lpStartupInfo, PROCESS_INFORMATION * lpProcessInformation);
BOOL RegisterWaitForSingleObject(HANDLE * phNewWaitObject, HANDLE hObject, WAITORTIMERCALLBACK Callback, void * Context, DWORD dwMilliseconds, WORKER_THREAD_FLAGS dwFlags);
BOOL UnregisterWait(HANDLE WaitHandle);
HANDLE SetTimerQueueTimer(HANDLE TimerQueue, WAITORTIMERCALLBACK Callback, void * Parameter, DWORD DueTime, DWORD Period, BOOL PreferIo);
BOOL CancelTimerQueueTimer(HANDLE TimerQueue, HANDLE Timer);
HANDLE CreatePrivateNamespaceA(SECURITY_ATTRIBUTES * lpPrivateNamespaceAttributes, void * lpBoundaryDescriptor, LPSTR lpAliasPrefix);
HANDLE OpenPrivateNamespaceA(void * lpBoundaryDescriptor, LPSTR lpAliasPrefix);
HANDLE CreateBoundaryDescriptorA(LPSTR Name, DWORD Flags);
BOOL AddIntegrityLabelToBoundaryDescriptor(HANDLE * BoundaryDescriptor, PSID IntegrityLabel);
WORD GetActiveProcessorGroupCount();
WORD GetMaximumProcessorGroupCount();
DWORD GetActiveProcessorCount(WORD GroupNumber);
DWORD GetMaximumProcessorCount(WORD GroupNumber);
BOOL GetNumaProcessorNode(BYTE Processor, BYTE * NodeNumber);
BOOL GetNumaNodeNumberFromHandle(HANDLE hFile, WORD * NodeNumber);
BOOL GetNumaProcessorNodeEx(PROCESSOR_NUMBER * Processor, WORD * NodeNumber);
BOOL GetNumaNodeProcessorMask(BYTE Node, ULONGLONG * ProcessorMask);
BOOL GetNumaAvailableMemoryNode(BYTE Node, ULONGLONG * AvailableBytes);
BOOL GetNumaAvailableMemoryNodeEx(WORD Node, ULONGLONG * AvailableBytes);
BOOL GetNumaProximityNode(DWORD ProximityId, BYTE * NodeNumber);
]]

return {
    ALL_PROCESSOR_GROUPS = 65535,
    CONDITION_VARIABLE_LOCKMODE_SHARED = 0x00000001,
    CREATE_MUTEX_INITIAL_OWNER = 0x00000001,
    CREATE_WAITABLE_TIMER_HIGH_RESOLUTION = 0x00000002,
    CREATE_WAITABLE_TIMER_MANUAL_RESET = 0x00000001,
    FLS_OUT_OF_INDEXES = 0xFFFFFFFF,
    INFINITE = 0xFFFFFFFF,
    INIT_ONCE_ASYNC = 0x00000002,
    INIT_ONCE_CHECK_ONLY = 0x00000001,
    INIT_ONCE_CTX_RESERVED_BITS = 0x00000002,
    INIT_ONCE_INIT_FAILED = 0x00000004,
    PME_CURRENT_VERSION = 0x00000001,
    PME_FAILFAST_ON_COMMIT_FAIL_DISABLE = 0x00000000,
    PME_FAILFAST_ON_COMMIT_FAIL_ENABLE = 0x00000001,
    PRIVATE_NAMESPACE_FLAG_DESTROY = 0x00000001,
    PROC_THREAD_ATTRIBUTE_ALL_APPLICATION_PACKAGES_POLICY = 0x0002000F,
    PROC_THREAD_ATTRIBUTE_CHILD_PROCESS_POLICY = 0x0002000E,
    PROC_THREAD_ATTRIBUTE_COMPONENT_FILTER = 0x0002001A,
    PROC_THREAD_ATTRIBUTE_DESKTOP_APP_POLICY = 0x00020012,
    PROC_THREAD_ATTRIBUTE_ENABLE_OPTIONAL_XSTATE_FEATURES = 0x0003001B,
    PROC_THREAD_ATTRIBUTE_GROUP_AFFINITY = 0x00030003,
    PROC_THREAD_ATTRIBUTE_HANDLE_LIST = 0x00020002,
    PROC_THREAD_ATTRIBUTE_IDEAL_PROCESSOR = 0x00030005,
    PROC_THREAD_ATTRIBUTE_JOB_LIST = 0x0002000D,
    PROC_THREAD_ATTRIBUTE_MACHINE_TYPE = 0x00020019,
    PROC_THREAD_ATTRIBUTE_MITIGATION_AUDIT_POLICY = 0x00020018,
    PROC_THREAD_ATTRIBUTE_MITIGATION_POLICY = 0x00020007,
    PROC_THREAD_ATTRIBUTE_PARENT_PROCESS = 0x00020000,
    PROC_THREAD_ATTRIBUTE_PREFERRED_NODE = 0x00020004,
    PROC_THREAD_ATTRIBUTE_PROTECTION_LEVEL = 0x0002000B,
    PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE = 0x00020016,
    PROC_THREAD_ATTRIBUTE_REPLACE_VALUE = 0x00000001,
    PROC_THREAD_ATTRIBUTE_SECURITY_CAPABILITIES = 0x00020009,
    PROC_THREAD_ATTRIBUTE_UMS_THREAD = 0x00030006,
    PROC_THREAD_ATTRIBUTE_WIN32K_FILTER = 0x00020010,
    PROCESS_LEAP_SECOND_INFO_FLAG_ENABLE_SIXTY_SECOND = 0x00000001,
    PROCESS_LEAP_SECOND_INFO_VALID_FLAGS = 0x00000001,
    PROCESS_POWER_THROTTLING_CURRENT_VERSION = 0x00000001,
    PROCESS_POWER_THROTTLING_EXECUTION_SPEED = 0x00000001,
    PROCESS_POWER_THROTTLING_IGNORE_TIMER_RESOLUTION = 0x00000004,
    RTL_CRITICAL_SECTION_ALL_FLAG_BITS = 0xFF000000,
    RTL_CRITICAL_SECTION_DEBUG_FLAG_STATIC_INIT = 0x00000001,
    RTL_CRITICAL_SECTION_FLAG_DYNAMIC_SPIN = 0x02000000,
    RTL_CRITICAL_SECTION_FLAG_FORCE_DEBUG_INFO = 0x10000000,
    RTL_CRITICAL_SECTION_FLAG_NO_DEBUG_INFO = 0x01000000,
    RTL_CRITICAL_SECTION_FLAG_RESOURCE_TYPE = 0x08000000,
    RTL_CRITICAL_SECTION_FLAG_STATIC_INIT = 0x04000000,
    SYNCHRONIZATION_BARRIER_FLAGS_BLOCK_ONLY = 0x00000002,
    SYNCHRONIZATION_BARRIER_FLAGS_NO_DELETE = 0x00000004,
    SYNCHRONIZATION_BARRIER_FLAGS_SPIN_ONLY = 0x00000001,
    THREAD_POWER_THROTTLING_CURRENT_VERSION = 0x00000001,
    THREAD_POWER_THROTTLING_EXECUTION_SPEED = 0x00000001,
    THREAD_POWER_THROTTLING_VALID_FLAGS = 0x00000001,
    TLS_OUT_OF_INDEXES = 0xFFFFFFFF,
    -- enum AVRT_PRIORITY
    AVRT_PRIORITY_AVRT_PRIORITY_VERYLOW = -2,
    AVRT_PRIORITY_AVRT_PRIORITY_LOW = -1,
    AVRT_PRIORITY_AVRT_PRIORITY_NORMAL = 0,
    AVRT_PRIORITY_AVRT_PRIORITY_HIGH = 1,
    AVRT_PRIORITY_AVRT_PRIORITY_CRITICAL = 2,
    -- enum CREATE_EVENT
    CREATE_EVENT_CREATE_EVENT_INITIAL_SET = 0x00000002,
    CREATE_EVENT_CREATE_EVENT_MANUAL_RESET = 0x00000001,
    -- enum CREATE_PROCESS_LOGON_FLAGS
    CREATE_PROCESS_LOGON_FLAGS_LOGON_WITH_PROFILE = 0x00000001,
    CREATE_PROCESS_LOGON_FLAGS_LOGON_NETCREDENTIALS_ONLY = 0x00000002,
    -- enum GET_GUI_RESOURCES_FLAGS
    GET_GUI_RESOURCES_FLAGS_GR_GLOBAL = 0xFFFFFFFE,
    GET_GUI_RESOURCES_FLAGS_GR_GDIOBJECTS = 0x00000000,
    GET_GUI_RESOURCES_FLAGS_GR_GDIOBJECTS_PEAK = 0x00000002,
    GET_GUI_RESOURCES_FLAGS_GR_USEROBJECTS = 0x00000001,
    GET_GUI_RESOURCES_FLAGS_GR_USEROBJECTS_PEAK = 0x00000004,
    -- enum MACHINE_ATTRIBUTES
    MACHINE_ATTRIBUTES_UserEnabled = 1,
    MACHINE_ATTRIBUTES_KernelEnabled = 2,
    MACHINE_ATTRIBUTES_Wow64Container = 4,
    -- enum MEMORY_PRIORITY
    MEMORY_PRIORITY_MEMORY_PRIORITY_VERY_LOW = 0x00000001,
    MEMORY_PRIORITY_MEMORY_PRIORITY_LOW = 0x00000002,
    MEMORY_PRIORITY_MEMORY_PRIORITY_MEDIUM = 0x00000003,
    MEMORY_PRIORITY_MEMORY_PRIORITY_BELOW_NORMAL = 0x00000004,
    MEMORY_PRIORITY_MEMORY_PRIORITY_NORMAL = 0x00000005,
    -- enum POWER_REQUEST_CONTEXT_FLAGS
    POWER_REQUEST_CONTEXT_FLAGS_POWER_REQUEST_CONTEXT_DETAILED_STRING = 0x00000002,
    POWER_REQUEST_CONTEXT_FLAGS_POWER_REQUEST_CONTEXT_SIMPLE_STRING = 0x00000001,
    -- enum PROC_THREAD_ATTRIBUTE_NUM
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeParentProcess = 0x00000000,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeHandleList = 0x00000002,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeGroupAffinity = 0x00000003,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributePreferredNode = 0x00000004,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeIdealProcessor = 0x00000005,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeUmsThread = 0x00000006,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeMitigationPolicy = 0x00000007,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeSecurityCapabilities = 0x00000009,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeProtectionLevel = 0x0000000B,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeJobList = 0x0000000D,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeChildProcessPolicy = 0x0000000E,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeAllApplicationPackagesPolicy = 0x0000000F,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeWin32kFilter = 0x00000010,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeSafeOpenPromptOriginClaim = 0x00000011,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeDesktopAppPolicy = 0x00000012,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributePseudoConsole = 0x00000016,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeMitigationAuditPolicy = 0x00000018,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeMachineType = 0x00000019,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeComponentFilter = 0x0000001A,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeEnableOptionalXStateFeatures = 0x0000001B,
    PROC_THREAD_ATTRIBUTE_NUM_ProcThreadAttributeTrustedApp = 0x0000001D,
    -- enum PROCESS_ACCESS_RIGHTS
    PROCESS_ACCESS_RIGHTS_PROCESS_TERMINATE = 0x00000001,
    PROCESS_ACCESS_RIGHTS_PROCESS_CREATE_THREAD = 0x00000002,
    PROCESS_ACCESS_RIGHTS_PROCESS_SET_SESSIONID = 0x00000004,
    PROCESS_ACCESS_RIGHTS_PROCESS_VM_OPERATION = 0x00000008,
    PROCESS_ACCESS_RIGHTS_PROCESS_VM_READ = 0x00000010,
    PROCESS_ACCESS_RIGHTS_PROCESS_VM_WRITE = 0x00000020,
    PROCESS_ACCESS_RIGHTS_PROCESS_DUP_HANDLE = 0x00000040,
    PROCESS_ACCESS_RIGHTS_PROCESS_CREATE_PROCESS = 0x00000080,
    PROCESS_ACCESS_RIGHTS_PROCESS_SET_QUOTA = 0x00000100,
    PROCESS_ACCESS_RIGHTS_PROCESS_SET_INFORMATION = 0x00000200,
    PROCESS_ACCESS_RIGHTS_PROCESS_QUERY_INFORMATION = 0x00000400,
    PROCESS_ACCESS_RIGHTS_PROCESS_SUSPEND_RESUME = 0x00000800,
    PROCESS_ACCESS_RIGHTS_PROCESS_QUERY_LIMITED_INFORMATION = 0x00001000,
    PROCESS_ACCESS_RIGHTS_PROCESS_SET_LIMITED_INFORMATION = 0x00002000,
    PROCESS_ACCESS_RIGHTS_PROCESS_ALL_ACCESS = 0x001FFFFF,
    PROCESS_ACCESS_RIGHTS_PROCESS_DELETE = 0x00010000,
    PROCESS_ACCESS_RIGHTS_PROCESS_READ_CONTROL = 0x00020000,
    PROCESS_ACCESS_RIGHTS_PROCESS_WRITE_DAC = 0x00040000,
    PROCESS_ACCESS_RIGHTS_PROCESS_WRITE_OWNER = 0x00080000,
    PROCESS_ACCESS_RIGHTS_PROCESS_SYNCHRONIZE = 0x00100000,
    PROCESS_ACCESS_RIGHTS_PROCESS_STANDARD_RIGHTS_REQUIRED = 0x000F0000,
    -- enum PROCESS_AFFINITY_AUTO_UPDATE_FLAGS
    PROCESS_AFFINITY_AUTO_UPDATE_FLAGS_PROCESS_AFFINITY_DISABLE_AUTO_UPDATE = 0x00000000,
    PROCESS_AFFINITY_AUTO_UPDATE_FLAGS_PROCESS_AFFINITY_ENABLE_AUTO_UPDATE = 0x00000001,
    -- enum PROCESS_CREATION_FLAGS
    PROCESS_CREATION_FLAGS_DEBUG_PROCESS = 0x00000001,
    PROCESS_CREATION_FLAGS_DEBUG_ONLY_THIS_PROCESS = 0x00000002,
    PROCESS_CREATION_FLAGS_CREATE_SUSPENDED = 0x00000004,
    PROCESS_CREATION_FLAGS_DETACHED_PROCESS = 0x00000008,
    PROCESS_CREATION_FLAGS_CREATE_NEW_CONSOLE = 0x00000010,
    PROCESS_CREATION_FLAGS_NORMAL_PRIORITY_CLASS = 0x00000020,
    PROCESS_CREATION_FLAGS_IDLE_PRIORITY_CLASS = 0x00000040,
    PROCESS_CREATION_FLAGS_HIGH_PRIORITY_CLASS = 0x00000080,
    PROCESS_CREATION_FLAGS_REALTIME_PRIORITY_CLASS = 0x00000100,
    PROCESS_CREATION_FLAGS_CREATE_NEW_PROCESS_GROUP = 0x00000200,
    PROCESS_CREATION_FLAGS_CREATE_UNICODE_ENVIRONMENT = 0x00000400,
    PROCESS_CREATION_FLAGS_CREATE_SEPARATE_WOW_VDM = 0x00000800,
    PROCESS_CREATION_FLAGS_CREATE_SHARED_WOW_VDM = 0x00001000,
    PROCESS_CREATION_FLAGS_CREATE_FORCEDOS = 0x00002000,
    PROCESS_CREATION_FLAGS_BELOW_NORMAL_PRIORITY_CLASS = 0x00004000,
    PROCESS_CREATION_FLAGS_ABOVE_NORMAL_PRIORITY_CLASS = 0x00008000,
    PROCESS_CREATION_FLAGS_INHERIT_PARENT_AFFINITY = 0x00010000,
    PROCESS_CREATION_FLAGS_INHERIT_CALLER_PRIORITY = 0x00020000,
    PROCESS_CREATION_FLAGS_CREATE_PROTECTED_PROCESS = 0x00040000,
    PROCESS_CREATION_FLAGS_EXTENDED_STARTUPINFO_PRESENT = 0x00080000,
    PROCESS_CREATION_FLAGS_PROCESS_MODE_BACKGROUND_BEGIN = 0x00100000,
    PROCESS_CREATION_FLAGS_PROCESS_MODE_BACKGROUND_END = 0x00200000,
    PROCESS_CREATION_FLAGS_CREATE_SECURE_PROCESS = 0x00400000,
    PROCESS_CREATION_FLAGS_CREATE_BREAKAWAY_FROM_JOB = 0x01000000,
    PROCESS_CREATION_FLAGS_CREATE_PRESERVE_CODE_AUTHZ_LEVEL = 0x02000000,
    PROCESS_CREATION_FLAGS_CREATE_DEFAULT_ERROR_MODE = 0x04000000,
    PROCESS_CREATION_FLAGS_CREATE_NO_WINDOW = 0x08000000,
    PROCESS_CREATION_FLAGS_PROFILE_USER = 0x10000000,
    PROCESS_CREATION_FLAGS_PROFILE_KERNEL = 0x20000000,
    PROCESS_CREATION_FLAGS_PROFILE_SERVER = 0x40000000,
    PROCESS_CREATION_FLAGS_CREATE_IGNORE_SYSTEM_DEFAULT = 0x80000000,
    -- enum PROCESS_DEP_FLAGS
    PROCESS_DEP_FLAGS_PROCESS_DEP_ENABLE = 0x00000001,
    PROCESS_DEP_FLAGS_PROCESS_DEP_DISABLE_ATL_THUNK_EMULATION = 0x00000002,
    PROCESS_DEP_FLAGS_PROCESS_DEP_NONE = 0x00000000,
    -- enum PROCESS_INFORMATION_CLASS
    PROCESS_INFORMATION_CLASS_ProcessMemoryPriority = 0,
    PROCESS_INFORMATION_CLASS_ProcessMemoryExhaustionInfo = 1,
    PROCESS_INFORMATION_CLASS_ProcessAppMemoryInfo = 2,
    PROCESS_INFORMATION_CLASS_ProcessInPrivateInfo = 3,
    PROCESS_INFORMATION_CLASS_ProcessPowerThrottling = 4,
    PROCESS_INFORMATION_CLASS_ProcessReservedValue1 = 5,
    PROCESS_INFORMATION_CLASS_ProcessTelemetryCoverageInfo = 6,
    PROCESS_INFORMATION_CLASS_ProcessProtectionLevelInfo = 7,
    PROCESS_INFORMATION_CLASS_ProcessLeapSecondInfo = 8,
    PROCESS_INFORMATION_CLASS_ProcessMachineTypeInfo = 9,
    PROCESS_INFORMATION_CLASS_ProcessOverrideSubsequentPrefetchParameter = 10,
    PROCESS_INFORMATION_CLASS_ProcessMaxOverridePrefetchParameter = 11,
    PROCESS_INFORMATION_CLASS_ProcessInformationClassMax = 12,
    -- enum PROCESS_MEMORY_EXHAUSTION_TYPE
    PROCESS_MEMORY_EXHAUSTION_TYPE_PMETypeFailFastOnCommitFailure = 0,
    PROCESS_MEMORY_EXHAUSTION_TYPE_PMETypeMax = 1,
    -- enum PROCESS_MITIGATION_POLICY
    PROCESS_MITIGATION_POLICY_ProcessDEPPolicy = 0,
    PROCESS_MITIGATION_POLICY_ProcessASLRPolicy = 1,
    PROCESS_MITIGATION_POLICY_ProcessDynamicCodePolicy = 2,
    PROCESS_MITIGATION_POLICY_ProcessStrictHandleCheckPolicy = 3,
    PROCESS_MITIGATION_POLICY_ProcessSystemCallDisablePolicy = 4,
    PROCESS_MITIGATION_POLICY_ProcessMitigationOptionsMask = 5,
    PROCESS_MITIGATION_POLICY_ProcessExtensionPointDisablePolicy = 6,
    PROCESS_MITIGATION_POLICY_ProcessControlFlowGuardPolicy = 7,
    PROCESS_MITIGATION_POLICY_ProcessSignaturePolicy = 8,
    PROCESS_MITIGATION_POLICY_ProcessFontDisablePolicy = 9,
    PROCESS_MITIGATION_POLICY_ProcessImageLoadPolicy = 10,
    PROCESS_MITIGATION_POLICY_ProcessSystemCallFilterPolicy = 11,
    PROCESS_MITIGATION_POLICY_ProcessPayloadRestrictionPolicy = 12,
    PROCESS_MITIGATION_POLICY_ProcessChildProcessPolicy = 13,
    PROCESS_MITIGATION_POLICY_ProcessSideChannelIsolationPolicy = 14,
    PROCESS_MITIGATION_POLICY_ProcessUserShadowStackPolicy = 15,
    PROCESS_MITIGATION_POLICY_ProcessRedirectionTrustPolicy = 16,
    PROCESS_MITIGATION_POLICY_ProcessUserPointerAuthPolicy = 17,
    PROCESS_MITIGATION_POLICY_ProcessSEHOPPolicy = 18,
    PROCESS_MITIGATION_POLICY_ProcessActivationContextTrustPolicy = 19,
    PROCESS_MITIGATION_POLICY_MaxProcessMitigationPolicy = 20,
    -- enum PROCESS_NAME_FORMAT
    PROCESS_NAME_FORMAT_PROCESS_NAME_WIN32 = 0x00000000,
    PROCESS_NAME_FORMAT_PROCESS_NAME_NATIVE = 0x00000001,
    -- enum PROCESS_PROTECTION_LEVEL
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_WINTCB_LIGHT = 0x00000000,
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_WINDOWS = 0x00000001,
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_WINDOWS_LIGHT = 0x00000002,
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_ANTIMALWARE_LIGHT = 0x00000003,
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_LSA_LIGHT = 0x00000004,
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_WINTCB = 0x00000005,
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_CODEGEN_LIGHT = 0x00000006,
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_AUTHENTICODE = 0x00000007,
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_PPL_APP = 0x00000008,
    PROCESS_PROTECTION_LEVEL_PROTECTION_LEVEL_NONE = 0xFFFFFFFE,
    -- enum PROCESSOR_FEATURE_ID
    PROCESSOR_FEATURE_ID_PF_FLOATING_POINT_PRECISION_ERRATA = 0x00000000,
    PROCESSOR_FEATURE_ID_PF_FLOATING_POINT_EMULATED = 0x00000001,
    PROCESSOR_FEATURE_ID_PF_COMPARE_EXCHANGE_DOUBLE = 0x00000002,
    PROCESSOR_FEATURE_ID_PF_MMX_INSTRUCTIONS_AVAILABLE = 0x00000003,
    PROCESSOR_FEATURE_ID_PF_PPC_MOVEMEM_64BIT_OK = 0x00000004,
    PROCESSOR_FEATURE_ID_PF_ALPHA_BYTE_INSTRUCTIONS = 0x00000005,
    PROCESSOR_FEATURE_ID_PF_XMMI_INSTRUCTIONS_AVAILABLE = 0x00000006,
    PROCESSOR_FEATURE_ID_PF_3DNOW_INSTRUCTIONS_AVAILABLE = 0x00000007,
    PROCESSOR_FEATURE_ID_PF_RDTSC_INSTRUCTION_AVAILABLE = 0x00000008,
    PROCESSOR_FEATURE_ID_PF_PAE_ENABLED = 0x00000009,
    PROCESSOR_FEATURE_ID_PF_XMMI64_INSTRUCTIONS_AVAILABLE = 0x0000000A,
    PROCESSOR_FEATURE_ID_PF_SSE_DAZ_MODE_AVAILABLE = 0x0000000B,
    PROCESSOR_FEATURE_ID_PF_NX_ENABLED = 0x0000000C,
    PROCESSOR_FEATURE_ID_PF_SSE3_INSTRUCTIONS_AVAILABLE = 0x0000000D,
    PROCESSOR_FEATURE_ID_PF_COMPARE_EXCHANGE128 = 0x0000000E,
    PROCESSOR_FEATURE_ID_PF_COMPARE64_EXCHANGE128 = 0x0000000F,
    PROCESSOR_FEATURE_ID_PF_CHANNELS_ENABLED = 0x00000010,
    PROCESSOR_FEATURE_ID_PF_XSAVE_ENABLED = 0x00000011,
    PROCESSOR_FEATURE_ID_PF_ARM_VFP_32_REGISTERS_AVAILABLE = 0x00000012,
    PROCESSOR_FEATURE_ID_PF_ARM_NEON_INSTRUCTIONS_AVAILABLE = 0x00000013,
    PROCESSOR_FEATURE_ID_PF_SECOND_LEVEL_ADDRESS_TRANSLATION = 0x00000014,
    PROCESSOR_FEATURE_ID_PF_VIRT_FIRMWARE_ENABLED = 0x00000015,
    PROCESSOR_FEATURE_ID_PF_RDWRFSGSBASE_AVAILABLE = 0x00000016,
    PROCESSOR_FEATURE_ID_PF_FASTFAIL_AVAILABLE = 0x00000017,
    PROCESSOR_FEATURE_ID_PF_ARM_DIVIDE_INSTRUCTION_AVAILABLE = 0x00000018,
    PROCESSOR_FEATURE_ID_PF_ARM_64BIT_LOADSTORE_ATOMIC = 0x00000019,
    PROCESSOR_FEATURE_ID_PF_ARM_EXTERNAL_CACHE_AVAILABLE = 0x0000001A,
    PROCESSOR_FEATURE_ID_PF_ARM_FMAC_INSTRUCTIONS_AVAILABLE = 0x0000001B,
    PROCESSOR_FEATURE_ID_PF_RDRAND_INSTRUCTION_AVAILABLE = 0x0000001C,
    PROCESSOR_FEATURE_ID_PF_ARM_V8_INSTRUCTIONS_AVAILABLE = 0x0000001D,
    PROCESSOR_FEATURE_ID_PF_ARM_V8_CRYPTO_INSTRUCTIONS_AVAILABLE = 0x0000001E,
    PROCESSOR_FEATURE_ID_PF_ARM_V8_CRC32_INSTRUCTIONS_AVAILABLE = 0x0000001F,
    PROCESSOR_FEATURE_ID_PF_RDTSCP_INSTRUCTION_AVAILABLE = 0x00000020,
    PROCESSOR_FEATURE_ID_PF_RDPID_INSTRUCTION_AVAILABLE = 0x00000021,
    PROCESSOR_FEATURE_ID_PF_ARM_V81_ATOMIC_INSTRUCTIONS_AVAILABLE = 0x00000022,
    PROCESSOR_FEATURE_ID_PF_MONITORX_INSTRUCTION_AVAILABLE = 0x00000023,
    PROCESSOR_FEATURE_ID_PF_SSSE3_INSTRUCTIONS_AVAILABLE = 0x00000024,
    PROCESSOR_FEATURE_ID_PF_SSE4_1_INSTRUCTIONS_AVAILABLE = 0x00000025,
    PROCESSOR_FEATURE_ID_PF_SSE4_2_INSTRUCTIONS_AVAILABLE = 0x00000026,
    PROCESSOR_FEATURE_ID_PF_AVX_INSTRUCTIONS_AVAILABLE = 0x00000027,
    PROCESSOR_FEATURE_ID_PF_AVX2_INSTRUCTIONS_AVAILABLE = 0x00000028,
    PROCESSOR_FEATURE_ID_PF_AVX512F_INSTRUCTIONS_AVAILABLE = 0x00000029,
    PROCESSOR_FEATURE_ID_PF_ERMS_AVAILABLE = 0x0000002A,
    PROCESSOR_FEATURE_ID_PF_ARM_V82_DP_INSTRUCTIONS_AVAILABLE = 0x0000002B,
    PROCESSOR_FEATURE_ID_PF_ARM_V83_JSCVT_INSTRUCTIONS_AVAILABLE = 0x0000002C,
    PROCESSOR_FEATURE_ID_PF_ARM_V83_LRCPC_INSTRUCTIONS_AVAILABLE = 0x0000002D,
    -- enum QUEUE_USER_APC_FLAGS
    QUEUE_USER_APC_FLAGS_QUEUE_USER_APC_FLAGS_NONE = 0,
    QUEUE_USER_APC_FLAGS_QUEUE_USER_APC_FLAGS_SPECIAL_USER_APC = 1,
    QUEUE_USER_APC_FLAGS_QUEUE_USER_APC_CALLBACK_DATA_CONTEXT = 65536,
    -- enum RTWQ_WORKQUEUE_TYPE
    RTWQ_WORKQUEUE_TYPE_RTWQ_STANDARD_WORKQUEUE = 0,
    RTWQ_WORKQUEUE_TYPE_RTWQ_WINDOW_WORKQUEUE = 1,
    RTWQ_WORKQUEUE_TYPE_RTWQ_MULTITHREADED_WORKQUEUE = 2,
    -- enum STARTUPINFOW_FLAGS
    STARTUPINFOW_FLAGS_STARTF_FORCEONFEEDBACK = 0x00000040,
    STARTUPINFOW_FLAGS_STARTF_FORCEOFFFEEDBACK = 0x00000080,
    STARTUPINFOW_FLAGS_STARTF_PREVENTPINNING = 0x00002000,
    STARTUPINFOW_FLAGS_STARTF_RUNFULLSCREEN = 0x00000020,
    STARTUPINFOW_FLAGS_STARTF_TITLEISAPPID = 0x00001000,
    STARTUPINFOW_FLAGS_STARTF_TITLEISLINKNAME = 0x00000800,
    STARTUPINFOW_FLAGS_STARTF_UNTRUSTEDSOURCE = 0x00008000,
    STARTUPINFOW_FLAGS_STARTF_USECOUNTCHARS = 0x00000008,
    STARTUPINFOW_FLAGS_STARTF_USEFILLATTRIBUTE = 0x00000010,
    STARTUPINFOW_FLAGS_STARTF_USEHOTKEY = 0x00000200,
    STARTUPINFOW_FLAGS_STARTF_USEPOSITION = 0x00000004,
    STARTUPINFOW_FLAGS_STARTF_USESHOWWINDOW = 0x00000001,
    STARTUPINFOW_FLAGS_STARTF_USESIZE = 0x00000002,
    STARTUPINFOW_FLAGS_STARTF_USESTDHANDLES = 0x00000100,
    -- enum SYNCHRONIZATION_ACCESS_RIGHTS
    SYNCHRONIZATION_ACCESS_RIGHTS_EVENT_ALL_ACCESS = 0x001F0003,
    SYNCHRONIZATION_ACCESS_RIGHTS_EVENT_MODIFY_STATE = 0x00000002,
    SYNCHRONIZATION_ACCESS_RIGHTS_MUTEX_ALL_ACCESS = 0x001F0001,
    SYNCHRONIZATION_ACCESS_RIGHTS_MUTEX_MODIFY_STATE = 0x00000001,
    SYNCHRONIZATION_ACCESS_RIGHTS_SEMAPHORE_ALL_ACCESS = 0x001F0003,
    SYNCHRONIZATION_ACCESS_RIGHTS_SEMAPHORE_MODIFY_STATE = 0x00000002,
    SYNCHRONIZATION_ACCESS_RIGHTS_TIMER_ALL_ACCESS = 0x001F0003,
    SYNCHRONIZATION_ACCESS_RIGHTS_TIMER_MODIFY_STATE = 0x00000002,
    SYNCHRONIZATION_ACCESS_RIGHTS_TIMER_QUERY_STATE = 0x00000001,
    SYNCHRONIZATION_ACCESS_RIGHTS_SYNCHRONIZATION_DELETE = 0x00010000,
    SYNCHRONIZATION_ACCESS_RIGHTS_SYNCHRONIZATION_READ_CONTROL = 0x00020000,
    SYNCHRONIZATION_ACCESS_RIGHTS_SYNCHRONIZATION_WRITE_DAC = 0x00040000,
    SYNCHRONIZATION_ACCESS_RIGHTS_SYNCHRONIZATION_WRITE_OWNER = 0x00080000,
    SYNCHRONIZATION_ACCESS_RIGHTS_SYNCHRONIZATION_SYNCHRONIZE = 0x00100000,
    -- enum THREAD_ACCESS_RIGHTS
    THREAD_ACCESS_RIGHTS_THREAD_TERMINATE = 0x00000001,
    THREAD_ACCESS_RIGHTS_THREAD_SUSPEND_RESUME = 0x00000002,
    THREAD_ACCESS_RIGHTS_THREAD_GET_CONTEXT = 0x00000008,
    THREAD_ACCESS_RIGHTS_THREAD_SET_CONTEXT = 0x00000010,
    THREAD_ACCESS_RIGHTS_THREAD_SET_INFORMATION = 0x00000020,
    THREAD_ACCESS_RIGHTS_THREAD_QUERY_INFORMATION = 0x00000040,
    THREAD_ACCESS_RIGHTS_THREAD_SET_THREAD_TOKEN = 0x00000080,
    THREAD_ACCESS_RIGHTS_THREAD_IMPERSONATE = 0x00000100,
    THREAD_ACCESS_RIGHTS_THREAD_DIRECT_IMPERSONATION = 0x00000200,
    THREAD_ACCESS_RIGHTS_THREAD_SET_LIMITED_INFORMATION = 0x00000400,
    THREAD_ACCESS_RIGHTS_THREAD_QUERY_LIMITED_INFORMATION = 0x00000800,
    THREAD_ACCESS_RIGHTS_THREAD_RESUME = 0x00001000,
    THREAD_ACCESS_RIGHTS_THREAD_ALL_ACCESS = 0x001FFFFF,
    THREAD_ACCESS_RIGHTS_THREAD_DELETE = 0x00010000,
    THREAD_ACCESS_RIGHTS_THREAD_READ_CONTROL = 0x00020000,
    THREAD_ACCESS_RIGHTS_THREAD_WRITE_DAC = 0x00040000,
    THREAD_ACCESS_RIGHTS_THREAD_WRITE_OWNER = 0x00080000,
    THREAD_ACCESS_RIGHTS_THREAD_SYNCHRONIZE = 0x00100000,
    THREAD_ACCESS_RIGHTS_THREAD_STANDARD_RIGHTS_REQUIRED = 0x000F0000,
    -- enum THREAD_CREATION_FLAGS
    THREAD_CREATION_FLAGS_THREAD_CREATE_RUN_IMMEDIATELY = 0x00000000,
    THREAD_CREATION_FLAGS_THREAD_CREATE_SUSPENDED = 0x00000004,
    THREAD_CREATION_FLAGS_STACK_SIZE_PARAM_IS_A_RESERVATION = 0x00010000,
    -- enum THREAD_INFORMATION_CLASS
    THREAD_INFORMATION_CLASS_ThreadMemoryPriority = 0,
    THREAD_INFORMATION_CLASS_ThreadAbsoluteCpuPriority = 1,
    THREAD_INFORMATION_CLASS_ThreadDynamicCodePolicy = 2,
    THREAD_INFORMATION_CLASS_ThreadPowerThrottling = 3,
    THREAD_INFORMATION_CLASS_ThreadInformationClassMax = 4,
    -- enum THREAD_PRIORITY
    THREAD_PRIORITY_THREAD_MODE_BACKGROUND_BEGIN = 65536,
    THREAD_PRIORITY_THREAD_MODE_BACKGROUND_END = 131072,
    THREAD_PRIORITY_THREAD_PRIORITY_ABOVE_NORMAL = 1,
    THREAD_PRIORITY_THREAD_PRIORITY_BELOW_NORMAL = -1,
    THREAD_PRIORITY_THREAD_PRIORITY_HIGHEST = 2,
    THREAD_PRIORITY_THREAD_PRIORITY_IDLE = -15,
    THREAD_PRIORITY_THREAD_PRIORITY_MIN = -2,
    THREAD_PRIORITY_THREAD_PRIORITY_LOWEST = -2,
    THREAD_PRIORITY_THREAD_PRIORITY_NORMAL = 0,
    THREAD_PRIORITY_THREAD_PRIORITY_TIME_CRITICAL = 15,
    -- enum TP_CALLBACK_PRIORITY
    TP_CALLBACK_PRIORITY_TP_CALLBACK_PRIORITY_HIGH = 0,
    TP_CALLBACK_PRIORITY_TP_CALLBACK_PRIORITY_NORMAL = 1,
    TP_CALLBACK_PRIORITY_TP_CALLBACK_PRIORITY_LOW = 2,
    TP_CALLBACK_PRIORITY_TP_CALLBACK_PRIORITY_INVALID = 3,
    TP_CALLBACK_PRIORITY_TP_CALLBACK_PRIORITY_COUNT = 3,
    -- enum UMS_THREAD_INFO_CLASS
    UMS_THREAD_INFO_CLASS_UmsThreadInvalidInfoClass = 0,
    UMS_THREAD_INFO_CLASS_UmsThreadUserContext = 1,
    UMS_THREAD_INFO_CLASS_UmsThreadPriority = 2,
    UMS_THREAD_INFO_CLASS_UmsThreadAffinity = 3,
    UMS_THREAD_INFO_CLASS_UmsThreadTeb = 4,
    UMS_THREAD_INFO_CLASS_UmsThreadIsSuspended = 5,
    UMS_THREAD_INFO_CLASS_UmsThreadIsTerminated = 6,
    UMS_THREAD_INFO_CLASS_UmsThreadMaxInfoClass = 7,
    -- enum WORKER_THREAD_FLAGS
    WORKER_THREAD_FLAGS_WT_EXECUTEDEFAULT = 0x00000000,
    WORKER_THREAD_FLAGS_WT_EXECUTEINIOTHREAD = 0x00000001,
    WORKER_THREAD_FLAGS_WT_EXECUTEINPERSISTENTTHREAD = 0x00000080,
    WORKER_THREAD_FLAGS_WT_EXECUTEINWAITTHREAD = 0x00000004,
    WORKER_THREAD_FLAGS_WT_EXECUTELONGFUNCTION = 0x00000010,
    WORKER_THREAD_FLAGS_WT_EXECUTEONLYONCE = 0x00000008,
    WORKER_THREAD_FLAGS_WT_TRANSFER_IMPERSONATION = 0x00000100,
    WORKER_THREAD_FLAGS_WT_EXECUTEINTIMERTHREAD = 0x00000020,
}
