-- AUTO-GENERATED by tools/winmd-gen (via gen-windows-package.ps1)
-- Namespace: Windows.Win32.System.LibraryLoader
-- Counts: 3 structs, 0 unions, 1 enums, 0 COM interfaces, 49 functions, 14 constants, 0 handle typedefs
--
local W = require "windows"

ffi.cdef[[

typedef struct _ENUMUILANG ENUMUILANG;
typedef struct _REDIRECTION_FUNCTION_DESCRIPTOR REDIRECTION_FUNCTION_DESCRIPTOR;
typedef struct _REDIRECTION_DESCRIPTOR REDIRECTION_DESCRIPTOR;

struct _ENUMUILANG {
    DWORD NumOfEnumUILang;
    DWORD SizeOfEnumUIBuffer;
    WORD * pEnumUIBuffer;
};
struct _REDIRECTION_FUNCTION_DESCRIPTOR {
    LPSTR DllName;
    LPSTR FunctionName;
    void * RedirectionTarget;
};
struct _REDIRECTION_DESCRIPTOR {
    DWORD Version;
    DWORD FunctionCount;
    REDIRECTION_FUNCTION_DESCRIPTOR * Redirections;
};
/* System.LibraryLoader -- 49 functions */
BOOL DisableThreadLibraryCalls(HMODULE hLibModule);
HRSRC FindResourceExW(HMODULE hModule, LPWSTR lpType, LPWSTR lpName, WORD wLanguage);
void FreeLibraryAndExitThread(HMODULE hLibModule, DWORD dwExitCode);
BOOL FreeResource(HGLOBAL hResData);
DWORD GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
DWORD GetModuleFileNameW(HMODULE hModule, LPWSTR lpFilename, DWORD nSize);
HMODULE GetModuleHandleA(LPSTR lpModuleName);
HMODULE GetModuleHandleW(LPWSTR lpModuleName);
BOOL GetModuleHandleExA(DWORD dwFlags, LPSTR lpModuleName, HMODULE * phModule);
BOOL GetModuleHandleExW(DWORD dwFlags, LPWSTR lpModuleName, HMODULE * phModule);
FARPROC GetProcAddress(HMODULE hModule, LPSTR lpProcName);
HMODULE LoadLibraryExA(LPSTR lpLibFileName, HANDLE hFile, LOAD_LIBRARY_FLAGS dwFlags);
HMODULE LoadLibraryExW(LPWSTR lpLibFileName, HANDLE hFile, LOAD_LIBRARY_FLAGS dwFlags);
HGLOBAL LoadResource(HMODULE hModule, HRSRC hResInfo);
void * LockResource(HGLOBAL hResData);
DWORD SizeofResource(HMODULE hModule, HRSRC hResInfo);
void * AddDllDirectory(LPWSTR NewDirectory);
BOOL RemoveDllDirectory(void * Cookie);
BOOL SetDefaultDllDirectories(LOAD_LIBRARY_FLAGS DirectoryFlags);
BOOL EnumResourceLanguagesExA(HMODULE hModule, LPSTR lpType, LPSTR lpName, ENUMRESLANGPROCA lpEnumFunc, void * lParam, DWORD dwFlags, WORD LangId);
BOOL EnumResourceLanguagesExW(HMODULE hModule, LPWSTR lpType, LPWSTR lpName, ENUMRESLANGPROCW lpEnumFunc, void * lParam, DWORD dwFlags, WORD LangId);
BOOL EnumResourceNamesExA(HMODULE hModule, LPSTR lpType, ENUMRESNAMEPROCA lpEnumFunc, void * lParam, DWORD dwFlags, WORD LangId);
BOOL EnumResourceNamesExW(HMODULE hModule, LPWSTR lpType, ENUMRESNAMEPROCW lpEnumFunc, void * lParam, DWORD dwFlags, WORD LangId);
BOOL EnumResourceTypesExA(HMODULE hModule, ENUMRESTYPEPROCA lpEnumFunc, void * lParam, DWORD dwFlags, WORD LangId);
BOOL EnumResourceTypesExW(HMODULE hModule, ENUMRESTYPEPROCW lpEnumFunc, void * lParam, DWORD dwFlags, WORD LangId);
HRSRC FindResourceW(HMODULE hModule, LPWSTR lpName, LPWSTR lpType);
HMODULE LoadLibraryA(LPSTR lpLibFileName);
HMODULE LoadLibraryW(LPWSTR lpLibFileName);
BOOL EnumResourceNamesW(HMODULE hModule, LPWSTR lpType, ENUMRESNAMEPROCW lpEnumFunc, void * lParam);
BOOL EnumResourceNamesA(HMODULE hModule, LPSTR lpType, ENUMRESNAMEPROCA lpEnumFunc, void * lParam);
HMODULE LoadPackagedLibrary(LPWSTR lpwLibFileName, DWORD Reserved);
BOOL QueryOptionalDelayLoadedAPI(HMODULE hParentModule, LPSTR lpDllName, LPSTR lpProcName, DWORD Reserved);
DWORD LoadModule(LPSTR lpModuleName, void * lpParameterBlock);
HRSRC FindResourceA(HMODULE hModule, LPSTR lpName, LPSTR lpType);
HRSRC FindResourceExA(HMODULE hModule, LPSTR lpType, LPSTR lpName, WORD wLanguage);
BOOL EnumResourceTypesA(HMODULE hModule, ENUMRESTYPEPROCA lpEnumFunc, void * lParam);
BOOL EnumResourceTypesW(HMODULE hModule, ENUMRESTYPEPROCW lpEnumFunc, void * lParam);
BOOL EnumResourceLanguagesA(HMODULE hModule, LPSTR lpType, LPSTR lpName, ENUMRESLANGPROCA lpEnumFunc, void * lParam);
BOOL EnumResourceLanguagesW(HMODULE hModule, LPWSTR lpType, LPWSTR lpName, ENUMRESLANGPROCW lpEnumFunc, void * lParam);
HANDLE BeginUpdateResourceA(LPSTR pFileName, BOOL bDeleteExistingResources);
HANDLE BeginUpdateResourceW(LPWSTR pFileName, BOOL bDeleteExistingResources);
BOOL UpdateResourceA(HANDLE hUpdate, LPSTR lpType, LPSTR lpName, WORD wLanguage, void * lpData, DWORD cb);
BOOL UpdateResourceW(HANDLE hUpdate, LPWSTR lpType, LPWSTR lpName, WORD wLanguage, void * lpData, DWORD cb);
BOOL EndUpdateResourceA(HANDLE hUpdate, BOOL fDiscard);
BOOL EndUpdateResourceW(HANDLE hUpdate, BOOL fDiscard);
BOOL SetDllDirectoryA(LPSTR lpPathName);
BOOL SetDllDirectoryW(LPWSTR lpPathName);
DWORD GetDllDirectoryA(DWORD nBufferLength, LPSTR lpBuffer);
DWORD GetDllDirectoryW(DWORD nBufferLength, LPWSTR lpBuffer);
]]

return {
    CURRENT_IMPORT_REDIRECTION_VERSION = 0x00000001,
    FIND_RESOURCE_DIRECTORY_LANGUAGES = 0x00000400,
    FIND_RESOURCE_DIRECTORY_NAMES = 0x00000200,
    FIND_RESOURCE_DIRECTORY_TYPES = 0x00000100,
    GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS = 0x00000004,
    GET_MODULE_HANDLE_EX_FLAG_PIN = 0x00000001,
    GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT = 0x00000002,
    LOAD_LIBRARY_OS_INTEGRITY_CONTINUITY = 0x00008000,
    RESOURCE_ENUM_LN = 0x00000001,
    RESOURCE_ENUM_MODULE_EXACT = 0x00000010,
    RESOURCE_ENUM_MUI = 0x00000002,
    RESOURCE_ENUM_MUI_SYSTEM = 0x00000004,
    RESOURCE_ENUM_VALIDATE = 0x00000008,
    SUPPORT_LANG_NUMBER = 0x00000020,
    -- enum LOAD_LIBRARY_FLAGS
    LOAD_LIBRARY_FLAGS_DONT_RESOLVE_DLL_REFERENCES = 0x00000001,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_AS_DATAFILE = 0x00000002,
    LOAD_LIBRARY_FLAGS_LOAD_WITH_ALTERED_SEARCH_PATH = 0x00000008,
    LOAD_LIBRARY_FLAGS_LOAD_IGNORE_CODE_AUTHZ_LEVEL = 0x00000010,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_AS_IMAGE_RESOURCE = 0x00000020,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE = 0x00000040,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_REQUIRE_SIGNED_TARGET = 0x00000080,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR = 0x00000100,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_SEARCH_APPLICATION_DIR = 0x00000200,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_SEARCH_USER_DIRS = 0x00000400,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_SEARCH_SYSTEM32 = 0x00000800,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_SEARCH_DEFAULT_DIRS = 0x00001000,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_SAFE_CURRENT_DIRS = 0x00002000,
    LOAD_LIBRARY_FLAGS_LOAD_LIBRARY_SEARCH_SYSTEM32_NO_FORWARDER = 0x00004000,
}
