-- AUTO-GENERATED by tools/winmd-gen (via gen-windows-package.ps1)
-- Namespace: Windows.Win32.System.Pipes
-- Counts: 0 structs, 0 unions, 1 enums, 0 COM interfaces, 22 functions, 4 constants, 0 handle typedefs
--
local W = require "windows"

ffi.cdef[[


/* System.Pipes -- 22 functions */
BOOL CreatePipe(HANDLE * hReadPipe, HANDLE * hWritePipe, SECURITY_ATTRIBUTES * lpPipeAttributes, DWORD nSize);
BOOL ConnectNamedPipe(HANDLE hNamedPipe, OVERLAPPED * lpOverlapped);
BOOL DisconnectNamedPipe(HANDLE hNamedPipe);
BOOL SetNamedPipeHandleState(HANDLE hNamedPipe, NAMED_PIPE_MODE * lpMode, DWORD * lpMaxCollectionCount, DWORD * lpCollectDataTimeout);
BOOL PeekNamedPipe(HANDLE hNamedPipe, void * lpBuffer, DWORD nBufferSize, DWORD * lpBytesRead, DWORD * lpTotalBytesAvail, DWORD * lpBytesLeftThisMessage);
BOOL TransactNamedPipe(HANDLE hNamedPipe, void * lpInBuffer, DWORD nInBufferSize, void * lpOutBuffer, DWORD nOutBufferSize, DWORD * lpBytesRead, OVERLAPPED * lpOverlapped);
HANDLE CreateNamedPipeW(LPWSTR lpName, FILE_FLAGS_AND_ATTRIBUTES dwOpenMode, NAMED_PIPE_MODE dwPipeMode, DWORD nMaxInstances, DWORD nOutBufferSize, DWORD nInBufferSize, DWORD nDefaultTimeOut, SECURITY_ATTRIBUTES * lpSecurityAttributes);
BOOL WaitNamedPipeW(LPWSTR lpNamedPipeName, DWORD nTimeOut);
BOOL GetNamedPipeClientComputerNameW(HANDLE Pipe, LPWSTR ClientComputerName, DWORD ClientComputerNameLength);
BOOL ImpersonateNamedPipeClient(HANDLE hNamedPipe);
BOOL GetNamedPipeInfo(HANDLE hNamedPipe, NAMED_PIPE_MODE * lpFlags, DWORD * lpOutBufferSize, DWORD * lpInBufferSize, DWORD * lpMaxInstances);
BOOL GetNamedPipeHandleStateW(HANDLE hNamedPipe, NAMED_PIPE_MODE * lpState, DWORD * lpCurInstances, DWORD * lpMaxCollectionCount, DWORD * lpCollectDataTimeout, LPWSTR lpUserName, DWORD nMaxUserNameSize);
BOOL CallNamedPipeW(LPWSTR lpNamedPipeName, void * lpInBuffer, DWORD nInBufferSize, void * lpOutBuffer, DWORD nOutBufferSize, DWORD * lpBytesRead, DWORD nTimeOut);
HANDLE CreateNamedPipeA(LPSTR lpName, FILE_FLAGS_AND_ATTRIBUTES dwOpenMode, NAMED_PIPE_MODE dwPipeMode, DWORD nMaxInstances, DWORD nOutBufferSize, DWORD nInBufferSize, DWORD nDefaultTimeOut, SECURITY_ATTRIBUTES * lpSecurityAttributes);
BOOL GetNamedPipeHandleStateA(HANDLE hNamedPipe, NAMED_PIPE_MODE * lpState, DWORD * lpCurInstances, DWORD * lpMaxCollectionCount, DWORD * lpCollectDataTimeout, LPSTR lpUserName, DWORD nMaxUserNameSize);
BOOL CallNamedPipeA(LPSTR lpNamedPipeName, void * lpInBuffer, DWORD nInBufferSize, void * lpOutBuffer, DWORD nOutBufferSize, DWORD * lpBytesRead, DWORD nTimeOut);
BOOL WaitNamedPipeA(LPSTR lpNamedPipeName, DWORD nTimeOut);
BOOL GetNamedPipeClientComputerNameA(HANDLE Pipe, LPSTR ClientComputerName, DWORD ClientComputerNameLength);
BOOL GetNamedPipeClientProcessId(HANDLE Pipe, DWORD * ClientProcessId);
BOOL GetNamedPipeClientSessionId(HANDLE Pipe, DWORD * ClientSessionId);
BOOL GetNamedPipeServerProcessId(HANDLE Pipe, DWORD * ServerProcessId);
BOOL GetNamedPipeServerSessionId(HANDLE Pipe, DWORD * ServerSessionId);
]]

return {
    NMPWAIT_NOWAIT = 0x00000001,
    NMPWAIT_USE_DEFAULT_WAIT = 0x00000000,
    NMPWAIT_WAIT_FOREVER = 0xFFFFFFFF,
    PIPE_UNLIMITED_INSTANCES = 0x000000FF,
    -- enum NAMED_PIPE_MODE
    NAMED_PIPE_MODE_PIPE_WAIT = 0x00000000,
    NAMED_PIPE_MODE_PIPE_NOWAIT = 0x00000001,
    NAMED_PIPE_MODE_PIPE_READMODE_BYTE = 0x00000000,
    NAMED_PIPE_MODE_PIPE_READMODE_MESSAGE = 0x00000002,
    NAMED_PIPE_MODE_PIPE_CLIENT_END = 0x00000000,
    NAMED_PIPE_MODE_PIPE_SERVER_END = 0x00000001,
    NAMED_PIPE_MODE_PIPE_TYPE_BYTE = 0x00000000,
    NAMED_PIPE_MODE_PIPE_TYPE_MESSAGE = 0x00000004,
    NAMED_PIPE_MODE_PIPE_ACCEPT_REMOTE_CLIENTS = 0x00000000,
    NAMED_PIPE_MODE_PIPE_REJECT_REMOTE_CLIENTS = 0x00000008,
}
