-- AUTO-GENERATED by tools/winmd-gen (via gen-windows-package.ps1)
-- Namespace: Windows.Win32.System.Power
-- Counts: 76 structs, 0 unions, 26 enums, 0 COM interfaces, 97 functions, 165 constants, 1 handle typedefs
--
local W = require "windows"

ffi.cdef[[
typedef void * HPOWERNOTIFY;

typedef struct _PROCESSOR_POWER_INFORMATION PROCESSOR_POWER_INFORMATION;
typedef struct _SYSTEM_POWER_INFORMATION SYSTEM_POWER_INFORMATION;
typedef struct _GLOBAL_MACHINE_POWER_POLICY GLOBAL_MACHINE_POWER_POLICY;
typedef struct _GLOBAL_USER_POWER_POLICY GLOBAL_USER_POWER_POLICY;
typedef struct _GLOBAL_POWER_POLICY GLOBAL_POWER_POLICY;
typedef struct _MACHINE_POWER_POLICY MACHINE_POWER_POLICY;
typedef struct _MACHINE_PROCESSOR_POWER_POLICY MACHINE_PROCESSOR_POWER_POLICY;
typedef struct _USER_POWER_POLICY USER_POWER_POLICY;
typedef struct _POWER_POLICY POWER_POLICY;
typedef struct _DEVICE_NOTIFY_SUBSCRIBE_PARAMETERS DEVICE_NOTIFY_SUBSCRIBE_PARAMETERS;
typedef struct _THERMAL_EVENT THERMAL_EVENT;
typedef struct _BATTERY_QUERY_INFORMATION BATTERY_QUERY_INFORMATION;
typedef struct _BATTERY_INFORMATION BATTERY_INFORMATION;
typedef struct _BATTERY_CHARGING_SOURCE BATTERY_CHARGING_SOURCE;
typedef struct _BATTERY_CHARGING_SOURCE_INFORMATION BATTERY_CHARGING_SOURCE_INFORMATION;
typedef struct _BATTERY_SET_INFORMATION BATTERY_SET_INFORMATION;
typedef struct _BATTERY_CHARGER_STATUS BATTERY_CHARGER_STATUS;
typedef struct _BATTERY_USB_CHARGER_STATUS BATTERY_USB_CHARGER_STATUS;
typedef struct _BATTERY_WAIT_STATUS BATTERY_WAIT_STATUS;
typedef struct _BATTERY_STATUS BATTERY_STATUS;
typedef struct _BATTERY_MANUFACTURE_DATE BATTERY_MANUFACTURE_DATE;
typedef struct _THERMAL_INFORMATION THERMAL_INFORMATION;
typedef struct _THERMAL_WAIT_READ THERMAL_WAIT_READ;
typedef struct _THERMAL_POLICY THERMAL_POLICY;
typedef struct _PROCESSOR_OBJECT_INFO PROCESSOR_OBJECT_INFO;
typedef struct _PROCESSOR_OBJECT_INFO_EX PROCESSOR_OBJECT_INFO_EX;
typedef struct _WAKE_ALARM_INFORMATION WAKE_ALARM_INFORMATION;
typedef struct _ACPI_REAL_TIME ACPI_REAL_TIME;
typedef struct _ACPI_TIME_AND_ALARM_CAPABILITIES ACPI_TIME_AND_ALARM_CAPABILITIES;
typedef struct _EMI_VERSION EMI_VERSION;
typedef struct _EMI_METADATA_SIZE EMI_METADATA_SIZE;
typedef struct _EMI_CHANNEL_MEASUREMENT_DATA EMI_CHANNEL_MEASUREMENT_DATA;
typedef struct _EMI_METADATA_V1 EMI_METADATA_V1;
typedef struct _EMI_CHANNEL_V2 EMI_CHANNEL_V2;
typedef struct _EMI_METADATA_V2 EMI_METADATA_V2;
typedef struct _EMI_MEASUREMENT_DATA_V2 EMI_MEASUREMENT_DATA_V2;
typedef struct _CM_POWER_DATA CM_POWER_DATA;
typedef struct _POWER_USER_PRESENCE POWER_USER_PRESENCE;
typedef struct _POWER_SESSION_CONNECT POWER_SESSION_CONNECT;
typedef struct _POWER_SESSION_TIMEOUTS POWER_SESSION_TIMEOUTS;
typedef struct _POWER_SESSION_RIT_STATE POWER_SESSION_RIT_STATE;
typedef struct _POWER_SESSION_WINLOGON POWER_SESSION_WINLOGON;
typedef struct _POWER_SESSION_ALLOW_EXTERNAL_DMA_DEVICES POWER_SESSION_ALLOW_EXTERNAL_DMA_DEVICES;
typedef struct _POWER_IDLE_RESILIENCY POWER_IDLE_RESILIENCY;
typedef struct _POWER_MONITOR_INVOCATION POWER_MONITOR_INVOCATION;
typedef struct _RESUME_PERFORMANCE RESUME_PERFORMANCE;
typedef struct _SET_POWER_SETTING_VALUE SET_POWER_SETTING_VALUE;
typedef struct _POWER_PLATFORM_INFORMATION POWER_PLATFORM_INFORMATION;
typedef struct _BATTERY_REPORTING_SCALE BATTERY_REPORTING_SCALE;
typedef struct _PPM_WMI_LEGACY_PERFSTATE PPM_WMI_LEGACY_PERFSTATE;
typedef struct _PPM_WMI_IDLE_STATE PPM_WMI_IDLE_STATE;
typedef struct _PPM_WMI_IDLE_STATES PPM_WMI_IDLE_STATES;
typedef struct _PPM_WMI_IDLE_STATES_EX PPM_WMI_IDLE_STATES_EX;
typedef struct _PPM_WMI_PERF_STATE PPM_WMI_PERF_STATE;
typedef struct _PPM_WMI_PERF_STATES PPM_WMI_PERF_STATES;
typedef struct _PPM_WMI_PERF_STATES_EX PPM_WMI_PERF_STATES_EX;
typedef struct _PPM_IDLE_STATE_ACCOUNTING PPM_IDLE_STATE_ACCOUNTING;
typedef struct _PPM_IDLE_ACCOUNTING PPM_IDLE_ACCOUNTING;
typedef struct _PPM_IDLE_STATE_BUCKET_EX PPM_IDLE_STATE_BUCKET_EX;
typedef struct _PPM_IDLE_STATE_ACCOUNTING_EX PPM_IDLE_STATE_ACCOUNTING_EX;
typedef struct _PPM_IDLE_ACCOUNTING_EX PPM_IDLE_ACCOUNTING_EX;
typedef struct _PPM_PERFSTATE_EVENT PPM_PERFSTATE_EVENT;
typedef struct _PPM_PERFSTATE_DOMAIN_EVENT PPM_PERFSTATE_DOMAIN_EVENT;
typedef struct _PPM_IDLESTATE_EVENT PPM_IDLESTATE_EVENT;
typedef struct _PPM_THERMALCHANGE_EVENT PPM_THERMALCHANGE_EVENT;
typedef struct _PPM_THERMAL_POLICY_EVENT PPM_THERMAL_POLICY_EVENT;
typedef struct _POWER_ACTION_POLICY POWER_ACTION_POLICY;
typedef struct _SYSTEM_POWER_LEVEL SYSTEM_POWER_LEVEL;
typedef struct _SYSTEM_POWER_POLICY SYSTEM_POWER_POLICY;
typedef struct _PROCESSOR_POWER_POLICY_INFO PROCESSOR_POWER_POLICY_INFO;
typedef struct _PROCESSOR_POWER_POLICY PROCESSOR_POWER_POLICY;
typedef struct _ADMINISTRATOR_POWER_POLICY ADMINISTRATOR_POWER_POLICY;
typedef struct _SYSTEM_POWER_CAPABILITIES SYSTEM_POWER_CAPABILITIES;
typedef struct _SYSTEM_BATTERY_STATE SYSTEM_BATTERY_STATE;
typedef struct _POWERBROADCAST_SETTING POWERBROADCAST_SETTING;
typedef struct _SYSTEM_POWER_STATUS SYSTEM_POWER_STATUS;

struct _PROCESSOR_POWER_INFORMATION {
    DWORD Number;
    DWORD MaxMhz;
    DWORD CurrentMhz;
    DWORD MhzLimit;
    DWORD MaxIdleState;
    DWORD CurrentIdleState;
};
struct _SYSTEM_POWER_INFORMATION {
    DWORD MaxIdlenessAllowed;
    DWORD Idleness;
    DWORD TimeRemaining;
    POWER_COOLING_MODE CoolingMode;
};
struct _GLOBAL_MACHINE_POWER_POLICY {
    DWORD Revision;
    SYSTEM_POWER_STATE LidOpenWakeAc;
    SYSTEM_POWER_STATE LidOpenWakeDc;
    DWORD BroadcastCapacityResolution;
};
struct _GLOBAL_USER_POWER_POLICY {
    DWORD Revision;
    POWER_ACTION_POLICY PowerButtonAc;
    POWER_ACTION_POLICY PowerButtonDc;
    POWER_ACTION_POLICY SleepButtonAc;
    POWER_ACTION_POLICY SleepButtonDc;
    POWER_ACTION_POLICY LidCloseAc;
    POWER_ACTION_POLICY LidCloseDc;
    SYSTEM_POWER_LEVEL * DischargePolicy;
    DWORD GlobalFlags;
};
struct _GLOBAL_POWER_POLICY {
    GLOBAL_USER_POWER_POLICY user;
    GLOBAL_MACHINE_POWER_POLICY mach;
};
struct _MACHINE_POWER_POLICY {
    DWORD Revision;
    SYSTEM_POWER_STATE MinSleepAc;
    SYSTEM_POWER_STATE MinSleepDc;
    SYSTEM_POWER_STATE ReducedLatencySleepAc;
    SYSTEM_POWER_STATE ReducedLatencySleepDc;
    DWORD DozeTimeoutAc;
    DWORD DozeTimeoutDc;
    DWORD DozeS4TimeoutAc;
    DWORD DozeS4TimeoutDc;
    BYTE MinThrottleAc;
    BYTE MinThrottleDc;
    BYTE * pad1;
    POWER_ACTION_POLICY OverThrottledAc;
    POWER_ACTION_POLICY OverThrottledDc;
};
struct _MACHINE_PROCESSOR_POWER_POLICY {
    DWORD Revision;
    PROCESSOR_POWER_POLICY ProcessorPolicyAc;
    PROCESSOR_POWER_POLICY ProcessorPolicyDc;
};
struct _USER_POWER_POLICY {
    DWORD Revision;
    POWER_ACTION_POLICY IdleAc;
    POWER_ACTION_POLICY IdleDc;
    DWORD IdleTimeoutAc;
    DWORD IdleTimeoutDc;
    BYTE IdleSensitivityAc;
    BYTE IdleSensitivityDc;
    BYTE ThrottlePolicyAc;
    BYTE ThrottlePolicyDc;
    SYSTEM_POWER_STATE MaxSleepAc;
    SYSTEM_POWER_STATE MaxSleepDc;
    DWORD * Reserved;
    DWORD VideoTimeoutAc;
    DWORD VideoTimeoutDc;
    DWORD SpindownTimeoutAc;
    DWORD SpindownTimeoutDc;
    BYTE OptimizeForPowerAc;
    BYTE OptimizeForPowerDc;
    BYTE FanThrottleToleranceAc;
    BYTE FanThrottleToleranceDc;
    BYTE ForcedThrottleAc;
    BYTE ForcedThrottleDc;
};
struct _POWER_POLICY {
    USER_POWER_POLICY user;
    MACHINE_POWER_POLICY mach;
};
struct _DEVICE_NOTIFY_SUBSCRIBE_PARAMETERS {
    PDEVICE_NOTIFY_CALLBACK_ROUTINE Callback;
    void * Context;
};
struct _THERMAL_EVENT {
    DWORD Version;
    DWORD Size;
    DWORD Type;
    DWORD Temperature;
    DWORD TripPointTemperature;
    LPWSTR Initiator;
};
struct _BATTERY_QUERY_INFORMATION {
    DWORD BatteryTag;
    BATTERY_QUERY_INFORMATION_LEVEL InformationLevel;
    DWORD AtRate;
};
struct _BATTERY_INFORMATION {
    DWORD Capabilities;
    BYTE Technology;
    BYTE * Reserved;
    BYTE * Chemistry;
    DWORD DesignedCapacity;
    DWORD FullChargedCapacity;
    DWORD DefaultAlert1;
    DWORD DefaultAlert2;
    DWORD CriticalBias;
    DWORD CycleCount;
};
struct _BATTERY_CHARGING_SOURCE {
    BATTERY_CHARGING_SOURCE_TYPE Type;
    DWORD MaxCurrent;
};
struct _BATTERY_CHARGING_SOURCE_INFORMATION {
    BATTERY_CHARGING_SOURCE_TYPE Type;
    BYTE SourceOnline;
};
struct _BATTERY_SET_INFORMATION {
    DWORD BatteryTag;
    BATTERY_SET_INFORMATION_LEVEL InformationLevel;
    BYTE * Buffer;
};
struct _BATTERY_CHARGER_STATUS {
    BATTERY_CHARGING_SOURCE_TYPE Type;
    DWORD * VaData;
};
struct _BATTERY_USB_CHARGER_STATUS {
    BATTERY_CHARGING_SOURCE_TYPE Type;
    DWORD Reserved;
    DWORD Flags;
    DWORD MaxCurrent;
    DWORD Voltage;
    USB_CHARGER_PORT PortType;
    ULONGLONG PortId;
    void * PowerSourceInformation;
    Guid OemCharger;
};
struct _BATTERY_WAIT_STATUS {
    DWORD BatteryTag;
    DWORD Timeout;
    DWORD PowerState;
    DWORD LowCapacity;
    DWORD HighCapacity;
};
struct _BATTERY_STATUS {
    DWORD PowerState;
    DWORD Capacity;
    DWORD Voltage;
    LONG Rate;
};
struct _BATTERY_MANUFACTURE_DATE {
    BYTE Day;
    BYTE Month;
    WORD Year;
};
struct _THERMAL_INFORMATION {
    DWORD ThermalStamp;
    DWORD ThermalConstant1;
    DWORD ThermalConstant2;
    void * Processors;
    DWORD SamplingPeriod;
    DWORD CurrentTemperature;
    DWORD PassiveTripPoint;
    DWORD CriticalTripPoint;
    BYTE ActiveTripPointCount;
    DWORD * ActiveTripPoint;
};
struct _THERMAL_WAIT_READ {
    DWORD Timeout;
    DWORD LowTemperature;
    DWORD HighTemperature;
};
struct _THERMAL_POLICY {
    DWORD Version;
    BYTE WaitForUpdate;
    BYTE Hibernate;
    BYTE Critical;
    BYTE ThermalStandby;
    DWORD ActivationReasons;
    DWORD PassiveLimit;
    DWORD ActiveLevel;
    BYTE OverThrottled;
};
struct _PROCESSOR_OBJECT_INFO {
    DWORD PhysicalID;
    DWORD PBlkAddress;
    BYTE PBlkLength;
};
struct _PROCESSOR_OBJECT_INFO_EX {
    DWORD PhysicalID;
    DWORD PBlkAddress;
    BYTE PBlkLength;
    DWORD InitialApicId;
};
struct _WAKE_ALARM_INFORMATION {
    DWORD TimerIdentifier;
    DWORD Timeout;
};
struct _ACPI_REAL_TIME {
    WORD Year;
    BYTE Month;
    BYTE Day;
    BYTE Hour;
    BYTE Minute;
    BYTE Second;
    BYTE Valid;
    WORD Milliseconds;
    short TimeZone;
    BYTE DayLight;
    BYTE * Reserved1;
};
struct _ACPI_TIME_AND_ALARM_CAPABILITIES {
    BYTE AcWakeSupported;
    BYTE DcWakeSupported;
    BYTE S4AcWakeSupported;
    BYTE S4DcWakeSupported;
    BYTE S5AcWakeSupported;
    BYTE S5DcWakeSupported;
    BYTE S4S5WakeStatusSupported;
    DWORD DeepestWakeSystemState;
    BYTE RealTimeFeaturesSupported;
    ACPI_TIME_RESOLUTION RealTimeResolution;
};
struct _EMI_VERSION {
    WORD EmiVersion;
};
struct _EMI_METADATA_SIZE {
    DWORD MetadataSize;
};
struct _EMI_CHANNEL_MEASUREMENT_DATA {
    ULONGLONG AbsoluteEnergy;
    ULONGLONG AbsoluteTime;
};
struct _EMI_METADATA_V1 {
    EMI_MEASUREMENT_UNIT MeasurementUnit;
    WCHAR * HardwareOEM;
    WCHAR * HardwareModel;
    WORD HardwareRevision;
    WORD MeteredHardwareNameSize;
    WCHAR * MeteredHardwareName;
};
struct _EMI_CHANNEL_V2 {
    EMI_MEASUREMENT_UNIT MeasurementUnit;
    WORD ChannelNameSize;
    WCHAR * ChannelName;
};
struct _EMI_METADATA_V2 {
    WCHAR * HardwareOEM;
    WCHAR * HardwareModel;
    WORD HardwareRevision;
    WORD ChannelCount;
    EMI_CHANNEL_V2 * Channels;
};
struct _EMI_MEASUREMENT_DATA_V2 {
    EMI_CHANNEL_MEASUREMENT_DATA * ChannelData;
};
struct _CM_POWER_DATA {
    DWORD PD_Size;
    DEVICE_POWER_STATE PD_MostRecentPowerState;
    DWORD PD_Capabilities;
    DWORD PD_D1Latency;
    DWORD PD_D2Latency;
    DWORD PD_D3Latency;
    DEVICE_POWER_STATE * PD_PowerStateMapping;
    SYSTEM_POWER_STATE PD_DeepestSystemWake;
};
struct _POWER_USER_PRESENCE {
    POWER_USER_PRESENCE_TYPE UserPresence;
};
struct _POWER_SESSION_CONNECT {
    BYTE Connected;
    BYTE Console;
};
struct _POWER_SESSION_TIMEOUTS {
    DWORD InputTimeout;
    DWORD DisplayTimeout;
};
struct _POWER_SESSION_RIT_STATE {
    BYTE Active;
    ULONGLONG LastInputTime;
};
struct _POWER_SESSION_WINLOGON {
    DWORD SessionId;
    BYTE Console;
    BYTE Locked;
};
struct _POWER_SESSION_ALLOW_EXTERNAL_DMA_DEVICES {
    BYTE IsAllowed;
};
struct _POWER_IDLE_RESILIENCY {
    DWORD CoalescingTimeout;
    DWORD IdleResiliencyPeriod;
};
struct _POWER_MONITOR_INVOCATION {
    BYTE Console;
    POWER_MONITOR_REQUEST_REASON RequestReason;
};
struct _RESUME_PERFORMANCE {
    DWORD PostTimeMs;
    ULONGLONG TotalResumeTimeMs;
    ULONGLONG ResumeCompleteTimestamp;
};
struct _SET_POWER_SETTING_VALUE {
    DWORD Version;
    Guid Guid;
    SYSTEM_POWER_CONDITION PowerCondition;
    DWORD DataLength;
    BYTE * Data;
};
struct _POWER_PLATFORM_INFORMATION {
    BYTE AoAc;
};
struct _BATTERY_REPORTING_SCALE {
    DWORD Granularity;
    DWORD Capacity;
};
struct _PPM_WMI_LEGACY_PERFSTATE {
    DWORD Frequency;
    DWORD Flags;
    DWORD PercentFrequency;
};
struct _PPM_WMI_IDLE_STATE {
    DWORD Latency;
    DWORD Power;
    DWORD TimeCheck;
    BYTE PromotePercent;
    BYTE DemotePercent;
    BYTE StateType;
    BYTE Reserved;
    DWORD StateFlags;
    DWORD Context;
    DWORD IdleHandler;
    DWORD Reserved1;
};
struct _PPM_WMI_IDLE_STATES {
    DWORD Type;
    DWORD Count;
    DWORD TargetState;
    DWORD OldState;
    ULONGLONG TargetProcessors;
    PPM_WMI_IDLE_STATE * State;
};
struct _PPM_WMI_IDLE_STATES_EX {
    DWORD Type;
    DWORD Count;
    DWORD TargetState;
    DWORD OldState;
    void * TargetProcessors;
    PPM_WMI_IDLE_STATE * State;
};
struct _PPM_WMI_PERF_STATE {
    DWORD Frequency;
    DWORD Power;
    BYTE PercentFrequency;
    BYTE IncreaseLevel;
    BYTE DecreaseLevel;
    BYTE Type;
    DWORD IncreaseTime;
    DWORD DecreaseTime;
    ULONGLONG Control;
    ULONGLONG Status;
    DWORD HitCount;
    DWORD Reserved1;
    ULONGLONG Reserved2;
    ULONGLONG Reserved3;
};
struct _PPM_WMI_PERF_STATES {
    DWORD Count;
    DWORD MaxFrequency;
    DWORD CurrentState;
    DWORD MaxPerfState;
    DWORD MinPerfState;
    DWORD LowestPerfState;
    DWORD ThermalConstraint;
    BYTE BusyAdjThreshold;
    BYTE PolicyType;
    BYTE Type;
    BYTE Reserved;
    DWORD TimerInterval;
    ULONGLONG TargetProcessors;
    DWORD PStateHandler;
    DWORD PStateContext;
    DWORD TStateHandler;
    DWORD TStateContext;
    DWORD FeedbackHandler;
    DWORD Reserved1;
    ULONGLONG Reserved2;
    PPM_WMI_PERF_STATE * State;
};
struct _PPM_WMI_PERF_STATES_EX {
    DWORD Count;
    DWORD MaxFrequency;
    DWORD CurrentState;
    DWORD MaxPerfState;
    DWORD MinPerfState;
    DWORD LowestPerfState;
    DWORD ThermalConstraint;
    BYTE BusyAdjThreshold;
    BYTE PolicyType;
    BYTE Type;
    BYTE Reserved;
    DWORD TimerInterval;
    void * TargetProcessors;
    DWORD PStateHandler;
    DWORD PStateContext;
    DWORD TStateHandler;
    DWORD TStateContext;
    DWORD FeedbackHandler;
    DWORD Reserved1;
    ULONGLONG Reserved2;
    PPM_WMI_PERF_STATE * State;
};
struct _PPM_IDLE_STATE_ACCOUNTING {
    DWORD IdleTransitions;
    DWORD FailedTransitions;
    DWORD InvalidBucketIndex;
    ULONGLONG TotalTime;
    DWORD * IdleTimeBuckets;
};
struct _PPM_IDLE_ACCOUNTING {
    DWORD StateCount;
    DWORD TotalTransitions;
    DWORD ResetCount;
    ULONGLONG StartTime;
    PPM_IDLE_STATE_ACCOUNTING * State;
};
struct _PPM_IDLE_STATE_BUCKET_EX {
    ULONGLONG TotalTimeUs;
    DWORD MinTimeUs;
    DWORD MaxTimeUs;
    DWORD Count;
};
struct _PPM_IDLE_STATE_ACCOUNTING_EX {
    ULONGLONG TotalTime;
    DWORD IdleTransitions;
    DWORD FailedTransitions;
    DWORD InvalidBucketIndex;
    DWORD MinTimeUs;
    DWORD MaxTimeUs;
    DWORD CancelledTransitions;
    PPM_IDLE_STATE_BUCKET_EX * IdleTimeBuckets;
};
struct _PPM_IDLE_ACCOUNTING_EX {
    DWORD StateCount;
    DWORD TotalTransitions;
    DWORD ResetCount;
    DWORD AbortCount;
    ULONGLONG StartTime;
    PPM_IDLE_STATE_ACCOUNTING_EX * State;
};
struct _PPM_PERFSTATE_EVENT {
    DWORD State;
    DWORD Status;
    DWORD Latency;
    DWORD Speed;
    DWORD Processor;
};
struct _PPM_PERFSTATE_DOMAIN_EVENT {
    DWORD State;
    DWORD Latency;
    DWORD Speed;
    ULONGLONG Processors;
};
struct _PPM_IDLESTATE_EVENT {
    DWORD NewState;
    DWORD OldState;
    ULONGLONG Processors;
};
struct _PPM_THERMALCHANGE_EVENT {
    DWORD ThermalConstraint;
    ULONGLONG Processors;
};
struct _PPM_THERMAL_POLICY_EVENT {
    BYTE Mode;
    ULONGLONG Processors;
};
struct _POWER_ACTION_POLICY {
    POWER_ACTION Action;
    DWORD Flags;
    POWER_ACTION_POLICY_EVENT_CODE EventCode;
};
struct _SYSTEM_POWER_LEVEL {
    BYTE Enable;
    BYTE * Spare;
    DWORD BatteryLevel;
    POWER_ACTION_POLICY PowerPolicy;
    SYSTEM_POWER_STATE MinSystemState;
};
struct _SYSTEM_POWER_POLICY {
    DWORD Revision;
    POWER_ACTION_POLICY PowerButton;
    POWER_ACTION_POLICY SleepButton;
    POWER_ACTION_POLICY LidClose;
    SYSTEM_POWER_STATE LidOpenWake;
    DWORD Reserved;
    POWER_ACTION_POLICY Idle;
    DWORD IdleTimeout;
    BYTE IdleSensitivity;
    BYTE DynamicThrottle;
    BYTE * Spare2;
    SYSTEM_POWER_STATE MinSleep;
    SYSTEM_POWER_STATE MaxSleep;
    SYSTEM_POWER_STATE ReducedLatencySleep;
    DWORD WinLogonFlags;
    DWORD Spare3;
    DWORD DozeS4Timeout;
    DWORD BroadcastCapacityResolution;
    SYSTEM_POWER_LEVEL * DischargePolicy;
    DWORD VideoTimeout;
    BYTE VideoDimDisplay;
    DWORD * VideoReserved;
    DWORD SpindownTimeout;
    BYTE OptimizeForPower;
    BYTE FanThrottleTolerance;
    BYTE ForcedThrottle;
    BYTE MinThrottle;
    POWER_ACTION_POLICY OverThrottled;
};
struct _PROCESSOR_POWER_POLICY_INFO {
    DWORD TimeCheck;
    DWORD DemoteLimit;
    DWORD PromoteLimit;
    BYTE DemotePercent;
    BYTE PromotePercent;
    BYTE * Spare;
    DWORD _bitfield;
};
struct _PROCESSOR_POWER_POLICY {
    DWORD Revision;
    BYTE DynamicThrottle;
    BYTE * Spare;
    DWORD _bitfield;
    DWORD PolicyCount;
    PROCESSOR_POWER_POLICY_INFO * Policy;
};
struct _ADMINISTRATOR_POWER_POLICY {
    SYSTEM_POWER_STATE MinSleep;
    SYSTEM_POWER_STATE MaxSleep;
    DWORD MinVideoTimeout;
    DWORD MaxVideoTimeout;
    DWORD MinSpindownTimeout;
    DWORD MaxSpindownTimeout;
};
struct _SYSTEM_POWER_CAPABILITIES {
    BYTE PowerButtonPresent;
    BYTE SleepButtonPresent;
    BYTE LidPresent;
    BYTE SystemS1;
    BYTE SystemS2;
    BYTE SystemS3;
    BYTE SystemS4;
    BYTE SystemS5;
    BYTE HiberFilePresent;
    BYTE FullWake;
    BYTE VideoDimPresent;
    BYTE ApmPresent;
    BYTE UpsPresent;
    BYTE ThermalControl;
    BYTE ProcessorThrottle;
    BYTE ProcessorMinThrottle;
    BYTE ProcessorMaxThrottle;
    BYTE FastSystemS4;
    BYTE Hiberboot;
    BYTE WakeAlarmPresent;
    BYTE AoAc;
    BYTE DiskSpinDown;
    BYTE HiberFileType;
    BYTE AoAcConnectivitySupported;
    BYTE * spare3;
    BYTE SystemBatteriesPresent;
    BYTE BatteriesAreShortTerm;
    BATTERY_REPORTING_SCALE * BatteryScale;
    SYSTEM_POWER_STATE AcOnLineWake;
    SYSTEM_POWER_STATE SoftLidWake;
    SYSTEM_POWER_STATE RtcWake;
    SYSTEM_POWER_STATE MinDeviceWakeState;
    SYSTEM_POWER_STATE DefaultLowLatencyWake;
};
struct _SYSTEM_BATTERY_STATE {
    BYTE AcOnLine;
    BYTE BatteryPresent;
    BYTE Charging;
    BYTE Discharging;
    BYTE * Spare1;
    BYTE Tag;
    DWORD MaxCapacity;
    DWORD RemainingCapacity;
    DWORD Rate;
    DWORD EstimatedTime;
    DWORD DefaultAlert1;
    DWORD DefaultAlert2;
};
struct _POWERBROADCAST_SETTING {
    Guid PowerSetting;
    DWORD DataLength;
    BYTE * Data;
};
struct _SYSTEM_POWER_STATUS {
    BYTE ACLineStatus;
    BYTE BatteryFlag;
    BYTE BatteryLifePercent;
    BYTE SystemStatusFlag;
    DWORD BatteryLifeTime;
    DWORD BatteryFullLifeTime;
};
/* System.Power -- 97 functions */
NTSTATUS CallNtPowerInformation(POWER_INFORMATION_LEVEL InformationLevel, void * InputBuffer, DWORD InputBufferLength, void * OutputBuffer, DWORD OutputBufferLength);
BYTE GetPwrCapabilities(SYSTEM_POWER_CAPABILITIES * lpspc);
POWER_PLATFORM_ROLE PowerDeterminePlatformRoleEx(POWER_PLATFORM_ROLE_VERSION Version);
WIN32_ERROR PowerRegisterSuspendResumeNotification(REGISTER_NOTIFICATION_FLAGS Flags, HANDLE Recipient, void * * RegistrationHandle);
WIN32_ERROR PowerUnregisterSuspendResumeNotification(HPOWERNOTIFY RegistrationHandle);
WIN32_ERROR PowerReadACValue(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * Type, BYTE * Buffer, DWORD * BufferSize);
WIN32_ERROR PowerReadDCValue(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * Type, BYTE * Buffer, DWORD * BufferSize);
WIN32_ERROR PowerWriteACValueIndex(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD AcValueIndex);
DWORD PowerWriteDCValueIndex(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD DcValueIndex);
WIN32_ERROR PowerGetActiveScheme(HKEY UserRootPowerKey, Guid * * ActivePolicyGuid);
WIN32_ERROR PowerSetActiveScheme(HKEY UserRootPowerKey, Guid * SchemeGuid);
WIN32_ERROR PowerSettingRegisterNotification(Guid * SettingGuid, REGISTER_NOTIFICATION_FLAGS Flags, HANDLE Recipient, void * * RegistrationHandle);
WIN32_ERROR PowerSettingUnregisterNotification(HPOWERNOTIFY RegistrationHandle);
HRESULT PowerRegisterForEffectivePowerModeNotifications(DWORD Version, EFFECTIVE_POWER_MODE_CALLBACK Callback, void * Context, void * * RegistrationHandle);
HRESULT PowerUnregisterFromEffectivePowerModeNotifications(void * RegistrationHandle);
BYTE GetPwrDiskSpindownRange(DWORD * puiMax, DWORD * puiMin);
BYTE EnumPwrSchemes(PWRSCHEMESENUMPROC lpfn, LPARAM lParam);
BYTE ReadGlobalPwrPolicy(GLOBAL_POWER_POLICY * pGlobalPowerPolicy);
BYTE ReadPwrScheme(DWORD uiID, POWER_POLICY * pPowerPolicy);
BYTE WritePwrScheme(DWORD * puiID, LPWSTR lpszSchemeName, LPWSTR lpszDescription, POWER_POLICY * lpScheme);
BYTE WriteGlobalPwrPolicy(GLOBAL_POWER_POLICY * pGlobalPowerPolicy);
BYTE DeletePwrScheme(DWORD uiID);
BYTE GetActivePwrScheme(DWORD * puiID);
BYTE SetActivePwrScheme(DWORD uiID, GLOBAL_POWER_POLICY * pGlobalPowerPolicy, POWER_POLICY * pPowerPolicy);
BYTE IsPwrSuspendAllowed();
BYTE IsPwrHibernateAllowed();
BYTE IsPwrShutdownAllowed();
BYTE IsAdminOverrideActive(ADMINISTRATOR_POWER_POLICY * papp);
BYTE SetSuspendState(BYTE bHibernate, BYTE bForce, BYTE bWakeupEventsDisabled);
BYTE GetCurrentPowerPolicies(GLOBAL_POWER_POLICY * pGlobalPowerPolicy, POWER_POLICY * pPowerPolicy);
BYTE CanUserWritePwrScheme();
BYTE ReadProcessorPwrScheme(DWORD uiID, MACHINE_PROCESSOR_POWER_POLICY * pMachineProcessorPowerPolicy);
BYTE WriteProcessorPwrScheme(DWORD uiID, MACHINE_PROCESSOR_POWER_POLICY * pMachineProcessorPowerPolicy);
BYTE ValidatePowerPolicies(GLOBAL_POWER_POLICY * pGlobalPowerPolicy, POWER_POLICY * pPowerPolicy);
BYTE PowerIsSettingRangeDefined(Guid * SubKeyGuid, Guid * SettingGuid);
WIN32_ERROR PowerSettingAccessCheckEx(POWER_DATA_ACCESSOR AccessFlags, Guid * PowerGuid, REG_SAM_FLAGS AccessType);
WIN32_ERROR PowerSettingAccessCheck(POWER_DATA_ACCESSOR AccessFlags, Guid * PowerGuid);
WIN32_ERROR PowerReadACValueIndex(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * AcValueIndex);
DWORD PowerReadDCValueIndex(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * DcValueIndex);
WIN32_ERROR PowerReadFriendlyName(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, BYTE * Buffer, DWORD * BufferSize);
WIN32_ERROR PowerReadDescription(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, BYTE * Buffer, DWORD * BufferSize);
WIN32_ERROR PowerReadPossibleValue(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * Type, DWORD PossibleSettingIndex, BYTE * Buffer, DWORD * BufferSize);
WIN32_ERROR PowerReadPossibleFriendlyName(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD PossibleSettingIndex, BYTE * Buffer, DWORD * BufferSize);
WIN32_ERROR PowerReadPossibleDescription(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD PossibleSettingIndex, BYTE * Buffer, DWORD * BufferSize);
WIN32_ERROR PowerReadValueMin(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * ValueMinimum);
WIN32_ERROR PowerReadValueMax(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * ValueMaximum);
WIN32_ERROR PowerReadValueIncrement(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * ValueIncrement);
WIN32_ERROR PowerReadValueUnitsSpecifier(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, BYTE * Buffer, DWORD * BufferSize);
DWORD PowerReadACDefaultIndex(HKEY RootPowerKey, Guid * SchemePersonalityGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * AcDefaultIndex);
DWORD PowerReadDCDefaultIndex(HKEY RootPowerKey, Guid * SchemePersonalityGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD * DcDefaultIndex);
WIN32_ERROR PowerReadIconResourceSpecifier(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, BYTE * Buffer, DWORD * BufferSize);
DWORD PowerReadSettingAttributes(Guid * SubGroupGuid, Guid * PowerSettingGuid);
WIN32_ERROR PowerWriteFriendlyName(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, BYTE * Buffer, DWORD BufferSize);
WIN32_ERROR PowerWriteDescription(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, BYTE * Buffer, DWORD BufferSize);
WIN32_ERROR PowerWritePossibleValue(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD Type, DWORD PossibleSettingIndex, BYTE * Buffer, DWORD BufferSize);
WIN32_ERROR PowerWritePossibleFriendlyName(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD PossibleSettingIndex, BYTE * Buffer, DWORD BufferSize);
WIN32_ERROR PowerWritePossibleDescription(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD PossibleSettingIndex, BYTE * Buffer, DWORD BufferSize);
WIN32_ERROR PowerWriteValueMin(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD ValueMinimum);
WIN32_ERROR PowerWriteValueMax(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD ValueMaximum);
WIN32_ERROR PowerWriteValueIncrement(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD ValueIncrement);
WIN32_ERROR PowerWriteValueUnitsSpecifier(HKEY RootPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, BYTE * Buffer, DWORD BufferSize);
DWORD PowerWriteACDefaultIndex(HKEY RootSystemPowerKey, Guid * SchemePersonalityGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD DefaultAcIndex);
DWORD PowerWriteDCDefaultIndex(HKEY RootSystemPowerKey, Guid * SchemePersonalityGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD DefaultDcIndex);
WIN32_ERROR PowerWriteIconResourceSpecifier(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, BYTE * Buffer, DWORD BufferSize);
WIN32_ERROR PowerWriteSettingAttributes(Guid * SubGroupGuid, Guid * PowerSettingGuid, DWORD Attributes);
WIN32_ERROR PowerDuplicateScheme(HKEY RootPowerKey, Guid * SourceSchemeGuid, Guid * * DestinationSchemeGuid);
WIN32_ERROR PowerImportPowerScheme(HKEY RootPowerKey, LPWSTR ImportFileNamePath, Guid * * DestinationSchemeGuid);
WIN32_ERROR PowerDeleteScheme(HKEY RootPowerKey, Guid * SchemeGuid);
WIN32_ERROR PowerRemovePowerSetting(Guid * PowerSettingSubKeyGuid, Guid * PowerSettingGuid);
WIN32_ERROR PowerCreateSetting(HKEY RootSystemPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid);
WIN32_ERROR PowerCreatePossibleSetting(HKEY RootSystemPowerKey, Guid * SubGroupOfPowerSettingsGuid, Guid * PowerSettingGuid, DWORD PossibleSettingIndex);
WIN32_ERROR PowerEnumerate(HKEY RootPowerKey, Guid * SchemeGuid, Guid * SubGroupOfPowerSettingsGuid, POWER_DATA_ACCESSOR AccessFlags, DWORD Index, BYTE * Buffer, DWORD * BufferSize);
DWORD PowerOpenUserPowerKey(HKEY * phUserPowerKey, DWORD Access, BOOL OpenExisting);
DWORD PowerOpenSystemPowerKey(HKEY * phSystemPowerKey, DWORD Access, BOOL OpenExisting);
WIN32_ERROR PowerCanRestoreIndividualDefaultPowerScheme(Guid * SchemeGuid);
WIN32_ERROR PowerRestoreIndividualDefaultPowerScheme(Guid * SchemeGuid);
WIN32_ERROR PowerRestoreDefaultPowerSchemes();
DWORD PowerReplaceDefaultPowerSchemes();
POWER_PLATFORM_ROLE PowerDeterminePlatformRole();
BYTE DevicePowerEnumDevices(DWORD QueryIndex, DWORD QueryInterpretationFlags, DWORD QueryFlags, BYTE * pReturnBuffer, DWORD * pBufferSize);
DWORD DevicePowerSetDeviceState(LPWSTR DeviceDescription, DWORD SetFlags, void * SetData);
BYTE DevicePowerOpen(DWORD DebugMask);
BYTE DevicePowerClose();
WIN32_ERROR PowerReportThermalEvent(THERMAL_EVENT * Event);
HPOWERNOTIFY RegisterPowerSettingNotification(HANDLE hRecipient, Guid * PowerSettingGuid, REGISTER_NOTIFICATION_FLAGS Flags);
BOOL UnregisterPowerSettingNotification(HPOWERNOTIFY Handle);
HPOWERNOTIFY RegisterSuspendResumeNotification(HANDLE hRecipient, REGISTER_NOTIFICATION_FLAGS Flags);
BOOL UnregisterSuspendResumeNotification(HPOWERNOTIFY Handle);
BOOL RequestWakeupLatency(LATENCY_TIME latency);
BOOL IsSystemResumeAutomatic();
EXECUTION_STATE SetThreadExecutionState(EXECUTION_STATE esFlags);
HANDLE PowerCreateRequest(REASON_CONTEXT * Context);
BOOL PowerSetRequest(HANDLE PowerRequest, POWER_REQUEST_TYPE RequestType);
BOOL PowerClearRequest(HANDLE PowerRequest, POWER_REQUEST_TYPE RequestType);
BOOL GetDevicePowerState(HANDLE hDevice, BOOL * pfOn);
BOOL SetSystemPowerState(BOOL fSuspend, BOOL fForce);
BOOL GetSystemPowerStatus(SYSTEM_POWER_STATUS * lpSystemPowerStatus);
]]

return {
    ACPI_TIME_ADJUST_DAYLIGHT = 0x00000001,
    ACPI_TIME_IN_DAYLIGHT = 0x00000002,
    ACPI_TIME_ZONE_UNKNOWN = 0x000007FF,
    ACTIVE_COOLING = 0x00000000,
    BATTERY_CAPACITY_RELATIVE = 0x40000000,
    BATTERY_CHARGING = 0x00000004,
    BATTERY_CLASS_MAJOR_VERSION = 0x00000001,
    BATTERY_CLASS_MINOR_VERSION = 0x00000000,
    BATTERY_CLASS_MINOR_VERSION_1 = 0x00000001,
    BATTERY_CRITICAL = 0x00000008,
    BATTERY_DISCHARGING = 0x00000002,
    BATTERY_IS_SHORT_TERM = 0x20000000,
    BATTERY_MINIPORT_UPDATE_DATA_VER_1 = 0x00000001,
    BATTERY_MINIPORT_UPDATE_DATA_VER_2 = 0x00000002,
    BATTERY_POWER_ON_LINE = 0x00000001,
    BATTERY_SEALED = 0x10000000,
    BATTERY_SET_CHARGE_SUPPORTED = 0x00000001,
    BATTERY_SET_CHARGER_ID_SUPPORTED = 0x00000008,
    BATTERY_SET_CHARGINGSOURCE_SUPPORTED = 0x00000004,
    BATTERY_SET_DISCHARGE_SUPPORTED = 0x00000002,
    BATTERY_SYSTEM_BATTERY = 0x80000000,
    BATTERY_TAG_INVALID = 0x00000000,
    BATTERY_UNKNOWN_CAPACITY = 0xFFFFFFFF,
    BATTERY_UNKNOWN_CURRENT = 0xFFFFFFFF,
    BATTERY_UNKNOWN_RATE = 0x80000000,
    BATTERY_UNKNOWN_TIME = 0xFFFFFFFF,
    BATTERY_UNKNOWN_VOLTAGE = 0xFFFFFFFF,
    BATTERY_USB_CHARGER_STATUS_FN_DEFAULT_USB = 0x00000001,
    BATTERY_USB_CHARGER_STATUS_UCM_PD = 0x00000002,
    DEVICEPOWER_AND_OPERATION = 0x40000000,
    DEVICEPOWER_CLEAR_WAKEENABLED = 0x00000002,
    DEVICEPOWER_FILTER_DEVICES_PRESENT = 0x20000000,
    DEVICEPOWER_FILTER_HARDWARE = 0x10000000,
    DEVICEPOWER_FILTER_ON_NAME = 0x02000000,
    DEVICEPOWER_FILTER_WAKEENABLED = 0x08000000,
    DEVICEPOWER_FILTER_WAKEPROGRAMMABLE = 0x04000000,
    DEVICEPOWER_HARDWAREID = 0x80000000,
    DEVICEPOWER_SET_WAKEENABLED = 0x00000001,
    EFFECTIVE_POWER_MODE_V1 = 0x00000001,
    EFFECTIVE_POWER_MODE_V2 = 0x00000002,
    EMI_NAME_MAX = 0x00000010,
    EMI_VERSION_V1 = 0x00000001,
    EMI_VERSION_V2 = 0x00000002,
    EnableMultiBatteryDisplay = 0x00000002,
    EnablePasswordLogon = 0x00000004,
    EnableSysTrayBatteryMeter = 0x00000001,
    EnableVideoDimDisplay = 0x00000010,
    EnableWakeOnRing = 0x00000008,
    IOCTL_ACPI_GET_REAL_TIME = 0x00294210,
    IOCTL_ACPI_SET_REAL_TIME = 0x00298214,
    IOCTL_BATTERY_CHARGING_SOURCE_CHANGE = 0x00294050,
    IOCTL_BATTERY_QUERY_INFORMATION = 0x00294044,
    IOCTL_BATTERY_QUERY_STATUS = 0x0029404C,
    IOCTL_BATTERY_QUERY_TAG = 0x00294040,
    IOCTL_BATTERY_SET_INFORMATION = 0x00298048,
    IOCTL_EMI_GET_MEASUREMENT = 0x0022400C,
    IOCTL_EMI_GET_METADATA = 0x00224008,
    IOCTL_EMI_GET_METADATA_SIZE = 0x00224004,
    IOCTL_EMI_GET_VERSION = 0x00224000,
    IOCTL_GET_ACPI_TIME_AND_ALARM_CAPABILITIES = 0x0029421C,
    IOCTL_GET_PROCESSOR_OBJ_INFO = 0x00294180,
    IOCTL_GET_SYS_BUTTON_CAPS = 0x00294140,
    IOCTL_GET_SYS_BUTTON_EVENT = 0x00294144,
    IOCTL_GET_WAKE_ALARM_POLICY = 0x0029C20C,
    IOCTL_GET_WAKE_ALARM_SYSTEM_POWERSTATE = 0x00294218,
    IOCTL_GET_WAKE_ALARM_VALUE = 0x0029C208,
    IOCTL_NOTIFY_SWITCH_EVENT = 0x00294100,
    IOCTL_QUERY_LID = 0x002940C0,
    IOCTL_RUN_ACTIVE_COOLING_METHOD = 0x00298088,
    IOCTL_SET_SYS_MESSAGE_INDICATOR = 0x002981C0,
    IOCTL_SET_WAKE_ALARM_POLICY = 0x00298204,
    IOCTL_SET_WAKE_ALARM_VALUE = 0x00298200,
    IOCTL_THERMAL_QUERY_INFORMATION = 0x00294080,
    IOCTL_THERMAL_READ_POLICY = 0x00294094,
    IOCTL_THERMAL_READ_TEMPERATURE = 0x00294090,
    IOCTL_THERMAL_SET_COOLING_POLICY = 0x00298084,
    IOCTL_THERMAL_SET_PASSIVE_LIMIT = 0x0029808C,
    MAX_ACTIVE_COOLING_LEVELS = 0x0000000A,
    MAX_BATTERY_STRING_SIZE = 0x00000080,
    PASSIVE_COOLING = 0x00000001,
    POWER_ATTRIBUTE_HIDE = 0x00000001,
    POWER_ATTRIBUTE_SHOW_AOAC = 0x00000002,
    PPM_FIRMWARE_ACPI1C2 = 0x00000001,
    PPM_FIRMWARE_ACPI1C3 = 0x00000002,
    PPM_FIRMWARE_ACPI1TSTATES = 0x00000004,
    PPM_FIRMWARE_CPC = 0x00040000,
    PPM_FIRMWARE_CSD = 0x00000010,
    PPM_FIRMWARE_CST = 0x00000008,
    PPM_FIRMWARE_LPI = 0x00080000,
    PPM_FIRMWARE_OSC = 0x00010000,
    PPM_FIRMWARE_PCCH = 0x00004000,
    PPM_FIRMWARE_PCCP = 0x00008000,
    PPM_FIRMWARE_PCT = 0x00000020,
    PPM_FIRMWARE_PDC = 0x00020000,
    PPM_FIRMWARE_PPC = 0x00000100,
    PPM_FIRMWARE_PSD = 0x00000200,
    PPM_FIRMWARE_PSS = 0x00000040,
    PPM_FIRMWARE_PTC = 0x00000400,
    PPM_FIRMWARE_TPC = 0x00001000,
    PPM_FIRMWARE_TSD = 0x00002000,
    PPM_FIRMWARE_TSS = 0x00000800,
    PPM_FIRMWARE_XPSS = 0x00000080,
    PPM_IDLE_IMPLEMENTATION_CSTATES = 0x00000001,
    PPM_IDLE_IMPLEMENTATION_LPISTATES = 0x00000004,
    PPM_IDLE_IMPLEMENTATION_MICROPEP = 0x00000003,
    PPM_IDLE_IMPLEMENTATION_NONE = 0x00000000,
    PPM_IDLE_IMPLEMENTATION_PEP = 0x00000002,
    PPM_PERFORMANCE_IMPLEMENTATION_CPPC = 0x00000003,
    PPM_PERFORMANCE_IMPLEMENTATION_NONE = 0x00000000,
    PPM_PERFORMANCE_IMPLEMENTATION_PCCV1 = 0x00000002,
    PPM_PERFORMANCE_IMPLEMENTATION_PEP = 0x00000004,
    PPM_PERFORMANCE_IMPLEMENTATION_PSTATES = 0x00000001,
    SYS_BUTTON_LID = 0x00000004,
    SYS_BUTTON_LID_CHANGED = 0x00080000,
    SYS_BUTTON_LID_CLOSED = 0x00020000,
    SYS_BUTTON_LID_INITIAL = 0x00040000,
    SYS_BUTTON_LID_OPEN = 0x00010000,
    SYS_BUTTON_LID_STATE_MASK = 0x00030000,
    SYS_BUTTON_POWER = 0x00000001,
    SYS_BUTTON_SLEEP = 0x00000002,
    SYS_BUTTON_WAKE = 0x80000000,
    THERMAL_COOLING_INTERFACE_VERSION = 0x00000001,
    THERMAL_DEVICE_INTERFACE_VERSION = 0x00000001,
    THERMAL_EVENT_VERSION = 0x00000001,
    THERMAL_POLICY_VERSION_1 = 0x00000001,
    THERMAL_POLICY_VERSION_2 = 0x00000002,
    TZ_ACTIVATION_REASON_CURRENT = 0x00000002,
    TZ_ACTIVATION_REASON_THERMAL = 0x00000001,
    UNKNOWN_CAPACITY = 0xFFFFFFFF,
    UNKNOWN_CURRENT = 0xFFFFFFFF,
    UNKNOWN_RATE = 0x80000000,
    UNKNOWN_VOLTAGE = 0xFFFFFFFF,
    -- enum ACPI_TIME_RESOLUTION
    ACPI_TIME_RESOLUTION_AcpiTimeResolutionMilliseconds = 0,
    ACPI_TIME_RESOLUTION_AcpiTimeResolutionSeconds = 1,
    ACPI_TIME_RESOLUTION_AcpiTimeResolutionMax = 2,
    -- enum BATTERY_CHARGING_SOURCE_TYPE
    BATTERY_CHARGING_SOURCE_TYPE_BatteryChargingSourceType_AC = 1,
    BATTERY_CHARGING_SOURCE_TYPE_BatteryChargingSourceType_USB = 2,
    BATTERY_CHARGING_SOURCE_TYPE_BatteryChargingSourceType_Wireless = 3,
    BATTERY_CHARGING_SOURCE_TYPE_BatteryChargingSourceType_Max = 4,
    -- enum BATTERY_QUERY_INFORMATION_LEVEL
    BATTERY_QUERY_INFORMATION_LEVEL_BatteryInformation = 0,
    BATTERY_QUERY_INFORMATION_LEVEL_BatteryGranularityInformation = 1,
    BATTERY_QUERY_INFORMATION_LEVEL_BatteryTemperature = 2,
    BATTERY_QUERY_INFORMATION_LEVEL_BatteryEstimatedTime = 3,
    BATTERY_QUERY_INFORMATION_LEVEL_BatteryDeviceName = 4,
    BATTERY_QUERY_INFORMATION_LEVEL_BatteryManufactureDate = 5,
    BATTERY_QUERY_INFORMATION_LEVEL_BatteryManufactureName = 6,
    BATTERY_QUERY_INFORMATION_LEVEL_BatteryUniqueID = 7,
    BATTERY_QUERY_INFORMATION_LEVEL_BatterySerialNumber = 8,
    -- enum BATTERY_SET_INFORMATION_LEVEL
    BATTERY_SET_INFORMATION_LEVEL_BatteryCriticalBias = 0,
    BATTERY_SET_INFORMATION_LEVEL_BatteryCharge = 1,
    BATTERY_SET_INFORMATION_LEVEL_BatteryDischarge = 2,
    BATTERY_SET_INFORMATION_LEVEL_BatteryChargingSource = 3,
    BATTERY_SET_INFORMATION_LEVEL_BatteryChargerId = 4,
    BATTERY_SET_INFORMATION_LEVEL_BatteryChargerStatus = 5,
    -- enum DEVICE_POWER_CAPABILITIES
    DEVICE_POWER_CAPABILITIES_PDCAP_D0_SUPPORTED = 0x00000001,
    DEVICE_POWER_CAPABILITIES_PDCAP_D1_SUPPORTED = 0x00000002,
    DEVICE_POWER_CAPABILITIES_PDCAP_D2_SUPPORTED = 0x00000004,
    DEVICE_POWER_CAPABILITIES_PDCAP_D3_SUPPORTED = 0x00000008,
    DEVICE_POWER_CAPABILITIES_PDCAP_WAKE_FROM_D0_SUPPORTED = 0x00000010,
    DEVICE_POWER_CAPABILITIES_PDCAP_WAKE_FROM_D1_SUPPORTED = 0x00000020,
    DEVICE_POWER_CAPABILITIES_PDCAP_WAKE_FROM_D2_SUPPORTED = 0x00000040,
    DEVICE_POWER_CAPABILITIES_PDCAP_WAKE_FROM_D3_SUPPORTED = 0x00000080,
    DEVICE_POWER_CAPABILITIES_PDCAP_WARM_EJECT_SUPPORTED = 0x00000100,
    DEVICE_POWER_CAPABILITIES_PDCAP_S0_SUPPORTED = 0x00010000,
    DEVICE_POWER_CAPABILITIES_PDCAP_S1_SUPPORTED = 0x00020000,
    DEVICE_POWER_CAPABILITIES_PDCAP_S2_SUPPORTED = 0x00040000,
    DEVICE_POWER_CAPABILITIES_PDCAP_S3_SUPPORTED = 0x00080000,
    DEVICE_POWER_CAPABILITIES_PDCAP_WAKE_FROM_S0_SUPPORTED = 0x00100000,
    DEVICE_POWER_CAPABILITIES_PDCAP_WAKE_FROM_S1_SUPPORTED = 0x00200000,
    DEVICE_POWER_CAPABILITIES_PDCAP_WAKE_FROM_S2_SUPPORTED = 0x00400000,
    DEVICE_POWER_CAPABILITIES_PDCAP_WAKE_FROM_S3_SUPPORTED = 0x00800000,
    DEVICE_POWER_CAPABILITIES_PDCAP_S4_SUPPORTED = 0x01000000,
    DEVICE_POWER_CAPABILITIES_PDCAP_S5_SUPPORTED = 0x02000000,
    -- enum DEVICE_POWER_STATE
    DEVICE_POWER_STATE_PowerDeviceUnspecified = 0,
    DEVICE_POWER_STATE_PowerDeviceD0 = 1,
    DEVICE_POWER_STATE_PowerDeviceD1 = 2,
    DEVICE_POWER_STATE_PowerDeviceD2 = 3,
    DEVICE_POWER_STATE_PowerDeviceD3 = 4,
    DEVICE_POWER_STATE_PowerDeviceMaximum = 5,
    -- enum EFFECTIVE_POWER_MODE
    EFFECTIVE_POWER_MODE_EffectivePowerModeBatterySaver = 0,
    EFFECTIVE_POWER_MODE_EffectivePowerModeBetterBattery = 1,
    EFFECTIVE_POWER_MODE_EffectivePowerModeBalanced = 2,
    EFFECTIVE_POWER_MODE_EffectivePowerModeHighPerformance = 3,
    EFFECTIVE_POWER_MODE_EffectivePowerModeMaxPerformance = 4,
    EFFECTIVE_POWER_MODE_EffectivePowerModeGameMode = 5,
    EFFECTIVE_POWER_MODE_EffectivePowerModeMixedReality = 6,
    -- enum EMI_MEASUREMENT_UNIT
    EMI_MEASUREMENT_UNIT_EmiMeasurementUnitPicowattHours = 0,
    -- enum EXECUTION_STATE
    EXECUTION_STATE_ES_AWAYMODE_REQUIRED = 0x00000040,
    EXECUTION_STATE_ES_CONTINUOUS = 0x80000000,
    EXECUTION_STATE_ES_DISPLAY_REQUIRED = 0x00000002,
    EXECUTION_STATE_ES_SYSTEM_REQUIRED = 0x00000001,
    EXECUTION_STATE_ES_USER_PRESENT = 0x00000004,
    -- enum LATENCY_TIME
    LATENCY_TIME_LT_DONT_CARE = 0,
    LATENCY_TIME_LT_LOWEST_LATENCY = 1,
    -- enum POWER_ACTION
    POWER_ACTION_PowerActionNone = 0,
    POWER_ACTION_PowerActionReserved = 1,
    POWER_ACTION_PowerActionSleep = 2,
    POWER_ACTION_PowerActionHibernate = 3,
    POWER_ACTION_PowerActionShutdown = 4,
    POWER_ACTION_PowerActionShutdownReset = 5,
    POWER_ACTION_PowerActionShutdownOff = 6,
    POWER_ACTION_PowerActionWarmEject = 7,
    POWER_ACTION_PowerActionDisplayOff = 8,
    -- enum POWER_ACTION_POLICY_EVENT_CODE
    POWER_ACTION_POLICY_EVENT_CODE_POWER_FORCE_TRIGGER_RESET = 0x80000000,
    POWER_ACTION_POLICY_EVENT_CODE_POWER_LEVEL_USER_NOTIFY_EXEC = 0x00000004,
    POWER_ACTION_POLICY_EVENT_CODE_POWER_LEVEL_USER_NOTIFY_SOUND = 0x00000002,
    POWER_ACTION_POLICY_EVENT_CODE_POWER_LEVEL_USER_NOTIFY_TEXT = 0x00000001,
    POWER_ACTION_POLICY_EVENT_CODE_POWER_USER_NOTIFY_BUTTON = 0x00000008,
    POWER_ACTION_POLICY_EVENT_CODE_POWER_USER_NOTIFY_SHUTDOWN = 0x00000010,
    -- enum POWER_COOLING_MODE
    POWER_COOLING_MODE_PO_TZ_ACTIVE = 0,
    POWER_COOLING_MODE_PO_TZ_PASSIVE = 0,
    POWER_COOLING_MODE_PO_TZ_INVALID_MODE = 0,
    -- enum POWER_DATA_ACCESSOR
    POWER_DATA_ACCESSOR_ACCESS_AC_POWER_SETTING_INDEX = 0,
    POWER_DATA_ACCESSOR_ACCESS_DC_POWER_SETTING_INDEX = 1,
    POWER_DATA_ACCESSOR_ACCESS_FRIENDLY_NAME = 2,
    POWER_DATA_ACCESSOR_ACCESS_DESCRIPTION = 3,
    POWER_DATA_ACCESSOR_ACCESS_POSSIBLE_POWER_SETTING = 4,
    POWER_DATA_ACCESSOR_ACCESS_POSSIBLE_POWER_SETTING_FRIENDLY_NAME = 5,
    POWER_DATA_ACCESSOR_ACCESS_POSSIBLE_POWER_SETTING_DESCRIPTION = 6,
    POWER_DATA_ACCESSOR_ACCESS_DEFAULT_AC_POWER_SETTING = 7,
    POWER_DATA_ACCESSOR_ACCESS_DEFAULT_DC_POWER_SETTING = 8,
    POWER_DATA_ACCESSOR_ACCESS_POSSIBLE_VALUE_MIN = 9,
    POWER_DATA_ACCESSOR_ACCESS_POSSIBLE_VALUE_MAX = 10,
    POWER_DATA_ACCESSOR_ACCESS_POSSIBLE_VALUE_INCREMENT = 11,
    POWER_DATA_ACCESSOR_ACCESS_POSSIBLE_VALUE_UNITS = 12,
    POWER_DATA_ACCESSOR_ACCESS_ICON_RESOURCE = 13,
    POWER_DATA_ACCESSOR_ACCESS_DEFAULT_SECURITY_DESCRIPTOR = 14,
    POWER_DATA_ACCESSOR_ACCESS_ATTRIBUTES = 15,
    POWER_DATA_ACCESSOR_ACCESS_SCHEME = 16,
    POWER_DATA_ACCESSOR_ACCESS_SUBGROUP = 17,
    POWER_DATA_ACCESSOR_ACCESS_INDIVIDUAL_SETTING = 18,
    POWER_DATA_ACCESSOR_ACCESS_ACTIVE_SCHEME = 19,
    POWER_DATA_ACCESSOR_ACCESS_CREATE_SCHEME = 20,
    POWER_DATA_ACCESSOR_ACCESS_AC_POWER_SETTING_MAX = 21,
    POWER_DATA_ACCESSOR_ACCESS_DC_POWER_SETTING_MAX = 22,
    POWER_DATA_ACCESSOR_ACCESS_AC_POWER_SETTING_MIN = 23,
    POWER_DATA_ACCESSOR_ACCESS_DC_POWER_SETTING_MIN = 24,
    POWER_DATA_ACCESSOR_ACCESS_PROFILE = 25,
    POWER_DATA_ACCESSOR_ACCESS_OVERLAY_SCHEME = 26,
    POWER_DATA_ACCESSOR_ACCESS_ACTIVE_OVERLAY_SCHEME = 27,
    -- enum POWER_INFORMATION_LEVEL
    POWER_INFORMATION_LEVEL_SystemPowerPolicyAc = 0,
    POWER_INFORMATION_LEVEL_SystemPowerPolicyDc = 1,
    POWER_INFORMATION_LEVEL_VerifySystemPolicyAc = 2,
    POWER_INFORMATION_LEVEL_VerifySystemPolicyDc = 3,
    POWER_INFORMATION_LEVEL_SystemPowerCapabilities = 4,
    POWER_INFORMATION_LEVEL_SystemBatteryState = 5,
    POWER_INFORMATION_LEVEL_SystemPowerStateHandler = 6,
    POWER_INFORMATION_LEVEL_ProcessorStateHandler = 7,
    POWER_INFORMATION_LEVEL_SystemPowerPolicyCurrent = 8,
    POWER_INFORMATION_LEVEL_AdministratorPowerPolicy = 9,
    POWER_INFORMATION_LEVEL_SystemReserveHiberFile = 10,
    POWER_INFORMATION_LEVEL_ProcessorInformation = 11,
    POWER_INFORMATION_LEVEL_SystemPowerInformation = 12,
    POWER_INFORMATION_LEVEL_ProcessorStateHandler2 = 13,
    POWER_INFORMATION_LEVEL_LastWakeTime = 14,
    POWER_INFORMATION_LEVEL_LastSleepTime = 15,
    POWER_INFORMATION_LEVEL_SystemExecutionState = 16,
    POWER_INFORMATION_LEVEL_SystemPowerStateNotifyHandler = 17,
    POWER_INFORMATION_LEVEL_ProcessorPowerPolicyAc = 18,
    POWER_INFORMATION_LEVEL_ProcessorPowerPolicyDc = 19,
    POWER_INFORMATION_LEVEL_VerifyProcessorPowerPolicyAc = 20,
    POWER_INFORMATION_LEVEL_VerifyProcessorPowerPolicyDc = 21,
    POWER_INFORMATION_LEVEL_ProcessorPowerPolicyCurrent = 22,
    POWER_INFORMATION_LEVEL_SystemPowerStateLogging = 23,
    POWER_INFORMATION_LEVEL_SystemPowerLoggingEntry = 24,
    POWER_INFORMATION_LEVEL_SetPowerSettingValue = 25,
    POWER_INFORMATION_LEVEL_NotifyUserPowerSetting = 26,
    POWER_INFORMATION_LEVEL_PowerInformationLevelUnused0 = 27,
    POWER_INFORMATION_LEVEL_SystemMonitorHiberBootPowerOff = 28,
    POWER_INFORMATION_LEVEL_SystemVideoState = 29,
    POWER_INFORMATION_LEVEL_TraceApplicationPowerMessage = 30,
    POWER_INFORMATION_LEVEL_TraceApplicationPowerMessageEnd = 31,
    POWER_INFORMATION_LEVEL_ProcessorPerfStates = 32,
    POWER_INFORMATION_LEVEL_ProcessorIdleStates = 33,
    POWER_INFORMATION_LEVEL_ProcessorCap = 34,
    POWER_INFORMATION_LEVEL_SystemWakeSource = 35,
    POWER_INFORMATION_LEVEL_SystemHiberFileInformation = 36,
    POWER_INFORMATION_LEVEL_TraceServicePowerMessage = 37,
    POWER_INFORMATION_LEVEL_ProcessorLoad = 38,
    POWER_INFORMATION_LEVEL_PowerShutdownNotification = 39,
    POWER_INFORMATION_LEVEL_MonitorCapabilities = 40,
    POWER_INFORMATION_LEVEL_SessionPowerInit = 41,
    POWER_INFORMATION_LEVEL_SessionDisplayState = 42,
    POWER_INFORMATION_LEVEL_PowerRequestCreate = 43,
    POWER_INFORMATION_LEVEL_PowerRequestAction = 44,
    POWER_INFORMATION_LEVEL_GetPowerRequestList = 45,
    POWER_INFORMATION_LEVEL_ProcessorInformationEx = 46,
    POWER_INFORMATION_LEVEL_NotifyUserModeLegacyPowerEvent = 47,
    POWER_INFORMATION_LEVEL_GroupPark = 48,
    POWER_INFORMATION_LEVEL_ProcessorIdleDomains = 49,
    POWER_INFORMATION_LEVEL_WakeTimerList = 50,
    POWER_INFORMATION_LEVEL_SystemHiberFileSize = 51,
    POWER_INFORMATION_LEVEL_ProcessorIdleStatesHv = 52,
    POWER_INFORMATION_LEVEL_ProcessorPerfStatesHv = 53,
    POWER_INFORMATION_LEVEL_ProcessorPerfCapHv = 54,
    POWER_INFORMATION_LEVEL_ProcessorSetIdle = 55,
    POWER_INFORMATION_LEVEL_LogicalProcessorIdling = 56,
    POWER_INFORMATION_LEVEL_UserPresence = 57,
    POWER_INFORMATION_LEVEL_PowerSettingNotificationName = 58,
    POWER_INFORMATION_LEVEL_GetPowerSettingValue = 59,
    POWER_INFORMATION_LEVEL_IdleResiliency = 60,
    POWER_INFORMATION_LEVEL_SessionRITState = 61,
    POWER_INFORMATION_LEVEL_SessionConnectNotification = 62,
    POWER_INFORMATION_LEVEL_SessionPowerCleanup = 63,
    POWER_INFORMATION_LEVEL_SessionLockState = 64,
    POWER_INFORMATION_LEVEL_SystemHiberbootState = 65,
    POWER_INFORMATION_LEVEL_PlatformInformation = 66,
    POWER_INFORMATION_LEVEL_PdcInvocation = 67,
    POWER_INFORMATION_LEVEL_MonitorInvocation = 68,
    POWER_INFORMATION_LEVEL_FirmwareTableInformationRegistered = 69,
    POWER_INFORMATION_LEVEL_SetShutdownSelectedTime = 70,
    POWER_INFORMATION_LEVEL_SuspendResumeInvocation = 71,
    POWER_INFORMATION_LEVEL_PlmPowerRequestCreate = 72,
    POWER_INFORMATION_LEVEL_ScreenOff = 73,
    POWER_INFORMATION_LEVEL_CsDeviceNotification = 74,
    POWER_INFORMATION_LEVEL_PlatformRole = 75,
    POWER_INFORMATION_LEVEL_LastResumePerformance = 76,
    POWER_INFORMATION_LEVEL_DisplayBurst = 77,
    POWER_INFORMATION_LEVEL_ExitLatencySamplingPercentage = 78,
    POWER_INFORMATION_LEVEL_RegisterSpmPowerSettings = 79,
    POWER_INFORMATION_LEVEL_PlatformIdleStates = 80,
    POWER_INFORMATION_LEVEL_ProcessorIdleVeto = 81,
    POWER_INFORMATION_LEVEL_PlatformIdleVeto = 82,
    POWER_INFORMATION_LEVEL_SystemBatteryStatePrecise = 83,
    POWER_INFORMATION_LEVEL_ThermalEvent = 84,
    POWER_INFORMATION_LEVEL_PowerRequestActionInternal = 85,
    POWER_INFORMATION_LEVEL_BatteryDeviceState = 86,
    POWER_INFORMATION_LEVEL_PowerInformationInternal = 87,
    POWER_INFORMATION_LEVEL_ThermalStandby = 88,
    POWER_INFORMATION_LEVEL_SystemHiberFileType = 89,
    POWER_INFORMATION_LEVEL_PhysicalPowerButtonPress = 90,
    POWER_INFORMATION_LEVEL_QueryPotentialDripsConstraint = 91,
    POWER_INFORMATION_LEVEL_EnergyTrackerCreate = 92,
    POWER_INFORMATION_LEVEL_EnergyTrackerQuery = 93,
    POWER_INFORMATION_LEVEL_UpdateBlackBoxRecorder = 94,
    POWER_INFORMATION_LEVEL_SessionAllowExternalDmaDevices = 95,
    POWER_INFORMATION_LEVEL_SendSuspendResumeNotification = 96,
    POWER_INFORMATION_LEVEL_BlackBoxRecorderDirectAccessBuffer = 97,
    POWER_INFORMATION_LEVEL_PowerInformationLevelMaximum = 98,
    -- enum POWER_MONITOR_REQUEST_REASON
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUnknown = 0,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPowerButton = 1,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonRemoteConnection = 2,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonScMonitorpower = 3,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInput = 4,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonAcDcDisplayBurst = 5,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserDisplayBurst = 6,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPoSetSystemState = 7,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonSetThreadExecutionState = 8,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonFullWake = 9,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonSessionUnlock = 10,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonScreenOffRequest = 11,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonIdleTimeout = 12,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPolicyChange = 13,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonSleepButton = 14,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonLid = 15,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonBatteryCountChange = 16,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonGracePeriod = 17,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPnP = 18,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonDP = 19,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonSxTransition = 20,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonSystemIdle = 21,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonNearProximity = 22,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonThermalStandby = 23,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonResumePdc = 24,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonResumeS4 = 25,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonTerminal = 26,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPdcSignal = 27,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonAcDcDisplayBurstSuppressed = 28,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonSystemStateEntered = 29,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonWinrt = 30,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputKeyboard = 31,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputMouse = 32,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputTouchpad = 33,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputPen = 34,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputAccelerometer = 35,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputHid = 36,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputPoUserPresent = 37,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputSessionSwitch = 38,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputInitialization = 39,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPdcSignalWindowsMobilePwrNotif = 40,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPdcSignalWindowsMobileShell = 41,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPdcSignalHeyCortana = 42,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPdcSignalHolographicShell = 43,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPdcSignalFingerprint = 44,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonDirectedDrips = 45,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonDim = 46,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonBuiltinPanel = 47,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonDisplayRequiredUnDim = 48,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonBatteryCountChangeSuppressed = 49,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonResumeModernStandby = 50,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonTerminalInit = 51,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonPdcSignalSensorsHumanPresence = 52,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonBatteryPreCritical = 53,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonUserInputTouch = 54,
    POWER_MONITOR_REQUEST_REASON_MonitorRequestReasonMax = 55,
    -- enum POWER_MONITOR_REQUEST_TYPE
    POWER_MONITOR_REQUEST_TYPE_MonitorRequestTypeOff = 0,
    POWER_MONITOR_REQUEST_TYPE_MonitorRequestTypeOnAndPresent = 1,
    POWER_MONITOR_REQUEST_TYPE_MonitorRequestTypeToggleOn = 2,
    -- enum POWER_PLATFORM_ROLE
    POWER_PLATFORM_ROLE_PlatformRoleUnspecified = 0,
    POWER_PLATFORM_ROLE_PlatformRoleDesktop = 1,
    POWER_PLATFORM_ROLE_PlatformRoleMobile = 2,
    POWER_PLATFORM_ROLE_PlatformRoleWorkstation = 3,
    POWER_PLATFORM_ROLE_PlatformRoleEnterpriseServer = 4,
    POWER_PLATFORM_ROLE_PlatformRoleSOHOServer = 5,
    POWER_PLATFORM_ROLE_PlatformRoleAppliancePC = 6,
    POWER_PLATFORM_ROLE_PlatformRolePerformanceServer = 7,
    POWER_PLATFORM_ROLE_PlatformRoleSlate = 8,
    POWER_PLATFORM_ROLE_PlatformRoleMaximum = 9,
    -- enum POWER_PLATFORM_ROLE_VERSION
    POWER_PLATFORM_ROLE_VERSION_POWER_PLATFORM_ROLE_V1 = 0x00000001,
    POWER_PLATFORM_ROLE_VERSION_POWER_PLATFORM_ROLE_V2 = 0x00000002,
    -- enum POWER_REQUEST_TYPE
    POWER_REQUEST_TYPE_PowerRequestDisplayRequired = 0,
    POWER_REQUEST_TYPE_PowerRequestSystemRequired = 1,
    POWER_REQUEST_TYPE_PowerRequestAwayModeRequired = 2,
    POWER_REQUEST_TYPE_PowerRequestExecutionRequired = 3,
    -- enum POWER_SETTING_ALTITUDE
    POWER_SETTING_ALTITUDE_ALTITUDE_GROUP_POLICY = 0,
    POWER_SETTING_ALTITUDE_ALTITUDE_USER = 1,
    POWER_SETTING_ALTITUDE_ALTITUDE_RUNTIME_OVERRIDE = 2,
    POWER_SETTING_ALTITUDE_ALTITUDE_PROVISIONING = 3,
    POWER_SETTING_ALTITUDE_ALTITUDE_OEM_CUSTOMIZATION = 4,
    POWER_SETTING_ALTITUDE_ALTITUDE_INTERNAL_OVERRIDE = 5,
    POWER_SETTING_ALTITUDE_ALTITUDE_OS_DEFAULT = 6,
    -- enum POWER_USER_PRESENCE_TYPE
    POWER_USER_PRESENCE_TYPE_UserNotPresent = 0,
    POWER_USER_PRESENCE_TYPE_UserPresent = 1,
    POWER_USER_PRESENCE_TYPE_UserUnknown = 255,
    -- enum SYSTEM_POWER_CONDITION
    SYSTEM_POWER_CONDITION_PoAc = 0,
    SYSTEM_POWER_CONDITION_PoDc = 1,
    SYSTEM_POWER_CONDITION_PoHot = 2,
    SYSTEM_POWER_CONDITION_PoConditionMaximum = 3,
    -- enum SYSTEM_POWER_STATE
    SYSTEM_POWER_STATE_PowerSystemUnspecified = 0,
    SYSTEM_POWER_STATE_PowerSystemWorking = 1,
    SYSTEM_POWER_STATE_PowerSystemSleeping1 = 2,
    SYSTEM_POWER_STATE_PowerSystemSleeping2 = 3,
    SYSTEM_POWER_STATE_PowerSystemSleeping3 = 4,
    SYSTEM_POWER_STATE_PowerSystemHibernate = 5,
    SYSTEM_POWER_STATE_PowerSystemShutdown = 6,
    SYSTEM_POWER_STATE_PowerSystemMaximum = 7,
    -- enum USB_CHARGER_PORT
    USB_CHARGER_PORT_UsbChargerPort_Legacy = 0,
    USB_CHARGER_PORT_UsbChargerPort_TypeC = 1,
    USB_CHARGER_PORT_UsbChargerPort_Max = 2,
    -- enum USER_ACTIVITY_PRESENCE
    USER_ACTIVITY_PRESENCE_PowerUserPresent = 0,
    USER_ACTIVITY_PRESENCE_PowerUserNotPresent = 1,
    USER_ACTIVITY_PRESENCE_PowerUserInactive = 2,
    USER_ACTIVITY_PRESENCE_PowerUserMaximum = 3,
    USER_ACTIVITY_PRESENCE_PowerUserInvalid = 3,
}
