-- AUTO-GENERATED by tools/winmd-gen (via gen-windows-package.ps1)
-- Namespace: Windows.Win32.System.WindowsProgramming
-- Counts: 66 structs, 0 unions, 21 enums, 10 COM interfaces, 213 functions, 586 constants, 2 handle typedefs
--
local W = require "windows"

ffi.cdef[[
typedef void * FEATURE_STATE_CHANGE_SUBSCRIPTION;
typedef void * HWINWATCH;

typedef struct _TCP_REQUEST_QUERY_INFORMATION_EX32_XP TCP_REQUEST_QUERY_INFORMATION_EX32_XP;
typedef struct _DELAYLOAD_INFO DELAYLOAD_INFO;
typedef struct _IMAGE_THUNK_DATA64 IMAGE_THUNK_DATA64;
typedef struct _IMAGE_THUNK_DATA32 IMAGE_THUNK_DATA32;
typedef struct _IMAGE_DELAYLOAD_DESCRIPTOR IMAGE_DELAYLOAD_DESCRIPTOR;
typedef struct _CUSTOM_SYSTEM_EVENT_TRIGGER_CONFIG CUSTOM_SYSTEM_EVENT_TRIGGER_CONFIG;
typedef struct _JIT_DEBUG_INFO JIT_DEBUG_INFO;
typedef struct _HW_PROFILE_INFOA HW_PROFILE_INFOA;
typedef struct _HW_PROFILE_INFOW HW_PROFILE_INFOW;
typedef struct _ACTCTX_SECTION_KEYED_DATA_2600 ACTCTX_SECTION_KEYED_DATA_2600;
typedef struct _ACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA ACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA;
typedef struct _ACTIVATION_CONTEXT_BASIC_INFORMATION ACTIVATION_CONTEXT_BASIC_INFORMATION;
typedef struct _CLIENT_ID CLIENT_ID;
typedef struct _LDR_DATA_TABLE_ENTRY LDR_DATA_TABLE_ENTRY;
typedef struct _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION;
typedef struct _SYSTEM_PROCESS_INFORMATION SYSTEM_PROCESS_INFORMATION;
typedef struct _SYSTEM_THREAD_INFORMATION SYSTEM_THREAD_INFORMATION;
typedef struct _SYSTEM_REGISTRY_QUOTA_INFORMATION SYSTEM_REGISTRY_QUOTA_INFORMATION;
typedef struct _SYSTEM_BASIC_INFORMATION SYSTEM_BASIC_INFORMATION;
typedef struct _SYSTEM_TIMEOFDAY_INFORMATION SYSTEM_TIMEOFDAY_INFORMATION;
typedef struct _SYSTEM_PERFORMANCE_INFORMATION SYSTEM_PERFORMANCE_INFORMATION;
typedef struct _SYSTEM_EXCEPTION_INFORMATION SYSTEM_EXCEPTION_INFORMATION;
typedef struct _SYSTEM_LOOKASIDE_INFORMATION SYSTEM_LOOKASIDE_INFORMATION;
typedef struct _SYSTEM_INTERRUPT_INFORMATION SYSTEM_INTERRUPT_INFORMATION;
typedef struct _SYSTEM_POLICY_INFORMATION SYSTEM_POLICY_INFORMATION;
typedef struct _THREAD_NAME_INFORMATION THREAD_NAME_INFORMATION;
typedef struct _SYSTEM_CODEINTEGRITY_INFORMATION SYSTEM_CODEINTEGRITY_INFORMATION;
typedef struct _PUBLIC_OBJECT_BASIC_INFORMATION PUBLIC_OBJECT_BASIC_INFORMATION;
typedef struct _PUBLIC_OBJECT_TYPE_INFORMATION PUBLIC_OBJECT_TYPE_INFORMATION;
typedef struct _WINSTATIONINFORMATIONW WINSTATIONINFORMATIONW;
typedef struct _CameraUIControl CameraUIControl;
typedef struct _EditionUpgradeHelper EditionUpgradeHelper;
typedef struct _EditionUpgradeBroker EditionUpgradeBroker;
typedef struct _FEATURE_ERROR FEATURE_ERROR;
typedef struct _DCICMD DCICMD;
typedef struct _DCICREATEINPUT DCICREATEINPUT;
typedef struct _DCISURFACEINFO DCISURFACEINFO;
typedef struct _DCIENUMINPUT DCIENUMINPUT;
typedef struct _DCIOFFSCREEN DCIOFFSCREEN;
typedef struct _DCIOVERLAY DCIOVERLAY;
typedef struct _STRENTRYA STRENTRYA;
typedef struct _STRENTRYW STRENTRYW;
typedef struct _STRTABLEA STRTABLEA;
typedef struct _STRTABLEW STRTABLEW;
typedef struct _CABINFOA CABINFOA;
typedef struct _CABINFOW CABINFOW;
typedef struct _PERUSERSECTIONA PERUSERSECTIONA;
typedef struct _PERUSERSECTIONW PERUSERSECTIONW;
typedef struct _IMESTRUCT IMESTRUCT;
typedef struct _UNDETERMINESTRUCT UNDETERMINESTRUCT;
typedef struct _STRINGEXSTRUCT STRINGEXSTRUCT;
typedef struct _DATETIME DATETIME;
typedef struct _IMEPROA IMEPROA;
typedef struct _IMEPROW IMEPROW;
typedef struct _JAVA_TRUST JAVA_TRUST;
typedef struct _TDIEntityID TDIEntityID;
typedef struct _TDIObjectID TDIObjectID;
typedef struct _TCP_REQUEST_QUERY_INFORMATION_EX_XP TCP_REQUEST_QUERY_INFORMATION_EX_XP;
typedef struct _TCP_REQUEST_QUERY_INFORMATION_EX_W2K TCP_REQUEST_QUERY_INFORMATION_EX_W2K;
typedef struct _TCP_REQUEST_SET_INFORMATION_EX TCP_REQUEST_SET_INFORMATION_EX;
typedef struct _TDI_TL_IO_CONTROL_ENDPOINT TDI_TL_IO_CONTROL_ENDPOINT;
typedef struct _WLDP_HOST_INFORMATION WLDP_HOST_INFORMATION;
typedef struct _WLDP_DEVICE_SECURITY_INFORMATION WLDP_DEVICE_SECURITY_INFORMATION;
typedef struct _DefaultBrowserSyncSettings DefaultBrowserSyncSettings;
typedef struct _DELAYLOAD_PROC_DESCRIPTOR DELAYLOAD_PROC_DESCRIPTOR;
typedef struct _DELAYLOAD_INFO DELAYLOAD_INFO;
typedef struct ICameraUIControlEventCallback ICameraUIControlEventCallback;
typedef struct ICameraUIControlEventCallbackVtbl ICameraUIControlEventCallbackVtbl;
typedef struct ICameraUIControl ICameraUIControl;
typedef struct ICameraUIControlVtbl ICameraUIControlVtbl;
typedef struct IEditionUpgradeHelper IEditionUpgradeHelper;
typedef struct IEditionUpgradeHelperVtbl IEditionUpgradeHelperVtbl;
typedef struct IWindowsLockModeHelper IWindowsLockModeHelper;
typedef struct IWindowsLockModeHelperVtbl IWindowsLockModeHelperVtbl;
typedef struct IEditionUpgradeBroker IEditionUpgradeBroker;
typedef struct IEditionUpgradeBrokerVtbl IEditionUpgradeBrokerVtbl;
typedef struct IContainerActivationHelper IContainerActivationHelper;
typedef struct IContainerActivationHelperVtbl IContainerActivationHelperVtbl;
typedef struct IClipServiceNotificationHelper IClipServiceNotificationHelper;
typedef struct IClipServiceNotificationHelperVtbl IClipServiceNotificationHelperVtbl;
typedef struct IFClipNotificationHelper IFClipNotificationHelper;
typedef struct IFClipNotificationHelperVtbl IFClipNotificationHelperVtbl;
typedef struct IDefaultBrowserSyncSettings IDefaultBrowserSyncSettings;
typedef struct IDefaultBrowserSyncSettingsVtbl IDefaultBrowserSyncSettingsVtbl;
typedef struct IDeleteBrowsingHistory IDeleteBrowsingHistory;
typedef struct IDeleteBrowsingHistoryVtbl IDeleteBrowsingHistoryVtbl;

struct _TCP_REQUEST_QUERY_INFORMATION_EX32_XP {
    TDIObjectID ID;
    DWORD * Context;
};
struct _DELAYLOAD_INFO {
    DWORD Size;
    IMAGE_DELAYLOAD_DESCRIPTOR * DelayloadDescriptor;
    IMAGE_THUNK_DATA64 * ThunkAddress;
    LPSTR TargetDllName;
    DELAYLOAD_PROC_DESCRIPTOR TargetApiDescriptor;
    void * TargetModuleBase;
    void * Unused;
    DWORD LastError;
};
struct _IMAGE_THUNK_DATA64 {
    _u1_e__Union u1;
};
struct _IMAGE_THUNK_DATA32 {
    _u1_e__Union u1;
};
struct _IMAGE_DELAYLOAD_DESCRIPTOR {
    _Attributes_e__Union Attributes;
    DWORD DllNameRVA;
    DWORD ModuleHandleRVA;
    DWORD ImportAddressTableRVA;
    DWORD ImportNameTableRVA;
    DWORD BoundImportAddressTableRVA;
    DWORD UnloadInformationTableRVA;
    DWORD TimeDateStamp;
};
struct _CUSTOM_SYSTEM_EVENT_TRIGGER_CONFIG {
    DWORD Size;
    LPWSTR TriggerId;
};
struct _JIT_DEBUG_INFO {
    DWORD dwSize;
    DWORD dwProcessorArchitecture;
    DWORD dwThreadID;
    DWORD dwReserved0;
    ULONGLONG lpExceptionAddress;
    ULONGLONG lpExceptionRecord;
    ULONGLONG lpContextRecord;
};
struct _HW_PROFILE_INFOA {
    DWORD dwDockInfo;
    CHAR * szHwProfileGuid;
    CHAR * szHwProfileName;
};
struct _HW_PROFILE_INFOW {
    DWORD dwDockInfo;
    WCHAR * szHwProfileGuid;
    WCHAR * szHwProfileName;
};
struct _ACTCTX_SECTION_KEYED_DATA_2600 {
    DWORD cbSize;
    DWORD ulDataFormatVersion;
    void * lpData;
    DWORD ulLength;
    void * lpSectionGlobalData;
    DWORD ulSectionGlobalDataLength;
    void * lpSectionBase;
    DWORD ulSectionTotalLength;
    HANDLE hActCtx;
    DWORD ulAssemblyRosterIndex;
};
struct _ACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA {
    void * lpInformation;
    void * lpSectionBase;
    DWORD ulSectionLength;
    void * lpSectionGlobalDataBase;
    DWORD ulSectionGlobalDataLength;
};
struct _ACTIVATION_CONTEXT_BASIC_INFORMATION {
    HANDLE hActCtx;
    DWORD dwFlags;
};
struct _CLIENT_ID {
    HANDLE UniqueProcess;
    HANDLE UniqueThread;
};
struct _LDR_DATA_TABLE_ENTRY {
    void * * Reserved1;
    LIST_ENTRY InMemoryOrderLinks;
    void * * Reserved2;
    void * DllBase;
    void * * Reserved3;
    UNICODE_STRING FullDllName;
    BYTE * Reserved4;
    void * * Reserved5;
    _Anonymous_e__Union Anonymous;
    DWORD TimeDateStamp;
};
struct _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION {
    LONGLONG IdleTime;
    LONGLONG KernelTime;
    LONGLONG UserTime;
    LONGLONG * Reserved1;
    DWORD Reserved2;
};
struct _SYSTEM_PROCESS_INFORMATION {
    DWORD NextEntryOffset;
    DWORD NumberOfThreads;
    BYTE * Reserved1;
    UNICODE_STRING ImageName;
    LONG BasePriority;
    HANDLE UniqueProcessId;
    void * Reserved2;
    DWORD HandleCount;
    DWORD SessionId;
    void * Reserved3;
    void * PeakVirtualSize;
    void * VirtualSize;
    DWORD Reserved4;
    void * PeakWorkingSetSize;
    void * WorkingSetSize;
    void * Reserved5;
    void * QuotaPagedPoolUsage;
    void * Reserved6;
    void * QuotaNonPagedPoolUsage;
    void * PagefileUsage;
    void * PeakPagefileUsage;
    void * PrivatePageCount;
    LONGLONG * Reserved7;
};
struct _SYSTEM_THREAD_INFORMATION {
    LONGLONG * Reserved1;
    DWORD Reserved2;
    void * StartAddress;
    CLIENT_ID ClientId;
    LONG Priority;
    LONG BasePriority;
    DWORD Reserved3;
    DWORD ThreadState;
    DWORD WaitReason;
};
struct _SYSTEM_REGISTRY_QUOTA_INFORMATION {
    DWORD RegistryQuotaAllowed;
    DWORD RegistryQuotaUsed;
    void * Reserved1;
};
struct _SYSTEM_BASIC_INFORMATION {
    BYTE * Reserved1;
    void * * Reserved2;
    char NumberOfProcessors;
};
struct _SYSTEM_TIMEOFDAY_INFORMATION {
    BYTE * Reserved1;
};
struct _SYSTEM_PERFORMANCE_INFORMATION {
    BYTE * Reserved1;
};
struct _SYSTEM_EXCEPTION_INFORMATION {
    BYTE * Reserved1;
};
struct _SYSTEM_LOOKASIDE_INFORMATION {
    BYTE * Reserved1;
};
struct _SYSTEM_INTERRUPT_INFORMATION {
    BYTE * Reserved1;
};
struct _SYSTEM_POLICY_INFORMATION {
    void * * Reserved1;
    DWORD * Reserved2;
};
struct _THREAD_NAME_INFORMATION {
    UNICODE_STRING ThreadName;
};
struct _SYSTEM_CODEINTEGRITY_INFORMATION {
    DWORD Length;
    DWORD CodeIntegrityOptions;
};
struct _PUBLIC_OBJECT_BASIC_INFORMATION {
    DWORD Attributes;
    DWORD GrantedAccess;
    DWORD HandleCount;
    DWORD PointerCount;
    DWORD * Reserved;
};
struct _PUBLIC_OBJECT_TYPE_INFORMATION {
    UNICODE_STRING TypeName;
    DWORD * Reserved;
};
struct _WINSTATIONINFORMATIONW {
    BYTE * Reserved2;
    DWORD LogonId;
    BYTE * Reserved3;
};
struct _CameraUIControl {
};
struct _EditionUpgradeHelper {
};
struct _EditionUpgradeBroker {
};
struct _FEATURE_ERROR {
    HRESULT hr;
    WORD lineNumber;
    LPSTR file;
    LPSTR process;
    LPSTR module;
    DWORD callerReturnAddressOffset;
    LPSTR callerModule;
    LPSTR message;
    WORD originLineNumber;
    LPSTR originFile;
    LPSTR originModule;
    DWORD originCallerReturnAddressOffset;
    LPSTR originCallerModule;
    LPSTR originName;
};
struct _DCICMD {
    DWORD dwCommand;
    DWORD dwParam1;
    DWORD dwParam2;
    DWORD dwVersion;
    DWORD dwReserved;
};
struct _DCICREATEINPUT {
    DCICMD cmd;
    DWORD dwCompression;
    DWORD * dwMask;
    DWORD dwWidth;
    DWORD dwHeight;
    DWORD dwDCICaps;
    DWORD dwBitCount;
    void * lpSurface;
};
struct _DCISURFACEINFO {
    DWORD dwSize;
    DWORD dwDCICaps;
    DWORD dwCompression;
    DWORD * dwMask;
    DWORD dwWidth;
    DWORD dwHeight;
    LONG lStride;
    DWORD dwBitCount;
    void * dwOffSurface;
    WORD wSelSurface;
    WORD wReserved;
    DWORD dwReserved1;
    DWORD dwReserved2;
    DWORD dwReserved3;
    void * BeginAccess;
    void * EndAccess;
    void * DestroySurface;
};
struct _DCIENUMINPUT {
    DCICMD cmd;
    RECT rSrc;
    RECT rDst;
    void * EnumCallback;
    void * lpContext;
};
struct _DCIOFFSCREEN {
    DCISURFACEINFO dciInfo;
    void * Draw;
    void * SetClipList;
    void * SetDestination;
};
struct _DCIOVERLAY {
    DCISURFACEINFO dciInfo;
    DWORD dwChromakeyValue;
    DWORD dwChromakeyMask;
};
struct _STRENTRYA {
    LPSTR pszName;
    LPSTR pszValue;
};
struct _STRENTRYW {
    LPWSTR pszName;
    LPWSTR pszValue;
};
struct _STRTABLEA {
    DWORD cEntries;
    STRENTRYA * pse;
};
struct _STRTABLEW {
    DWORD cEntries;
    STRENTRYW * pse;
};
struct _CABINFOA {
    LPSTR pszCab;
    LPSTR pszInf;
    LPSTR pszSection;
    CHAR * szSrcPath;
    DWORD dwFlags;
};
struct _CABINFOW {
    LPWSTR pszCab;
    LPWSTR pszInf;
    LPWSTR pszSection;
    WCHAR * szSrcPath;
    DWORD dwFlags;
};
struct _PERUSERSECTIONA {
    CHAR * szGUID;
    CHAR * szDispName;
    CHAR * szLocale;
    CHAR * szStub;
    CHAR * szVersion;
    CHAR * szCompID;
    DWORD dwIsInstalled;
    BOOL bRollback;
};
struct _PERUSERSECTIONW {
    WCHAR * szGUID;
    WCHAR * szDispName;
    WCHAR * szLocale;
    WCHAR * szStub;
    WCHAR * szVersion;
    WCHAR * szCompID;
    DWORD dwIsInstalled;
    BOOL bRollback;
};
struct _IMESTRUCT {
    DWORD fnc;
    WPARAM wParam;
    DWORD wCount;
    DWORD dchSource;
    DWORD dchDest;
    LPARAM lParam1;
    LPARAM lParam2;
    LPARAM lParam3;
};
struct _UNDETERMINESTRUCT {
    DWORD dwSize;
    DWORD uDefIMESize;
    DWORD uDefIMEPos;
    DWORD uUndetTextLen;
    DWORD uUndetTextPos;
    DWORD uUndetAttrPos;
    DWORD uCursorPos;
    DWORD uDeltaStart;
    DWORD uDetermineTextLen;
    DWORD uDetermineTextPos;
    DWORD uDetermineDelimPos;
    DWORD uYomiTextLen;
    DWORD uYomiTextPos;
    DWORD uYomiDelimPos;
};
struct _STRINGEXSTRUCT {
    DWORD dwSize;
    DWORD uDeterminePos;
    DWORD uDetermineDelimPos;
    DWORD uYomiPos;
    DWORD uYomiDelimPos;
};
struct _DATETIME {
    WORD year;
    WORD month;
    WORD day;
    WORD hour;
    WORD min;
    WORD sec;
};
struct _IMEPROA {
    HWND hWnd;
    DATETIME InstDate;
    DWORD wVersion;
    BYTE * szDescription;
    BYTE * szName;
    BYTE * szOptions;
};
struct _IMEPROW {
    HWND hWnd;
    DATETIME InstDate;
    DWORD wVersion;
    WCHAR * szDescription;
    WCHAR * szName;
    WCHAR * szOptions;
};
struct _JAVA_TRUST {
    DWORD cbSize;
    DWORD flag;
    BOOL fAllActiveXPermissions;
    BOOL fAllPermissions;
    DWORD dwEncodingType;
    BYTE * pbJavaPermissions;
    DWORD cbJavaPermissions;
    BYTE * pbSigner;
    DWORD cbSigner;
    LPWSTR pwszZone;
    Guid guidZone;
    HRESULT hVerify;
};
struct _TDIEntityID {
    TDIENTITY_ENTITY_TYPE tei_entity;
    DWORD tei_instance;
};
struct _TDIObjectID {
    TDIEntityID toi_entity;
    DWORD toi_class;
    DWORD toi_type;
    DWORD toi_id;
};
struct _TCP_REQUEST_QUERY_INFORMATION_EX_XP {
    TDIObjectID ID;
    void * * Context;
};
struct _TCP_REQUEST_QUERY_INFORMATION_EX_W2K {
    TDIObjectID ID;
    BYTE * Context;
};
struct _TCP_REQUEST_SET_INFORMATION_EX {
    TDIObjectID ID;
    DWORD BufferSize;
    BYTE * Buffer;
};
struct _TDI_TL_IO_CONTROL_ENDPOINT {
    TDI_TL_IO_CONTROL_TYPE Type;
    DWORD Level;
    _Anonymous_e__Union Anonymous;
    void * InputBuffer;
    DWORD InputBufferLength;
    void * OutputBuffer;
    DWORD OutputBufferLength;
};
struct _WLDP_HOST_INFORMATION {
    DWORD dwRevision;
    WLDP_HOST_ID dwHostId;
    LPWSTR szSource;
    HANDLE hSource;
};
struct _WLDP_DEVICE_SECURITY_INFORMATION {
    DWORD UnlockIdSize;
    BYTE * UnlockId;
    DWORD ManufacturerIDLength;
    LPWSTR ManufacturerID;
};
struct _DefaultBrowserSyncSettings {
};
struct _DELAYLOAD_PROC_DESCRIPTOR {
    DWORD ImportDescribedByName;
    _Description_e__Union Description;
};
struct _DELAYLOAD_INFO {
    DWORD Size;
    IMAGE_DELAYLOAD_DESCRIPTOR * DelayloadDescriptor;
    IMAGE_THUNK_DATA32 * ThunkAddress;
    LPSTR TargetDllName;
    DELAYLOAD_PROC_DESCRIPTOR TargetApiDescriptor;
    void * TargetModuleBase;
    void * Unused;
    DWORD LastError;
};
/* ===== COM interfaces ===== */
struct ICameraUIControlEventCallbackVtbl {
    HRESULT (__stdcall *QueryInterface)(ICameraUIControlEventCallback *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(ICameraUIControlEventCallback *This);
    ULONG (__stdcall *Release)(ICameraUIControlEventCallback *This);
    void (__stdcall *OnStartupComplete)(ICameraUIControlEventCallback *This);
    void (__stdcall *OnSuspendComplete)(ICameraUIControlEventCallback *This);
    void (__stdcall *OnItemCaptured)(ICameraUIControlEventCallback *This, LPWSTR pszPath);
    void (__stdcall *OnItemDeleted)(ICameraUIControlEventCallback *This, LPWSTR pszPath);
    void (__stdcall *OnClosed)(ICameraUIControlEventCallback *This);
};
struct ICameraUIControlEventCallback { ICameraUIControlEventCallbackVtbl *lpVtbl; };
struct ICameraUIControlVtbl {
    HRESULT (__stdcall *QueryInterface)(ICameraUIControl *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(ICameraUIControl *This);
    ULONG (__stdcall *Release)(ICameraUIControl *This);
    HRESULT (__stdcall *Show)(ICameraUIControl *This, IUnknown pWindow, CameraUIControlMode mode, CameraUIControlLinearSelectionMode selectionMode, CameraUIControlCaptureMode captureMode, CameraUIControlPhotoFormat photoFormat, CameraUIControlVideoFormat videoFormat, BOOL bHasCloseButton, ICameraUIControlEventCallback pEventCallback);
    HRESULT (__stdcall *Close)(ICameraUIControl *This);
    HRESULT (__stdcall *Suspend)(ICameraUIControl *This, BOOL * pbDeferralRequired);
    HRESULT (__stdcall *Resume)(ICameraUIControl *This);
    HRESULT (__stdcall *GetCurrentViewType)(ICameraUIControl *This, CameraUIControlViewType * pViewType);
    HRESULT (__stdcall *GetActiveItem)(ICameraUIControl *This, BSTR * pbstrActiveItemPath);
    HRESULT (__stdcall *GetSelectedItems)(ICameraUIControl *This, SAFEARRAY * * ppSelectedItemPaths);
    HRESULT (__stdcall *RemoveCapturedItem)(ICameraUIControl *This, LPWSTR pszPath);
};
struct ICameraUIControl { ICameraUIControlVtbl *lpVtbl; };
struct IEditionUpgradeHelperVtbl {
    HRESULT (__stdcall *QueryInterface)(IEditionUpgradeHelper *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IEditionUpgradeHelper *This);
    ULONG (__stdcall *Release)(IEditionUpgradeHelper *This);
    HRESULT (__stdcall *CanUpgrade)(IEditionUpgradeHelper *This, BOOL * isAllowed);
    HRESULT (__stdcall *UpdateOperatingSystem)(IEditionUpgradeHelper *This, LPWSTR contentId);
    HRESULT (__stdcall *ShowProductKeyUI)(IEditionUpgradeHelper *This);
    HRESULT (__stdcall *GetOsProductContentId)(IEditionUpgradeHelper *This, LPWSTR * contentId);
    HRESULT (__stdcall *GetGenuineLocalStatus)(IEditionUpgradeHelper *This, BOOL * isGenuine);
};
struct IEditionUpgradeHelper { IEditionUpgradeHelperVtbl *lpVtbl; };
struct IWindowsLockModeHelperVtbl {
    HRESULT (__stdcall *QueryInterface)(IWindowsLockModeHelper *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IWindowsLockModeHelper *This);
    ULONG (__stdcall *Release)(IWindowsLockModeHelper *This);
    HRESULT (__stdcall *GetSMode)(IWindowsLockModeHelper *This, BOOL * isSmode);
};
struct IWindowsLockModeHelper { IWindowsLockModeHelperVtbl *lpVtbl; };
struct IEditionUpgradeBrokerVtbl {
    HRESULT (__stdcall *QueryInterface)(IEditionUpgradeBroker *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IEditionUpgradeBroker *This);
    ULONG (__stdcall *Release)(IEditionUpgradeBroker *This);
    HRESULT (__stdcall *InitializeParentWindow)(IEditionUpgradeBroker *This, OLE_HANDLE parentHandle);
    HRESULT (__stdcall *UpdateOperatingSystem)(IEditionUpgradeBroker *This, BSTR parameter);
    HRESULT (__stdcall *ShowProductKeyUI)(IEditionUpgradeBroker *This);
    HRESULT (__stdcall *CanUpgrade)(IEditionUpgradeBroker *This);
};
struct IEditionUpgradeBroker { IEditionUpgradeBrokerVtbl *lpVtbl; };
struct IContainerActivationHelperVtbl {
    HRESULT (__stdcall *QueryInterface)(IContainerActivationHelper *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IContainerActivationHelper *This);
    ULONG (__stdcall *Release)(IContainerActivationHelper *This);
    HRESULT (__stdcall *CanActivateClientVM)(IContainerActivationHelper *This, VARIANT_BOOL * isAllowed);
};
struct IContainerActivationHelper { IContainerActivationHelperVtbl *lpVtbl; };
struct IClipServiceNotificationHelperVtbl {
    HRESULT (__stdcall *QueryInterface)(IClipServiceNotificationHelper *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IClipServiceNotificationHelper *This);
    ULONG (__stdcall *Release)(IClipServiceNotificationHelper *This);
    HRESULT (__stdcall *ShowToast)(IClipServiceNotificationHelper *This, BSTR titleText, BSTR bodyText, BSTR packageName, BSTR appId, BSTR launchCommand);
};
struct IClipServiceNotificationHelper { IClipServiceNotificationHelperVtbl *lpVtbl; };
struct IFClipNotificationHelperVtbl {
    HRESULT (__stdcall *QueryInterface)(IFClipNotificationHelper *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IFClipNotificationHelper *This);
    ULONG (__stdcall *Release)(IFClipNotificationHelper *This);
    HRESULT (__stdcall *ShowSystemDialog)(IFClipNotificationHelper *This, BSTR titleText, BSTR bodyText);
};
struct IFClipNotificationHelper { IFClipNotificationHelperVtbl *lpVtbl; };
struct IDefaultBrowserSyncSettingsVtbl {
    HRESULT (__stdcall *QueryInterface)(IDefaultBrowserSyncSettings *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IDefaultBrowserSyncSettings *This);
    ULONG (__stdcall *Release)(IDefaultBrowserSyncSettings *This);
    BOOL (__stdcall *IsEnabled)(IDefaultBrowserSyncSettings *This);
};
struct IDefaultBrowserSyncSettings { IDefaultBrowserSyncSettingsVtbl *lpVtbl; };
struct IDeleteBrowsingHistoryVtbl {
    HRESULT (__stdcall *QueryInterface)(IDeleteBrowsingHistory *This, GUID_W *riid, void **ppvObject);
    ULONG (__stdcall *AddRef)(IDeleteBrowsingHistory *This);
    ULONG (__stdcall *Release)(IDeleteBrowsingHistory *This);
    HRESULT (__stdcall *DeleteBrowsingHistory)(IDeleteBrowsingHistory *This, DWORD dwFlags);
};
struct IDeleteBrowsingHistory { IDeleteBrowsingHistoryVtbl *lpVtbl; };
/* System.WindowsProgramming -- 213 functions */
LONG uaw_lstrcmpW(WORD * String1, WORD * String2);
LONG uaw_lstrcmpiW(WORD * String1, WORD * String2);
LONG uaw_lstrlenW(WORD * String);
WORD * uaw_wcschr(WORD * String, WCHAR Character);
WORD * uaw_wcscpy(WORD * Destination, WORD * Source);
LONG uaw_wcsicmp(WORD * String1, WORD * String2);
void * uaw_wcslen(WORD * String);
WORD * uaw_wcsrchr(WORD * String, WCHAR Character);
void * RtlGetReturnAddressHijackTarget();
DWORD RtlRaiseCustomSystemEventTrigger(CUSTOM_SYSTEM_EVENT_TRIGGER_CONFIG * TriggerConfig);
BOOL IsApiSetImplemented(LPSTR Contract);
BOOL QueryThreadCycleTime(HANDLE ThreadHandle, ULONGLONG * CycleTime);
BOOL QueryProcessCycleTime(HANDLE ProcessHandle, ULONGLONG * CycleTime);
BOOL QueryIdleProcessorCycleTime(DWORD * BufferLength, ULONGLONG * ProcessorIdleCycleTime);
BOOL QueryIdleProcessorCycleTimeEx(WORD Group, DWORD * BufferLength, ULONGLONG * ProcessorIdleCycleTime);
void QueryInterruptTimePrecise(ULONGLONG * lpInterruptTimePrecise);
void QueryUnbiasedInterruptTimePrecise(ULONGLONG * lpUnbiasedInterruptTimePrecise);
void QueryInterruptTime(ULONGLONG * lpInterruptTime);
BOOL QueryUnbiasedInterruptTime(ULONGLONG * UnbiasedTime);
HRESULT QueryAuxiliaryCounterFrequency(ULONGLONG * lpAuxiliaryCounterFrequency);
HRESULT ConvertAuxiliaryCounterToPerformanceCounter(ULONGLONG ullAuxiliaryCounterValue, ULONGLONG * lpPerformanceCounterValue, ULONGLONG * lpConversionError);
HRESULT ConvertPerformanceCounterToAuxiliaryCounter(ULONGLONG ullPerformanceCounterValue, ULONGLONG * lpAuxiliaryCounterValue, ULONGLONG * lpConversionError);
void * GlobalCompact(DWORD dwMinFree);
void GlobalFix(HGLOBAL hMem);
void GlobalUnfix(HGLOBAL hMem);
void * GlobalWire(HGLOBAL hMem);
BOOL GlobalUnWire(HGLOBAL hMem);
void * LocalShrink(HLOCAL hMem, DWORD cbNewSize);
void * LocalCompact(DWORD uMinFree);
BOOL SetEnvironmentStringsA(LPSTR NewEnvironment);
DWORD SetHandleCount(DWORD uNumber);
BOOL RequestDeviceWakeup(HANDLE hDevice);
BOOL CancelDeviceWakeupRequest(HANDLE hDevice);
BOOL SetMessageWaitingIndicator(HANDLE hMsgIndicator, DWORD ulMsgCount);
LONG MulDiv(LONG nNumber, LONG nNumerator, LONG nDenominator);
BOOL GetSystemRegistryQuota(DWORD * pdwQuotaAllowed, DWORD * pdwQuotaUsed);
BOOL FileTimeToDosDateTime(FILETIME * lpFileTime, WORD * lpFatDate, WORD * lpFatTime);
BOOL DosDateTimeToFileTime(WORD wFatDate, WORD wFatTime, FILETIME * lpFileTime);
LONG _lopen(LPSTR lpPathName, LONG iReadWrite);
LONG _lcreat(LPSTR lpPathName, LONG iAttribute);
DWORD _lread(LONG hFile, void * lpBuffer, DWORD uBytes);
DWORD _lwrite(LONG hFile, LPSTR lpBuffer, DWORD uBytes);
LONG _hread(LONG hFile, void * lpBuffer, LONG lBytes);
LONG _hwrite(LONG hFile, LPSTR lpBuffer, LONG lBytes);
LONG _lclose(LONG hFile);
LONG _llseek(LONG hFile, LONG lOffset, LONG iOrigin);
HANDLE OpenMutexA(DWORD dwDesiredAccess, BOOL bInheritHandle, LPSTR lpName);
HANDLE OpenSemaphoreA(DWORD dwDesiredAccess, BOOL bInheritHandle, LPSTR lpName);
DWORD GetFirmwareEnvironmentVariableA(LPSTR lpName, LPSTR lpGuid, void * pBuffer, DWORD nSize);
DWORD GetFirmwareEnvironmentVariableW(LPWSTR lpName, LPWSTR lpGuid, void * pBuffer, DWORD nSize);
DWORD GetFirmwareEnvironmentVariableExA(LPSTR lpName, LPSTR lpGuid, void * pBuffer, DWORD nSize, DWORD * pdwAttribubutes);
DWORD GetFirmwareEnvironmentVariableExW(LPWSTR lpName, LPWSTR lpGuid, void * pBuffer, DWORD nSize, DWORD * pdwAttribubutes);
BOOL SetFirmwareEnvironmentVariableA(LPSTR lpName, LPSTR lpGuid, void * pValue, DWORD nSize);
BOOL SetFirmwareEnvironmentVariableW(LPWSTR lpName, LPWSTR lpGuid, void * pValue, DWORD nSize);
BOOL SetFirmwareEnvironmentVariableExA(LPSTR lpName, LPSTR lpGuid, void * pValue, DWORD nSize, DWORD dwAttributes);
BOOL SetFirmwareEnvironmentVariableExW(LPWSTR lpName, LPWSTR lpGuid, void * pValue, DWORD nSize, DWORD dwAttributes);
BOOL IsNativeVhdBoot(BOOL * NativeVhdBoot);
DWORD GetProfileIntA(LPSTR lpAppName, LPSTR lpKeyName, LONG nDefault);
DWORD GetProfileIntW(LPWSTR lpAppName, LPWSTR lpKeyName, LONG nDefault);
DWORD GetProfileStringA(LPSTR lpAppName, LPSTR lpKeyName, LPSTR lpDefault, LPSTR lpReturnedString, DWORD nSize);
DWORD GetProfileStringW(LPWSTR lpAppName, LPWSTR lpKeyName, LPWSTR lpDefault, LPWSTR lpReturnedString, DWORD nSize);
BOOL WriteProfileStringA(LPSTR lpAppName, LPSTR lpKeyName, LPSTR lpString);
BOOL WriteProfileStringW(LPWSTR lpAppName, LPWSTR lpKeyName, LPWSTR lpString);
DWORD GetProfileSectionA(LPSTR lpAppName, LPSTR lpReturnedString, DWORD nSize);
DWORD GetProfileSectionW(LPWSTR lpAppName, LPWSTR lpReturnedString, DWORD nSize);
BOOL WriteProfileSectionA(LPSTR lpAppName, LPSTR lpString);
BOOL WriteProfileSectionW(LPWSTR lpAppName, LPWSTR lpString);
DWORD GetPrivateProfileIntA(LPSTR lpAppName, LPSTR lpKeyName, LONG nDefault, LPSTR lpFileName);
LONG GetPrivateProfileIntW(LPWSTR lpAppName, LPWSTR lpKeyName, LONG nDefault, LPWSTR lpFileName);
DWORD GetPrivateProfileStringA(LPSTR lpAppName, LPSTR lpKeyName, LPSTR lpDefault, LPSTR lpReturnedString, DWORD nSize, LPSTR lpFileName);
DWORD GetPrivateProfileStringW(LPWSTR lpAppName, LPWSTR lpKeyName, LPWSTR lpDefault, LPWSTR lpReturnedString, DWORD nSize, LPWSTR lpFileName);
BOOL WritePrivateProfileStringA(LPSTR lpAppName, LPSTR lpKeyName, LPSTR lpString, LPSTR lpFileName);
BOOL WritePrivateProfileStringW(LPWSTR lpAppName, LPWSTR lpKeyName, LPWSTR lpString, LPWSTR lpFileName);
DWORD GetPrivateProfileSectionA(LPSTR lpAppName, LPSTR lpReturnedString, DWORD nSize, LPSTR lpFileName);
DWORD GetPrivateProfileSectionW(LPWSTR lpAppName, LPWSTR lpReturnedString, DWORD nSize, LPWSTR lpFileName);
BOOL WritePrivateProfileSectionA(LPSTR lpAppName, LPSTR lpString, LPSTR lpFileName);
BOOL WritePrivateProfileSectionW(LPWSTR lpAppName, LPWSTR lpString, LPWSTR lpFileName);
DWORD GetPrivateProfileSectionNamesA(LPSTR lpszReturnBuffer, DWORD nSize, LPSTR lpFileName);
DWORD GetPrivateProfileSectionNamesW(LPWSTR lpszReturnBuffer, DWORD nSize, LPWSTR lpFileName);
BOOL GetPrivateProfileStructA(LPSTR lpszSection, LPSTR lpszKey, void * lpStruct, DWORD uSizeStruct, LPSTR szFile);
BOOL GetPrivateProfileStructW(LPWSTR lpszSection, LPWSTR lpszKey, void * lpStruct, DWORD uSizeStruct, LPWSTR szFile);
BOOL WritePrivateProfileStructA(LPSTR lpszSection, LPSTR lpszKey, void * lpStruct, DWORD uSizeStruct, LPSTR szFile);
BOOL WritePrivateProfileStructW(LPWSTR lpszSection, LPWSTR lpszKey, void * lpStruct, DWORD uSizeStruct, LPWSTR szFile);
BOOL IsBadHugeReadPtr(void * lp, void * ucb);
BOOL IsBadHugeWritePtr(void * lp, void * ucb);
BOOL GetComputerNameA(LPSTR lpBuffer, DWORD * nSize);
BOOL GetComputerNameW(LPWSTR lpBuffer, DWORD * nSize);
BOOL DnsHostnameToComputerNameA(LPSTR Hostname, LPSTR ComputerName, DWORD * nSize);
BOOL DnsHostnameToComputerNameW(LPWSTR Hostname, LPWSTR ComputerName, DWORD * nSize);
BOOL GetUserNameA(LPSTR lpBuffer, DWORD * pcbBuffer);
BOOL GetUserNameW(LPWSTR lpBuffer, DWORD * pcbBuffer);
BOOL IsTokenUntrusted(HANDLE TokenHandle);
BOOL GetCurrentHwProfileA(HW_PROFILE_INFOA * lpHwProfileInfo);
BOOL GetCurrentHwProfileW(HW_PROFILE_INFOW * lpHwProfileInfo);
BOOL ReplacePartitionUnit(LPWSTR TargetPartition, LPWSTR SparePartition, DWORD Flags);
ULONGLONG GetThreadEnabledXStateFeatures();
BOOL EnableProcessOptionalXStateFeatures(ULONGLONG Features);
DWORD RaiseCustomSystemEventTrigger(CUSTOM_SYSTEM_EVENT_TRIGGER_CONFIG * CustomSystemEventTriggerConfig);
BYTE RtlIsNameLegalDOS8Dot3(UNICODE_STRING * Name, STRING * OemName, BYTE * NameContainsSpaces);
NTSTATUS RtlLocalTimeToSystemTime(LONGLONG * LocalTime, LONGLONG * SystemTime);
BYTE RtlTimeToSecondsSince1970(LONGLONG * Time, DWORD * ElapsedSeconds);
void RtlFreeAnsiString(STRING * AnsiString);
void RtlFreeUnicodeString(UNICODE_STRING * UnicodeString);
void RtlFreeOemString(STRING * OemString);
void RtlInitString(STRING * DestinationString, char * SourceString);
NTSTATUS RtlInitStringEx(STRING * DestinationString, char * SourceString);
void RtlInitAnsiString(STRING * DestinationString, char * SourceString);
NTSTATUS RtlInitAnsiStringEx(STRING * DestinationString, char * SourceString);
void RtlInitUnicodeString(UNICODE_STRING * DestinationString, LPWSTR SourceString);
NTSTATUS RtlAnsiStringToUnicodeString(UNICODE_STRING * DestinationString, STRING * SourceString, BYTE AllocateDestinationString);
NTSTATUS RtlUnicodeStringToAnsiString(STRING * DestinationString, UNICODE_STRING * SourceString, BYTE AllocateDestinationString);
NTSTATUS RtlUnicodeStringToOemString(STRING * DestinationString, UNICODE_STRING * SourceString, BYTE AllocateDestinationString);
NTSTATUS RtlUnicodeToMultiByteSize(DWORD * BytesInMultiByteString, LPWSTR UnicodeString, DWORD BytesInUnicodeString);
NTSTATUS RtlCharToInteger(char * String, DWORD Base, DWORD * Value);
DWORD RtlUniform(DWORD * Seed);
FEATURE_ENABLED_STATE GetFeatureEnabledState(DWORD featureId, FEATURE_CHANGE_TIME changeTime);
void RecordFeatureUsage(DWORD featureId, DWORD kind, DWORD addend, LPSTR originName);
void RecordFeatureError(DWORD featureId, FEATURE_ERROR * error);
void SubscribeFeatureStateChangeNotification(FEATURE_STATE_CHANGE_SUBSCRIPTION * subscription, PFEATURE_STATE_CHANGE_CALLBACK callback, void * context);
void UnsubscribeFeatureStateChangeNotification(FEATURE_STATE_CHANGE_SUBSCRIPTION subscription);
DWORD GetFeatureVariant(DWORD featureId, FEATURE_CHANGE_TIME changeTime, DWORD * payloadId, BOOL * hasNotification);
HDC DCIOpenProvider();
void DCICloseProvider(HDC hdc);
LONG DCICreatePrimary(HDC hdc, DCISURFACEINFO * * lplpSurface);
LONG DCICreateOffscreen(HDC hdc, DWORD dwCompression, DWORD dwRedMask, DWORD dwGreenMask, DWORD dwBlueMask, DWORD dwWidth, DWORD dwHeight, DWORD dwDCICaps, DWORD dwBitCount, DCIOFFSCREEN * * lplpSurface);
LONG DCICreateOverlay(HDC hdc, void * lpOffscreenSurf, DCIOVERLAY * * lplpSurface);
LONG DCIEnum(HDC hdc, RECT * lprDst, RECT * lprSrc, void * lpFnCallback, void * lpContext);
LONG DCISetSrcDestClip(DCIOFFSCREEN * pdci, RECT * srcrc, RECT * destrc, RGNDATA * prd);
HWINWATCH WinWatchOpen(HWND hwnd);
void WinWatchClose(HWINWATCH hWW);
DWORD WinWatchGetClipList(HWINWATCH hWW, RECT * prc, DWORD size, RGNDATA * prd);
BOOL WinWatchDidStatusChange(HWINWATCH hWW);
DWORD GetWindowRegionData(HWND hwnd, DWORD size, RGNDATA * prd);
DWORD GetDCRegionData(HDC hdc, DWORD size, RGNDATA * prd);
BOOL WinWatchNotify(HWINWATCH hWW, WINWATCHNOTIFYPROC NotifyCallback, LPARAM NotifyParam);
void DCIEndAccess(DCISURFACEINFO * pdci);
LONG DCIBeginAccess(DCISURFACEINFO * pdci, LONG x, LONG y, LONG dx, LONG dy);
void DCIDestroy(DCISURFACEINFO * pdci);
LONG DCIDraw(DCIOFFSCREEN * pdci);
LONG DCISetClipList(DCIOFFSCREEN * pdci, RGNDATA * prd);
LONG DCISetDestination(DCIOFFSCREEN * pdci, RECT * dst, RECT * src);
DWORD GdiEntry13();
HRESULT RunSetupCommandA(HWND hWnd, LPSTR szCmdName, LPSTR szInfSection, LPSTR szDir, LPSTR lpszTitle, HANDLE * phEXE, DWORD dwFlags, void * pvReserved);
HRESULT RunSetupCommandW(HWND hWnd, LPWSTR szCmdName, LPWSTR szInfSection, LPWSTR szDir, LPWSTR lpszTitle, HANDLE * phEXE, DWORD dwFlags, void * pvReserved);
DWORD NeedRebootInit();
BOOL NeedReboot(DWORD dwRebootCheck);
HRESULT RebootCheckOnInstallA(HWND hwnd, LPSTR pszINF, LPSTR pszSec, DWORD dwReserved);
HRESULT RebootCheckOnInstallW(HWND hwnd, LPWSTR pszINF, LPWSTR pszSec, DWORD dwReserved);
HRESULT TranslateInfStringA(LPSTR pszInfFilename, LPSTR pszInstallSection, LPSTR pszTranslateSection, LPSTR pszTranslateKey, LPSTR pszBuffer, DWORD cchBuffer, DWORD * pdwRequiredSize, void * pvReserved);
HRESULT TranslateInfStringW(LPWSTR pszInfFilename, LPWSTR pszInstallSection, LPWSTR pszTranslateSection, LPWSTR pszTranslateKey, LPWSTR pszBuffer, DWORD cchBuffer, DWORD * pdwRequiredSize, void * pvReserved);
HRESULT RegInstallA(HMODULE hmod, LPSTR pszSection, STRTABLEA * pstTable);
HRESULT RegInstallW(HMODULE hmod, LPWSTR pszSection, STRTABLEW * pstTable);
HRESULT LaunchINFSectionExW(HWND hwnd, HINSTANCE hInstance, LPWSTR pszParms, LONG nShow);
HRESULT ExecuteCabA(HWND hwnd, CABINFOA * pCab, void * pReserved);
HRESULT ExecuteCabW(HWND hwnd, CABINFOW * pCab, void * pReserved);
HRESULT AdvInstallFileA(HWND hwnd, LPSTR lpszSourceDir, LPSTR lpszSourceFile, LPSTR lpszDestDir, LPSTR lpszDestFile, DWORD dwFlags, DWORD dwReserved);
HRESULT AdvInstallFileW(HWND hwnd, LPWSTR lpszSourceDir, LPWSTR lpszSourceFile, LPWSTR lpszDestDir, LPWSTR lpszDestFile, DWORD dwFlags, DWORD dwReserved);
HRESULT RegSaveRestoreA(HWND hWnd, LPSTR pszTitleString, HKEY hkBckupKey, LPSTR pcszRootKey, LPSTR pcszSubKey, LPSTR pcszValueName, DWORD dwFlags);
HRESULT RegSaveRestoreW(HWND hWnd, LPWSTR pszTitleString, HKEY hkBckupKey, LPWSTR pcszRootKey, LPWSTR pcszSubKey, LPWSTR pcszValueName, DWORD dwFlags);
HRESULT RegSaveRestoreOnINFA(HWND hWnd, LPSTR pszTitle, LPSTR pszINF, LPSTR pszSection, HKEY hHKLMBackKey, HKEY hHKCUBackKey, DWORD dwFlags);
HRESULT RegSaveRestoreOnINFW(HWND hWnd, LPWSTR pszTitle, LPWSTR pszINF, LPWSTR pszSection, HKEY hHKLMBackKey, HKEY hHKCUBackKey, DWORD dwFlags);
HRESULT RegRestoreAllA(HWND hWnd, LPSTR pszTitleString, HKEY hkBckupKey);
HRESULT RegRestoreAllW(HWND hWnd, LPWSTR pszTitleString, HKEY hkBckupKey);
HRESULT FileSaveRestoreW(HWND hDlg, LPWSTR lpFileList, LPWSTR lpDir, LPWSTR lpBaseName, DWORD dwFlags);
HRESULT FileSaveRestoreOnINFA(HWND hWnd, LPSTR pszTitle, LPSTR pszINF, LPSTR pszSection, LPSTR pszBackupDir, LPSTR pszBaseBackupFile, DWORD dwFlags);
HRESULT FileSaveRestoreOnINFW(HWND hWnd, LPWSTR pszTitle, LPWSTR pszINF, LPWSTR pszSection, LPWSTR pszBackupDir, LPWSTR pszBaseBackupFile, DWORD dwFlags);
HRESULT AddDelBackupEntryA(LPSTR lpcszFileList, LPSTR lpcszBackupDir, LPSTR lpcszBaseName, DWORD dwFlags);
HRESULT AddDelBackupEntryW(LPWSTR lpcszFileList, LPWSTR lpcszBackupDir, LPWSTR lpcszBaseName, DWORD dwFlags);
HRESULT FileSaveMarkNotExistA(LPSTR lpFileList, LPSTR lpDir, LPSTR lpBaseName);
HRESULT FileSaveMarkNotExistW(LPWSTR lpFileList, LPWSTR lpDir, LPWSTR lpBaseName);
HRESULT GetVersionFromFileA(LPSTR lpszFilename, DWORD * pdwMSVer, DWORD * pdwLSVer, BOOL bVersion);
HRESULT GetVersionFromFileW(LPWSTR lpszFilename, DWORD * pdwMSVer, DWORD * pdwLSVer, BOOL bVersion);
HRESULT GetVersionFromFileExA(LPSTR lpszFilename, DWORD * pdwMSVer, DWORD * pdwLSVer, BOOL bVersion);
HRESULT GetVersionFromFileExW(LPWSTR lpszFilename, DWORD * pdwMSVer, DWORD * pdwLSVer, BOOL bVersion);
BOOL IsNTAdmin(DWORD dwReserved, DWORD * lpdwReserved);
HRESULT DelNodeA(LPSTR pszFileOrDirName, DWORD dwFlags);
HRESULT DelNodeW(LPWSTR pszFileOrDirName, DWORD dwFlags);
HRESULT DelNodeRunDLL32W(HWND hwnd, HINSTANCE hInstance, LPWSTR pszParms, LONG nShow);
HRESULT OpenINFEngineA(LPSTR pszInfFilename, LPSTR pszInstallSection, DWORD dwFlags, void * * phInf, void * pvReserved);
HRESULT OpenINFEngineW(LPWSTR pszInfFilename, LPWSTR pszInstallSection, DWORD dwFlags, void * * phInf, void * pvReserved);
HRESULT TranslateInfStringExA(void * hInf, LPSTR pszInfFilename, LPSTR pszTranslateSection, LPSTR pszTranslateKey, LPSTR pszBuffer, DWORD dwBufferSize, DWORD * pdwRequiredSize, void * pvReserved);
HRESULT TranslateInfStringExW(void * hInf, LPWSTR pszInfFilename, LPWSTR pszTranslateSection, LPWSTR pszTranslateKey, LPWSTR pszBuffer, DWORD dwBufferSize, DWORD * pdwRequiredSize, void * pvReserved);
HRESULT CloseINFEngine(void * hInf);
HRESULT ExtractFilesA(LPSTR pszCabName, LPSTR pszExpandDir, DWORD dwFlags, LPSTR pszFileList, void * lpReserved, DWORD dwReserved);
HRESULT ExtractFilesW(LPWSTR pszCabName, LPWSTR pszExpandDir, DWORD dwFlags, LPWSTR pszFileList, void * lpReserved, DWORD dwReserved);
LONG LaunchINFSectionW(HWND hwndOwner, HINSTANCE hInstance, LPWSTR pszParams, LONG nShow);
HRESULT UserInstStubWrapperA(HWND hwnd, HINSTANCE hInstance, LPSTR pszParms, LONG nShow);
HRESULT UserInstStubWrapperW(HWND hwnd, HINSTANCE hInstance, LPWSTR pszParms, LONG nShow);
HRESULT UserUnInstStubWrapperA(HWND hwnd, HINSTANCE hInstance, LPSTR pszParms, LONG nShow);
HRESULT UserUnInstStubWrapperW(HWND hwnd, HINSTANCE hInstance, LPWSTR pszParms, LONG nShow);
HRESULT SetPerUserSecValuesA(PERUSERSECTIONA * pPerUser);
HRESULT SetPerUserSecValuesW(PERUSERSECTIONW * pPerUser);
LRESULT SendIMEMessageExA(HWND param0, LPARAM param1);
LRESULT SendIMEMessageExW(HWND param0, LPARAM param1);
BOOL IMPGetIMEA(HWND param0, IMEPROA * param1);
BOOL IMPGetIMEW(HWND param0, IMEPROW * param1);
BOOL IMPQueryIMEA(IMEPROA * param0);
BOOL IMPQueryIMEW(IMEPROW * param0);
BOOL IMPSetIMEA(HWND param0, IMEPROA * param1);
BOOL IMPSetIMEW(HWND param0, IMEPROW * param1);
DWORD WINNLSGetIMEHotkey(HWND param0);
BOOL WINNLSEnableIME(HWND param0, BOOL param1);
BOOL WINNLSGetEnableStatus(HWND param0);
BOOL ApphelpCheckShellObject(Guid * ObjectCLSID, BOOL bShimIfNecessary, ULONGLONG * pullFlags);
HRESULT WldpGetLockdownPolicy(WLDP_HOST_INFORMATION * hostInformation, DWORD * lockdownState, DWORD lockdownFlags);
HRESULT WldpIsClassInApprovedList(Guid * classID, WLDP_HOST_INFORMATION * hostInformation, BOOL * isApproved, DWORD optionalFlags);
HRESULT WldpSetDynamicCodeTrust(HANDLE fileHandle);
HRESULT WldpIsDynamicCodePolicyEnabled(BOOL * isEnabled);
HRESULT WldpQueryDynamicCodeTrust(HANDLE fileHandle, void * baseImage, DWORD imageSize);
HRESULT WldpQueryDeviceSecurityInformation(WLDP_DEVICE_SECURITY_INFORMATION * information, DWORD informationLength, DWORD * returnLength);
HRESULT WldpCanExecuteFile(Guid * host, WLDP_EXECUTION_EVALUATION_OPTIONS options, HANDLE fileHandle, LPWSTR auditInfo, WLDP_EXECUTION_POLICY * result);
HRESULT WldpCanExecuteBuffer(Guid * host, WLDP_EXECUTION_EVALUATION_OPTIONS options, BYTE * buffer, DWORD bufferSize, LPWSTR auditInfo, WLDP_EXECUTION_POLICY * result);
HRESULT WldpCanExecuteStream(Guid * host, WLDP_EXECUTION_EVALUATION_OPTIONS options, IStream stream, LPWSTR auditInfo, WLDP_EXECUTION_POLICY * result);
]]

return {
    AADBE_ADD_ENTRY = 0x00000001,
    AADBE_DEL_ENTRY = 0x00000002,
    AC_LINE_BACKUP_POWER = 0x00000002,
    AC_LINE_OFFLINE = 0x00000000,
    AC_LINE_ONLINE = 0x00000001,
    AC_LINE_UNKNOWN = 0x000000FF,
    ACTCTX_FLAG_APPLICATION_NAME_VALID = 0x00000020,
    ACTCTX_FLAG_ASSEMBLY_DIRECTORY_VALID = 0x00000004,
    ACTCTX_FLAG_HMODULE_VALID = 0x00000080,
    ACTCTX_FLAG_LANGID_VALID = 0x00000002,
    ACTCTX_FLAG_PROCESSOR_ARCHITECTURE_VALID = 0x00000001,
    ACTCTX_FLAG_RESOURCE_NAME_VALID = 0x00000008,
    ACTCTX_FLAG_SET_PROCESS_DEFAULT = 0x00000010,
    ACTCTX_FLAG_SOURCE_IS_ASSEMBLYREF = 0x00000040,
    ACTIVATION_CONTEXT_BASIC_INFORMATION_DEFINED = 0x00000001,
    ADN_DEL_IF_EMPTY = 0x00000001,
    ADN_DEL_UNC_PATHS = 0x00000008,
    ADN_DONT_DEL_DIR = 0x00000004,
    ADN_DONT_DEL_SUBDIRS = 0x00000002,
    AFSR_BACKNEW = 0x00000002,
    AFSR_EXTRAINCREFCNT = 0x00000800,
    AFSR_NODELETENEW = 0x00000004,
    AFSR_NOMESSAGES = 0x00000008,
    AFSR_NOPROGRESS = 0x00000010,
    AFSR_RESTORE = 0x00000001,
    AFSR_UPDREFCNT = 0x00000200,
    AFSR_USEREFCNT = 0x00000400,
    AIF_FORCE_FILE_IN_USE = 0x00000008,
    AIF_NO_VERSION_DIALOG = 0x00000020,
    AIF_NOLANGUAGECHECK = 0x10000000,
    AIF_NOOVERWRITE = 0x00000010,
    AIF_NOSKIP = 0x00000002,
    AIF_NOVERSIONCHECK = 0x00000004,
    AIF_QUIET = 0x20000000,
    AIF_REPLACEONLY = 0x00000400,
    AIF_WARNIFSKIP = 0x00000001,
    ALINF_BKINSTALL = 0x00000020,
    ALINF_CHECKBKDATA = 0x00000080,
    ALINF_DELAYREGISTEROCX = 0x00000200,
    ALINF_NGCONV = 0x00000008,
    ALINF_QUIET = 0x00000004,
    ALINF_ROLLBACK = 0x00000040,
    ALINF_ROLLBKDOALL = 0x00000100,
    ALINF_UPDHLPDLLS = 0x00000010,
    ARSR_NOMESSAGES = 0x00000008,
    ARSR_REGSECTION = 0x00000080,
    ARSR_REMOVREGBKDATA = 0x00001000,
    ARSR_RESTORE = 0x00000001,
    AT_ARP = 0x00000280,
    AT_NULL = 0x00000282,
    ATOM_FLAG_GLOBAL = 0x00000002,
    BACKUP_GHOSTED_FILE_EXTENTS = 0x0000000B,
    BACKUP_INVALID = 0x00000000,
    BASE_SEARCH_PATH_DISABLE_SAFE_SEARCHMODE = 0x00010000,
    BASE_SEARCH_PATH_ENABLE_SAFE_SEARCHMODE = 0x00000001,
    BASE_SEARCH_PATH_PERMANENT = 0x00008000,
    BATTERY_FLAG_CHARGING = 0x00000008,
    BATTERY_FLAG_CRITICAL = 0x00000004,
    BATTERY_FLAG_HIGH = 0x00000001,
    BATTERY_FLAG_LOW = 0x00000002,
    BATTERY_FLAG_NO_BATTERY = 0x00000080,
    BATTERY_FLAG_UNKNOWN = 0x000000FF,
    BATTERY_LIFE_UNKNOWN = 0xFFFFFFFF,
    BATTERY_PERCENTAGE_UNKNOWN = 0x000000FF,
    BAUD_075 = 0x00000001,
    BAUD_110 = 0x00000002,
    BAUD_115200 = 0x00020000,
    BAUD_1200 = 0x00000040,
    BAUD_128K = 0x00010000,
    BAUD_134_5 = 0x00000004,
    BAUD_14400 = 0x00001000,
    BAUD_150 = 0x00000008,
    BAUD_1800 = 0x00000080,
    BAUD_19200 = 0x00002000,
    BAUD_2400 = 0x00000100,
    BAUD_300 = 0x00000010,
    BAUD_38400 = 0x00004000,
    BAUD_4800 = 0x00000200,
    BAUD_56K = 0x00008000,
    BAUD_57600 = 0x00040000,
    BAUD_600 = 0x00000020,
    BAUD_7200 = 0x00000400,
    BAUD_9600 = 0x00000800,
    BAUD_USER = 0x10000000,
    CBR_110 = 0x0000006E,
    CBR_115200 = 0x0001C200,
    CBR_1200 = 0x000004B0,
    CBR_128000 = 0x0001F400,
    CBR_14400 = 0x00003840,
    CBR_19200 = 0x00004B00,
    CBR_2400 = 0x00000960,
    CBR_256000 = 0x0003E800,
    CBR_300 = 0x0000012C,
    CBR_38400 = 0x00009600,
    CBR_4800 = 0x000012C0,
    CBR_56000 = 0x0000DAC0,
    CBR_57600 = 0x0000E100,
    CBR_600 = 0x00000258,
    CBR_9600 = 0x00002580,
    CE_DNS = 0x00000800,
    CE_IOE = 0x00000400,
    CE_MODE = 0x00008000,
    CE_OOP = 0x00001000,
    CE_PTO = 0x00000200,
    CE_TXFULL = 0x00000100,
    CL_NL_IP = 0x00000303,
    CL_NL_IPX = 0x00000301,
    CL_TL_NBF = 0x00000401,
    CL_TL_UDP = 0x00000403,
    CO_TL_NBF = 0x00000400,
    CO_TL_SPP = 0x00000406,
    CO_TL_SPX = 0x00000402,
    CO_TL_TCP = 0x00000404,
    CODEINTEGRITY_OPTION_DEBUGMODE_ENABLED = 0x00000080,
    CODEINTEGRITY_OPTION_ENABLED = 0x00000001,
    CODEINTEGRITY_OPTION_FLIGHT_BUILD = 0x00000100,
    CODEINTEGRITY_OPTION_FLIGHTING_ENABLED = 0x00000200,
    CODEINTEGRITY_OPTION_HVCI_IUM_ENABLED = 0x00002000,
    CODEINTEGRITY_OPTION_HVCI_KMCI_AUDITMODE_ENABLED = 0x00000800,
    CODEINTEGRITY_OPTION_HVCI_KMCI_ENABLED = 0x00000400,
    CODEINTEGRITY_OPTION_HVCI_KMCI_STRICTMODE_ENABLED = 0x00001000,
    CODEINTEGRITY_OPTION_PREPRODUCTION_BUILD = 0x00000040,
    CODEINTEGRITY_OPTION_TEST_BUILD = 0x00000020,
    CODEINTEGRITY_OPTION_TESTSIGN = 0x00000002,
    CODEINTEGRITY_OPTION_UMCI_AUDITMODE_ENABLED = 0x00000008,
    CODEINTEGRITY_OPTION_UMCI_ENABLED = 0x00000004,
    CODEINTEGRITY_OPTION_UMCI_EXCLUSIONPATHS_ENABLED = 0x00000010,
    COMMPROP_INITIALIZED = 0xE73CF52E,
    CONTEXT_SIZE = 0x00000010,
    CP_DIRECT = 0x00000002,
    CP_HWND = 0x00000000,
    CP_LEVEL = 0x00000003,
    CP_OPEN = 0x00000001,
    CREATE_FOR_DIR = 0x00000002,
    CREATE_FOR_IMPORT = 0x00000001,
    CRITICAL_SECTION_NO_DEBUG_INFO = 0x01000000,
    DCI_1632_ACCESS = 0x00000040,
    DCI_ASYNC = 0x00000400,
    DCI_CAN_STRETCHX = 0x00001000,
    DCI_CAN_STRETCHXN = 0x00004000,
    DCI_CAN_STRETCHY = 0x00002000,
    DCI_CAN_STRETCHYN = 0x00008000,
    DCI_CANOVERLAY = 0x00010000,
    DCI_CHROMAKEY = 0x00000020,
    DCI_DWORDALIGN = 0x00000100,
    DCI_DWORDSIZE = 0x00000080,
    DCI_ERR_CURRENTLYNOTAVAIL = -5,
    DCI_ERR_HEIGHTALIGN = -21,
    DCI_ERR_INVALIDCLIPLIST = -15,
    DCI_ERR_INVALIDPOSITION = -13,
    DCI_ERR_INVALIDRECT = -6,
    DCI_ERR_INVALIDSTRETCH = -14,
    DCI_ERR_OUTOFMEMORY = -12,
    DCI_ERR_SURFACEISOBSCURED = -16,
    DCI_ERR_TOOBIGHEIGHT = -9,
    DCI_ERR_TOOBIGSIZE = -11,
    DCI_ERR_TOOBIGWIDTH = -10,
    DCI_ERR_UNSUPPORTEDFORMAT = -7,
    DCI_ERR_UNSUPPORTEDMASK = -8,
    DCI_ERR_WIDTHALIGN = -20,
    DCI_ERR_XALIGN = -17,
    DCI_ERR_XYALIGN = -19,
    DCI_ERR_YALIGN = -18,
    DCI_FAIL_GENERIC = -1,
    DCI_FAIL_INVALIDSURFACE = -3,
    DCI_FAIL_UNSUPPORTED = -4,
    DCI_FAIL_UNSUPPORTEDVERSION = -2,
    DCI_OFFSCREEN = 0x00000001,
    DCI_OK = 0x00000000,
    DCI_OVERLAY = 0x00000002,
    DCI_PRIMARY = 0x00000000,
    DCI_STATUS_CHROMAKEYCHANGED = 0x00000010,
    DCI_STATUS_FORMATCHANGED = 0x00000004,
    DCI_STATUS_POINTERCHANGED = 0x00000001,
    DCI_STATUS_STRIDECHANGED = 0x00000002,
    DCI_STATUS_SURFACEINFOCHANGED = 0x00000008,
    DCI_STATUS_WASSTILLDRAWING = 0x00000020,
    DCI_SURFACE_TYPE = 0x0000000F,
    DCI_VERSION = 0x00000100,
    DCI_VISIBLE = 0x00000010,
    DCI_WRITEONLY = 0x00000200,
    DCICREATEOFFSCREENSURFACE = 0x00000002,
    DCICREATEOVERLAYSURFACE = 0x00000003,
    DCICREATEPRIMARYSURFACE = 0x00000001,
    DCIENUMSURFACE = 0x00000004,
    DCIESCAPE = 0x00000005,
    DEACTIVATE_ACTCTX_FLAG_FORCE_EARLY_DEACTIVATION = 0x00000001,
    DELAYLOAD_GPA_FAILURE = 0x00000004,
    DELETE_BROWSING_HISTORY_COOKIES = 0x00000002,
    DELETE_BROWSING_HISTORY_DOWNLOADHISTORY = 0x00000040,
    DELETE_BROWSING_HISTORY_FORMDATA = 0x00000008,
    DELETE_BROWSING_HISTORY_HISTORY = 0x00000001,
    DELETE_BROWSING_HISTORY_PASSWORDS = 0x00000010,
    DELETE_BROWSING_HISTORY_PRESERVEFAVORITES = 0x00000020,
    DELETE_BROWSING_HISTORY_TIF = 0x00000004,
    DOCKINFO_DOCKED = 0x00000002,
    DOCKINFO_UNDOCKED = 0x00000001,
    DOCKINFO_USER_SUPPLIED = 0x00000004,
    DRIVE_CDROM = 0x00000005,
    DRIVE_FIXED = 0x00000003,
    DRIVE_NO_ROOT_DIR = 0x00000001,
    DRIVE_RAMDISK = 0x00000006,
    DRIVE_REMOTE = 0x00000004,
    DRIVE_REMOVABLE = 0x00000002,
    DRIVE_UNKNOWN = 0x00000000,
    DTR_CONTROL_DISABLE = 0x00000000,
    DTR_CONTROL_ENABLE = 0x00000001,
    DTR_CONTROL_HANDSHAKE = 0x00000002,
    EFS_DROP_ALTERNATE_STREAMS = 0x00000010,
    EFS_USE_RECOVERY_KEYS = 0x00000001,
    EFSRPC_SECURE_ONLY = 0x00000008,
    ENTITY_LIST_ID = 0x00000000,
    ENTITY_TYPE_ID = 0x00000001,
    ER_ICMP = 0x00000380,
    EVENTLOG_FULL_INFO = 0x00000000,
    FAIL_FAST_GENERATE_EXCEPTION_ADDRESS = 0x00000001,
    FAIL_FAST_NO_HARD_ERROR_DLG = 0x00000002,
    FIBER_FLAG_FLOAT_SWITCH = 0x00000001,
    FILE_CREATED = 0x00000002,
    FILE_DIR_DISALLOWED = 0x00000009,
    FILE_DOES_NOT_EXIST = 0x00000005,
    FILE_ENCRYPTABLE = 0x00000000,
    FILE_EXISTS = 0x00000004,
    FILE_FLAG_IGNORE_IMPERSONATED_DEVICEMAP = 0x00020000,
    FILE_FLAG_OPEN_REQUIRING_OPLOCK = 0x00040000,
    FILE_IS_ENCRYPTED = 0x00000001,
    FILE_MAXIMUM_DISPOSITION = 0x00000005,
    FILE_NO_COMPRESSION = 0x00008000,
    FILE_OPEN_NO_RECALL = 0x00400000,
    FILE_OPEN_REMOTE_INSTANCE = 0x00000400,
    FILE_OPENED = 0x00000001,
    FILE_OVERWRITTEN = 0x00000003,
    FILE_READ_ONLY = 0x00000008,
    FILE_RENAME_FLAG_POSIX_SEMANTICS = 0x00000002,
    FILE_RENAME_FLAG_REPLACE_IF_EXISTS = 0x00000001,
    FILE_RENAME_FLAG_SUPPRESS_PIN_STATE_INHERITANCE = 0x00000004,
    FILE_ROOT_DIR = 0x00000003,
    FILE_SKIP_COMPLETION_PORT_ON_SUCCESS = 0x00000001,
    FILE_SKIP_SET_EVENT_ON_HANDLE = 0x00000002,
    FILE_SUPERSEDED = 0x00000000,
    FILE_SYSTEM_ATTR = 0x00000002,
    FILE_SYSTEM_DIR = 0x00000004,
    FILE_SYSTEM_NOT_SUPPORT = 0x00000006,
    FILE_UNKNOWN = 0x00000005,
    FILE_USER_DISALLOWED = 0x00000007,
    FILE_VALID_MAILSLOT_OPTION_FLAGS = 0x00000032,
    FILE_VALID_OPTION_FLAGS = 0x00FFFFFF,
    FILE_VALID_PIPE_OPTION_FLAGS = 0x00000032,
    FILE_VALID_SET_FLAGS = 0x00000036,
    FIND_ACTCTX_SECTION_KEY_RETURN_ASSEMBLY_METADATA = 0x00000004,
    FIND_ACTCTX_SECTION_KEY_RETURN_FLAGS = 0x00000002,
    FIND_ACTCTX_SECTION_KEY_RETURN_HACTCTX = 0x00000001,
    FORMAT_MESSAGE_MAX_WIDTH_MASK = 0x000000FF,
    FS_CASE_IS_PRESERVED = 0x00000002,
    FS_CASE_SENSITIVE = 0x00000001,
    FS_FILE_COMPRESSION = 0x00000010,
    FS_FILE_ENCRYPTION = 0x00020000,
    FS_PERSISTENT_ACLS = 0x00000008,
    FS_UNICODE_STORED_ON_DISK = 0x00000004,
    FS_VOL_IS_COMPRESSED = 0x00008000,
    GET_SYSTEM_WOW64_DIRECTORY_NAME_A_A = "GetSystemWow64DirectoryA",
    GET_SYSTEM_WOW64_DIRECTORY_NAME_A_T = "GetSystemWow64DirectoryA",
    GET_SYSTEM_WOW64_DIRECTORY_NAME_A_W = "GetSystemWow64DirectoryA",
    GET_SYSTEM_WOW64_DIRECTORY_NAME_T_A = "GetSystemWow64DirectoryW",
    GET_SYSTEM_WOW64_DIRECTORY_NAME_T_T = "GetSystemWow64DirectoryW",
    GET_SYSTEM_WOW64_DIRECTORY_NAME_T_W = "GetSystemWow64DirectoryW",
    GET_SYSTEM_WOW64_DIRECTORY_NAME_W_A = "GetSystemWow64DirectoryW",
    GET_SYSTEM_WOW64_DIRECTORY_NAME_W_T = "GetSystemWow64DirectoryW",
    GET_SYSTEM_WOW64_DIRECTORY_NAME_W_W = "GetSystemWow64DirectoryW",
    GMEM_DDESHARE = 0x00002000,
    GMEM_DISCARDABLE = 0x00000100,
    GMEM_DISCARDED = 0x00004000,
    GMEM_INVALID_HANDLE = 0x00008000,
    GMEM_LOCKCOUNT = 0x000000FF,
    GMEM_LOWER = 0x00001000,
    GMEM_MODIFY = 0x00000080,
    GMEM_NOCOMPACT = 0x00000010,
    GMEM_NODISCARD = 0x00000020,
    GMEM_NOT_BANKED = 0x00001000,
    GMEM_NOTIFY = 0x00004000,
    GMEM_SHARE = 0x00002000,
    GMEM_VALID_FLAGS = 0x00007F72,
    HANJA_WINDOW = 0x00000002,
    HINSTANCE_ERROR = 0x00000020,
    HW_PROFILE_GUIDLEN = 0x00000027,
    IE_BADID = -1,
    IE_BAUDRATE = -12,
    IE_BYTESIZE = -11,
    IE_DEFAULT = -5,
    IE_HARDWARE = -10,
    IE_MEMORY = -4,
    IE_NOPEN = -3,
    IE_OPEN = -2,
    IE4_BACKNEW = 0x00000002,
    IE4_EXTRAINCREFCNT = 0x00000800,
    IE4_FRDOALL = 0x00000100,
    IE4_NO_CRC_MAPPING = 0x00000040,
    IE4_NODELETENEW = 0x00000004,
    IE4_NOENUMKEY = 0x00000020,
    IE4_NOMESSAGES = 0x00000008,
    IE4_NOPROGRESS = 0x00000010,
    IE4_REGSECTION = 0x00000080,
    IE4_REMOVREGBKDATA = 0x00001000,
    IE4_RESTORE = 0x00000001,
    IE4_UPDREFCNT = 0x00000200,
    IE4_USEREFCNT = 0x00000400,
    IF_GENERIC = 0x00000200,
    IF_MIB = 0x00000202,
    IGNORE = 0x00000000,
    IME_BANJAtoJUNJA = 0x00000013,
    IME_ENABLE_CONVERT = 0x00000002,
    IME_ENTERWORDREGISTERMODE = 0x00000018,
    IME_GETCONVERSIONMODE = 0x00000011,
    IME_GETIMECAPS = 0x00000003,
    IME_GETOPEN = 0x00000005,
    IME_GETVERSION = 0x00000007,
    IME_JOHABtoKS = 0x00000015,
    IME_JUNJAtoBANJA = 0x00000014,
    IME_KStoJOHAB = 0x00000016,
    IME_MAXPROCESS = 0x00000020,
    IME_MODE_ALPHANUMERIC = 0x00000001,
    IME_MODE_CODEINPUT = 0x00000080,
    IME_MODE_DBCSCHAR = 0x00000010,
    IME_MODE_HANJACONVERT = 0x00000004,
    IME_MODE_HIRAGANA = 0x00000004,
    IME_MODE_KATAKANA = 0x00000002,
    IME_MODE_NOCODEINPUT = 0x00000100,
    IME_MODE_NOROMAN = 0x00000040,
    IME_MODE_ROMAN = 0x00000020,
    IME_MODE_SBCSCHAR = 0x00000002,
    IME_MOVEIMEWINDOW = 0x00000008,
    IME_REQUEST_CONVERT = 0x00000001,
    IME_RS_DISKERROR = 0x0000000E,
    IME_RS_ERROR = 0x00000001,
    IME_RS_ILLEGAL = 0x00000006,
    IME_RS_INVALID = 0x00000011,
    IME_RS_NEST = 0x00000012,
    IME_RS_NOIME = 0x00000002,
    IME_RS_NOROOM = 0x0000000A,
    IME_RS_NOTFOUND = 0x00000007,
    IME_RS_SYSTEMMODAL = 0x00000013,
    IME_RS_TOOLONG = 0x00000005,
    IME_SENDVKEY = 0x00000013,
    IME_SET_MODE = 0x00000012,
    IME_SETCONVERSIONFONTEX = 0x00000019,
    IME_SETCONVERSIONMODE = 0x00000010,
    IME_SETCONVERSIONWINDOW = 0x00000008,
    IME_SETOPEN = 0x00000004,
    IMEA_INIT = 0x00000001,
    IMEA_NEXT = 0x00000002,
    IMEA_PREV = 0x00000003,
    INFO_CLASS_GENERIC = 0x00000100,
    INFO_CLASS_IMPLEMENTATION = 0x00000300,
    INFO_CLASS_PROTOCOL = 0x00000200,
    INFO_TYPE_ADDRESS_OBJECT = 0x00000200,
    INFO_TYPE_CONNECTION = 0x00000300,
    INFO_TYPE_PROVIDER = 0x00000100,
    INTERIM_WINDOW = 0x00000000,
    INVALID_ENTITY_INSTANCE = -1,
    IOCTL_TDI_TL_IO_CONTROL_ENDPOINT = 0x00210038,
    IR_CHANGECONVERT = 0x00000121,
    IR_CLOSECONVERT = 0x00000122,
    IR_DBCSCHAR = 0x00000160,
    IR_FULLCONVERT = 0x00000123,
    IR_IMESELECT = 0x00000130,
    IR_MODEINFO = 0x00000190,
    IR_OPENCONVERT = 0x00000120,
    IR_STRING = 0x00000140,
    IR_STRINGEND = 0x00000101,
    IR_STRINGEX = 0x00000180,
    IR_STRINGSTART = 0x00000100,
    IR_UNDETERMINE = 0x00000170,
    LIS_NOGRPCONV = 0x00000002,
    LIS_QUIET = 0x00000001,
    LOGON_ZERO_PASSWORD_BUFFER = 0x80000000,
    LOGON32_PROVIDER_VIRTUAL = 0x00000004,
    LOGON32_PROVIDER_WINNT35 = 0x00000001,
    LPTx = 0x00000080,
    MAX_COMPUTERNAME_LENGTH = 0x0000000F,
    MAX_TDI_ENTITIES = 0x00001000,
    MAXINTATOM = 0x0000C000,
    MCW_DEFAULT = 0x00000000,
    MCW_HIDDEN = 0x00000010,
    MCW_RECT = 0x00000001,
    MCW_SCREEN = 0x00000004,
    MCW_VERTICAL = 0x00000008,
    MCW_WINDOW = 0x00000002,
    MICROSOFT_WINBASE_H_DEFINE_INTERLOCKED_CPLUSPLUS_OVERLOADS = 0x00000000,
    MICROSOFT_WINDOWS_WINBASE_H_DEFINE_INTERLOCKED_CPLUSPLUS_OVERLOADS = 0x00000000,
    MODE_WINDOW = 0x00000001,
    OFS_MAXPATHNAME = 0x00000080,
    OPERATION_API_VERSION = 0x00000001,
    OVERWRITE_HIDDEN = 0x00000004,
    PCF_16BITMODE = 0x00000200,
    PCF_DTRDSR = 0x00000001,
    PCF_INTTIMEOUTS = 0x00000080,
    PCF_PARITY_CHECK = 0x00000008,
    PCF_RLSD = 0x00000004,
    PCF_RTSCTS = 0x00000002,
    PCF_SETXCHAR = 0x00000020,
    PCF_SPECIALCHARS = 0x00000100,
    PCF_TOTALTIMEOUTS = 0x00000040,
    PCF_XONXOFF = 0x00000010,
    PROC_THREAD_ATTRIBUTE_ADDITIVE = 0x00040000,
    PROC_THREAD_ATTRIBUTE_INPUT = 0x00020000,
    PROC_THREAD_ATTRIBUTE_NUMBER = 0x0000FFFF,
    PROC_THREAD_ATTRIBUTE_THREAD = 0x00010000,
    PROCESS_CREATION_ALL_APPLICATION_PACKAGES_OPT_OUT = 0x00000001,
    PROCESS_CREATION_CHILD_PROCESS_OVERRIDE = 0x00000002,
    PROCESS_CREATION_CHILD_PROCESS_RESTRICTED = 0x00000001,
    PROCESS_CREATION_CHILD_PROCESS_RESTRICTED_UNLESS_SECURE = 0x00000004,
    PROCESS_CREATION_DESKTOP_APP_BREAKAWAY_DISABLE_PROCESS_TREE = 0x00000002,
    PROCESS_CREATION_DESKTOP_APP_BREAKAWAY_ENABLE_PROCESS_TREE = 0x00000001,
    PROCESS_CREATION_DESKTOP_APP_BREAKAWAY_OVERRIDE = 0x00000004,
    PROCESS_CREATION_MITIGATION_POLICY_DEP_ATL_THUNK_ENABLE = 0x00000002,
    PROCESS_CREATION_MITIGATION_POLICY_DEP_ENABLE = 0x00000001,
    PROCESS_CREATION_MITIGATION_POLICY_SEHOP_ENABLE = 0x00000004,
    PROTECTION_LEVEL_SAME = 0xFFFFFFFF,
    PST_FAX = 0x00000021,
    PST_LAT = 0x00000101,
    PST_MODEM = 0x00000006,
    PST_NETWORK_BRIDGE = 0x00000100,
    PST_PARALLELPORT = 0x00000002,
    PST_RS232 = 0x00000001,
    PST_RS422 = 0x00000003,
    PST_RS423 = 0x00000004,
    PST_RS449 = 0x00000005,
    PST_SCANNER = 0x00000022,
    PST_TCPIP_TELNET = 0x00000102,
    PST_UNSPECIFIED = 0x00000000,
    PST_X25 = 0x00000103,
    QUERY_ACTCTX_FLAG_ACTCTX_IS_ADDRESS = 0x00000010,
    QUERY_ACTCTX_FLAG_ACTCTX_IS_HMODULE = 0x00000008,
    QUERY_ACTCTX_FLAG_NO_ADDREF = 0x80000000,
    QUERY_ACTCTX_FLAG_USE_ACTIVE_ACTCTX = 0x00000004,
    RECOVERY_DEFAULT_PING_INTERVAL = 0x00001388,
    REG_RESTORE_LOG_KEY = "RegRestoreLogFile",
    REG_SAVE_LOG_KEY = "RegSaveLogFile",
    REMOTE_PROTOCOL_INFO_FLAG_LOOPBACK = 0x00000001,
    REMOTE_PROTOCOL_INFO_FLAG_OFFLINE = 0x00000002,
    REMOTE_PROTOCOL_INFO_FLAG_PERSISTENT_HANDLE = 0x00000004,
    RESETDEV = 0x00000007,
    RESTART_MAX_CMD_LINE = 0x00000400,
    RPI_FLAG_SMB2_SHARECAP_CLUSTER = 0x00000040,
    RPI_FLAG_SMB2_SHARECAP_CONTINUOUS_AVAILABILITY = 0x00000010,
    RPI_FLAG_SMB2_SHARECAP_DFS = 0x00000008,
    RPI_FLAG_SMB2_SHARECAP_SCALEOUT = 0x00000020,
    RPI_FLAG_SMB2_SHARECAP_TIMEWARP = 0x00000002,
    RPI_SMB2_FLAG_SERVERCAP_DFS = 0x00000001,
    RPI_SMB2_FLAG_SERVERCAP_DIRECTORY_LEASING = 0x00000020,
    RPI_SMB2_FLAG_SERVERCAP_LARGEMTU = 0x00000004,
    RPI_SMB2_FLAG_SERVERCAP_LEASING = 0x00000002,
    RPI_SMB2_FLAG_SERVERCAP_MULTICHANNEL = 0x00000008,
    RPI_SMB2_FLAG_SERVERCAP_PERSISTENT_HANDLES = 0x00000010,
    RPI_SMB2_SHAREFLAG_COMPRESS_DATA = 0x00000002,
    RPI_SMB2_SHAREFLAG_ENCRYPT_DATA = 0x00000001,
    RSC_FLAG_DELAYREGISTEROCX = 0x00000200,
    RSC_FLAG_INF = 0x00000001,
    RSC_FLAG_NGCONV = 0x00000008,
    RSC_FLAG_QUIET = 0x00000004,
    RSC_FLAG_SETUPAPI = 0x00000400,
    RSC_FLAG_SKIPDISKSPACECHECK = 0x00000002,
    RSC_FLAG_UPDHLPDLLS = 0x00000010,
    RTS_CONTROL_DISABLE = 0x00000000,
    RTS_CONTROL_ENABLE = 0x00000001,
    RTS_CONTROL_HANDSHAKE = 0x00000002,
    RTS_CONTROL_TOGGLE = 0x00000003,
    RUNCMDS_DELAYPOSTCMD = 0x00000004,
    RUNCMDS_NOWAIT = 0x00000002,
    RUNCMDS_QUIET = 0x00000001,
    S_ALLTHRESHOLD = 0x00000002,
    S_LEGATO = 0x00000001,
    S_NORMAL = 0x00000000,
    S_PERIOD1024 = 0x00000001,
    S_PERIOD2048 = 0x00000002,
    S_PERIOD512 = 0x00000000,
    S_PERIODVOICE = 0x00000003,
    S_QUEUEEMPTY = 0x00000000,
    S_SERBDNT = -5,
    S_SERDCC = -7,
    S_SERDDR = -14,
    S_SERDFQ = -13,
    S_SERDLN = -6,
    S_SERDMD = -10,
    S_SERDPT = -12,
    S_SERDSH = -11,
    S_SERDSR = -15,
    S_SERDST = -16,
    S_SERDTP = -8,
    S_SERDVL = -9,
    S_SERDVNA = -1,
    S_SERMACT = -3,
    S_SEROFM = -2,
    S_SERQFUL = -4,
    S_STACCATO = 0x00000002,
    S_THRESHOLD = 0x00000001,
    S_WHITE1024 = 0x00000005,
    S_WHITE2048 = 0x00000006,
    S_WHITE512 = 0x00000004,
    S_WHITEVOICE = 0x00000007,
    SCS_32BIT_BINARY = 0x00000000,
    SCS_64BIT_BINARY = 0x00000006,
    SCS_DOS_BINARY = 0x00000001,
    SCS_OS216_BINARY = 0x00000005,
    SCS_PIF_BINARY = 0x00000003,
    SCS_POSIX_BINARY = 0x00000004,
    SCS_THIS_PLATFORM_BINARY = 0x00000006,
    SCS_WOW_BINARY = 0x00000002,
    SHUTDOWN_NORETRY = 0x00000001,
    SP_BAUD = 0x00000002,
    SP_DATABITS = 0x00000004,
    SP_HANDSHAKING = 0x00000010,
    SP_PARITY = 0x00000001,
    SP_PARITY_CHECK = 0x00000020,
    SP_RLSD = 0x00000040,
    SP_SERIALCOMM = 0x00000001,
    SP_STOPBITS = 0x00000008,
    STARTF_HOLOGRAPHIC = 0x00040000,
    STORAGE_INFO_FLAGS_ALIGNED_DEVICE = 0x00000001,
    STORAGE_INFO_FLAGS_PARTITION_ALIGNED_ON_DEVICE = 0x00000002,
    STORAGE_INFO_OFFSET_UNKNOWN = 0xFFFFFFFF,
    STREAM_CONTAINS_GHOSTED_FILE_EXTENTS = 0x00000010,
    STREAM_CONTAINS_PROPERTIES = 0x00000004,
    STREAM_CONTAINS_SECURITY = 0x00000002,
    STREAM_MODIFIED_WHEN_READ = 0x00000001,
    STREAM_NORMAL_ATTRIBUTE = 0x00000000,
    STREAM_SPARSE_ATTRIBUTE = 0x00000008,
    SYSTEM_STATUS_FLAG_POWER_SAVING_ON = 0x00000001,
    TC_GP_TRAP = 0x00000002,
    TC_HARDERR = 0x00000001,
    TC_NORMAL = 0x00000000,
    TC_SIGNAL = 0x00000003,
    THREAD_PRIORITY_ERROR_RETURN = 0x7FFFFFFF,
    UMS_VERSION = 0x00000100,
    WINWATCHNOTIFY_CHANGED = 0x00000004,
    WINWATCHNOTIFY_CHANGING = 0x00000003,
    WINWATCHNOTIFY_DESTROY = 0x00000002,
    WINWATCHNOTIFY_START = 0x00000000,
    WINWATCHNOTIFY_STOP = 0x00000001,
    WLDP_CANEXECUTEBUFFER_FN = "WldpCanExecuteBuffer",
    WLDP_CANEXECUTEFILE_FN = "WldpCanExecuteFile",
    WLDP_DLL = "WLDP.DLL",
    WLDP_FLAGS_SKIPSIGNATUREVALIDATION = 0x00000100,
    WLDP_GETLOCKDOWNPOLICY_FN = "WldpGetLockdownPolicy",
    WLDP_HOST_INFORMATION_REVISION = 0x00000001,
    WLDP_ISAPPAPPROVEDBYPOLICY_FN = "WldpIsAppApprovedByPolicy",
    WLDP_ISCLASSINAPPROVEDLIST_FN = "WldpIsClassInApprovedList",
    WLDP_ISDYNAMICCODEPOLICYENABLED_FN = "WldpIsDynamicCodePolicyEnabled",
    WLDP_ISPRODUCTIONCONFIGURATION_FN = "WldpIsProductionConfiguration",
    WLDP_ISWCOSPRODUCTIONCONFIGURATION_FN = "WldpIsWcosProductionConfiguration",
    WLDP_LOCKDOWN_AUDIT_FLAG = 0x00000008,
    WLDP_LOCKDOWN_CONFIG_CI_AUDIT_FLAG = 0x00000002,
    WLDP_LOCKDOWN_CONFIG_CI_FLAG = 0x00000001,
    WLDP_LOCKDOWN_DEFINED_FLAG = 0x80000000,
    WLDP_LOCKDOWN_EXCLUSION_FLAG = 0x00000010,
    WLDP_LOCKDOWN_OFF = 0x80000000,
    WLDP_LOCKDOWN_UMCIENFORCE_FLAG = 0x00000004,
    WLDP_LOCKDOWN_UNDEFINED = 0x00000000,
    WLDP_QUERYDANAMICCODETRUST_FN = "WldpQueryDynamicCodeTrust",
    WLDP_QUERYDEVICESECURITYINFORMATION_FN = "WldpQueryDeviceSecurityInformation",
    WLDP_QUERYDYNAMICCODETRUST_FN = "WldpQueryDynamicCodeTrust",
    WLDP_QUERYPOLICYSETTINGENABLED_FN = "WldpQueryPolicySettingEnabled",
    WLDP_QUERYPOLICYSETTINGENABLED2_FN = "WldpQueryPolicySettingEnabled2",
    WLDP_QUERYWINDOWSLOCKDOWNMODE_FN = "WldpQueryWindowsLockdownMode",
    WLDP_QUERYWINDOWSLOCKDOWNRESTRICTION_FN = "WldpQueryWindowsLockdownRestriction",
    WLDP_RESETPRODUCTIONCONFIGURATION_FN = "WldpResetProductionConfiguration",
    WLDP_RESETWCOSPRODUCTIONCONFIGURATION_FN = "WldpResetWcosProductionConfiguration",
    WLDP_SETDYNAMICCODETRUST_FN = "WldpSetDynamicCodeTrust",
    WLDP_SETWINDOWSLOCKDOWNRESTRICTION_FN = "WldpSetWindowsLockdownRestriction",
    WM_CONVERTREQUEST = 0x0000010A,
    WM_CONVERTRESULT = 0x0000010B,
    WM_IME_REPORT = 0x00000280,
    WM_IMEKEYDOWN = 0x00000290,
    WM_IMEKEYUP = 0x00000291,
    WM_INTERIM = 0x0000010C,
    WM_WNT_CONVERTREQUESTEX = 0x00000109,
    -- enum CameraUIControlCaptureMode
    CameraUIControlCaptureMode_PhotoOrVideo = 0,
    CameraUIControlCaptureMode_Photo = 1,
    CameraUIControlCaptureMode_Video = 2,
    -- enum CameraUIControlLinearSelectionMode
    CameraUIControlLinearSelectionMode_Single = 0,
    CameraUIControlLinearSelectionMode_Multiple = 1,
    -- enum CameraUIControlMode
    CameraUIControlMode_Browse = 0,
    CameraUIControlMode_Linear = 1,
    -- enum CameraUIControlPhotoFormat
    CameraUIControlPhotoFormat_Jpeg = 0,
    CameraUIControlPhotoFormat_Png = 1,
    CameraUIControlPhotoFormat_JpegXR = 2,
    -- enum CameraUIControlVideoFormat
    CameraUIControlVideoFormat_Mp4 = 0,
    CameraUIControlVideoFormat_Wmv = 1,
    -- enum CameraUIControlViewType
    CameraUIControlViewType_SingleItem = 0,
    CameraUIControlViewType_ItemList = 1,
    -- enum DECISION_LOCATION
    DECISION_LOCATION_DECISION_LOCATION_REFRESH_GLOBAL_DATA = 0,
    DECISION_LOCATION_DECISION_LOCATION_PARAMETER_VALIDATION = 1,
    DECISION_LOCATION_DECISION_LOCATION_AUDIT = 2,
    DECISION_LOCATION_DECISION_LOCATION_FAILED_CONVERT_GUID = 3,
    DECISION_LOCATION_DECISION_LOCATION_ENTERPRISE_DEFINED_CLASS_ID = 4,
    DECISION_LOCATION_DECISION_LOCATION_GLOBAL_BUILT_IN_LIST = 5,
    DECISION_LOCATION_DECISION_LOCATION_PROVIDER_BUILT_IN_LIST = 6,
    DECISION_LOCATION_DECISION_LOCATION_ENFORCE_STATE_LIST = 7,
    DECISION_LOCATION_DECISION_LOCATION_NOT_FOUND = 8,
    DECISION_LOCATION_DECISION_LOCATION_UNKNOWN = 9,
    -- enum FEATURE_CHANGE_TIME
    FEATURE_CHANGE_TIME_FEATURE_CHANGE_TIME_READ = 0,
    FEATURE_CHANGE_TIME_FEATURE_CHANGE_TIME_MODULE_RELOAD = 1,
    FEATURE_CHANGE_TIME_FEATURE_CHANGE_TIME_SESSION = 2,
    FEATURE_CHANGE_TIME_FEATURE_CHANGE_TIME_REBOOT = 3,
    -- enum FEATURE_ENABLED_STATE
    FEATURE_ENABLED_STATE_FEATURE_ENABLED_STATE_DEFAULT = 0,
    FEATURE_ENABLED_STATE_FEATURE_ENABLED_STATE_DISABLED = 1,
    FEATURE_ENABLED_STATE_FEATURE_ENABLED_STATE_ENABLED = 2,
    -- enum TDI_TL_IO_CONTROL_TYPE
    TDI_TL_IO_CONTROL_TYPE_EndpointIoControlType = 0,
    TDI_TL_IO_CONTROL_TYPE_SetSockOptIoControlType = 1,
    TDI_TL_IO_CONTROL_TYPE_GetSockOptIoControlType = 2,
    TDI_TL_IO_CONTROL_TYPE_SocketIoControlType = 3,
    -- enum TDIENTITY_ENTITY_TYPE
    TDIENTITY_ENTITY_TYPE_GENERIC_ENTITY = 0x00000000,
    TDIENTITY_ENTITY_TYPE_AT_ENTITY = 0x00000280,
    TDIENTITY_ENTITY_TYPE_CL_NL_ENTITY = 0x00000301,
    TDIENTITY_ENTITY_TYPE_CO_NL_ENTITY = 0x00000300,
    TDIENTITY_ENTITY_TYPE_CL_TL_ENTITY = 0x00000401,
    TDIENTITY_ENTITY_TYPE_CO_TL_ENTITY = 0x00000400,
    TDIENTITY_ENTITY_TYPE_ER_ENTITY = 0x00000380,
    TDIENTITY_ENTITY_TYPE_IF_ENTITY = 0x00000200,
    -- enum VALUENAME
    VALUENAME_VALUENAME_UNKNOWN = 0,
    VALUENAME_VALUENAME_ENTERPRISE_DEFINED_CLASS_ID = 1,
    VALUENAME_VALUENAME_BUILT_IN_LIST = 2,
    -- enum WINSTATIONINFOCLASS
    WINSTATIONINFOCLASS_WinStationInformation = 8,
    -- enum WLDP_EXECUTION_EVALUATION_OPTIONS
    WLDP_EXECUTION_EVALUATION_OPTIONS_WLDP_EXECUTION_EVALUATION_OPTION_NONE = 0,
    WLDP_EXECUTION_EVALUATION_OPTIONS_WLDP_EXECUTION_EVALUATION_OPTION_EXECUTE_IN_INTERACTIVE_SESSION = 1,
    -- enum WLDP_EXECUTION_POLICY
    WLDP_EXECUTION_POLICY_WLDP_EXECUTION_POLICY_BLOCKED = 0,
    WLDP_EXECUTION_POLICY_WLDP_EXECUTION_POLICY_ALLOWED = 1,
    WLDP_EXECUTION_POLICY_WLDP_EXECUTION_POLICY_REQUIRE_SANDBOX = 2,
    -- enum WLDP_HOST
    WLDP_HOST_WLDP_HOST_RUNDLL32 = 0,
    WLDP_HOST_WLDP_HOST_SVCHOST = 1,
    WLDP_HOST_WLDP_HOST_MAX = 2,
    -- enum WLDP_HOST_ID
    WLDP_HOST_ID_WLDP_HOST_ID_UNKNOWN = 0,
    WLDP_HOST_ID_WLDP_HOST_ID_GLOBAL = 1,
    WLDP_HOST_ID_WLDP_HOST_ID_VBA = 2,
    WLDP_HOST_ID_WLDP_HOST_ID_WSH = 3,
    WLDP_HOST_ID_WLDP_HOST_ID_POWERSHELL = 4,
    WLDP_HOST_ID_WLDP_HOST_ID_IE = 5,
    WLDP_HOST_ID_WLDP_HOST_ID_MSI = 6,
    WLDP_HOST_ID_WLDP_HOST_ID_ALL = 7,
    WLDP_HOST_ID_WLDP_HOST_ID_MAX = 8,
    -- enum WLDP_KEY
    WLDP_KEY_KEY_UNKNOWN = 0,
    WLDP_KEY_KEY_OVERRIDE = 1,
    WLDP_KEY_KEY_ALL_KEYS = 2,
    -- enum WLDP_POLICY_SETTING
    WLDP_POLICY_SETTING_WLDP_POLICY_SETTING_AV_PERF_MODE = 1000,
    -- enum WLDP_WINDOWS_LOCKDOWN_MODE
    WLDP_WINDOWS_LOCKDOWN_MODE_WLDP_WINDOWS_LOCKDOWN_MODE_UNLOCKED = 0,
    WLDP_WINDOWS_LOCKDOWN_MODE_WLDP_WINDOWS_LOCKDOWN_MODE_TRIAL = 1,
    WLDP_WINDOWS_LOCKDOWN_MODE_WLDP_WINDOWS_LOCKDOWN_MODE_LOCKED = 2,
    WLDP_WINDOWS_LOCKDOWN_MODE_WLDP_WINDOWS_LOCKDOWN_MODE_MAX = 3,
    -- enum WLDP_WINDOWS_LOCKDOWN_RESTRICTION
    WLDP_WINDOWS_LOCKDOWN_RESTRICTION_WLDP_WINDOWS_LOCKDOWN_RESTRICTION_NONE = 0,
    WLDP_WINDOWS_LOCKDOWN_RESTRICTION_WLDP_WINDOWS_LOCKDOWN_RESTRICTION_NOUNLOCK = 1,
    WLDP_WINDOWS_LOCKDOWN_RESTRICTION_WLDP_WINDOWS_LOCKDOWN_RESTRICTION_NOUNLOCK_PERMANENT = 2,
    WLDP_WINDOWS_LOCKDOWN_RESTRICTION_WLDP_WINDOWS_LOCKDOWN_RESTRICTION_MAX = 3,
}
