/*!
 * @file aot_entry.c
 * @brief
 *  AOT program entry: the main() of every compiled LuaC program.
 *
 *  Unlike v1's RuntimeMain (runtime_init.c), there is NO embedded bytecode
 *  blob, NO embedded packages, NO native-DLL bootstrap and NO blob crypto/
 *  decompress passes -- those symbols (g_LuaBlob, Runtime_GetPackages,
 *  EmbeddedLoader_*, InstallEmbeddedPackages, Native_Bootstrap) do not exist
 *  in an AOT program and referencing them would break the link.
 *
 *  Instead, the program's function bodies are compiled to native code ahead
 *  of time and emitted as luac_fn_<id> symbols. At startup we:
 *      1. stand up a Lua state and open the standard libraries,
 *      2. install a lookup-only dispatch hook so luaV_execute routes a Lua
 *         closure call to its pre-registered AOT body (no JIT at runtime),
 *      3. call the generated LuacProgram_BuildEntry, which reconstructs every
 *         Proto and registers each one's luac_fn_<id> into the dispatch cache
 *         (via Jit_RegisterCompiled), returning the main-chunk Proto,
 *      4. build the entry LClosure, bind its _ENV upvalue to the globals table
 *         exactly as lua_load does for a main chunk, and
 *      5. invoke it with a normal lua_pcall -- luaV_execute's hook then
 *         dispatches to the entry body.
 *
 *  TODO(M0+): VEH, coroutine fiber init, FFI open -- added by their slices.
 */

#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include "lstate.h"
#include "lobject.h"
#include "lfunc.h"
#include "lgc.h"
#include "ldo.h"
#include "lvm.h"        /* luavm_jit_compile_hook + luavm_jit_compile_t typedef */

#include "jit/dispatch.h"
#include "runtime/coro.h"   /* fiber-based coroutines so native code can yield */

#include <stdio.h>

/* Generated by the AOT codegen (Task 13): reconstructs all Protos, registers
 * their native bodies into the dispatch cache, and returns the main-chunk
 * Proto (the program entry). Unresolved at `-c` time; linked in for real by
 * the program build. */
extern Proto *LuacProgram_BuildEntry( lua_State *L );

/*!
 * @brief
 *  Lookup-only dispatch hook installed into luavm_jit_compile_hook.
 *
 *  luaV_execute (lvm.c:1199) calls this with the callee closure's Proto*; we
 *  return the pre-registered AOT body for that Proto (or NULL). We use
 *  Jit_LookupCached -- NEVER Jit_Compile -- because AOT bodies are registered
 *  up front by LuacProgram_BuildEntry and there is no JIT in an AOT program.
 *
 *  Signature matches luavm_jit_compile_t == void *(*)(lua_State *, void *).
 */
static void *AotLookupHook( lua_State *L, void *proto ) {
    ( void )L;
    return ( void * )Jit_LookupCached( ( Proto * )proto );
}

int main( int argc, char **argv ) {
    ( void )argc;
    ( void )argv;

    lua_State *L = luaL_newstate( );
    if ( L == NULL ) {
        fprintf( stderr, "luac: cannot create state\n" );
        return 1;
    }
    luaL_openlibs( L );                       /* installs print, etc. into _G */
    Coro_OpenLib( L );                        /* replace stock coroutine with the
                                                 fiber-based lib (native code can
                                                 yield across call frames), as v1's
                                                 RuntimeMain does (runtime_init.c) */
    luavm_jit_compile_hook = AotLookupHook;   /* AOT dispatch (lookup-only)   */

    /* Build every Proto + register each luac_fn_* body; returns the entry. */
    Proto *entry = LuacProgram_BuildEntry( L );
    if ( entry == NULL ) {
        fprintf( stderr, "luac: build entry failed\n" );
        lua_close( L );
        return 1;
    }

    /* Create the entry closure and bind its _ENV upvalue to the globals
     * table, exactly as lua_load does for a main chunk (lapi.c f_Lua path:
     * setobj(L, f->upvals[0]->v.p, getGtable(L)); luaC_barrier(...)). */
    LClosure *cl = luaF_newLclosure( L, entry->sizeupvalues );
    cl->p = entry;
    setclLvalue2s( L, L->top.p, cl );         /* push the closure            */
    L->top.p++;
    luaF_initupvals( L, cl );                 /* allocate fresh upvalue boxes */
    if ( entry->sizeupvalues >= 1 ) {         /* bind upvalue 0 (_ENV)        */
        /* getGtable(L): the globals table lives in the registry at the fixed
         * index LUA_RIDX_GLOBALS (array part, 1-based -> array[idx-1]). This
         * is the exact accessor the real Lua loader uses. */
        const TValue *gt =
            &hvalue( &G( L )->l_registry )->array[ LUA_RIDX_GLOBALS - 1 ];
        setobj( L, cl->upvals[ 0 ]->v.p, gt );
        luaC_barrier( L, cl->upvals[ 0 ], gt );
    }

    /* Invoke it like a normal call; luaV_execute's hook dispatches to the
     * entry's registered AOT body (luac_fn_<entry>). */
    int status = lua_pcall( L, 0, 0, 0 );
    if ( status != LUA_OK ) {
        const char *msg = lua_tostring( L, -1 );
        fprintf( stderr, "luac: runtime error: %s\n",
                 msg ? msg : "(unknown)" );
        lua_close( L );
        return 1;
    }

    lua_close( L );
    return 0;
}
