#include "runtime/runtime_init.h"
#include "runtime/blob_reader.h"
#include "runtime/embedded_loader.h"
#include "runtime/coro.h"
#include "runtime/native_loader.h"
#include "common/version.h"
#include "common/blob_format.h"
#include "common/stream_cipher.h"
#include "jit/dispatch.h"
#include "jit/exec_mem.h"
#include "ffi/ffi_lib.h"
#include "ffi/ffi_load.h"
#include "ffi/ffi_callback.h"
#include "ffi/ctype.h"
#include "ffi/win_types.h"
#include "ffi/veh.h"

#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include "lstate.h"
#include "lvm.h"

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
 * The blob is compiled into the runtime as a regular C const array.
 * The compiler emits a temp blob_gen.c file containing the bytes,
 * compiles it with the same C frontend that built the rest of the
 * runtime, and links the result in. The bytes land in .rdata along
 * with every other read-only constant -- no dedicated section header.
 *
 * Symbols:
 *   const unsigned char g_LuaBlob[];
 *   const unsigned int  g_LuaBlob_size;
 */
extern const unsigned char g_LuaBlob[ ];
extern const unsigned int  g_LuaBlob_size;

/* Embedded packages. Each Lua source under src/runtime/packages/
   is compiled to its own _pkg_gen.o that defines a g_PackageXxxLua
   const char array. THIS file does NOT reference those symbols
   directly anymore -- doing so would force every package's .o to
   be linked into every output binary. Instead, the per-build
   packages_refs.o (generated by compiler.exe based on the resolver's
   BuiltinPackages list) defines Runtime_GetPackages(), which returns
   a table naming only the packages the program actually require()'d.
   The linker then drags in only those _pkg_gen.o files. */
typedef struct _REGISTERED_PACKAGE {
    const char         *Name;     /* dotted require()-name, e.g. "windows.bcrypt" */
    const char         *Src;      /* points at the corresponding g_PackageXxxLua */
    const unsigned int *LenPtr;   /* points at the corresponding g_PackageXxxLua_len */
} REGISTERED_PACKAGE_T;

/* Defined per-build by the compiler-emitted packages_refs.c.
   Returns NULL when the build had zero required packages
   (luavm.exe REPL is not produced through pe_link, so it gets a
   weak stub elsewhere; see luavm_main.c's own preload setup). */
extern const REGISTERED_PACKAGE_T *Runtime_GetPackages( size_t *OutCount );

/* luaD_rawrunprotected is in ldo.h which is LUA_CORE-only; declare its
   prototype here so we can call the symbol from the runtime archive. */
typedef void ( *LuaPFunc )( lua_State *L, void *Ud );
extern int luaD_rawrunprotected( lua_State *L, LuaPFunc F, void *Ud );


typedef struct _JIT_INVOKE_ARGS {
    JIT_FUNC_T  Jitted;
    int         NResults;
} JIT_INVOKE_ARGS_T, *PJIT_INVOKE_ARGS_T;

static void Runtime_JitInvokeProtected( lua_State *L, void *Ud ) {
    PJIT_INVOKE_ARGS_T Args = ( PJIT_INVOKE_ARGS_T )Ud;
    /* Route through Jit_TrampolineEntry so VEH-caught faults longjmp into a
       setjmp frame here and surface as Lua errors (which luaD_rawrunprotected
       catches). Direct-calling Args->Jitted would abort the process on any
       fault since g_CurrentJitFrame would be NULL.

       Bump L->nny ("non-yieldable count") so any pcall/xpcall in the top
       chunk takes the conventional luaD_pcall path (with setjmp) instead
       of the continuation-based path that lua_pcallk uses when k != NULL
       and yields are allowed. The continuation path assumes the caller is
       lua_resume + the interpreter loop to call the continuation function
       on error -- which doesn't exist in our JIT-only runtime, so pcall
       would silently lose the error catch otherwise.

       Coroutines call Jitted directly via their fiber's Coro_FiberEntry
       (NOT through here), so they don't get this nny bump -- yield from
       inside a coroutine still works. */
    /* nny is encoded in the high 16 bits of nCcalls in Lua 5.4. */
    L->nCcalls += 0x10000;
    Args->NResults = Jit_TrampolineEntry( L, Args->Jitted );
    L->nCcalls -= 0x10000;
}

static int PushArgTable( lua_State *L, int Argc, char **Argv ) {
    int I = { 0 };
    lua_createtable( L, Argc - 1, 0 );
    for ( I = 1; I < Argc; I++ ) {
        lua_pushstring( L, Argv[ I ] );
        lua_rawseti( L, -2, I );
    }
    lua_setglobal( L, "arg" );
    return 0;
}

/* Lua-level message handler. Installed via L->errfunc before the top
   JIT entry runs; called inside luaG_errormsg WHILE the stack is still
   valid (i.e. before the longjmp unwinds), so luaL_traceback can walk
   the live call chain. The string this returns becomes the error
   object that surfaces to luaD_rawrunprotected. */
static int Runtime_Msghandler( lua_State *L ) {
    const char *Msg = lua_tostring( L, 1 );
    if ( Msg == NULL ) {
        if ( luaL_callmeta( L, 1, "__tostring" ) && lua_type( L, -1 ) == LUA_TSTRING ) {
            return 1;
        }
        Msg = lua_pushfstring( L, "(error object is a %s value)",
                                luaL_typename( L, 1 ) );
    }
    luaL_traceback( L, L, Msg, 1 );
    return 1;
}

/* The error object on top of the stack already includes the traceback
   appended by Runtime_Msghandler -- just print it. Tolerate the
   no-msghandler path (e.g. errors raised before we set L->errfunc) by
   falling back to the bare message. */
static void PrintLuaError( lua_State *L ) {
    const char *Msg = lua_tostring( L, -1 );
    fprintf( stderr, "[-] lua error :: %s\n", Msg ? Msg : "(no message)" );
    lua_pop( L, 1 );
}

/* Wrapper bridging luavm_jit_compile_hook's (L, void*proto) -> void*
 * signature to Jit_Compile which returns a JIT_FUNC_T pointer. */
static void *Runtime_JitCompileHook( lua_State *L, void *Proto ) {
    return ( void * )Jit_Compile( L, ( struct Proto * )Proto );
}

/* Package compression header magic. embed_luac.exe prefixes compressed
   packages with "LVC1" + a uint32 holding the original (uncompressed)
   length; the runtime detects this prefix and runs RtlDecompressBuffer
   via ntdll's Cabinet.dll-equivalent path before handing the bytes to
   luaL_loadbuffer. Packages that were emitted uncompressed (legacy
   path or --no-compress-pkgs) load directly. */
#define LUAVM_PKG_COMPRESS_MAGIC 0x3143564Cu  /* 'LVC1' little-endian */
#define LUAVM_PKG_COMPRESS_HDR   8            /* magic (4) + uncompressed len (4) */

/* Loaded lazily on first compressed-package load. NULL on systems that
   somehow lack ntdll (i.e. never). */
typedef LONG ( WINAPI *PRtlDecompressBufferEx )(
    USHORT, PUCHAR, ULONG, PUCHAR, ULONG, PULONG, PVOID );
static PRtlDecompressBufferEx g_RtlDecompress = NULL;

/* COMPRESSION_FORMAT_XPRESS_HUFF = 4 (LZ77 + Huffman, best ratio of the
   built-in formats; LZNT1 = 2 was the legacy alternative). */
#define LUAVM_PKG_COMPRESSION_FORMAT 4

/*!
 * @brief
 *  Generic package-loader closure. Reads its three upvalues:
 *      1: lightuserdata pointing at g_PackageXxxLua bytes
 *      2: lightuserdata pointing at g_PackageXxxLua_len
 *      3: string -- the dotted package name (for the chunk label)
 *  and compiles+runs the chunk, returning the module table.
 *  Transparently decompresses LVC1-prefixed packages via ntdll's
 *  RtlDecompressBufferEx (XPRESS_HUFF) before luaL_loadbuffer.
 */
static int Runtime_PackageLoader( lua_State *L ) {
    const char         *Src    = ( const char         * )lua_touserdata( L, lua_upvalueindex( 1 ) );
    const unsigned int *LenPtr = ( const unsigned int * )lua_touserdata( L, lua_upvalueindex( 2 ) );
    const char         *Name   = lua_tostring( L, lua_upvalueindex( 3 ) );
    char  Chunkname[ 128 ] = { 0 };
    snprintf( Chunkname, sizeof( Chunkname ), "=%s", Name ? Name : "?" );

    size_t          Len  = ( size_t )*LenPtr;
    const char     *Body = Src;
    size_t          BodyLen = Len;
    unsigned char  *Decomp = NULL;

    /* Compressed-package detection: first 4 bytes == "LVC1" => decompress. */
    if ( Len >= LUAVM_PKG_COMPRESS_HDR &&
         *( const uint32_t * )Src == LUAVM_PKG_COMPRESS_MAGIC ) {
        uint32_t UncompLen = *( const uint32_t * )( Src + 4 );
        if ( g_RtlDecompress == NULL ) {
            HMODULE H = GetModuleHandleA( "ntdll.dll" );
            if ( H == NULL ) H = LoadLibraryA( "ntdll.dll" );
            if ( H != NULL ) {
                g_RtlDecompress = ( PRtlDecompressBufferEx )( void * )
                    GetProcAddress( H, "RtlDecompressBufferEx" );
            }
        }
        if ( g_RtlDecompress == NULL ) {
            lua_pushfstring( L,
                "package %s: compressed but RtlDecompressBufferEx unavailable",
                Name ? Name : "?" );
            return lua_error( L );
        }
        Decomp = ( unsigned char * )malloc( UncompLen );
        if ( Decomp == NULL ) {
            lua_pushfstring( L,
                "package %s: oom allocating %u bytes for decompress",
                Name ? Name : "?", ( unsigned )UncompLen );
            return lua_error( L );
        }
        /* Scratch buffer: docs say worst case ~5% of input + headers, give 8x as cushion. */
        ULONG ScratchLen = ( ULONG )( Len * 8 + 4096 );
        void *Scratch    = malloc( ScratchLen );
        ULONG OutLen = 0;
        LONG  Status = g_RtlDecompress(
            LUAVM_PKG_COMPRESSION_FORMAT,
            ( PUCHAR )Decomp, UncompLen,
            ( PUCHAR )( Src + LUAVM_PKG_COMPRESS_HDR ),
            ( ULONG )( Len - LUAVM_PKG_COMPRESS_HDR ),
            &OutLen, Scratch );
        if ( Scratch ) free( Scratch );
        if ( Status != 0 || OutLen != UncompLen ) {
            free( Decomp );
            lua_pushfstring( L,
                "package %s: RtlDecompressBufferEx failed status=0x%X",
                Name ? Name : "?", ( unsigned )Status );
            return lua_error( L );
        }
        Body    = ( const char * )Decomp;
        BodyLen = ( size_t )UncompLen;
    }

    int Rc = luaL_loadbuffer( L, Body, BodyLen, Chunkname );
    if ( Decomp ) free( Decomp );  /* loadbuffer copied the bytes */
    if ( Rc != LUA_OK ) return lua_error( L );
    lua_call( L, 0, 1 );
    return 1;
}

/*!
 * @brief
 *  Register all bundled packages into package.preload so user code
 *  can `require "<name>"` without a search path. Driven by the
 *  per-build packages_refs.o's Runtime_GetPackages(); a binary that
 *  required zero packages gets zero entries and the rest of the
 *  package surface lives outside its .rdata.
 */
static void InstallEmbeddedPackages( lua_State *L ) {
    size_t Count = 0;
    const REGISTERED_PACKAGE_T *Pkgs = Runtime_GetPackages( &Count );
    if ( Pkgs == NULL || Count == 0 ) return;
    lua_getglobal( L, "package" );
    lua_getfield( L, -1, "preload" );
    for ( size_t I = 0; I < Count; I++ ) {
        if ( Pkgs[ I ].Name == NULL || Pkgs[ I ].Src == NULL ||
             Pkgs[ I ].LenPtr == NULL ) continue;
        lua_pushlightuserdata( L, ( void * )Pkgs[ I ].Src );
        lua_pushlightuserdata( L, ( void * )Pkgs[ I ].LenPtr );
        lua_pushstring( L, Pkgs[ I ].Name );
        lua_pushcclosure( L, Runtime_PackageLoader, 3 );
        lua_setfield( L, -2, Pkgs[ I ].Name );
    }
    lua_pop( L, 2 ); /* preload, package */
}

/*!
 * @brief
 *  Locate the runtime .exe's .text section via PE headers and register it
 *  as a VEH code region. Faults inside our own runtime helpers (called
 *  from JIT) will then be caught.
 */
static void RegisterRuntimeTextRegion( void ) {
    HMODULE  Hm  = GetModuleHandleW( NULL );
    if ( Hm == NULL ) return;
    BYTE    *Base = ( BYTE * )Hm;
    PIMAGE_DOS_HEADER Dos = ( PIMAGE_DOS_HEADER )Base;
    if ( Dos->e_magic != IMAGE_DOS_SIGNATURE ) return;
    PIMAGE_NT_HEADERS Nt = ( PIMAGE_NT_HEADERS )( Base + Dos->e_lfanew );
    if ( Nt->Signature != IMAGE_NT_SIGNATURE ) return;

    PIMAGE_SECTION_HEADER Sec = IMAGE_FIRST_SECTION( Nt );
    int I = { 0 };
    for ( I = 0; I < Nt->FileHeader.NumberOfSections; I++ ) {
        if ( memcmp( Sec[ I ].Name, ".text", 5 ) == 0 ) {
            void *Start = Base + Sec[ I ].VirtualAddress;
            size_t Size = ( size_t )Sec[ I ].Misc.VirtualSize;
            Veh_RegisterRegion( Start, Size );
            return;
        }
    }
}

int RuntimeMain( int Argc, char **Argv ) {
    BLOB_READER_T  Reader   = { 0 };
    BLOB_LOOKUP_T  Entry    = { 0 };
    lua_State     *L        = { 0 };
    size_t         BlobSize = ( size_t )g_LuaBlob_size;
    int            Rc       = { 0 };
    const unsigned char *BlobBase = g_LuaBlob;

    /* install the JIT hook so luaV_execute trampolines into JIT code
     * for all re-entry paths (require, pcall, C→Lua callbacks) */
    luavm_jit_compile_hook = Runtime_JitCompileHook;
    luavm_jit_invoke_hook = ( luavm_jit_invoke_t )Jit_TrampolineEntry;

    if ( !Veh_Init( ) ) {
        fprintf( stderr, "[-] Veh_Init failed (GetLastError=%lu)\n",
                 ( unsigned long )GetLastError( ) );
        return EXIT_FAILURE;
    }
    RegisterRuntimeTextRegion( );

    /* Native-embed bootstrap: extract any per-build embedded DLLs to
       a per-binary temp dir and prepend that dir to the DLL search
       path. No-op when nothing embedded (weak symbol returns empty).
       Runs BEFORE Lua state init so packages whose load-path happens
       at require time (e.g. sqlite calling ffi.load("sqlite3") inside
       its preload) find the DLLs. */
    Native_Bootstrap( );

    /* Capture the blob's feature flags for use after the Lua state is up.
       LUA_SANDBOX applies after luaL_openlibs() and can't ride the pre-state pass. */
    uint32_t BlobFlagsSnapshot = 0;
    if ( BlobSize >= sizeof( LUAVM_BLOB_HEADER_T ) ) {
        PLUAVM_BLOB_HEADER_T HdrPeek = ( PLUAVM_BLOB_HEADER_T )BlobBase;
        if ( HdrPeek->Magic == LUAVM_BLOB_MAGIC ) BlobFlagsSnapshot = HdrPeek->Flags;
    }

    /* Pre-pass: if any processing flag is set (decrypt, integrity check,
       decompress), copy the blob into a writable buffer and run the
       matching pass(es) before BlobReader_Open sees it. */
    if ( BlobSize >= sizeof( LUAVM_BLOB_HEADER_T ) ) {
        PLUAVM_BLOB_HEADER_T Hdr = ( PLUAVM_BLOB_HEADER_T )BlobBase;
        if ( Hdr->Magic == LUAVM_BLOB_MAGIC && Hdr->Flags != 0 ) {
            unsigned char *Mut = ( unsigned char * )malloc( BlobSize );
            if ( Mut == NULL ) {
                fprintf( stderr, "[-] blob mutable copy alloc failed\n" );
                return EXIT_FAILURE;
            }
            memcpy( Mut, BlobBase, BlobSize );
            PLUAVM_BLOB_HEADER_T MutHdr = ( PLUAVM_BLOB_HEADER_T )Mut;
            size_t HdrSize     = sizeof( LUAVM_BLOB_HEADER_T );
            size_t PayloadSize = BlobSize - HdrSize;

            if ( MutHdr->Flags & LUAVM_BLOB_FLAG_ENCRYPTED ) {
                StreamCipher_Apply( MutHdr->EncryptionKey,
                                    Mut + HdrSize,
                                    PayloadSize );
            }

            /* --compress-blob: decompress the payload region. The
               in-blob layout is `LVCB` magic + uint32 uncompressed-size
               + XPRESS_HUFF data, sitting right after the header.
               Runs AFTER decrypt because ciphertext doesn't compress;
               build time applied compression first then encryption,
               so we reverse that order here. */
            if ( ( MutHdr->Flags & LUAVM_BLOB_FLAG_COMPRESS_PAYLOAD ) &&
                 PayloadSize >= 8 &&
                 *( uint32_t * )( Mut + HdrSize ) == 0x42435643u /* 'LVCB' */ ) {
                uint32_t UncompSize = *( uint32_t * )( Mut + HdrSize + 4 );
                HMODULE  Nt = GetModuleHandleA( "ntdll.dll" );
                if ( Nt == NULL ) Nt = LoadLibraryA( "ntdll.dll" );
                typedef LONG ( WINAPI *PRtlDecompressBufferEx )(
                    USHORT, PUCHAR, ULONG, PUCHAR, ULONG, PULONG, PVOID );
                PRtlDecompressBufferEx Dec = ( PRtlDecompressBufferEx )( void * )
                    GetProcAddress( Nt, "RtlDecompressBufferEx" );
                if ( Dec == NULL ) {
                    fprintf( stderr, "[-] --compress-blob: RtlDecompressBufferEx unavailable\n" );
                    free( Mut );
                    return EXIT_FAILURE;
                }
                size_t         NewBlobSize = HdrSize + UncompSize;
                unsigned char *NewBlob     = ( unsigned char * )malloc( NewBlobSize );
                if ( NewBlob == NULL ) {
                    fprintf( stderr, "[-] --compress-blob: oom decompressing %u bytes\n",
                             ( unsigned )UncompSize );
                    free( Mut );
                    return EXIT_FAILURE;
                }
                memcpy( NewBlob, Mut, HdrSize );
                ULONG ScratchLen = ( ULONG )( PayloadSize * 8 + 4096 );
                void *Scratch    = malloc( ScratchLen );
                ULONG OutLen     = 0;
                LONG  St = Dec( 4 /*XPRESS_HUFF*/,
                                NewBlob + HdrSize, UncompSize,
                                Mut + HdrSize + 8,
                                ( ULONG )( PayloadSize - 8 ),
                                &OutLen, Scratch );
                if ( Scratch ) free( Scratch );
                if ( St != 0 || OutLen != UncompSize ) {
                    fprintf( stderr, "[-] --compress-blob: decompress failed status=0x%X\n",
                             ( unsigned )St );
                    free( NewBlob );
                    free( Mut );
                    return EXIT_FAILURE;
                }
                /* Rewrite header sizes inside NewBlob to match the
                   inflated payload. */
                PLUAVM_BLOB_HEADER_T NewHdr = ( PLUAVM_BLOB_HEADER_T )NewBlob;
                NewHdr->TotalSize = ( uint32_t )NewBlobSize;
                NewHdr->Flags    &= ~LUAVM_BLOB_FLAG_COMPRESS_PAYLOAD;
                free( Mut );
                Mut         = NewBlob;
                MutHdr      = NewHdr;
                BlobSize    = NewBlobSize;
                PayloadSize = UncompSize;
            }

            BlobBase = Mut;   /* leak intentional: held for process lifetime */
        }
    }

    if ( !BlobReader_Open( BlobBase, BlobSize, &Reader ) ) {
        fprintf( stderr, "[-] embedded blob invalid (%zu bytes)\n", BlobSize );
        return EXIT_FAILURE;
    }
    if ( !BlobReader_GetEntry( &Reader, &Entry ) ) {
        fprintf( stderr, "[-] embedded entry module missing\n" );
        return EXIT_FAILURE;
    }

    L = luaL_newstate( );
    if ( L == NULL ) {
        fprintf( stderr, "[-] luaL_newstate failed\n" );
        return EXIT_FAILURE;
    }
    /* Register L for the callback dispatcher (v1 single-threaded). */
    Ffi_SetDispatchL( L );
    luaL_openlibs( L );

    /* --lua-version-strip: nil out the version / copyright strings that
       Lua wires into _G during openlibs. */
    if ( BlobFlagsSnapshot & LUAVM_BLOB_FLAG_LUA_VERSION_STRIP ) {
        lua_pushnil( L ); lua_setglobal( L, "_VERSION" );
        lua_pushnil( L ); lua_setglobal( L, "_COPYRIGHT" );
        lua_pushnil( L ); lua_setglobal( L, "_DESCRIPTION" );
        lua_pushnil( L ); lua_setglobal( L, "_AUTHORS" );
        lua_pushnil( L ); lua_setglobal( L, "_RELEASE" );
    }

    /* --lua-sandbox: remove a curated set of dangerous globals so a
       compromised script can't shell out, write to arbitrary files,
       load arbitrary code, or introspect debug state. The package
       sub-table needs special handling: keep `package.preload` (our
       package system depends on it) and `package.loaded`, drop the
       rest. */
    if ( BlobFlagsSnapshot & LUAVM_BLOB_FLAG_LUA_SANDBOX ) {
        static const char *const k_DropGlobals[] = {
            "loadfile", "dofile", "load",
            NULL
        };
        for ( int I = 0; k_DropGlobals[ I ]; I++ ) {
            lua_pushnil( L );
            lua_setglobal( L, k_DropGlobals[ I ] );
        }
        /* os.*: drop spawn / exit / fs-modify / env-mutate, keep
           timekeeping and read-only queries. */
        lua_getglobal( L, "os" );
        if ( lua_type( L, -1 ) == LUA_TTABLE ) {
            static const char *const k_DropOs[] = {
                "execute", "exit", "remove", "rename", "tmpname",
                "setlocale", "getenv", NULL
            };
            for ( int I = 0; k_DropOs[ I ]; I++ ) {
                lua_pushnil( L );
                lua_setfield( L, -2, k_DropOs[ I ] );
            }
        }
        lua_pop( L, 1 );
        /* io.*: drop spawn + arbitrary file open. */
        lua_getglobal( L, "io" );
        if ( lua_type( L, -1 ) == LUA_TTABLE ) {
            static const char *const k_DropIo[] = {
                "popen", "open", "tmpfile", "lines", NULL
            };
            for ( int I = 0; k_DropIo[ I ]; I++ ) {
                lua_pushnil( L );
                lua_setfield( L, -2, k_DropIo[ I ] );
            }
        }
        lua_pop( L, 1 );
        /* debug.*: drop everything except traceback (useful for error
           reporting). */
        lua_getglobal( L, "debug" );
        if ( lua_type( L, -1 ) == LUA_TTABLE ) {
            static const char *const k_KeepDb[] = { "traceback", NULL };
            /* iterate keys -- can't enumerate + mutate at once safely,
               so collect names first, then nil them. */
            char Names[ 32 ][ 32 ] = { { 0 } };
            int  N = 0;
            lua_pushnil( L );
            while ( N < 32 && lua_next( L, -2 ) != 0 ) {
                if ( lua_type( L, -2 ) == LUA_TSTRING ) {
                    const char *K = lua_tostring( L, -2 );
                    int Keep = 0;
                    for ( int I = 0; k_KeepDb[ I ]; I++ ) {
                        if ( strcmp( K, k_KeepDb[ I ] ) == 0 ) { Keep = 1; break; }
                    }
                    if ( !Keep ) {
                        size_t L2 = strlen( K );
                        if ( L2 < sizeof( Names[ 0 ] ) ) {
                            memcpy( Names[ N++ ], K, L2 + 1 );
                        }
                    }
                }
                lua_pop( L, 1 );  /* value */
            }
            for ( int I = 0; I < N; I++ ) {
                lua_pushnil( L );
                lua_setfield( L, -2, Names[ I ] );
            }
        }
        lua_pop( L, 1 );
        /* package.loadlib: drop arbitrary DLL loading via Lua. */
        lua_getglobal( L, "package" );
        if ( lua_type( L, -1 ) == LUA_TTABLE ) {
            lua_pushnil( L ); lua_setfield( L, -2, "loadlib" );
            lua_pushnil( L ); lua_setfield( L, -2, "searchpath" );
            lua_pushnil( L ); lua_setfield( L, -2, "cpath" );
        }
        lua_pop( L, 1 );
    }

    Coro_OpenLib( L );  /* replace stock coroutine with fiber-based */
    InstallEmbeddedPackages( L );
    Ctype_Init( );
    Ffi_RegisterWindowsTypes( );
    Ffi_OpenLib( L );
    EmbeddedLoader_Install( L, &Reader );
    PushArgTable( L, Argc, Argv );

    Rc = luaL_loadbufferx( L,
                           ( const char * )Entry.Bytes,
                           Entry.BytesLen,
                           "@embedded:<entry>",
                           "b" );
    if ( Rc != LUA_OK ) {
        PrintLuaError( L );
        lua_close( L );
        return EXIT_FAILURE;
    }

    /* Install a message handler beneath the entry closure so any error
       raised from the script (or from JIT-compiled code it calls into)
       is intercepted while the Lua call chain is still live. The handler
       appends debug.traceback(msg) and that combined string becomes the
       error object surfaced to luaD_rawrunprotected / PrintLuaError. */
    lua_pushcfunction( L, Runtime_Msghandler );
    lua_insert( L, -2 );  /* stack: [..., msghandler, chunk] */

    /* Try JIT-compiling the entry. If successful, set up its CallInfo and
       direct-call the JIT entry. Otherwise fall back to lua_pcall. */
    {
        const LClosure *EntryClosure = clLvalue( s2v( L->top.p - 1 ) );
        JIT_FUNC_T      Jitted       = Jit_Compile( L, EntryClosure->p );
        StkId           Func         = { 0 };
        Proto          *Pr           = { 0 };
        CallInfo       *Ci           = { 0 };
        if ( Jitted != NULL ) {
            fprintf( stderr, "[*] runtime: invoking JIT entry %p\n", ( void * )Jitted );
            Pr   = EntryClosure->p;
            /* Reserve stack space before taking any stack pointers — the
               reallocation would invalidate any pointer captured before it. */
            lua_checkstack( L, Pr->maxstacksize + 5 );
            /* Capture the closure + msghandler slots only after the stack
               is stable. errfunc offset is for the msghandler at top-2. */
            Func = L->top.p - 1;
            ptrdiff_t ErrfuncOff = savestack( L, Func - 1 );
            /* Manually do a small subset of luaD_precall for a Lua function. */
            Ci = luaE_extendCI( L );
            Ci->func.p          = Func;
            Ci->top.p           = Func + 1 + Pr->maxstacksize;
            Ci->u.l.savedpc     = Pr->code;
            Ci->u.l.trap        = 0;
            Ci->u.l.nextraargs  = 0;
            Ci->callstatus      = 0;
            Ci->nresults        = 0;
            L->ci    = Ci;
            /* For vararg entry: leave L->top.p at Func+1 (0 actual args)
               so OP_VARARGPREP counts args correctly.
               For non-vararg entry: set to Ci->top.p to cover all registers. */
            if ( !Pr->is_vararg ) {
                L->top.p = Ci->top.p;
            }
            JIT_INVOKE_ARGS_T InvokeArgs = { Jitted, 0 };
            int OldNCcalls = ( int )L->nCcalls;
            ptrdiff_t OldErrfunc = L->errfunc;
            L->errfunc = ErrfuncOff;
            int Status = luaD_rawrunprotected( L, Runtime_JitInvokeProtected, &InvokeArgs );
            L->errfunc = OldErrfunc;
            if ( Status != LUA_OK ) {
                /* Lua error during JIT execution. Restore nCcalls + ci, print, fail. */
                L->nCcalls = ( unsigned int )OldNCcalls;
                L->ci = Ci->previous;
                PrintLuaError( L );
                lua_close( L );
                return EXIT_FAILURE;
            }
            ( void )InvokeArgs.NResults;
            L->ci = Ci->previous;
            Rc = LUA_OK;
        } else {
            fprintf( stderr, "[*] runtime: entry not JIT-able, using interpreter\n" );
            /* lua_pcall takes the errfunc index directly (1-based stack idx). */
            Rc = lua_pcall( L, 0, 0, lua_gettop( L ) - 1 );
        }
    }
    if ( Rc != LUA_OK ) {
        PrintLuaError( L );
        lua_close( L );
        return EXIT_FAILURE;
    }

    lua_close( L );
    return EXIT_SUCCESS;
}

/* DLL-build entry: hosts that LoadLibrary the runtime call this to run
 * the embedded blob. Returns the same exit code RuntimeMain would.
 * No argv plumbing -- if you need args, link the same runtime.a into
 * a custom DLL with your own export that forwards to RuntimeMain. */
__declspec(dllexport) int luavm_run( void ) {
    return RuntimeMain( 0, NULL );
}

/* main() lives in runtime_entry.c so that linking a custom-main host
 * against the static lib doesn't get a duplicate-main collision when
 * the linker pulls runtime_init.o for RuntimeMain/luavm_run. The
 * separate-TU split means runtime_entry.o is only pulled when nothing
 * else defines main. */
