/*!
 * @file aot_entry.c
 * @brief
 *  AOT program entry: the main() of every compiled LuaC program.
 *
 *  Unlike v1's RuntimeMain (runtime_init.c), there is NO embedded bytecode
 *  blob, NO embedded packages, NO native-DLL bootstrap and NO blob crypto/
 *  decompress passes -- those symbols (g_LuaBlob, Runtime_GetPackages,
 *  EmbeddedLoader_*, InstallEmbeddedPackages, Native_Bootstrap) do not exist
 *  in an AOT program and referencing them would break the link.
 *
 *  Instead, the program's function bodies are compiled to native code ahead
 *  of time and emitted as luac_fn_<id> symbols. At startup we:
 *      1. stand up a Lua state and open the standard libraries,
 *      2. install a lookup-only dispatch hook so luaV_execute routes a Lua
 *         closure call to its pre-registered AOT body (no JIT at runtime),
 *      3. call the generated LuacProgram_BuildEntry, which reconstructs every
 *         Proto and registers each one's luac_fn_<id> into the dispatch cache
 *         (via Jit_RegisterCompiled), returning the main-chunk Proto,
 *      4. build the entry LClosure, bind its _ENV upvalue to the globals table
 *         exactly as lua_load does for a main chunk, and
 *      5. invoke it with a normal lua_pcall -- luaV_execute's hook then
 *         dispatches to the entry body.
 *
 *  Coroutines: fiber-based lib installed below (Coro_OpenLib). VEH and the
 *  FFI are deliberately NOT initialized in AOT programs today — no FFI means
 *  no foreign threads/faulting stubs (and ~25 KB less per exe); FFI-in-exes
 *  is an M4 item alongside builtin-package bundling.
 */

#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include "lstate.h"
#include "lobject.h"
#include "lfunc.h"
#include "lgc.h"
#include "ldo.h"
#include "lvm.h"        /* clua_dispatch_hook + clua_dispatch_t typedef */

#include "jit/dispatch.h"
#include "runtime/coro.h"   /* fiber-based coroutines so native code can yield */

#include "lzio.h"           /* closed-world stub signatures (luaY_parser/luaU_*) */
#include "llex.h"
#include "lparser.h"
#include "lundump.h"

#define WIN32_LEAN_AND_MEAN
#include <windows.h>        /* native OS-thread workers: CreateThread + events  */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <process.h>       /* _beginthreadex -- CRT-correct thread creation */

/* Generated by the AOT codegen (Task 13): reconstructs all Protos, registers
 * their native bodies into the dispatch cache, and returns the main-chunk
 * Proto (the program entry). Unresolved at `-c` time; linked in for real by
 * the program build. */
extern Proto *LuacProgram_BuildEntry( lua_State *L );

/*!
 * @brief
 *  Lookup-only dispatch hook installed into clua_dispatch_hook.
 *
 *  luaV_execute (lvm.c:1199) calls this with the callee closure's Proto*; we
 *  return the pre-registered AOT body for that Proto (or NULL). Lookup only:
 *  AOT bodies are registered up front by LuacProgram_BuildEntry and no code
 *  generation exists at run time.
 *
 *  Signature matches clua_dispatch_t == void *(*)(lua_State *, void *).
 */
static void *AotLookupHook( lua_State *L, void *proto ) {
    ( void )L;
    return ( void * )Jit_LookupCached( ( Proto * )proto );
}

/* FFI bring-up, linked only when the program references ffi/bit (the driver
 * adds -Wl,--undefined=Clua_OpenFfi then; see ffi_anchor.c). Weak: NULL when
 * the anchor isn't in the link. */
extern void Clua_OpenFfi( lua_State *L ) __attribute__(( weak ));

/* Basename of argv[0]: drop any directory / drive prefix, keep the file name.
 * Used for the uncaught-error banner so a compiled program reports under its
 * own name, exactly as reference Lua prints "<progname>: <msg>". */
static const char *AotProgName( const char *argv0 ) {
    const char *base = argv0;
    const char *p;
    if ( argv0 == NULL || argv0[ 0 ] == '\0' ) return "clua";
    for ( p = argv0; *p != '\0'; p++ ) {
        if ( *p == '\\' || *p == '/' || *p == ':' ) base = p + 1;
    }
    return ( *base != '\0' ) ? base : "clua";
}

/* Message handler installed under the entry call: appends a stack traceback
 * to the error object while the call chain is still live, so an uncaught
 * runtime error reports exactly like the reference interpreter does -- same
 * "<name>: <message>\n<traceback>" shape (AOT-ERRBANNER-001 resolved). The
 * leading name token is the program's own basename rather than a fixed
 * string, which is correct: a standalone exe is not the compiler. */
static int AotMsgHandler( lua_State *L ) {
    const char *msg = lua_tostring( L, 1 );
    if ( msg == NULL ) {
        if ( luaL_callmeta( L, 1, "__tostring" ) &&
             lua_type( L, -1 ) == LUA_TSTRING ) {
            return 1;
        }
        msg = lua_pushfstring( L, "(error object is a %s value)",
                               luaL_typename( L, 1 ) );
    }
    luaL_traceback( L, L, msg, 1 );
    return 1;
}

/* Closed-world stubs (AOT-CLOSEDWORLD-002): luaY_parser/luaU_undump/
** luaU_dump/luaX_init. Textually included so aot_entry.o keeps defining
** them ahead of the archives on the static link line (unchanged), while
** the SAME source compiles standalone into clua-rt.dll for --shared-rt
** builds. The stub bodies + full rationale live in that file. */
#include "closed_world_stubs.c"

/* ===================================================================== *
 *  Native OS-thread workers (thread.spawn native path).
 *
 *  A function is identified across lua_States by its compile-time function-id
 *  (the protoblob index, recorded in the dispatch cache by ProtoInit). The
 *  `_clua` internal library exposes that id to Lua (fn_id), resolves it back to
 *  a fresh closure in a worker state (resolve_fn), and drives a real OS thread
 *  (spawn_native/join_native/alive_native). The worker runs a small Lua
 *  trampoline (thread.lua's worker_main) so argument/result (de)serialization
 *  reuses the package's pure-Lua serializer rather than a second C copy.
 *
 *  Isolation: the worker builds its OWN Protos in its OWN lua_State and
 *  registers them in a private thread-local dispatch cache (Jit_WorkerCache*),
 *  and the JIT recovery frame / tail-call flag / coroutine pointer are all
 *  thread-local, so a worker never races the main thread. Workers do NOT open
 *  the FFI (its callback-dispatch state is a single shared lua_State), so a
 *  native worker function must be ffi-free; thread.lua falls back to cooperative
 *  mode for functions that capture upvalues or are otherwise not shippable.
 * ===================================================================== */

static void Clua_OpenInternal( lua_State *L );   /* defined below; used by the bootstrap */

/* Push an LClosure over Proto P with upvalue 0 (_ENV) bound to this state's
   globals -- exactly how lua_load / ProtoInit root a main chunk / module. */
static void AotPushClosure( lua_State *L, Proto *P ) {
    LClosure *cl = luaF_newLclosure( L, P->sizeupvalues );
    cl->p = P;
    setclLvalue2s( L, L->top.p, cl );
    L->top.p++;
    luaF_initupvals( L, cl );
    if ( P->sizeupvalues >= 1 ) {
        const TValue *gt =
            &hvalue( &G( L )->l_registry )->array[ LUA_RIDX_GLOBALS - 1 ];
        setobj( L, cl->upvals[ 0 ]->v.p, gt );
        luaC_barrier( L, cl->upvals[ 0 ], gt );
    }
}

/* The Proto behind the Lua function at stack index Idx (NULL if not an
   LClosure / a C function). Uses the internal stack accessor. */
static Proto *AotArgProto( lua_State *L, int Idx ) {
    TValue *v = s2v( L->ci->func.p + Idx );
    if ( !ttisLclosure( v ) ) return NULL;
    return clLvalue( v )->p;
}

/* A function is "shippable" to a worker iff it captures nothing but _ENV (a
   fresh worker closure binds fresh globals; a captured local could not be
   reconstructed). Conservative when upvalue debug names are absent. */
static int AotFnShippable( Proto *P ) {
    int i;
    for ( i = 0; i < P->sizeupvalues; i++ ) {
        TString *nm = P->upvalues[ i ].name;
        if ( nm == NULL || strcmp( getstr( nm ), "_ENV" ) != 0 ) return 0;
    }
    return 1;
}

/* _clua.fn_id(fn) -> integer id, or nil if fn is not a shippable compiled
   Lua function. */
static int Clua_FnId( lua_State *L ) {
    Proto *P = AotArgProto( L, 1 );
    int    Id;
    if ( P == NULL ) { lua_pushnil( L ); return 1; }
    Id = Jit_ProtoFuncId( P );
    if ( Id < 0 || !AotFnShippable( P ) ) { lua_pushnil( L ); return 1; }
    lua_pushinteger( L, Id );
    return 1;
}

/* _clua.resolve_fn(id) -> a fresh closure over the Proto with that id, or nil. */
static int Clua_ResolveFn( lua_State *L ) {
    int    Id = ( int )luaL_checkinteger( L, 1 );
    Proto *P  = Jit_ResolveFuncId( Id );
    if ( P == NULL ) { lua_pushnil( L ); return 1; }
    AotPushClosure( L, P );
    return 1;
}

/* Per-worker handoff. Allocated by spawn_native, owned by the worker until
   join_native reads the result and frees it. */
typedef struct {
    volatile LONG  Status;       /* 0 pending, 1 ok, 2 error */
    char          *Payload;      /* serialized result, or error message */
    int            PayloadLen;
} CluaThrResult;

typedef struct {
    int            WorkerMainId; /* thread.lua's worker_main trampoline */
    int            WorkerFnId;   /* the user's worker function */
    char          *ArgsBlob;     /* serialized varargs (malloc'd copy) */
    int            ArgsLen;
    CluaThrResult  Result;
    HANDLE         Thread;
    HANDLE         DoneEvent;
} CluaThrCtx;

/* Serialize worker STATE BRING-UP (luaL_newstate / openlibs / proto build).
   The actual worker function runs OUTSIDE this lock, fully concurrently; only
   the construction of a fresh state is one-at-a-time, which is cheap and rules
   out any non-reentrancy in luaL_newstate / library open / ProtoInit. */
static CRITICAL_SECTION g_BringupCs;
static INIT_ONCE        g_BringupOnce = INIT_ONCE_STATIC_INIT;
static BOOL CALLBACK BringupInitCb( PINIT_ONCE O, PVOID P, PVOID *C ) {
    ( void )O; ( void )P; ( void )C;
    InitializeCriticalSection( &g_BringupCs );
    return TRUE;
}
static void BringupLock( void ) {
    InitOnceExecuteOnce( &g_BringupOnce, BringupInitCb, NULL, NULL );
    EnterCriticalSection( &g_BringupCs );
}
static void BringupUnlock( void ) { LeaveCriticalSection( &g_BringupCs ); }

static void ThrSetError( CluaThrCtx *Ctx, const char *Msg ) {
    size_t n = strlen( Msg );
    char  *p = ( char * )malloc( n + 1 );
    if ( p != NULL ) { memcpy( p, Msg, n + 1 ); Ctx->Result.Payload = p; Ctx->Result.PayloadLen = ( int )n; }
    Ctx->Result.Status = 2;
}

/* The OS-thread entry: bring a worker lua_State up to the full AOT environment
   (stdlibs, the proto registry + package.preload), then run
   worker_main(worker_fn_id, args_blob) and capture its serialized result.
   Created via _beginthreadex (NOT CreateThread): the worker runs Lua, which
   leans on the CRT (malloc/free/errno/locale) -- a CreateThread'd thread skips
   the CRT's per-thread initialization, which silently corrupts the heap under
   concurrency. _beginthreadex sets that state up (and _endthreadex tears it
   down on return). */
static unsigned __stdcall Clua_ThreadBootstrap( void *Param ) {
    CluaThrCtx *Ctx = ( CluaThrCtx * )Param;
    lua_State  *L;
    Proto      *Entry;
    Proto      *Wm;
    int         St;

    if ( Jit_WorkerCacheBegin( ) == NULL ) {  /* this thread's private dispatch cache */
        /* Without a private cache the worker would register its Protos into the
           SHARED global cache and race the main thread -- refuse instead. */
        ThrSetError( Ctx, "thread worker: dispatch-cache alloc failed" );
        SetEvent( Ctx->DoneEvent );
        return 1;
    }

    BringupLock( );                           /* one-at-a-time state construction */
    L = luaL_newstate( );
    if ( L == NULL ) {
        BringupUnlock( );
        ThrSetError( Ctx, "thread worker: cannot create state" );
        SetEvent( Ctx->DoneEvent );
        Jit_WorkerCacheEnd( );
        return 1;
    }
    luaL_openlibs( L );
    /* NOTE: the worker deliberately does NOT install the fiber-based coroutine
       lib -- it runs straight-line worker functions, and ConvertThreadToFiber
       per worker is both unnecessary and a concurrency hazard. (A worker that
       needs coroutines should be spawned cooperatively.) */
    Clua_OpenInternal( L );                   /* _clua.resolve_fn etc. in the worker */
    /* clua_dispatch_hook is process-global (set by main); leave it. The worker
       deliberately does NOT open the FFI (single shared callback-dispatch L). */

    lua_gc( L, LUA_GCSTOP );                   /* AOT-MULTIMOD-001: anchor before any cycle */
    Entry = LuacProgram_BuildEntry( L );        /* builds + registers ALL protos here */
    if ( Entry == NULL ) {
        lua_gc( L, LUA_GCRESTART );
        BringupUnlock( );
        ThrSetError( Ctx, "thread worker: proto build failed" );
        lua_close( L );
        SetEvent( Ctx->DoneEvent );
        Jit_WorkerCacheEnd( );
        return 1;
    }
    /* Root the WHOLE proto tree (the entry chunk + every nested function the
       user defined inside it) so a GC cycle cannot sweep a function the worker
       is about to resolve by id. BuildEntry roots required *modules* via
       package.preload, but the entry tree -- which holds the user's worker
       functions -- is otherwise unreferenced here (the worker runs worker_main,
       not the entry). A closure over the entry Proto pins the entire tree; we
       keep it in the registry for the worker's life. (Without this, the GC
       sweeps the user functions and resolve_fn returns a freed Proto -> the
       crash this fixes; same class as AOT-MULTIMOD-001.) */
    AotPushClosure( L, Entry );
    luaL_ref( L, LUA_REGISTRYINDEX );           /* pins the entry tree; pops the closure */
    Wm = Jit_ResolveFuncId( Ctx->WorkerMainId );
    if ( Wm == NULL ) {
        lua_gc( L, LUA_GCRESTART );
        BringupUnlock( );
        ThrSetError( Ctx, "thread worker: trampoline unresolved" );
        lua_close( L );
        SetEvent( Ctx->DoneEvent );
        Jit_WorkerCacheEnd( );
        return 1;
    }
    AotPushClosure( L, Wm );
    lua_gc( L, LUA_GCRESTART );                /* safe now: the proto tree is rooted */
    BringupUnlock( );                         /* state is built; the work runs concurrently */

    lua_pushinteger( L, Ctx->WorkerFnId );
    lua_pushlstring( L, Ctx->ArgsBlob ? Ctx->ArgsBlob : "", ( size_t )Ctx->ArgsLen );
    St = lua_pcall( L, 2, 1, 0 );             /* worker_main(fn_id, args_blob) -> string */

    if ( St == LUA_OK && lua_type( L, -1 ) == LUA_TSTRING ) {
        size_t      len = 0;
        const char *s   = lua_tolstring( L, -1, &len );
        char       *p   = ( char * )malloc( len > 0 ? len : 1 );
        if ( p != NULL ) {
            if ( len > 0 ) memcpy( p, s, len );
            Ctx->Result.Payload    = p;
            Ctx->Result.PayloadLen = ( int )len;
        }
        Ctx->Result.Status = 1;
    } else {
        const char *msg = ( St != LUA_OK ) ? lua_tostring( L, -1 ) : NULL;
        ThrSetError( Ctx, msg ? msg : "thread worker: trampoline returned non-string" );
    }

    lua_close( L );
    Jit_WorkerCacheEnd( );
    SetEvent( Ctx->DoneEvent );               /* full barrier: result is visible to join */
    return 0;
}

/* _clua.spawn_native(worker_main, worker_fn, args_blob)
     -> handle (lightuserdata) | nil, err
   worker_main is thread.lua's trampoline; worker_fn is the user function. */
static int Clua_SpawnNative( lua_State *L ) {
    Proto      *Wmp = AotArgProto( L, 1 );
    Proto      *Wfp = AotArgProto( L, 2 );
    size_t      blen = 0;
    const char *blob;
    CluaThrCtx *Ctx;
    int         WmId, WfId;

    if ( Wmp == NULL || Wfp == NULL ) {
        lua_pushnil( L ); lua_pushstring( L, "spawn_native: expected compiled functions" );
        return 2;
    }
    WmId = Jit_ProtoFuncId( Wmp );
    WfId = Jit_ProtoFuncId( Wfp );
    if ( WmId < 0 || WfId < 0 ) {
        lua_pushnil( L ); lua_pushstring( L, "spawn_native: function not registered" );
        return 2;
    }
    if ( !AotFnShippable( Wfp ) ) {
        lua_pushnil( L ); lua_pushstring( L, "spawn_native: worker captures upvalues" );
        return 2;
    }
    blob = lua_tolstring( L, 3, &blen );

    Ctx = ( CluaThrCtx * )calloc( 1, sizeof( CluaThrCtx ) );
    if ( Ctx == NULL ) { lua_pushnil( L ); lua_pushstring( L, "spawn_native: out of memory" ); return 2; }
    Ctx->WorkerMainId = WmId;
    Ctx->WorkerFnId   = WfId;
    if ( blen > 0 && blob != NULL ) {
        Ctx->ArgsBlob = ( char * )malloc( blen );
        if ( Ctx->ArgsBlob == NULL ) { free( Ctx ); lua_pushnil( L ); lua_pushstring( L, "spawn_native: oom" ); return 2; }
        memcpy( Ctx->ArgsBlob, blob, blen );
        Ctx->ArgsLen = ( int )blen;
    }
    Ctx->DoneEvent = CreateEventW( NULL, TRUE, FALSE, NULL );   /* manual-reset */
    if ( Ctx->DoneEvent == NULL ) {
        free( Ctx->ArgsBlob ); free( Ctx );
        lua_pushnil( L ); lua_pushstring( L, "spawn_native: CreateEvent failed" );
        return 2;
    }
    Ctx->Thread = ( HANDLE )_beginthreadex( NULL, 0, Clua_ThreadBootstrap, Ctx, 0, NULL );
    if ( Ctx->Thread == NULL ) {
        CloseHandle( Ctx->DoneEvent ); free( Ctx->ArgsBlob ); free( Ctx );
        lua_pushnil( L ); lua_pushstring( L, "spawn_native: thread create failed" );
        return 2;
    }
    lua_pushlightuserdata( L, Ctx );          /* the handle */
    return 1;
}

/* _clua.join_native(handle, timeout_ms?) -> ok(bool), payload(string)
   Blocks (timeout_ms < 0 / nil = INFINITE), then frees the handle. Must be
   called at most once per handle (thread.lua memoizes). */
static int Clua_JoinNative( lua_State *L ) {
    CluaThrCtx *Ctx = ( CluaThrCtx * )lua_touserdata( L, 1 );
    lua_Integer to  = luaL_optinteger( L, 2, -1 );
    DWORD       ms  = ( to < 0 ) ? INFINITE : ( DWORD )to;
    DWORD       r;
    if ( Ctx == NULL ) { lua_pushnil( L ); lua_pushstring( L, "join: bad handle" ); return 2; }
    r = WaitForSingleObject( Ctx->Thread, ms );
    if ( r == WAIT_TIMEOUT )   { lua_pushnil( L ); lua_pushstring( L, "timeout" ); return 2; }
    if ( r != WAIT_OBJECT_0 )  { lua_pushnil( L ); lua_pushstring( L, "wait failed" ); return 2; }

    if ( Ctx->Result.Status == 1 ) {
        lua_pushboolean( L, 1 );
        lua_pushlstring( L, Ctx->Result.Payload ? Ctx->Result.Payload : "",
                         ( size_t )Ctx->Result.PayloadLen );
    } else {
        lua_pushboolean( L, 0 );
        lua_pushstring( L, Ctx->Result.Payload ? Ctx->Result.Payload : "worker error" );
    }
    CloseHandle( Ctx->Thread );
    CloseHandle( Ctx->DoneEvent );
    free( Ctx->ArgsBlob );
    free( Ctx->Result.Payload );
    free( Ctx );
    return 2;
}

/* _clua.alive_native(handle) -> bool (still running) */
static int Clua_AliveNative( lua_State *L ) {
    CluaThrCtx *Ctx = ( CluaThrCtx * )lua_touserdata( L, 1 );
    if ( Ctx == NULL ) { lua_pushboolean( L, 0 ); return 1; }
    lua_pushboolean( L, WaitForSingleObject( Ctx->Thread, 0 ) == WAIT_TIMEOUT );
    return 1;
}

/* ---- cross-state value (de)serialization ---------------------------------
   Worker args + results cross the lua_State boundary as bytes. The worker
   trampoline must be shippable (capture nothing but _ENV), so it cannot close
   over a Lua serializer -- these live in C and are reached as _clua.serialize /
   _clua.deserialize (globals) on both sides. Supported: nil, boolean, integer,
   float, string, and table (recursive, any of these as keys). A function /
   userdata / cdata / thread is unsupported -> serialize fails and thread.lua
   falls back to cooperative spawning. */
#define CLUA_SER_MAXDEPTH 32

typedef struct { char *P; size_t Len, Cap; int Ok; } CluaSBuf;

static void SbufPut( CluaSBuf *B, const void *Data, size_t N ) {
    if ( !B->Ok ) return;
    if ( B->Len + N > B->Cap ) {
        size_t nc = B->Cap ? B->Cap * 2 : 64;
        char  *np;
        while ( nc < B->Len + N ) nc *= 2;
        np = ( char * )realloc( B->P, nc );
        if ( np == NULL ) { B->Ok = 0; return; }
        B->P = np; B->Cap = nc;
    }
    memcpy( B->P + B->Len, Data, N );
    B->Len += N;
}
static void SbufByte( CluaSBuf *B, unsigned char C ) { SbufPut( B, &C, 1 ); }

static int SerOne( lua_State *L, int Idx, CluaSBuf *B, int Depth ) {
    if ( Depth > CLUA_SER_MAXDEPTH ) return 0;
    switch ( lua_type( L, Idx ) ) {
        case LUA_TNIL:     SbufByte( B, 'n' ); return 1;
        case LUA_TBOOLEAN: SbufByte( B, 'b' );
                           SbufByte( B, ( unsigned char )lua_toboolean( L, Idx ) ); return 1;
        case LUA_TNUMBER:
            if ( lua_isinteger( L, Idx ) ) {
                int64_t v = ( int64_t )lua_tointeger( L, Idx );
                SbufByte( B, 'i' ); SbufPut( B, &v, 8 );
            } else {
                double v = ( double )lua_tonumber( L, Idx );
                SbufByte( B, 'd' ); SbufPut( B, &v, 8 );
            }
            return 1;
        case LUA_TSTRING: {
            size_t      len = 0;
            const char *s   = lua_tolstring( L, Idx, &len );
            uint32_t    n   = ( uint32_t )len;
            SbufByte( B, 's' ); SbufPut( B, &n, 4 ); SbufPut( B, s, len );
            return 1;
        }
        case LUA_TTABLE: {
            int      t      = lua_absindex( L, Idx );
            uint32_t cnt    = 0, zero = 0;
            size_t   cntpos;
            SbufByte( B, 't' );
            cntpos = B->Len;
            SbufPut( B, &zero, 4 );             /* patched with the pair count below */
            lua_pushnil( L );
            while ( lua_next( L, t ) != 0 ) {
                if ( !SerOne( L, -2, B, Depth + 1 ) ) { lua_pop( L, 2 ); return 0; }
                if ( !SerOne( L, -1, B, Depth + 1 ) ) { lua_pop( L, 2 ); return 0; }
                cnt++;
                lua_pop( L, 1 );                /* drop value, keep key for lua_next */
            }
            if ( B->Ok && cntpos + 4 <= B->Len ) memcpy( B->P + cntpos, &cnt, 4 );
            return 1;
        }
        default: return 0;                       /* function / userdata / thread / cdata */
    }
}

static int Clua_Serialize( lua_State *L ) {
    CluaSBuf b = { NULL, 0, 0, 1 };
    if ( !SerOne( L, 1, &b, 0 ) || !b.Ok ) {
        free( b.P );
        lua_pushnil( L );
        lua_pushstring( L, "serialize: unsupported value" );
        return 2;
    }
    lua_pushlstring( L, b.P ? b.P : "", b.Len );
    free( b.P );
    return 1;
}

typedef struct { const char *P; size_t Len, Off; int Ok; } CluaRd;

static unsigned char RdByte( CluaRd *R ) {
    if ( R->Off + 1 > R->Len ) { R->Ok = 0; return 0; }
    return ( unsigned char )R->P[ R->Off++ ];
}
static void RdRaw( CluaRd *R, void *Out, size_t N ) {
    if ( R->Off + N > R->Len ) { R->Ok = 0; memset( Out, 0, N ); return; }
    memcpy( Out, R->P + R->Off, N ); R->Off += N;
}

static int DeOne( lua_State *L, CluaRd *R, int Depth ) {
    unsigned char tag;
    if ( Depth > CLUA_SER_MAXDEPTH ) return 0;
    if ( !lua_checkstack( L, 4 ) ) return 0;
    tag = RdByte( R );
    if ( !R->Ok ) return 0;
    switch ( tag ) {
        case 'n': lua_pushnil( L ); return 1;
        case 'b': { unsigned char v = RdByte( R ); if ( !R->Ok ) return 0;
                    lua_pushboolean( L, v ); return 1; }
        case 'i': { int64_t v; RdRaw( R, &v, 8 ); if ( !R->Ok ) return 0;
                    lua_pushinteger( L, ( lua_Integer )v ); return 1; }
        case 'd': { double v; RdRaw( R, &v, 8 ); if ( !R->Ok ) return 0;
                    lua_pushnumber( L, ( lua_Number )v ); return 1; }
        case 's': { uint32_t n; RdRaw( R, &n, 4 ); if ( !R->Ok ) return 0;
                    if ( R->Off + n > R->Len ) return 0;
                    lua_pushlstring( L, R->P + R->Off, n ); R->Off += n; return 1; }
        case 't': {
            uint32_t cnt, i;
            RdRaw( R, &cnt, 4 ); if ( !R->Ok ) return 0;
            lua_newtable( L );
            for ( i = 0; i < cnt; i++ ) {
                if ( !DeOne( L, R, Depth + 1 ) ) return 0;                /* key */
                if ( !DeOne( L, R, Depth + 1 ) ) { lua_pop( L, 1 ); return 0; } /* value */
                lua_settable( L, -3 );
            }
            return 1;
        }
        default: return 0;
    }
}

static int Clua_Deserialize( lua_State *L ) {
    size_t      len = 0;
    const char *s   = lua_tolstring( L, 1, &len );
    CluaRd      r;
    if ( s == NULL ) { lua_pushnil( L ); return 1; }
    r.P = s; r.Len = len; r.Off = 0; r.Ok = 1;
    if ( !DeOne( L, &r, 0 ) ) {
        lua_pushnil( L ); lua_pushstring( L, "deserialize: malformed blob" );
        return 2;
    }
    return 1;
}

/* Register the `_clua` internal library. Called in both the main bring-up and
   every worker bring-up. */
static void Clua_OpenInternal( lua_State *L ) {
    lua_createtable( L, 0, 7 );
    lua_pushcfunction( L, Clua_FnId );        lua_setfield( L, -2, "fn_id" );
    lua_pushcfunction( L, Clua_ResolveFn );   lua_setfield( L, -2, "resolve_fn" );
    lua_pushcfunction( L, Clua_SpawnNative ); lua_setfield( L, -2, "spawn_native" );
    lua_pushcfunction( L, Clua_JoinNative );  lua_setfield( L, -2, "join_native" );
    lua_pushcfunction( L, Clua_AliveNative ); lua_setfield( L, -2, "alive_native" );
    lua_pushcfunction( L, Clua_Serialize );   lua_setfield( L, -2, "serialize" );
    lua_pushcfunction( L, Clua_Deserialize ); lua_setfield( L, -2, "deserialize" );
    lua_setglobal( L, "_clua" );
}

int main( int argc, char **argv ) {
    lua_State *L = luaL_newstate( );
    if ( L == NULL ) {
        fprintf( stderr, "clua: cannot create state\n" );
        return 1;
    }
    luaL_openlibs( L );                       /* installs print, etc. into _G */

    /* Build the `arg` global exactly as v1's PushArgTable does
     * (runtime_init.c): arg[1..argc-1], no arg[0] -- interpreter parity. */
    {
        int i;
        lua_createtable( L, argc - 1, 0 );
        for ( i = 1; i < argc; i++ ) {
            lua_pushstring( L, argv[ i ] );
            lua_rawseti( L, -2, i );
        }
        lua_setglobal( L, "arg" );
    }

    Coro_OpenLib( L );                        /* replace stock coroutine with the
                                                 fiber-based lib (native code can
                                                 yield across call frames), as v1's
                                                 RuntimeMain does (runtime_init.c) */
    if ( &Clua_OpenFfi != NULL ) {            /* ffi/bit referenced: anchor linked */
        Clua_OpenFfi( L );
    }
    clua_dispatch_hook = AotLookupHook;   /* AOT dispatch (lookup-only)   */
    Jit_InitWorkerTls( );                 /* one-time: TLS slot for native worker caches */
    Clua_OpenInternal( L );               /* _clua: fn_id / resolve_fn / spawn_native ... */

    /* Build every Proto + register each luac_fn_* body; returns the entry.
     * GC MUST be stopped across the build (AOT-MULTIMOD-001): the Protos
     * under construction are white and unanchored until the entry closure /
     * package.preload closures root them, so a collection cycle completing
     * mid-build (guaranteed once a program's blob allocation volume is large
     * enough) sweeps them and the exe runs on freed memory. */
    lua_gc( L, LUA_GCSTOP );
    Proto *entry = LuacProgram_BuildEntry( L );
    if ( entry == NULL ) {
        fprintf( stderr, "clua: build entry failed\n" );
        lua_close( L );
        return 1;
    }

    /* Create the entry closure and bind its _ENV upvalue to the globals
     * table, exactly as lua_load does for a main chunk (lapi.c f_Lua path:
     * setobj(L, f->upvals[0]->v.p, getGtable(L)); luaC_barrier(...)). */
    LClosure *cl = luaF_newLclosure( L, entry->sizeupvalues );
    cl->p = entry;
    setclLvalue2s( L, L->top.p, cl );         /* push the closure            */
    L->top.p++;
    luaF_initupvals( L, cl );                 /* allocate fresh upvalue boxes */
    if ( entry->sizeupvalues >= 1 ) {         /* bind upvalue 0 (_ENV)        */
        /* getGtable(L): the globals table lives in the registry at the fixed
         * index LUA_RIDX_GLOBALS (array part, 1-based -> array[idx-1]). This
         * is the exact accessor the real Lua loader uses. */
        const TValue *gt =
            &hvalue( &G( L )->l_registry )->array[ LUA_RIDX_GLOBALS - 1 ];
        setobj( L, cl->upvals[ 0 ]->v.p, gt );
        luaC_barrier( L, cl->upvals[ 0 ], gt );
    }
    lua_gc( L, LUA_GCRESTART );   /* everything is rooted now: the entry tree
                                     via the closure on the stack, required
                                     modules via package.preload */

    /* Install the traceback handler UNDER the entry closure, then invoke it
     * like a normal call; luaV_execute's hook dispatches to the entry's
     * registered AOT body (luac_fn_<entry>). */
    lua_pushcfunction( L, AotMsgHandler );
    lua_insert( L, -2 );                      /* [handler, closure] */
    int status = lua_pcall( L, 0, 0, -2 );
    if ( status != LUA_OK ) {
        const char *msg = lua_tostring( L, -1 );
        /* "<progname>: <message>\n<traceback>" -- reference-Lua format. msg
         * already carries the traceback (AotMsgHandler ran under the call). */
        fprintf( stderr, "%s: %s\n", AotProgName( argv[ 0 ] ),
                 msg ? msg : "(unknown)" );
        lua_close( L );
        return 1;
    }

    lua_close( L );
    return 0;
}
