/*!
 * @file aot_entry.c
 * @brief
 *  AOT program entry: the main() of every compiled LuaC program.
 *
 *  Unlike v1's RuntimeMain (runtime_init.c), there is NO embedded bytecode
 *  blob, NO embedded packages, NO native-DLL bootstrap and NO blob crypto/
 *  decompress passes -- those symbols (g_LuaBlob, Runtime_GetPackages,
 *  EmbeddedLoader_*, InstallEmbeddedPackages, Native_Bootstrap) do not exist
 *  in an AOT program and referencing them would break the link.
 *
 *  Instead, the program's function bodies are compiled to native code ahead
 *  of time and emitted as luac_fn_<id> symbols. At startup we:
 *      1. stand up a Lua state and open the standard libraries,
 *      2. install a lookup-only dispatch hook so luaV_execute routes a Lua
 *         closure call to its pre-registered AOT body (no JIT at runtime),
 *      3. call the generated LuacProgram_BuildEntry, which reconstructs every
 *         Proto and registers each one's luac_fn_<id> into the dispatch cache
 *         (via Jit_RegisterCompiled), returning the main-chunk Proto,
 *      4. build the entry LClosure, bind its _ENV upvalue to the globals table
 *         exactly as lua_load does for a main chunk, and
 *      5. invoke it with a normal lua_pcall -- luaV_execute's hook then
 *         dispatches to the entry body.
 *
 *  Coroutines: fiber-based lib installed below (Coro_OpenLib). VEH and the
 *  FFI are deliberately NOT initialized in AOT programs today — no FFI means
 *  no foreign threads/faulting stubs (and ~25 KB less per exe); FFI-in-exes
 *  is an M4 item alongside builtin-package bundling.
 */

#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include "lstate.h"
#include "lobject.h"
#include "lfunc.h"
#include "lgc.h"
#include "ldo.h"
#include "lvm.h"        /* clua_dispatch_hook + clua_dispatch_t typedef */

#include "jit/dispatch.h"
#include "runtime/coro.h"   /* fiber-based coroutines so native code can yield */

#include "lzio.h"           /* closed-world stub signatures (luaY_parser/luaU_*) */
#include "llex.h"
#include "lparser.h"
#include "lundump.h"

#include <stdio.h>

/* Generated by the AOT codegen (Task 13): reconstructs all Protos, registers
 * their native bodies into the dispatch cache, and returns the main-chunk
 * Proto (the program entry). Unresolved at `-c` time; linked in for real by
 * the program build. */
extern Proto *LuacProgram_BuildEntry( lua_State *L );

/*!
 * @brief
 *  Lookup-only dispatch hook installed into clua_dispatch_hook.
 *
 *  luaV_execute (lvm.c:1199) calls this with the callee closure's Proto*; we
 *  return the pre-registered AOT body for that Proto (or NULL). We use
 *  Jit_LookupCached -- NEVER Jit_Compile -- because AOT bodies are registered
 *  up front by LuacProgram_BuildEntry and there is no JIT in an AOT program.
 *
 *  Signature matches clua_dispatch_t == void *(*)(lua_State *, void *).
 */
static void *AotLookupHook( lua_State *L, void *proto ) {
    ( void )L;
    return ( void * )Jit_LookupCached( ( Proto * )proto );
}

/* FFI bring-up, linked only when the program references ffi/bit (the driver
 * adds -Wl,--undefined=Clua_OpenFfi then; see ffi_anchor.c). Weak: NULL when
 * the anchor isn't in the link. */
extern void Clua_OpenFfi( lua_State *L ) __attribute__(( weak ));

/* Message handler installed under the entry call: appends a stack traceback
 * to the error object while the call chain is still live, so an uncaught
 * runtime error reports like the reference interpreter does
 * (AOT-ERRBANNER-001 narrowed; the banner prefix still differs). */
static int AotMsgHandler( lua_State *L ) {
    const char *msg = lua_tostring( L, 1 );
    if ( msg == NULL ) {
        if ( luaL_callmeta( L, 1, "__tostring" ) &&
             lua_type( L, -1 ) == LUA_TSTRING ) {
            return 1;
        }
        msg = lua_pushfstring( L, "(error object is a %s value)",
                               luaL_typename( L, 1 ) );
    }
    luaL_traceback( L, L, msg, 1 );
    return 1;
}

/* Closed-world stubs (AOT-CLOSEDWORLD-002): luaY_parser/luaU_undump/
** luaU_dump/luaX_init. Textually included so aot_entry.o keeps defining
** them ahead of the archives on the static link line (unchanged), while
** the SAME source compiles standalone into clua-rt.dll for --shared-rt
** builds. The stub bodies + full rationale live in that file. */
#include "closed_world_stubs.c"

int main( int argc, char **argv ) {
    lua_State *L = luaL_newstate( );
    if ( L == NULL ) {
        fprintf( stderr, "clua: cannot create state\n" );
        return 1;
    }
    luaL_openlibs( L );                       /* installs print, etc. into _G */

    /* Build the `arg` global exactly as v1's PushArgTable does
     * (runtime_init.c): arg[1..argc-1], no arg[0] -- interpreter parity. */
    {
        int i;
        lua_createtable( L, argc - 1, 0 );
        for ( i = 1; i < argc; i++ ) {
            lua_pushstring( L, argv[ i ] );
            lua_rawseti( L, -2, i );
        }
        lua_setglobal( L, "arg" );
    }

    Coro_OpenLib( L );                        /* replace stock coroutine with the
                                                 fiber-based lib (native code can
                                                 yield across call frames), as v1's
                                                 RuntimeMain does (runtime_init.c) */
    if ( &Clua_OpenFfi != NULL ) {            /* ffi/bit referenced: anchor linked */
        Clua_OpenFfi( L );
    }
    clua_dispatch_hook = AotLookupHook;   /* AOT dispatch (lookup-only)   */

    /* Build every Proto + register each luac_fn_* body; returns the entry.
     * GC MUST be stopped across the build (AOT-MULTIMOD-001): the Protos
     * under construction are white and unanchored until the entry closure /
     * package.preload closures root them, so a collection cycle completing
     * mid-build (guaranteed once a program's blob allocation volume is large
     * enough) sweeps them and the exe runs on freed memory. */
    lua_gc( L, LUA_GCSTOP );
    Proto *entry = LuacProgram_BuildEntry( L );
    if ( entry == NULL ) {
        fprintf( stderr, "clua: build entry failed\n" );
        lua_close( L );
        return 1;
    }

    /* Create the entry closure and bind its _ENV upvalue to the globals
     * table, exactly as lua_load does for a main chunk (lapi.c f_Lua path:
     * setobj(L, f->upvals[0]->v.p, getGtable(L)); luaC_barrier(...)). */
    LClosure *cl = luaF_newLclosure( L, entry->sizeupvalues );
    cl->p = entry;
    setclLvalue2s( L, L->top.p, cl );         /* push the closure            */
    L->top.p++;
    luaF_initupvals( L, cl );                 /* allocate fresh upvalue boxes */
    if ( entry->sizeupvalues >= 1 ) {         /* bind upvalue 0 (_ENV)        */
        /* getGtable(L): the globals table lives in the registry at the fixed
         * index LUA_RIDX_GLOBALS (array part, 1-based -> array[idx-1]). This
         * is the exact accessor the real Lua loader uses. */
        const TValue *gt =
            &hvalue( &G( L )->l_registry )->array[ LUA_RIDX_GLOBALS - 1 ];
        setobj( L, cl->upvals[ 0 ]->v.p, gt );
        luaC_barrier( L, cl->upvals[ 0 ], gt );
    }
    lua_gc( L, LUA_GCRESTART );   /* everything is rooted now: the entry tree
                                     via the closure on the stack, required
                                     modules via package.preload */

    /* Install the traceback handler UNDER the entry closure, then invoke it
     * like a normal call; luaV_execute's hook dispatches to the entry's
     * registered AOT body (luac_fn_<entry>). */
    lua_pushcfunction( L, AotMsgHandler );
    lua_insert( L, -2 );                      /* [handler, closure] */
    int status = lua_pcall( L, 0, 0, -2 );
    if ( status != LUA_OK ) {
        const char *msg = lua_tostring( L, -1 );
        fprintf( stderr, "clua: runtime error: %s\n",
                 msg ? msg : "(unknown)" );
        lua_close( L );
        return 1;
    }

    lua_close( L );
    return 0;
}
