# Embed the pure-Lua lint package source into a C header so compiler.exe can
# run it as the diagnostics engine (syntax check + warnings) without shipping
# the repo. Emits an uncompressed byte array -- lint/init.lua is ~20 KB, small
# enough that compression isn't worth pulling the decompressor into the
# compiler. Regenerated by the Makefile whenever lint/init.lua changes.
param(
    [Parameter(Mandatory = $true)] [string] $In,
    [Parameter(Mandatory = $true)] [string] $Out
)

$ErrorActionPreference = "Stop"

$bytes = [System.IO.File]::ReadAllBytes($In)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* AUTO-GENERATED from $([System.IO.Path]::GetFileName($In)) by tools/gen-lint-header.ps1 -- do not edit. */")
[void]$sb.AppendLine("#ifndef CLUA_GEN_LINT_SRC_H")
[void]$sb.AppendLine("#define CLUA_GEN_LINT_SRC_H")
[void]$sb.AppendLine("static const unsigned char g_LintSource[] = {")

$line = "    "
for ($i = 0; $i -lt $bytes.Length; $i++) {
    $line += "0x{0:x2}," -f $bytes[$i]
    if ((($i + 1) % 16) -eq 0) {
        [void]$sb.AppendLine($line)
        $line = "    "
    }
}
if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line) }
# Trailing NUL so (const char *)g_LintSource is a valid C string for strlen().
# g_LintSourceLen below is the content length, excluding this terminator.
[void]$sb.AppendLine("    0x00")

[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const unsigned int g_LintSourceLen = $($bytes.Length)u;")
[void]$sb.AppendLine("#endif /* CLUA_GEN_LINT_SRC_H */")

# ASCII, no BOM -- gcc is happy and the file diffs cleanly.
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($Out, $sb.ToString(), $enc)
Write-Host "[*] gen-lint-header: $($bytes.Length) bytes -> $Out"
