-- parse_return_table test: the closed-world literal-table parser that replaced
-- the four load() sites in rover (package-manager/src/luavm-pkg.lua) so the
-- package manager compiles under aotc.exe (which bans the global `load`).
-- Pure-logic checks use the $LUAVM_PKG_TEST export hook; a final end-to-end
-- check asserts the rebranded usage banner. Run from the repo root by luavm.exe.

local function abscwd()
  local p = io.popen("cd"); if not p then return "." end
  local d = p:read("*a") or ""; p:close(); return (d:gsub("%s+$", ""))
end
local ROOT  = abscwd()
local LUAVM = ROOT .. "\\build\\bin\\luavm.exe"
local PKG   = ROOT .. "\\package-manager\\src\\luavm-pkg.lua"

local function slurp(p) local f = io.open(p, "rb"); if not f then return nil end local s = f:read("*a"); f:close(); return s end
local function spit(p, s) local f = io.open(p, "wb"); if not f then return false end f:write(s); f:close(); return true end
local function fail(m) print("[-] FAIL test-pkgmgr-parse: " .. m); os.exit(1) end

----------------------------------------------------------------------
-- A) parse_return_table unit tests via the test-export hook.
----------------------------------------------------------------------
do
  local driver = (os.getenv("TEMP") or ".") .. "\\luavm-parsedriver.lua"
  spit(driver, [==[
dofile("package-manager/src/luavm-pkg.lua")
local M = _G.LUAVM_PKG
-- the hook must keep its existing exports AND export the parser
for _, k in ipairs({ "name_ok", "parse_semver", "registry_ok", "semver_cmp",
                     "semver_satisfies", "parse_return_table" }) do
  if type(M[k]) ~= "function" then print("FAILCASE:export-" .. k); os.exit(7) end
end
local P = M.parse_return_table
local function ok(cond, label)
  if not cond then print("FAILCASE:" .. label); os.exit(7) end
end
local function bad(src, label)
  if P(src) ~= nil then print("FAILCASE:" .. label); os.exit(7) end
end

-- 1) plain manifest shape (write_manifest output)
local t = P('return {\n  name = "pkg",\n  version = "1.2.3",\n  description = "hi",\n  hash = "ab",\n  tree = "",\n}\n')
ok(type(t) == "table" and t.name == "pkg" and t.version == "1.2.3"
   and t.description == "hi" and t.hash == "ab" and t.tree == "", "plain-manifest")

-- 2) comments, whitespace, trailing comma, single quotes, booleans, numbers
t = P("-- header comment\n-- second line\nreturn { -- inline\n  a = 'single', -- after a field\n  n = 42, f = 1.5, neg = -7, yes = true, no = false,\n}\n")
ok(t and t.a == "single" and t.n == 42 and t.f == 1.5 and t.neg == -7
   and t.yes == true and t.no == false, "comments-trailing-comma")

-- 3) bracket keys + nesting (2 levels deep)
t = P('return { ["a-b"] = "^1.0.0", deps = { ["x.y"] = "~2", inner = { deep = "ok" } } }')
ok(t and t["a-b"] == "^1.0.0" and t.deps["x.y"] == "~2" and t.deps.inner.deep == "ok", "brackets-nesting")

-- 4) escape decoding: \" \' \\ \r \t literal \ddd and zero-padded \000
t = P([[return { s = "q\"q \'x\' b\\b r\rr t\tt abc\65\66\67 pad\0009" }]])
ok(t and t.s == "q\"q 'x' b\\b r\rr t\tt abcABC pad\0009", "escape-decoding")

-- 5) backslash-newline (%q's encoding of a newline) decodes to \n
t = P('return { s = "line1\\\nline2" }')
ok(t and t.s == "line1\nline2", "backslash-newline")

-- 6) %q round-trip, write_manifest style (quotes, backslashes, \n, \r, ctrl)
local nasty = 'he said "hi" \\path\\x\nnext\rline\ttab\1ctrl and \250 high'
local txt = string.format(
  "return {\n  name = %q,\n  version = %q,\n  description = %q,\n  hash = %q,\n  tree = %q,\n}\n",
  "p-k_g.1", "1.2.3", nasty, "deadbeef", "")
t = P(txt)
ok(t and t.name == "p-k_g.1" and t.version == "1.2.3" and t.description == nasty
   and t.hash == "deadbeef" and t.tree == "", "q-roundtrip-manifest")

-- 7) lock-shape round-trip (header comments + bracket keys + nested deps)
local lock = '-- luavm.lock -- resolved dependency versions + content hashes.\n'
          .. '-- Generated by rover; do not edit by hand.\n'
          .. 'return {\n'
          .. '  ["leaf"] = { version = "1.0.0", hash = "ab12", tree = "cd34", deps = { ["x-y"] = "^1.0.0", ["z"] = "*" } },\n'
          .. '  ["mid"] = { version = "2.0.0", hash = "ef56" },\n'
          .. '}\n'
t = P(lock)
ok(t and t["leaf"] and t["leaf"].version == "1.0.0" and t["leaf"].tree == "cd34"
   and t["leaf"].deps["x-y"] == "^1.0.0" and t["leaf"].deps.z == "*"
   and t["mid"].hash == "ef56", "lock-shape")

-- 8) array part tolerated; empty table
t = P('return { "a", "b", k = "v" }')
ok(t and t[1] == "a" and t[2] == "b" and t.k == "v", "array-part")
t = P('return {}')
ok(type(t) == "table" and next(t) == nil, "empty-table")

-- failures: anything non-literal must yield nil (and never raise)
bad('return { x = 1+1 }',            'computed-arith')
bad('return { x = foo() }',          'function-call')
bad('return { x = os.exit(1) }',     'method-call')
bad('return { x = "a" .. "b" }',     'concat')
bad('return { x = bare }',           'identifier-value')
bad('return { x = "unterminated }',  'unterminated-string')
bad('return { x = "a"',              'unbalanced-brace')
bad('return { a = { b = "c" }',      'unbalanced-nested')
bad('os.exit(1)',                    'not-a-return')
bad('return "x"',                    'return-non-table')
bad('return {} return {}',           'trailing-garbage')
bad('return { x = "bad\\q" }',       'unknown-escape')
bad('return { ["k" = "v" }',         'bad-bracket-key')
bad('',                              'empty-input')
-- and every bad case above must not raise either
for _, s in ipairs({ 'return { x = 1+1 }', 'return { x = foo() }', '{', 'return [' }) do
  local pc = pcall(P, s)
  if not pc then print("FAILCASE:raised-" .. s); os.exit(7) end
end
print("PARSE_OK")
]==])
  local p = io.popen('set "LUAVM_PKG_TEST=1" && "' .. LUAVM .. '" -i "' .. driver .. '" 2>&1')
  local out = p and p:read("*a") or ""; if p then p:close() end
  os.remove(driver)
  if not out:match("PARSE_OK") then fail("parser checks failed: " .. (out:gsub("%s+", " "))) end
end

----------------------------------------------------------------------
-- B) Rebrand: the usage banner identifies the tool as rover (CLua).
----------------------------------------------------------------------
do
  local outf = (os.getenv("TEMP") or ".") .. "\\rover-usage.txt"
  os.execute('""' .. LUAVM .. '" -i "' .. PKG .. '" > "' .. outf .. '" 2>&1"')
  local usage = slurp(outf) or ""
  os.remove(outf)
  if not usage:match("rover %-%- the CLua package manager") then
    fail("usage banner is not rebranded to rover")
  end
  if usage:match("LuaVM package manager") then
    fail("usage banner still says 'LuaVM package manager'")
  end
end

print("[+] PASS test-pkgmgr-parse (closed-world literal parser: %q round-trips, lock shape, comments; non-literals -> nil; rover banner)")
os.exit(0)
