-- imgui: full Dear ImGui surface bound to Lua via cimgui.
--
-- All ~1200 cimgui functions are reachable as `imgui.<Name>` (matching the
-- C++ API spelling -- imgui.Begin, imgui.Button, imgui.SliderFloat, ...).
-- Enums become tables (imgui.Col.Text, imgui.StyleVar.WindowRounding, ...).
-- Field-accessible structs (ImGuiIO, ImGuiStyle, ImFontAtlas, ImFontConfig,
-- ImDrawList, ImDrawData, ...) are reachable through their accessors --
-- imgui.GetIO(), imgui.GetStyle() -- and their fields are normal FFI cdata
-- so style.Colors[imgui.Col.Text].x = 1.0 just works.
--
-- The compiler auto-detects `require("imgui")` and links imgui.a (Dear
-- ImGui + cimgui + Win32 + DX11 + host shim). cimgui's symbols are
-- dllexport'd; the link line passes --export-all-symbols, so every cimgui
-- entry point is in the exe's PE export table where ffi.C can find it via
-- GetProcAddress on the main module handle.
--
-- The runtime preload `imgui_bindings` (generated by
-- tools/gen-imgui-bindings.py) provides the cdef text + an array of wrap
-- specs that this module turns into Lua functions.
--
-- Lifecycle (always available, talks to imgui_host.cpp):
--   imgui.init(title, w, h)         -- create window + D3D11 + ImGui context
--   imgui.pump_events()             -- returns true when window wants close
--   imgui.new_frame()               -- backend new-frame + ImGui::NewFrame
--   imgui.render(r, g, b, a)        -- ImGui::Render + clear + present
--   imgui.shutdown()                -- tear it all down

local function MakeImGui()
    assert(ffi, "imgui needs ffi")
    local bindings = require("imgui_bindings")

    -- ---- 1. Register the full cimgui cdef --------------------------------
    ffi.cdef(bindings.__cdef)

    -- Lifecycle entry points from src/runtime/native/imgui_host.cpp. These
    -- get dllexport'd through the same --export-all-symbols path so ffi.C
    -- finds them on the main module.
    ffi.cdef[[
    int   LuaVM_ImGuiHost_Init(const char *title_utf8, int width, int height);
    int   LuaVM_ImGuiHost_PumpEvents(void);
    void  LuaVM_ImGuiHost_NewFrame(void);
    void  LuaVM_ImGuiHost_Render(float r, float g, float b, float a);
    void  LuaVM_ImGuiHost_Shutdown(void);
    int   LuaVM_ImGuiHost_Version(void);
    void *LuaVM_ImGuiHost_GetD3DDevice(void);
    void *LuaVM_ImGuiHost_GetD3DContext(void);
    void  LuaVM_ImGuiHost_RebuildFontAtlas(void);
    ]]

    -- Known FFI gap: cimgui declares ImGuiViewport as a forward-only
    -- opaque tag in bindings.lua and exposes only the GetCenter /
    -- GetWorkCenter helpers, no Pos/Size/WorkPos/WorkSize accessor.
    -- Completing the struct from the Lua side via ffi.cdef doesn't
    -- work today (our cdef parser doesn't fully support nested-struct-
    -- by-value fields like `ImVec2 Pos;` and doesn't allow completing
    -- an already-forward-typedef'd struct). Callers that need
    -- viewport-sized windows should use SetNextWindowSize with explicit
    -- pixel dimensions and the "Once" condition for the initial frame
    -- (see examples/revshell-handler/main.lua for the pattern). When
    -- the cdef parser grows that support, ImGuiViewport access can be
    -- added here without touching call sites.

    local C = ffi.C

    -- ---- 2. ImVec2/ImVec4 constructors -----------------------------------
    -- Two ImVec2 builders -- pick by what you'll do with the result:
    --
    --   imgui.ImVec2(x, y) -> uint64  (PACKED -- for FFI args)
    --       Win64 ABI passes ImVec2 (8 bytes) in a single integer
    --       register, ABI-compatible with a uint64. The cdef declares
    --       cimgui's ImVec2-by-value args as `uint64_t`, so this is
    --       what you pass to imgui.Begin/Button/SetCursorPos/etc.
    --       Cheap (re-used scratch buffer; no allocation per call) but
    --       NOT field-accessible from Lua -- `.x` / `.y` will error.
    --
    --   imgui.vec2(x, y)   -> ImVec2  (STRUCT cdata)
    --       Fresh struct with `.x` / `.y` fields. Use this when you
    --       want to hold a coordinate, do hit-test math, or pass it
    --       to a function that takes `const ImVec2*` (pointer). Costs
    --       one ffi.new per call; no concern at UI frame rates.
    --
    -- ImVec4 (16 bytes) doesn't fit a register; the cdef declares
    -- ImVec4-by-value args as `const ImVec4*`, so the single ImVec4
    -- constructor returns a struct that's pointer-passable.
    local M = {}

    -- Shared scratch ImVec2 used to bit-pack into a uint64 for the
    -- by-value-ImVec2-as-uint64 ABI hack. The aliasing int64_t* is
    -- cached so M.ImVec2 doesn't allocate or call ffi.cast per frame.
    -- Use SIGNED int64_t* (not uint64_t*): LuaVM's marshal returns
    -- signed int64 reads as lua_Integer (primitive, no cdata), but
    -- unsigned int64 boxes into a fresh cdata per read. The bit
    -- pattern is identical to the C-side uint64_t param.
    local _v2_send   = ffi.new("ImVec2[1]")
    local _v2_send_i = ffi.cast("int64_t*", _v2_send)

    function M.ImVec2(x, y)
        -- Accept a single struct-cdata arg (e.g. `vp.WorkPos`) and
        -- repack it as uint64. Saves callers from writing
        -- `imgui.ImVec2(vp.WorkPos.x, vp.WorkPos.y)` every time.
        if type(x) == "cdata" and y == nil then
            _v2_send[0].x = x.x
            _v2_send[0].y = x.y
        else
            _v2_send[0].x = x or 0
            _v2_send[0].y = y or 0
        end
        return _v2_send_i[0]
    end

    -- vec2 / vec4 rotating pool. Returns a cached struct cdata that the
    -- caller can read .x / .y / .z / .w from and pass to C functions by
    -- pointer. The pool size is chosen so realistic UI code can hold
    -- this many results simultaneously (usually 2-4: p_min, p_max,
    -- maybe a midpoint). Callers that need to STORE the result long-
    -- term must copy it explicitly with `imgui.vec2_copy(v)` (added
    -- below) -- otherwise the next pool wraparound will overwrite.
    --
    -- This eliminates the ~500-per-frame ffi.new("ImVec2") churn that
    -- otherwise fragments the C heap (Lua heap stays bounded via GC,
    -- but the underlying msvcrt heap commits pages it never returns).
    local _VEC2_POOL_SIZE = 64
    local _VEC4_POOL_SIZE = 32
    local _vec2_pool = ffi.new("ImVec2[?]", _VEC2_POOL_SIZE)
    local _vec4_pool = ffi.new("ImVec4[?]", _VEC4_POOL_SIZE)
    local _vec2_idx = 0
    local _vec4_idx = 0

    function M.vec2(x, y)
        local i = _vec2_idx
        _vec2_idx = (i + 1) % _VEC2_POOL_SIZE
        local v = _vec2_pool[i]
        v.x = x or 0; v.y = y or 0
        return v
    end

    function M.ImVec4(x, y, z, w)
        local i = _vec4_idx
        _vec4_idx = (i + 1) % _VEC4_POOL_SIZE
        local v = _vec4_pool[i]
        v.x = x or 0; v.y = y or 0; v.z = z or 0; v.w = w or 0
        return v
    end

    -- Make a heap-allocated copy of a pool-returned vec2/vec4 so callers
    -- that need persistence (storing in a table across frames) don't
    -- alias a slot that will be reused.
    function M.vec2_copy(src)
        local v = ffi.new("ImVec2")
        v.x = src.x; v.y = src.y
        return v
    end
    function M.vec4_copy(src)
        local v = ffi.new("ImVec4")
        v.x = src.x; v.y = src.y; v.z = src.z; v.w = src.w
        return v
    end

    -- Unpack a uint64-encoded ImVec2 return value into a pool-managed
    -- ImVec2. Uses the same rotating pool as M.vec2; ffi.copy(8) shoves
    -- the 8 packed bytes straight into the pool slot's float[2] storage.
    -- Eliminates the per-call ffi.new("ImVec2") that the menu would
    -- otherwise hit hundreds of times per frame via GetCursorPos /
    -- GetItemRectSize / CalcTextSize.
    local _v2_recv = ffi.new("int64_t[1]")
    local function _unpack_v2(u)
        _v2_recv[0] = u
        local i = _vec2_idx
        _vec2_idx = (i + 1) % _VEC2_POOL_SIZE
        local out = _vec2_pool[i]
        ffi.copy(out, _v2_recv, 8)
        return out
    end

    -- ---- 3. Enum tables --------------------------------------------------
    -- The bindings module already populated tables like bindings.Col,
    -- bindings.StyleVar, bindings.WindowFlags ...; copy them onto M.
    for k, v in pairs(bindings) do
        if not k:match("^__") and type(v) == "table" then
            M[k] = v
        end
    end

    -- ---- 4. Function wrappers --------------------------------------------
    -- Parse the wraps text (one record per line, ";"-separated fields,
    -- arg tags ","-separated). Cheaper to ship as one string than as a
    -- 1500-entry array literal -- the latter blows past sensible JIT
    -- bytecode limits.
    local function parse_wraps(text)
        local specs = {}
        for line in text:gmatch("[^\r\n]+") do
            local cname, funcname, stname, ret_tag, args_csv =
                line:match("([^;]*);([^;]*);([^;]*);([^;]*);(.*)")
            if cname and #cname > 0 then
                local args = {}
                if args_csv and #args_csv > 0 then
                    for tag in args_csv:gmatch("[^,]+") do
                        args[#args + 1] = tag
                    end
                end
                specs[#specs + 1] = {
                    cname    = cname,
                    funcname = funcname,
                    stname   = stname,
                    ret      = ret_tag,
                    args     = args,
                }
            end
        end
        return specs
    end

    local wrap_specs = parse_wraps(bindings.__wraps_text)

    -- Group specs by (stname, funcname). Single-overload groups expose the
    -- bare funcname; multi-overload groups expose every overload under
    -- its cname (so PushStyleColor splits into PushStyleColor_U32 +
    -- PushStyleColor_Vec4 etc.).
    local groups = {}
    for _, spec in ipairs(wrap_specs) do
        local key = spec.stname .. ":" .. spec.funcname
        local g = groups[key]
        if g then g[#g + 1] = spec else groups[key] = { spec } end
    end

    local function build_wrapper(spec)
        local ok, cfn = pcall(function() return C[spec.cname] end)
        if not ok or cfn == nil then
            -- symbol missing from the exe -- maybe the link rule didn't
            -- pull in cimgui yet, or this function wasn't dllexport'd.
            return function(...)
                error("imgui: missing C symbol " .. spec.cname, 2)
            end
        end
        local rt = spec.ret
        if rt == "v2" then
            return function(...) return _unpack_v2(cfn(...)) end
        elseif rt == "v4" then
            return function(...)
                local out = ffi.new("ImVec4[1]")
                cfn(out, ...)
                return out[0]
            end
        else
            return cfn
        end
    end

    -- Top-level functions go on M.<funcname>; struct methods go on
    -- M.<stname>.<funcname> so users can do `imgui.ImGuiIO.AddInputCharacter(io, c)`.
    local function ensure_sub(name)
        local t = M[name]
        if t == nil then t = {}; M[name] = t end
        return t
    end

    for _, group in pairs(groups) do
        if #group == 1 then
            local s = group[1]
            local fn = build_wrapper(s)
            if s.stname ~= "" then
                ensure_sub(s.stname)[s.funcname] = fn
            else
                M[s.funcname] = fn
            end
        else
            -- multiple overloads -- expose each by its cimgui suffix.
            -- e.g. cname "igPushStyleColor_Vec4" -> M.PushStyleColor_Vec4
            for _, s in ipairs(group) do
                local suffix = s.cname:match("[^_]+$") or s.cname
                local short = s.funcname .. "_" .. suffix
                local fn = build_wrapper(s)
                if s.stname ~= "" then
                    ensure_sub(s.stname)[short] = fn
                else
                    M[short] = fn
                end
            end
        end
    end

    -- ---- 5. Lifecycle ----------------------------------------------------

    function M.init(title, w, h)
        local rc = C.LuaVM_ImGuiHost_Init(title or "LuaVM ImGui",
                                          w or 800, h or 600)
        if rc ~= 0 then
            error("imgui.init failed (code " .. tostring(rc) .. ")")
        end
    end

    function M.pump_events()
        return C.LuaVM_ImGuiHost_PumpEvents() ~= 0
    end

    function M.new_frame() C.LuaVM_ImGuiHost_NewFrame() end

    function M.render(r, g, b, a)
        C.LuaVM_ImGuiHost_Render(r or 0.1, g or 0.1, b or 0.1, a or 1.0)
    end

    function M.shutdown() C.LuaVM_ImGuiHost_Shutdown() end

    function M.host_version() return tonumber(C.LuaVM_ImGuiHost_Version()) end

    -- Tell the DX11 backend to drop its current font texture and rebuild
    -- it from the current ImGuiIO.Fonts atlas. Call after loading new
    -- fonts at runtime.
    function M.rebuild_font_atlas() C.LuaVM_ImGuiHost_RebuildFontAtlas() end

    -- ---- 6. Ergonomic conveniences --------------------------------------
    -- Common shortcuts so users don't have to remember every cimgui-
    -- generated default for trivial widget calls. The full cimgui surface
    -- stays directly callable -- these are just sugar.

    -- imgui.Text(s) -> TextUnformatted(s, nil) (igText is varargs, skipped)
    function M.Text(s) C.igTextUnformatted(tostring(s), nil) end

    -- Safe scope-exit helpers. Idiomatic ImGui pairs many Begin*/End*
    -- calls where the End* MUST run regardless of whether Begin*
    -- returned `false` (Begin/End, BeginChild/EndChild). Forgetting that
    -- corrupts the window stack on the next frame and asserts deep
    -- inside ImGui. These helpers swallow the boilerplate.
    --
    --   if imgui.Begin("win") then ... end
    --   imgui.safe_end_window()      -- ALWAYS pair with Begin
    --
    --   if imgui.BeginChild("scroll", sz, 0, 0) then ... end
    --   imgui.safe_end_child()       -- ALWAYS pair with BeginChild
    function M.safe_end_window() C.igEnd() end
    function M.safe_end_child()  C.igEndChild() end

    -- One-shot colour override. ImGui requires PushStyleColor + a
    -- matching PopStyleColor; this wraps both around `body`.
    --   imgui.with_color(imgui.Col.Text, 0xFFFF6644, function() ... end)
    -- Accepts either an ImU32 (number) or an ImVec4 cdata. Numbers go
    -- through PushStyleColor_U32; cdata goes through PushStyleColor_Vec4.
    function M.with_color(slot, color, body)
        if type(color) == "number" then
            C.igPushStyleColor_U32(slot, color)
        else
            C.igPushStyleColor_Vec4(slot, color)
        end
        local ok, err = pcall(body)
        C.igPopStyleColor(1)
        if not ok then error(err, 2) end
    end

    return M
end

return MakeImGui()
